### ISSUE TITLE
how to config listeners with domain:port

### ISSUE THREAD

**Issue by xiongxin** [nginx/unit#100]
webs.json
```
{
  "listeners": {
    "app1.com:80": {
      "application" : "app1"
    },
    "app2.com:80": {
      "application" : "app2"
    }
  },
  "applications": {
    "app1" : {
      "type": "php",
      "processes": 1,
      "root" : "/home/codes/php-apps/app1",
      "index":"index.php"
    },
    "app2" : {
      "type": "php",
      "processes": 1,
      "root" : "/home/codes/php-apps/app2",
      "index":"index.php"
    }
  }
}
```
/etc/hosts

```
127.0.0.1       app1.com
127.0.0.1       app2.com

```

when i put this json file, i get
```
➜  ~ curl -X PUT -d @webs.json 127.0.0.1:8443
{
	"error": "Failed to apply new configuration."
}
➜  ~
```

**Comment by hongzhidao** [comment]
Unfortunately, only the format "ip:port" is supported currently.

**Comment by VBart** [comment]
There's no virtual servers support at the moment. You have to specify different ip:port for each application.

This feature is planned. Currently, for virtual servers it's recommended to use nginx in front.

**Comment by VBart** [comment]
@almarklein Unit will have routing capabilities equal to nginx.

**Comment by vitalyzhakov** [comment]
When the feature is sheduled for release?

**Comment by tippexs** [comment]
This functionality is now build in the Unit `router`. Use `match` object to find `hostname` or `uri` segments and pass the request to the right application. More information can be found here: http://unit.nginx.org/configuration/#routes
