### ISSUE TITLE
PHP 8.3 official unit image

### ISSUE THREAD

**Issue by abramchikd** [nginx/unit#1010]
Hello,

PHP 8.3 has been out for a few days now. When will be published  an official unit:php8.3 tag on the [docker hub](https://hub.docker.com/_/unit/tags?page=1&name=php)?
Thank you

**Comment by tippexs** [comment]
Hi @abramchikd thanks for reaching out.

We are NOT building images outside of our own release cycle, yet. This might change in the future. Beside from that, we are relaying on the official PHP Image and PHP 8.3 is not yet available. 

https://github.com/docker-library/php/issues/1466

As soon as it is available you will be able to build your own Image using our `pkg/docker` `make` process. Documentation can be found on the website.

https://unit.nginx.org/installation/#inst-lang-docker
As soon as PHP8.3 is available it will look like this.
```bash
git clone https://github.com/nginx/unit

cd unit

git checkout 1.31.1  # Optional; use to choose a specific Unit version

cd pkg/docker/

make build-php8.3 VERSIONS_php=8.3
```

**Comment by abramchikd** [comment]
Thank you for your help!

**Comment by zip-fa** [comment]
Hi again. 8.3 is officially available for some time. When to expect unit to release it?

**Comment by ac000** [comment]
As per @tippexs comment. I think you need to wait for PHP to release the 8.3 dockerfile image.

**Comment by zip-fa** [comment]
Here you go:
https://hub.docker.com/_/php/tags?page=1&name=8.3

**Comment by abramchikd** [comment]
@zip-fa I managed to build unit image using instructions posted by @tippexs. It is pretty straightforward and built an image without any issues

**Comment by zip-fa** [comment]
Thanks for instruction and sorry for disturbing, but is official image of unit with PHP 8.3 planned to be released?
