### ISSUE TITLE
Does ngix for windows support http_perl_module?

### ISSUE THREAD

**Issue by wangdbang** [nginx/unit#1023]
I tried to compile nginx-release-1.25.3, configed it with parameter --with-http_perl_module, but failed, it printed as follow:
LINK : warning LNK4044: unrecognized option '/s'; ignored
LINK : warning LNK4044: unrecognized option '/LD:\STRAWB~1\perl\lib\CORE'; ignored
LINK : warning LNK4044: unrecognized option '/LD:\STRAWB~1\c\lib'; ignored
LINK : warning LNK4044: unrecognized option '/LD:\STRAWB~1\c\x86_64-w64-mingw32\lib'; ignored
LINK : warning LNK4044: unrecognized option '/LD:\STRAWB~1\c\lib\gcc\x86_64-w64-mingw32\13.1.0'; ignored
LINK : fatal error LNK1104: cannot open file 'objs\src\http\modules\perl\ngx_http_perl_module.obj'
NMAKE : fatal error U1077: 'cl @C:\Users\MyPc\AppData\Local\Temp\nm3042.tmp' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\MVS\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\nmake.exe -f objs/Makefile' : return code '0x2'
Stop.

**Comment by ac000** [comment]
This is the issue tracker for NGINX **Unit**. Have look [here](https://nginx.org/en/support.html) for getting help with nginx.
