### ISSUE TITLE
How can I configure the payload size?

### ISSUE THREAD

**Issue by mcuervoe** [nginx/unit#103]
I am trying to upload a file using flask python3 api, but it seems I reached the default max size for the payload. I am getting a 413 status code (Payload Too Large). 

How can I increase this limit? Can it be done through the control API?

I am using the official docker image nginx/unit:1.0-python3.5

**Comment by VBart** [comment]
Sorry, not yet. It's planned for the near future.

**Comment by VBart** [comment]
Now it's configurable via control API. The relevant interface was added with commit https://github.com/nginx/unit/commit/1abdcfb2d85a04b27ac4fc52619b63917b980839 and will be a part of following Unit 1.3 release.

See also ticket #135.
