### ISSUE TITLE
nodejs unit-http misses `options` in createServer function

### ISSUE THREAD

**Issue by stefanhuber** [nginx/unit#1043]
I tried to run [strapi ](https://strapi.io/) inside nginx unit. The startup of strapi doesn't work because of the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:270:3)
    at _addListener (node:events:550:3)
    at Server.addListener (node:events:609:10)
    at new Server (/usr/local/lib/node_modules/unit-http/http_server.js:426:14)
    at Object.createServer (/usr/local/lib/node_modules/unit-http/http.js:15:12)
    at Module.createHTTPServer (/var/www/node_modules/@strapi/strapi/dist/services/server/http-server.js:16:40)
    at Module.createServer (/var/www/node_modules/@strapi/strapi/dist/services/server/index.js:26:35)
    at new Strapi (/var/www/node_modules/@strapi/strapi/dist/Strapi.js:130:27)
    at initFn (/var/www/node_modules/@strapi/strapi/dist/Strapi.js:466:18)
    at Object.<anonymous> (/var/www/index.js:2:1) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Strapi uses `options` with the `http.createServer` function as seen [here](https://github.com/strapi/strapi/blob/762abbf7f8a8cae3cda9b6affcea50be8abc3ce9/packages/core/strapi/src/services/server/http-server.ts#L25C31-L25C68) in the source code. The node signature of the `createServer` function looks like this: `http.createServer([options][, requestListener])`. Looking at the `http` module inside the `unit-http` package the `createServer` function is missing the [options argument](https://github.com/nginx/unit/blob/49aee6760a26b14c06180e4f25088cb18e2037a7/src/nodejs/unit-http/http.js#L14).

Can this be solved somehow? How could strapi be started otherwise within nginx unit?

Nginx Unit has the following config.json:
```json
{
    "listeners": {
        "*:1337": {
            "pass": "routes/main"
        }
    },
    "routes": {
        "main": [
            {
                "action": {
                    "pass": "applications/app"
                }
            }
        ]
    },
    "applications": {
        "app": {
            "type": "external",
            "working_directory": "/var/www/",
            "executable": "/usr/bin/env",
            "arguments": [
                "node",
                "--loader",
                "unit-http/loader.mjs",
                "--require",
                "unit-http/loader",
                "index.js"
            ]
        }
    }
}
```

**Comment by stefanhuber** [comment]
I could create a fix by using `patch-package` with the following steps:

- Install `unit-http` and `patch-package` as npm dependencies: `npm i unit-http patch-package --save`
- Add `"postinstall": "patch-package"` under `"scripts"` inside `package.json`
- Edit the `http.js` file inside `node_modules/unit-http` by adding `options` as the first argument to the `createServer` function:
   ```
   function createServer (options, requestHandler) {
    return new Server(requestHandler);
   }
   ```
- Apply the patch: `npx patch-package unit-http`

As a current workaround this is ok. Although I think this might not be a sustainable approach. The `options` could be ignored in the case of our strapi deployment.

**Comment by callahad** [comment]
Looks like the `options` argument was added in Node.js v9.6.0 (2018-02-22) / v8.12.0 (2018-09-11) in https://github.com/nodejs/node/pull/15752 and we missed it when implementing our shim for `http.createServer`.

We should fix this in Unit, but the patch-package workaround should be fine for your use case until we can get a release out with a proper fix.
