### ISSUE TITLE
download unit.nginx.org/download/*.tar.gz is 404

### ISSUE THREAD

**Issue by en-jschuetze** [nginx/unit#1074]
Hello,

since today (I did not check earlier) the download links like e.g. https://unit.nginx.org/download/unit-1.31.1.tar.gz do throw 404 now.

Is it going to last like this?

The link is currently mentioned at https://unit.nginx.org/installation/#source-code 

![Bildschirmfoto 2024-01-18 um 17 40 41](https://github.com/nginx/unit/assets/126695184/da4ec651-0564-4eab-a739-30a9e1666408)

and used at alpine packages to pull the source https://git.alpinelinux.org/aports/tree/community/unit/APKBUILD#n36.

**Comment by callahad** [comment]
This is a regression with moving the Unit docs to Netlify in https://github.com/nginx/unit-docs/issues/75

We're reverting DNS and should be back up and working shortly.

**Comment by en-jschuetze** [comment]
Thanks a lot!

**Comment by callahad** [comment]
Thank you for reporting, and apologies for the downtime :)

**Comment by ac000** [comment]
Can't we just point to package links under https://github.com/nginx/unit/tags ?

**Comment by thresheek** [comment]
No, as the checksums will not match for the current releases - the tarballs are done via `make -C pkg dist`, and tags are pointing to snapshots of the repos.
