### ISSUE TITLE
 If php version > 8, multiple versions cannot be used.

### ISSUE THREAD

**Issue by sia-fl** [nginx/unit#1075]
If you use php7+, you can tell the php version.

config:
```json
{
    "listeners": {
        "127.0.0.1:71": {
            "pass": "applications/php71"
        },
        "127.0.0.1:74": {
            "pass": "applications/php74"
        }
    },
    "applications": {
        "php71": {
            "type": "php 7.1",
            "root": "/code/php74/", // out php version = 7.1
            "script": "index.php"
        },
        "php74": {
            "type": "php 7.4",
            "root": "/code/php74/", // out php version = 7.4
            "script": "index.php"
        }
    }
}
```

but when I use php8+, the most advanced version is always used

config:
```json
{
    "listeners": {
        "127.0.0.1:71": {
            "pass": "applications/php71"
        },
        "127.0.0.1:74": {
            "pass": "applications/php74"
        },
        "127.0.0.1:81": {
            "pass": "applications/php81" 
        },
        "127.0.0.1:82": {
            "pass": "applications/php82"
        }
    },
    "applications": {
        "php71": {
            "type": "php 7.1",
            "root": "/code/php71/",  // out php version = 7.1
            "script": "index.php"
        },
        "php74": {
            "type": "php 7.4",
            "root": "/code/php74/", // out php version = 7.4
            "script": "index.php"
        },
        "php81": {
            "type": "php 8.1",
            "root": "/code/php81/",  // out php version = 8.2
            "script": "index.php"
        },
        "php82": {
            "type": "php 8.2",
            "root": "/code/php82/",  // out php version = 8.2
            "script": "index.php"
        }
    }
}
```

**Comment by sia-fl** [comment]
operation process:

`./configure --njs --openssl               --cc-opt="-I../njs/src/ -I../njs/build/"                --ld-opt="-L../njs/build/"`
`make && make install`

` ./configure php --module=php71 --config=/usr/bin/php-config7.1 --lib-path=/usr/lib/php/7.1/sapi`
`make php71 & php71-install`

` ./configure php --module=php72 --config=/usr/bin/php-config7.2 --lib-path=/usr/lib/php/7.2/sapi`
`make php72 & php72-install`

` ./configure php --module=php81 --config=/usr/bin/php-config8.1 --lib-path=/usr/lib/php/8.1/sapi`
`make php81 & php81-install`

` ./configure php --module=php82 --config=/usr/bin/php-config8.2 --lib-path=/usr/lib/php/8.2/sapi`
`make php82 & php82-install`

**Comment by sia-fl** [comment]
logs:

`
2024/01/19 03:55:31 [info] 9521#9521 discovery started
2024/01/19 03:55:31 [notice] 9521#9521 module: php 7.1.33-56+ubuntu22.04.1+deb.sury.org+1 "/usr/local/lib/unit/modules/php71.unit.so"
2024/01/19 03:55:31 [notice] 9521#9521 module: php 7.4.33 "/usr/local/lib/unit/modules/php74.unit.so"
2024/01/19 03:55:31 [notice] 9521#9521 module: php 8.1.27 "/usr/local/lib/unit/modules/php81.unit.so"
2024/01/19 03:55:31 [notice] 9521#9521 module: php 8.2.14 "/usr/local/lib/unit/modules/php82.unit.so"
2024/01/19 03:55:31 [info] 9520#9520 controller started
2024/01/19 03:55:31 [notice] 9520#9520 process 9521 exited with code 0
2024/01/19 03:55:31 [info] 9523#9523 router started
2024/01/19 03:55:31 [info] 9523#9523 OpenSSL 3.0.2 15 Mar 2022, 30000020
2024/01/19 03:55:31 [info] 9524#9524 "php71" prototype started
2024/01/19 03:55:31 [info] 9525#9525 "php71" application started
2024/01/19 03:55:31 [info] 9526#9526 "php74" prototype started
2024/01/19 03:55:31 [info] 9527#9527 "php74" application started
2024/01/19 03:55:32 [info] 9544#9544 "php81" prototype started
2024/01/19 03:55:32 [info] 9545#9545 "php81" application started
2024/01/19 03:55:32 [info] 9546#9546 "php82" prototype started
2024/01/19 03:55:32 [info] 9547#9547 "php82" application started
2024/01/19 03:58:11 [info] 9568#9568 "php81" prototype started
2024/01/19 03:58:11 [info] 9569#9569 "php81" application started
2024/01/19 03:58:11 [notice] 9544#9544 app process 9545 exited with code 0
2024/01/19 03:58:11 [notice] 9520#9520 process 9544 exited with code 0
2024/01/19 04:03:30 [info] 15027#15027 discovery started
2024/01/19 04:03:30 [notice] 15027#15027 module: php 8.1.27 "/usr/local/lib/unit/modules/php81.unit.so"
2024/01/19 04:03:30 [notice] 15027#15027 module: php 8.2.14 "/usr/local/lib/unit/modules/php82.unit.so"
2024/01/19 04:03:30 [info] 15026#15026 controller started
2024/01/19 04:03:30 [alert] 15028#15028 the previous configuration is invalid: The module to run "php 7.1" is not found among the available application modules.
2024/01/19 04:03:30 [notice] 15026#15026 process 15027 exited with code 0
2024/01/19 04:03:30 [info] 15029#15029 router started
2024/01/19 04:03:30 [info] 15029#15029 OpenSSL 3.0.2 15 Mar 2022, 30000020
2024/01/19 04:03:42 [info] 15030#15030 "php81" prototype started
2024/01/19 04:03:42 [info] 15031#15031 "php81" application started
2024/01/19 04:03:42 [info] 15032#15032 "php82" prototype started
2024/01/19 04:03:42 [info] 15033#15033 "php82" application started
`

**Comment by tippexs** [comment]
@sia-fl thanks for reaching out. What's OS are you using and where did you get the PHP packages from?

**Comment by sia-fl** [comment]
@tippexs , hi

os: Ubuntu22.04

it is my install process:

`sudo apt update && sudo apt upgrade `
`sudo apt install software-properties-common ca-certificates lsb-release apt-transport-https `
`LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php `
`sudo apt update `
`sudo apt install php8.2 php8.2-dev libphp8.2-embed`
`sudo apt install php8.1 php8.1-dev libphp8.1-embed`
`sudo apt install php7.4 php7.4-dev libphp7.4-embed`
`sudo apt install php7.1 php7.1-dev libphp7.1-embed`

other `sudo apt install php[version]-[extension]`

change php version script
`sudo update-alternatives --config php`

I have tried repeatedly. I have successfully configured php7+ 3 times on different computers, but php8+ always fails.

**Comment by tippexs** [comment]
Thanks for providing additional information! I was able to build for php 8.2 but will check with your configuration provided. I afk the whole day but back in the office later today.

**Comment by sia-fl** [comment]
thank you for your attention to the problem. Please let me know if there is any progress.

**Comment by tippexs** [comment]
@sia-fl  I was just able to reproduce this behaviour. As I thought there is something going on with the PHP8.3 `so` files. Trying to find the root cause.

**Comment by tippexs** [comment]
@ac000 My idea would be to have a static version of PHP `libphp.a` instead of `.so` and use this to build the language module. Thoughts?

**Comment by tippexs** [comment]
I am happy to test but will this help with this issue?

```bash
$# objdump -p /usr/lib/libphp8.2.so |grep SONAME
  SONAME               libphp.so
```

No matter where I copy the `so` it will always look for `libphp.so`? Am I right?

**Comment by sia-fl** [comment]
> I am happy to test but will this help with this issue?我很乐意测试，但这对解决这个问题有帮助吗？
> 
> ```shell
> $# objdump -p /usr/lib/libphp8.2.so |grep SONAME
>   SONAME               libphp.so
> ```
> 
> No matter where I copy the `so` it will always look for `libphp.so`? Am I right?无论我在哪里复制它 `so` 都会一直寻找 `libphp.so` ？我说得对吗？

problem solved, if php8+ is searching for libphp.so instead of libphp8.so then I just need to adjust the link

current:
`ln -s /usr/lib/libphp8.1.so /usr/lib/php/8.1/sapi/libphp8.so`

now:
`ln -s /usr/lib/libphp8.1.so /usr/lib/php/8.1/sapi/libphp.so`

it works fine now 😄

**Comment by sia-fl** [comment]
> You could statically link the php libs with the `--lib-static` option to the php language module configure command perhaps.您可以静态地将带有 `--lib-static` 选项的 php 库链接到 php 语言模块 configure 命令。
> 
> It's unfortunate some of those php libs aren't versioned.不幸的是，其中一些 php 库没有版本控制。
> 
> You could work around it by putting the php .so's each into their own directories and using `--lib-path=` with the php language module configure command.您可以通过将每个 php .so 放入自己的目录中并与 php 语言模块 configure 命令一起使用 `--lib-path=` 来解决它。
> 
> As a quick test作为快速测试
> 
> ```
> $ cp /lib64/libphp-8.2.so /tmp/
> $ ./configure php --lib-path=/tmp/
> configuring PHP module
> checking for PHP ... found
>  + PHP SAPI: [apache2handler litespeed fpm phpdbg cli embed cgi]
> checking for PHP version ... 8.2.14
> checking for PHP embed SAPI ... found
> checking for PHP Zend Thread Safety ... not found
> checking for PHP zend_signal_startup() ... found
>  + PHP module: php.unit.so
> $ make -j
> $ ldd build/lib/unit/modules/php.unit.so | grep libphp
>         libphp-8.2.so => /tmp/libphp-8.2.so (0x00007fa8aec5a000)
> ```

i can build fine now, the problem occurs in case of php8+ he always looks for the latest version

**Comment by sia-fl** [comment]
> You could statically link the php libs with the `--lib-static` option to the php language module configure command perhaps.
> 
> It's unfortunate some of those php libs aren't versioned.
> 
> You could work around it by putting the php .so's each into their own directories and using `--lib-path=` with the php language module configure command.
> 
> As a quick test
> 
> ```
> $ cp /lib64/libphp-8.2.so /tmp/
> $ ./configure php --lib-path=/tmp/
> configuring PHP module
> checking for PHP ... found
>  + PHP SAPI: [apache2handler litespeed fpm phpdbg cli embed cgi]
> checking for PHP version ... 8.2.14
> checking for PHP embed SAPI ... found
> checking for PHP Zend Thread Safety ... not found
> checking for PHP zend_signal_startup() ... found
>  + PHP module: php.unit.so
> $ make -j
> $ ldd build/lib/unit/modules/php.unit.so | grep libphp
>         libphp-8.2.so => /tmp/libphp-8.2.so (0x00007fa8aec5a000)
> ```

I can build fine now, the problem occurs in case of php8+ he always looks for the latest version
