### ISSUE TITLE
read request body not work as expected in golang

### ISSUE THREAD

**Issue by binnnliu** [nginx/unit#108]
```golang
func (r *request) Read(p []byte) (n int, err error) {
	c := C.size_t(cap(p))

	b := C.uintptr_t(uintptr(unsafe.Pointer(&p[0])))

	res := C.nxt_go_request_read(r.c_req, b, c)

	return int(res), nil
}
```

This Read function always return nil as error, it should return EOF when all data has been read. Or it will block ioutil.ReadAll(r.body).

**Comment by binnnliu** [comment]
@mar0x  This patch does not work when the request body is larger than 1024. I can get rid of this in my app code.

Is there any plan to fix this?

**Comment by mar0x** [comment]
Could you please provide sample to reproduce issue with large body.
Yes, we have a plan to fix this and I'm working on this issue.

**Comment by binnnliu** [comment]
@mar0x  sorry. my fault. this patch works.
