### ISSUE TITLE
Add arguments to go executable

### ISSUE THREAD

**Issue by krombel** [nginx/unit#110]
Is it possible to pass args to a go binary?

So I might want to start `/path/to/goapp --config=/path/to/goconfig`
Is there some way to pass `--config=/path/to/goconfig` to the binary via unit?

**Comment by martinr92** [comment]
@VBart Thanks for implementing this feature.
Will it be available in the next unit release?

**Comment by VBart** [comment]
@martinr92 Yes, it will be available in the next release.
