### ISSUE TITLE
Using process->port instead of process->ports

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#114]
Hi.

I'm wondering what case process has multi ports? It seems that process->port is enough. 
If process->port can be used instead of process->ports, we can simplify this part.

Thanks.

**Comment by igorsysoev** [comment]
> On 24 Apr 2018, at 19:54, hongzhidao <notifications@github.com> wrote:
> 
> Hi.
> 
> I'm wondering what case process has multi ports? It seems that process->port is enough.
> If process->port can be used instead of process->ports, we can simplify this part.

The router process runs several worker threads and each thread has own incoming port.


-- 
Igor Sysoev
http://nginx.com

**Comment by hongzhidao** [comment]
I know it. Each worker thread has its own engine which has one own port.
Is this port the same as you called "incoming port"?
But the port doesn't add to the process.
In what case, the main/controller/worker process has multiple ports?

**Comment by mar0x** [comment]
Application worker process may have multiple ports for router process structure.

**Comment by hongzhidao** [comment]
Can you point out which place has multiple ports for router process?
Or how to reproduce it?  @mar0x

**Comment by mar0x** [comment]
Router process may have multiple worker threads (equals number of CPU cores for now).  Each thread have it's own port for application response (this ports are not in process->ports on router side). On application worker this ports will be in process->ports.
To reproduce start Unit on multi-core host, configure 1 worker process, generate multiple connection load to utilise all router worker threads, see unix sockets on application worker process (via lsof).

**Comment by hongzhidao** [comment]
I totally get it now, thanks for your reply.
