### ISSUE TITLE
Getting strange message when trying to get static files

### ISSUE THREAD

**Issue by devel96** [nginx/unit#1146]
![image](https://github.com/nginx/unit/assets/55926214/c16d9649-c765-4f73-b4d9-4e92a2d14754)

Hi. getting this error when trying to get this js file.

unit config:

```
{
  "listeners":{
    "*:80":{
      "pass":"routes"
    }
  },
  "routes":[
    {
      "match":{
        "uri":[
          "*.php",
          "*.php/*"
        ]
      },
      "action":{
        "pass":"applications/laravel/direct"
      }
    },
    {
      "action":{
        "share":"/var/www/app/public$uri",
        "fallback":{
          "pass":"applications/laravel/index"
        }
      }
    }
  ],
  "applications":{
    "laravel":{
      "type":"php",
      "processes":{
        "max":25,
        "spare":10,
        "idle_timeout":120
      },
      "user": "unit",
      "group": "unit",
      "targets":{
        "direct":{
          "root":"/var/www/app/public/"
        },
        "index":{
          "root":"/var/www/app/public/",
          "script":"index.php"
        }
      }
    }
  }
}
```

docker image version unit:1.31.1-php8.2

**Comment by andrey-zelenkov** [comment]
Hi @devel96 

Thank you for the report.

This looks similar to the https://github.com/nginx/unit/issues/1064 and fix has been already committed here https://github.com/nginx/unit/commit/02d1984c912261a1274534a24a2d94ac7c7abfa7 but has not been released yet. Please check if this fix works for you as well.

**Comment by devel96** [comment]
Hi @andrey-zelenkov. Thanks for the answer. Is there a docker image for this commit or should I wait for release?

**Comment by tippexs** [comment]
We are just wrapping up everything for a release. The release is scheduled for 27-February. So it it just arround the corner.

**Comment by devel96** [comment]
Cool. Will wait then ) thanks guys
