### ISSUE TITLE
Add PHP 8.3 image

### ISSUE THREAD

**Issue by Ferikl** [nginx/unit#1149]
Hi guys! 
As I can see here: https://hub.docker.com/_/unit There is no PHP 8.3 version :( 
Since we have stable PHP 8.3, can you create new docker image with this version please?

Alpine version: https://hub.docker.com/layers/library/php/8.3.3-alpine/images/sha256-898ebc36826f43f0de25313396354349cba0a7480fd8c86588686fe776731d06

Thanks a lot!

**Comment by callahad** [comment]
We expect to release Unit 1.32.0 early next week, and it will have a PHP 8.3 Docker image :)
