### ISSUE TITLE
Python trailing slash for home directory

### ISSUE THREAD

**Issue by tamarintech** [nginx/unit#115]
This does not work (`Fatal Python error: Py_Initialize: Unable to get the locale encoding`):

`"path": "/srv/env-py3"`

This works fine:

`"path": "/srv/env-py3/"`

Looks like there's a path concatenation problem and that we need a trailing slash.

**Comment by VBart** [comment]
@tamarintech Are you sure that the problem is with the `path` option (instead of `home`)?

The path bellow should fix the issue (but with `home`):
```diff
diff -r 2ef5c9cb2d71 src/nxt_python_wsgi.c
--- a/src/nxt_python_wsgi.c     Tue Apr 24 20:49:36 2018 +0300
+++ b/src/nxt_python_wsgi.c     Tue Apr 24 23:56:14 2018 +0300
@@ -210,7 +210,7 @@ nxt_python_init(nxt_task_t *task, nxt_co
     size_t                 size;
     nxt_int_t              pep405;
 
-    static const char pyvenv[] = "pyvenv.cfg";
+    static const char pyvenv[] = "/pyvenv.cfg";
     static const char bin_python[] = "/bin/python";
 #endif
 
```

**Comment by tamarintech** [comment]
You are right. I think I transposed the _path_ to _home_ in my head and wrote path accidentally.

Sorry. Silly mistake on my part.
