### ISSUE TITLE
Need to invoke unitd with root access?

### ISSUE THREAD

**Issue by almarklein** [nginx/unit#116]
Hi, 

I've been playing with nginx unit, and love it so far; thanks! I installed `unit` via the precompiled packages. (on Ubuntu 18.04, using the 17.10 binaries, which seems to work fine). The documentation is (understandably) a bit sparse though, and there's a few things that I have trouble with. Any help would be appreciated, and I'd be happy to contribute a little (e.g. docs) to help make getting started easier for others.

1: It took me a while to figure out how I should start `unit`. So maybe this could be added to the docs (are the docs also open source? If so I could submit a PR). In particular, when to use the service and when the `unitd` executable, and the consequences.

2: I initially tried with `service unit restart`, but `curl --unix-socket /var/run/control.unit.sock http://localhost` gives me nothing but a "cannot connect to server". Also tried `/run/control.unit.sock`, same. `service unit status` indicates that its running fine. Any idea what this could be? 

So from there, I tried to get `unit` running with `--control` on a normal http port on localhost.

3: I managed to add the `--control` parameter for the service by changing `/etc/defaults/unit` . Would this be the recommended way? Or would it be cleaner to run `unitd` directy?

4: When running `unitd` directly, I got it working with `sudo unitd --control 127.0.0.1:8443`. However, one pitfall is that when the `sudo` is omitted, the process *seems* to start just fine, but closes immediately. Is this supposed to happen? If it does, it might be good to document this and/or perhaps print a message when unit exits.

**Comment by almarklein** [comment]
> 4: 

Ah, I guess this is a Linux thing, related to binding of low port numbers. Sorry, I am not a daily Linux user :)

**Comment by VBart** [comment]
The documentation is open-sourced. See a separate repository: https://github.com/nginx/unit-docs

Please note that in typical case user will never use `unitd` directly, since in most systems the daemon is controlled by some service management system and all depends on the particular OS. The paths and what to change may vary.

**Comment by almarklein** [comment]
Thanks. I made a PR for the docs (https://github.com/nginx/unit-docs/pull/5).

This question still stands:  Using `curl --unix-socket /var/run/control.unit.sock http://localhost` gives me nothing but a "cannot connect to server". Also tried `/run/control.unit.sock`, same. `service unit status` indicates that its running fine. Any idea what this could be?

**Comment by almarklein** [comment]
Ok, thanks. Its working now anyway using ``--control``
