### ISSUE TITLE
WebsocketConnection WebSocket onerror while trying nginx htpasswd protection 

### ISSUE THREAD

**Issue by achoud42** [nginx/unit#1168]
when i simply try my streamlit url at browser it works fine 
But when i add protection for this url under nginx like below it keeps loading (https://passimage.in/i/f1180559e5da64ada49a.png)

server {
        listen       81 default_server;
        listen       [::]:81 default_server;
        proxy_ignore_client_abort on;
        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;
        server_name _;  # Change to your domain name
        root /var/www/html/dashboard/;
        location / {
          auth_basic "Restricted Content";
          auth_basic_user_file /etc/nginx/.htpasswd;
          proxy_pass http://127.0.0.1:8501/;
          proxy_set_header Host \$host;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
        
        
        At ui end i get request is going to healthz or stream endpoint 
        https://passimage.in/i/4170ed83d0454d5472cc.png
        
        At console i see these errors 
        https://passimage.in/i/3b5d08724005a57f025c.png

**Comment by tippexs** [comment]
Hi @achoud42 - thanks for reaching out but this is the issue tracker for NGINX Unit and not NGINX. Please see http://nginx.org/en/support.html for more details about getting support for NGINX. For now, I would suggest the mailing list or our community Slack channel!
