### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by Madhu1512** [nginx/unit#119]
I don't see Unit docker image for python 3.6 in Docker Hub. Is there a plan to release python 3.6 docker image?

**Comment by thresheek** [comment]
No plans for now.

A possible approach to achieve that is not to use precompiled unit packages, but to inherit python/ruby/go environment from docker official images project, and then build unit on top of those images.

**Comment by Madhu1512** [comment]
Thanks. for anyone who is interested, I created unit python 3.6 docker images using official docker python images.
https://github.com/mthota15/unit-python/tree/master/3.6

**Comment by j7an** [comment]
Another possibility is to use Ubuntu's 18.04 LTS container image since Debian is slow to update their repos.

**Comment by thresheek** [comment]
Hi @j7an @Madhu1512,

We've decided to provide a way to use newer language runtimes without being tied to Debian or Ubuntu releases in our dockerfiles. Now, we don't build and publish Python 3.6 images, but 3.9 instead; you can, however easily build those with the following commands:

$ git clone https://github.com/nginx/unit
$ cd unit
$ git checkout 1.22.0
$ cd pkg/docker/
$ make build-python3.6 VERSION_python=3.6

As a result you will have a local docker image under the name of `unit:1.22.0-python3.6` which you can use for your deployments and/or push to your local registries.

As the images are based on official Docker images for the runtimes, you can use the same tricks installing the extensions.

**Comment by Ankitkushwaha90** [comment]
make: *** [Makefile:95: build-python3.6] Error 127
