### ISSUE TITLE
Very hard to run .sh scripts from within Flask app

### ISSUE THREAD

**Issue by jli05** [nginx/unit#1193]
Hi,

My Flask app in the `setup.py` has lines

```
    setup(...,
               scripts=[...],
               ...)
```

so some `.sh` scripts are installed into `venv/bin` directory.

Then in the Flask app the scripts would be called by `subprocess` functions as `Popen()` etc.

Some script would call other scripts in the same `venv/bin` directory, and walk through filesystem somewhere. Overall it is very difficult to obtain expected results. I guess it is that the user is `unit`, different than my user.

I checked my nginx configuration file. It runs as user `nginx` but can run the Flask app with no problem, passing calls to the WSGI server `uwsgi`.

**Comment by ac000** [comment]
Do you have `working_directory`[0] set?

[0]: <https://unit.nginx.org/configuration/#configuration-apps-common>

**Comment by jli05** [comment]
You are right @ac000 . So in the `config.json` I added `working_directory` parameter.

Then in Python code:

```python
  from os import getcwd, environ
  from os.path import join
  env = {'PATH': join(getcwd(), 'venv', 'bin') + ':' + environ['PATH']}
  ...
  Popen([...], env=env, ...)
```
