### ISSUE TITLE
Consider updating containers to bookworm base image

### ISSUE THREAD

**Issue by costasd** [nginx/unit#1195]
Hello,

since bookworm was released last year, bullseye has become the oldstable - while not pressing right now, security support for bullseye (and relevant images) will cease at some (not very far) point.

Would be good to move to bookworm earlier than that, to allow ample time for any bugfixes or any changes needed for package names, scripts etc.

Thanks!

**Comment by thresheek** [comment]
Hi @costasd!

Yeah it's a good idea - however I'm pretty sure we're quite close to the bugfix release where we don't really want to bump too many things.  I agree that it's needed, but this probably should wait for a non-bugfix release.

**Comment by costasd** [comment]
Hi @thresheek, yeah makes total sense, whenever's more convenient!

**Comment by ac000** [comment]
> Yeah it's a good idea - however I'm pretty sure we're quite close to
> the bugfix release where we don't really want to bump too many things.
> I agree that it's needed, but this probably should wait for a
> non-bugfix release.

Seeing as the bugfix release is happening in a _separate_ branch,
there's no need to delay this...
