### ISSUE TITLE
CLI: `unitctl edit` should get editor from environment variables

### ISSUE THREAD

**Issue by avahahn** [nginx/unit#1253]
Currently `unitctl edit` picks an editor form a list of known paths. It has the logic to select from environment variables including EDITOR and VISUAL but that logic isnt called.

**Comment by ac000** [comment]
I didn't check the code but it should try `$VISUAL` then `$EDITOR` then fallback to something standard like `vi(1)`

**Comment by avahahn** [comment]
Closing as additional testing revealed that this logic was working as expected.
Sorry for the noise!
