### ISSUE TITLE
Golang Hello world example can not work

### ISSUE THREAD

**Issue by lth2015** [nginx/unit#126]
When I use the nginx/unit project as my LoadBalancer component, I want use golang programming language to make a plugin tool. According to the official document, I `config/make` unit source code and `go build` my program, then use http put command to update the config:
```json
{
    "listeners": {
        "*:8500": {
            "application": "go_chat_app"
        }
    },

    "applications": {
        "go_chat_app": {
            "type": "go",
            "working_directory": "/tmp",
            "executable": "/tmp/unit-go"
        }
    }
}
```
```bash
#curl -X PUT -d @go.json --unix-socket /var/run/control.unit.sock http://localhost/
```
After start unit service, I can't see the unit-go child process in `ps` commond, but I see the 8500 port is listing by unit router process:

```bash
#netstat -anpt | grep 8500
tcp        0      0 0.0.0.0:8500            0.0.0.0:*               LISTEN      12798/unit: router
```
```bash
#ps auxf 
root     12795  0.0  0.0  16224   952 ?        Ss   5月25   0:00 unit: main [/usr/sbin/unitd --log /var/log/unitd.log --pid /run/unitd.pid]
nobody   12797  0.0  0.0  26468   976 ?        S    5月25   0:00  \_ unit: controller
nobody   12798  0.0  0.0 174076   932 ?        Sl   5月25   0:00  \_ unit: router
```

and my golang code:
```golang
package main

import (
    "fmt"
    "net/http"
    "nginx/unit"
)

func handler(w http.ResponseWriter, r *http.Request) {
    w.Header().Add("Content-Type", "text/plain");

    fmt.Fprintf(w, "Method : %s\n", r.Method)
    fmt.Fprintf(w, "URL    : %s\n", r.URL.Path)
    fmt.Fprintf(w, "Host   : %s\n", r.Host)
}

func main() {
    http.HandleFunc("/", handler)
    unit.ListenAndServe("8000", nil)
}
```
go.json:
```json
{
    "listeners": {
        "*:8500": {
            "application": "go_chat_app"
        }
    },

    "applications": {
        "go_chat_app": {
            "type": "go",
            "working_directory": "/tmp",
            "executable": "/tmp/unit-go"
        }
    }
}
```
Anybody has same problem?

**Comment by lth2015** [comment]
When I curl `localhost:8500`, it returns "Read header timeout" error.

**Comment by mar0x** [comment]
Please provide more information about your environment: OS version, golang version, configure command line options to reproduce the issue.

**Comment by lth2015** [comment]
Thank you very much~
More Info:
OS version: CentOS 7 
Kernel version: 3.10.0-693.2.2.el7.x86_64
Golang version: go1.9.5 linux/amd64

Configure commands:
Firstly:  `./config`
Then: `./config go`
Then `make all`
Finally: `make go-install`

My directory: 
~/unit
├── full.json
├── get.sh
├── go.json
├── put.sh
├── src
│   ├── nginx
│   │   └── unit
│   └── unit
│       ├── auto
│       ├── build
│       ├── CHANGES
│       ├── configure
│       ├── docs
│       ├── LICENSE
│       ├── Makefile
│       ├── NOTICE
│       ├── pkg
│       ├── README
│       ├── sbin
│       ├── src
│       └── test
├── unit
└── unit.go

GOPATH: ~/unit

**Comment by lth2015** [comment]
This problem also posted on [stackoverflow-Can not find unit-go child process in nginx unit, curl request timeout](https://stackoverflow.com/questions/50558936/can-not-find-unit-go-child-process-in-nginx-unit-curl-request-timeout/50569123#50569123), welcoming everyone to join the discussion~

**Comment by VBart** [comment]
@lth2015 What Unit version are you trying to run? Please, note that currently supported version is 1.1 and all the instructions are valid for it.

**Comment by lth2015** [comment]
@mar0x thank you very much! It's works! may be I use a different version of unit by `yum install unit` and `service unitd start`.
@VBart thank you~

I will write a document to show how to can run unit-go step-by-step, thank you all guys~
