### ISSUE TITLE
Cannot build packages for Raspbian

### ISSUE THREAD

**Issue by mpmc** [nginx/unit#129]
Hi there,

I'm trying to build unit deb packages for Raspbian as they're not available in the unit repo, however it's not possible due some golang packages not being available on Raspbian OOTB.

There seems to be no way to pick which modules to package, it's all or nothing. I know I can just make & make install, but I prefer using proper packages.

Any assistance gratefully received :)

**Comment by mpmc** [comment]
Just a small update to this, I added a workaround you can see that [here](https://github.com/mpmc/unit/commit/5a34261c57d4991b42464bba9804a44388ad58fa).

However, the build still failed due to the recent version bump, so I reverted that too & it builts the packages fine. Those can be found [here](https://doozer.io/mpmc/doozer-unit/build/28).

**Comment by defanator** [comment]
@mpmc thanks for your efforts. We don't consider Raspbian as one of primary platforms to support, so we'd like to avoid including any specific hacks around it in the base tree.

However, you always can build separate packages by simply running e.g. `make unit unit-php unit-python` inside `pkg/deb` and use the resulting binaries.
