### ISSUE TITLE
unitctl not installed with `brew install nginx/unit/unit` on macOS

### ISSUE THREAD

**Issue by tddschn** [nginx/unit#1298]
I installed unit with `$ brew install nginx/unit/unit` on my Intel Mac, and the binaries I got are

```
unitc
unitd
njs-unit
setup-unit
```

`unitctl` is not included.

**Comment by danielledeleo** [comment]
Looks like we [merged the README](https://github.com/nginx/unit/pull/1267) change before [updating Homebrew](https://github.com/nginx/homebrew-unit/issues/39). Thank you for the report.

**Comment by ava-affine** [comment]
This is currently waiting on the following:
https://github.com/nginx/unit/issues/1298

**Comment by avahahn** [comment]
This is currently waiting on the following:
https://github.com/nginx/homebrew-unit/issues/39

**Comment by lcrilly** [comment]
@tddschn which `unitctl` features are you looking for, that are not provided by the other tools?
