### ISSUE TITLE
test_listeners_empty test fails on Raspberry 3

### ISSUE THREAD

**Issue by baranyaib90** [nginx/unit#130]
Test run failed with:
> test_listeners_empty (test_configuration.TestUnitConfiguration) ...
> All alerts/sanitizer errors found in log:
> 2018/06/09 19:10:08.684 [alert] 27708#27708 process 27711 exited on signal 11
> skipped.
> unexpected success

Unit compiled from github source, commit hash: f2a856aa3b0ea0e0d892a9a3865c54de83c71a74

> $ unitd --version
> unit version: 1.2
> configured as ./configure --tests --debug

[unit.log](https://github.com/nginx/unit/files/2087194/unit.log)

System info:
Raspberry PI 3 with OSMC (based on debian stretch)
kernel: Linux pi 4.14.34-1-osmc #1 SMP PREEMPT Wed Apr 25 16:58:37 UTC 2018 armv7l GNU/Linux
gcc: gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by VBart** [comment]
"unexpected success" doesn't mean that the test is failed. This test is expected to fail because of the known bug in the code, but on your system the bug didn't manifested itself, which is ok.
