### ISSUE TITLE
Change server name header

### ISSUE THREAD

**Issue by aljaznuncic** [nginx/unit#1346]
Just as it is possible to remove the nginx version from the header with `server_tokens off;`, it would be very welcome to be able to change the 'nginx' text as well, without the need to additionally install the _more_set_headers_ plugin (eg: `server_name 'New Server Name';`). Use this `server_name` also at error pages (here: `<hr><center>nginx</center>`).

**Comment by ac000** [comment]
I think you're asking about nginx the web server. Whereas this is the issue tracker for NGINX Unit.

Perhaps you could ask on the [nginx mailing list](https://mailman.nginx.org/mailman/listinfo/nginx)
