### ISSUE TITLE
nginx configuration to redirect to existing maintenance page with env var condition

### ISSUE THREAD

**Issue by Sheelayathakula** [nginx/unit#1367]
Hi Team,

I have a nginx.conf file while is declared this way

server {
  listen       80;
  location / {
    root   /usr/share/nginx/html;
    sub_filter 'ENV_ID' '${ENV_ID}';
    sub_filter 'ENV_MAINTAINANCE_MODE' '${ENV_MAINTAINANCE_MODE}';

    if ('${ENV_MAINTAINANCE_MODE}' = 'Yes') {
        rewrite https://example.com/service-maintenance.html break; 
}

wherein i have the sub_filter, i wanted to use that sub_filter substitutional value in the if condition, if env-maintainance-mode is set to yes then it should redirect to this maintenance.hml page

I'm getting errors if I'm using the sub-filter substitution in if condition. Could you please help me here

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for [NGINX Unit](https://unit.nginx.org/). Please see https://nginx.org/en/community.html for how to get help with the NGINX web server project.
