### ISSUE TITLE
Inconsistency in Supported Language Count Between Repository Description and README

### ISSUE THREAD

**Issue by PalmeseMattia** [nginx/unit#1376]
Hi,

I noticed an inconsistency in the documentation regarding the number of supported programming languages. The repository description mentions "natively executing application code across eight different programming language runtimes," while the README states that it "runs application code in seven languages."

As someone who is not familiar with NGINX, this discrepancy is confusing. Could you please clarify the correct number of supported languages and update the documentation accordingly?

Thank you!

**Comment by ac000** [comment]
Ah, I guess the number in the README wasn't updated for WebAssembly...
