### ISSUE TITLE
grpc idle timeout is affected by  `client_header_timeout header`

### ISSUE THREAD

**Issue by anda-ren** [nginx/unit#1380]
The field `client_header_timeout` affects grpc keep alive idle time out which is unexpected.  

As nginx has  configurations named `http2_idle_timeout ` or `keepalive_timeout`  which explicitly sets the idle timeout , `client_header_timeout` works in the darkness really makes a lot trouble. 

Could someone disable `client_header_timeout`  timer if `http2_idle_timeout ` or `keepalive_timeou`  is set?

You could verify "The field `client_header_timeout` affects grpc keep alive idle time out " by steps below:

**Comment by ac000** [comment]
Hi, 

It looks like this is an [nginx](http://nginx.org/) issue, not NGINX [Unit](https://unit.nginx.org/), which this issue tracker is for.

See [here](http://nginx.org/en/community.html) for how to contact those fine folks...

**Comment by anda-ren** [comment]
> Hi,
> 
> It looks like this is an [nginx](http://nginx.org/) issue, not NGINX [Unit](https://unit.nginx.org/), which this issue tracker is for.
> 
> See [here](http://nginx.org/en/community.html) for how to contact those fine folks...

@ac000 
oh, I entered the wrong room :< thank you
