### ISSUE TITLE
The issue about try_files cmd

### ISSUE THREAD

**Issue by Drakeeagle** [nginx/unit#1381]
my nginx version is 1.16.1. this is my try_filse configure:

```
location / {
     root /home/nginx/html/dist/;
     try_files $uri $uri/ /index.html;
}

location /index.html {
    root /home/nginx/html/dist/
}

```
as what said on nginx.org, if $uri and $uri failed. will redirect to /index.html. pay attention to my **root configure** and i do not configure index config, so the index default value will be index.html.

1. create index.html in file path /home/nginx/html/dist/home/nginx/html/dist/index.html
2. 127.0.0.1/home/nginx/html/dist/ in browser. defalut index file, index.html , will be found, so the finally file path found by nginx is that rootpaht + rui + default index file = /hmoe/nginx/html/dist/home/nginx/html/dist/idnex.html 
3. if index.html existed in the file path of step1, it works. but there was no index.html, failed. Refer to nginx.org, the request will be indirect to from /home/nginx/html/dist/home/nginx/html/dist/index.html to the root path + defautl index =/home/nginx/html/dist/index.html.
4. but the result awlays 403 forbiden. 

i trace the source code and debug them step by step, if redirection triggered .this branch must be tirggerd.
**[enter link description here][1] but tf->names is /index.html, never be null.**

so the reindrect function will be called.
[enter link description here][2]

but always goto to this code , 403 forbiden. because open file failed in the ngx_http_static_modue.
[enter link description here][3]

if tf->names is /index.html, this record may never be null, the branch and redirect never be triggerd, maybe a bug. 

  [1]: https://github.com/nginx/nginx/blob/branches/stable-1.16/src/http/modules/ngx_http_try_files_module.c#L194
  [2]: https://github.com/nginx/nginx/blob/branches/stable-1.16/src/http/modules/ngx_http_try_files_module.c#L209
  [3]: https://github.com/nginx/nginx/blob/branches/stable-1.16/src/http/ngx_http_core_module.c#L1201

**Comment by javorszky** [comment]
Hey @Drakeeagle, welcome to the NGINX Unit repository!

Your issue seems like it's with NGINX itself at https://github.com/nginx/nginx. This repository is for a different project. Would you mind opening this issue on the right repository?

If we're missing something that relates to Unit, we're happy to look again, and please reopen the issue with what we missed.

**Comment by lcrilly** [comment]
> Your issue seems like it's with NGINX itself at https://github.com/nginx/nginx

But please don't open issues there. See https://nginx.org/en/community.html for ways to connect with the NGINX community.
