### ISSUE TITLE
review unit type choice

### ISSUE THREAD

**Issue by gcb** [nginx/unit#1382]
regarding https://github.com/nginx/unit/blob/master/pkg/deb/debian/unit.service#L7

The discussion started a long time ago on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728015 with the proposal to move to `type=simple`, but now more apt choice are available on systemd that do not have the limitations pointed out on simple mode, such as `type=notify-reload` (or even better but with a larger effort in nginx, `type=dbus`)

**Comment by ac000** [comment]
That's for nginx the webserver...

For NGINX Unit, we switched back to `type=forking` to allow per-application logging to work out the box.

It's possible in the future we might implement one of the systemd specific ones, but currently see no real need...
