### ISSUE TITLE
Listeners 127.0.0.1:xx is not working, The prompt already exists, but I haven't seen the configuration anywhere

### ISSUE THREAD

**Issue by oopsoop2** [nginx/unit#1386]
![mspaint_NpngMVMOfH](https://github.com/user-attachments/assets/2132af30-1d9a-43eb-995e-ac32d4eb95c0)
![WindowsTerminal_zcY0C1ByrZ](https://github.com/user-attachments/assets/ad835277-9f95-4a7d-a5f1-a809aded7279)
------------------------------------------------------------------------------------------------------------
It's wonder why it's 0.0.0.0 here?
![mspaint_CdTLtlur1n](https://github.com/user-attachments/assets/156a08cc-4972-4d35-959e-78a65dd69ab1)
 @ac000

**Comment by ac000** [comment]
If you clear the config with

```
$ sudo curl -X DELETE --unix-socket /var/run/control.unit.sock http://localhost/config/
```

Then apply it.

Does it work?

**Comment by oopsoop2** [comment]
> If you clear the config with
> 
> ```
> $ sudo curl -X DELETE --unix-socket /var/run/control.unit.sock http://localhost/config/
> ```
> 
> Then apply it.
> 
> Does it work?

yes, It Works !

**Comment by ac000** [comment]
You perhaps ran into a variation of the "Note" [here](https://unit.nginx.org/configuration/#listeners).
