### ISSUE TITLE
Update the documentation to include the new features introduced in version 1.2

### ISSUE THREAD

**Issue by joseph-pg** [nginx/unit#139]
Unit [introduced a number of new features in version 1.2](https://mailman.nginx.org/pipermail/unit/2018-June/000055.html): the environment variables configuration, php.ini customization, and execution arguments for Go applications; but they're not mentioned anywhere in [the current documentation](https://unit.nginx.org/configuration/).

**Comment by nshadrin** [comment]
Joseph,

You are right, and we are sorry that documentation is lagging behind.
We are planning some updates, and possibly a rewrite of the documentation with a more readable structure.

If you can help, please submit your pull requests here: https://github.com/nginx/unit-docs

If you know who would fit the best for the full-time role of Technical Writer at NGINX, please send them this link: https://www.nginx.com/careers/current-openings/?job_id=1187667

**Comment by joseph-pg** [comment]
Hi, Nick,

I just submitted a pull request [here] (https://github.com/nginx/unit-docs/pull/6).

**Comment by joseph-pg** [comment]
Hi, @nshadrin,

I just submitted a pull request [here] (nginx/unit-docs#6).

**Comment by joseph-pg** [comment]
Hi, @nshadrin,

I just submitted a pull request [here](https://github.com/nginx/unit-docs/pull/6)

**Comment by nshadrin** [comment]
Thanks! We will review this very soon.

**Comment by joseph-pg** [comment]
Nice.

By the way, I'm not sure about the differences between the "admin" and "user" objects in the php.ini customization feature since I don't do PHP, so you may want to edit that part with clearer explanation.

**Comment by nshadrin** [comment]
"admin" settings cannot be redefined from within the application with ini_set().
"user" settings can.

**Comment by joseph-pg** [comment]
Thanks, Nick, it all made sense now.
I've updated the pull request with the explanation.

**Comment by joseph-pg** [comment]
The pull request has been updated with an explanation for dynamic process management.
This feature was added in Unit 0.5.

**Comment by artemkonev** [comment]
Added a section on dynamic process management: http://unit.nginx.org/configuration/#process-management. Thank you for your contribution!
