### ISSUE TITLE
Upgrade wasm-wasi-component to latest Wasmtime

### ISSUE THREAD

**Issue by callahad** [nginx/unit#1392]
Hey friends, it's release prep time. Let's bump to the latest Wasmtime (23.0.2 at time of writing) for our `wasm-wasi-component` module.

There have been interface changes, so this won't be a trivial change to the version string, but hopefully it's nothing too invasive.

Assigning to @avahahn and @javorszky to spread around knowledge. Please ask @ac000 for review when y'all have a patch ready.

**Comment by ac000** [comment]
After that, we can add [this](https://github.com/nginx/unit/issues/1312#issuecomment-2176574568) (which I can do, just adding a link here for remind me).

**Comment by ac000** [comment]
Just for clarity. This isn't about upgrading the wasmtime package as used by the original `wasm` language module, but rather upgrading the `wasm-wasi-component` language module (as found under `src/wasm-wasi-component`) to use the latest version of the wasmtime crate.
