### ISSUE TITLE
Change dir to app dir for Go applications

### ISSUE THREAD

**Issue by andboson** [nginx/unit#14]
Go apps needs configs, templates, etc often. So we need to change dir to the application directory and run from it.

**Comment by mar0x** [comment]
You can use 'working_directory' directive for particular application. We will add it to the documentation ASAP.

**Comment by andboson** [comment]
Thanks for answer,
Another question: how Unit will communicate with my Go app? Where can I set http-port of Go app? Like proxy-pass from nginx...

**Comment by mar0x** [comment]
unit.ListenAndServe(..) will use unix socket and shared memory segment created by Unit for communication. Actual TCP port listen, connection establishment etc. is done internally by Unit. Listen port can be (re-)configured via the control socket using JSON.

**Comment by andboson** [comment]
Hm, something wrong in my configs?

My Go app listens to 8001 port.

`
$ sudo service unitd dumpconfig                                                     
The following configuration has been saved to /etc/unit/config:
{
	"applications": {
		"sale_go": {
			"type": "go",
			"user": "nobody",
			"group": "nogroup",
			"working_directory": "/home/drew/Work/www/app_go",
			"executable": "/home/drew/Work/www/app_go/app"
		}
	},

	"listeners": {
		"*:8001": {
			"application": "sale_go"
		}
	}
}
`
Logs
`
$ sudo tail  /var/log/unitd.log
2017/09/08 09:48:05 net.Listen error: listen tcp 127.0.0.1:8001: bind: address already in use
2017/09/08 09:48:05 net.Listen error: listen tcp 127.0.0.1:8001: bind: address already in use
`

while 
`curl http://localhost:8001/ -d'{}'`

**Comment by mar0x** [comment]
Try to find the process listening the port (sudo netstat -ntlp | grep 8001) and stop it.

**Comment by andboson** [comment]
No )  It`s my mistake. Thanks )

But what about tons of frameworks which use owns http wrappers?

**Comment by mar0x** [comment]
Working directory seems working for now. Let's discuss other frameworks separately.
