### ISSUE TITLE
"error": "Failed to apply new configuration."

### ISSUE THREAD

**Issue by Furuk1** [nginx/unit#1409]
Can someone please tell me how to resolve this error?

json file is:
{
    "listeners": {
        "127.0.0.1:443": {
            "pass": "applications/mockup",
            "tls": {
                "certificate": "fullchain"
            }
        }
    },
    "applications": {
        "mockup": {
            "type": "python 3.9",
            "path": "/var/www/html/mockup",
            "module": "wsgi"
        }
    }
}

execute:
sudo curl -X PUT --data-binary @/etc/unit/mockup.json --unix-socket /var/run/unit/control.sock http://localhost/config

occurred error:
"error": "Failed to apply new configuration."

**Comment by Furuk1** [comment]
unit.log is:
2024/09/02 13:39:06 [alert] 1145771#1145771 bind(\"127.0.0.1:443\") failed (98: Address already in use)
2024/09/02 13:39:06 [alert] 1145774#1145774 failed to apply new conf

**Comment by Furuk1** [comment]
I was able to resolve it.
[1st.]
service nginx stop
[2nd.]
Proxy settings from “nginx” to “unit”. In this case, port 443 is used for nginx, and port 8300 is used for unit.

**Comment by callahad** [comment]
I'm glad you were able to resolve it; thank you for following up :)
