### ISSUE TITLE
PSGI streaming support

### ISSUE THREAD

**Issue by claviola** [nginx/unit#141]
I've noticed that unit correctly sets `psgi.streaming` to false, but I'm testing out a PSGI application that assumes it is available. Are there any plans to add support to it?

**Comment by vividsnow** [comment]
:+1:

**Comment by lexborisov** [comment]
@mar0x 
Like

**Comment by VBart** [comment]
This was actually implemented in https://github.com/nginx/unit/commit/3b2c1d0eaaf8252242d2a164ad768a985e8ded5c and released with Unit 1.8.0.
