### ISSUE TITLE
unitctl binaries should have better version reporting

### ISSUE THREAD

**Issue by callahad** [nginx/unit#1427]
Right now `unitctl --version` just reports the contents of `Cargo.toml`, namely: `"unitctl 0.4.0-beta"`

Things that need to change:

1. `0.4.0-beta` is wrong; our version should follow unit's version
2. If known, we should incorporate and report the commit hash that we built from

**Comment by ac000** [comment]
Hmm, this version is in quite a few places...

```
openapi-config.json:3:  "packageVersion": "0.4.0-beta",
unit-client-rs/Cargo.toml:3:version = "0.4.0-beta"
unit-openapi/Cargo.toml:3:version = "0.4.0-beta"
unit-openapi/README.md:24:- Package version: 0.4.0-beta
unitctl/Cargo.toml:4:version = "0.4.0-beta"
Cargo.lock:2024:version = "0.4.0-beta"
Cargo.lock:2047:version = "0.4.0-beta"
Cargo.lock:2061:version = "0.4.0-beta"
```
