### ISSUE TITLE
Plack integration

### ISSUE THREAD

**Issue by claviola** [nginx/unit#143]
It'd be nice if unit would at least set the `PLACK_SERVER` environment variable as shown in [Plack::Loader](https://metacpan.org/pod/release/MIYAGAWA/Plack-1.0045/lib/Plack/Loader.pm). This is not a high priority issue as there's no unit specific backend for Plack to load, but maybe it could "lie" about being uwsgi or one of the other implementations for now.

**Comment by VBart** [comment]
You can already set it to any preferred value using the `environment` object, e.g.:
```json
{
    "type": "perl",
    "script": "/www/bugtracker/app.psgi",
    "working_directory": "/www/bugtracker",
    "environment": {
        "PLACK_SERVER": "foobar"
    }
}
```

**Comment by claviola** [comment]
That's true, but Plack makes certain assumptions based on the servers it knows. If unit could emulate one of them (like uwsgi) that'd be ideal for a drop-in replacement eventually.

**Comment by VBart** [comment]
I've looked through the Plack sources and couldn't found any mentions of uwsgi. Could you point out what certain assumptions it makes?

**Comment by claviola** [comment]
I've got it the other way around, apparently. I thought I'd seen a specific handler for it, but it seems like it's only uwsgi itself that has plack specific code. My apologies.
