### ISSUE TITLE
Error in the hyper legacy client: client error (Connect)

### ISSUE THREAD

**Issue by zwn** [nginx/unit#1438]
When using `unitctl` I always see this message: `Error in the hyper legacy client: client error (Connect)`
Afterwards everything seems to be working.

I am working with version 1.33 of both `unitd` and `unitctl` on Debian 12. Default install, no changes.

**Comment by avahahn** [comment]
Hello there! 
We just merged a fix for this. If you are interested in trying a nightly build fresh from our CI pipelines to verify that our fix is working in your environment I can link you to one here:
https://github.com/nginx/unit/actions/runs/11019141121/artifacts/1973044785

I stress that this is not a supported release

**Comment by avahahn** [comment]
Closing issue for now, but if you continue to experience this once you are running the new code feel free to reopen, thank you!

**Comment by zwn** [comment]
> Hello there! We just merged a fix for this. If you are interested in trying a nightly build fresh from our CI pipelines to verify that our fix is working in your environment I can link you to one here: https://github.com/nginx/unit/actions/runs/11019141121/artifacts/1973044785

Thanks for the fix. I tested the linked artifact but it is straight 1.33.0 release. I tried to find the correct link, but the [build job](https://github.com/nginx/unit/actions/runs/11019141121/job/30600998116) contains the same link so I am lost.

**Comment by ac000** [comment]
@zwn 

Are you sure?

```
$ ls -l unitctl-*
-rwxr-xr-x 1 andrew andrew 12214560 Sep 17 02:26 unitctl-1.33.0-x86_64-unknown-linux-gnu
-rwxr-xr-x 1 andrew andrew 15447840 Sep 24 17:48 unitctl-merge-x86_64-unknown-linux-gnu
```

The second binary is from the above link.

Let's take a closer look

```console
$ readelf -a unitctl-1.33.0-x86_64-unknown-linux-gnu | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libssl.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
$ readelf -a unitctl-merge-x86_64-unknown-linux-gnu | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

The 1.33.0 version dynamically links against OpenSSL, the other does not...

**Comment by zwn** [comment]
Sorry, you are right. I messed up while copying the executable to the target machine (2 different accounts). I can confirm it works as expected. Thanks again and sorry for the trouble.
