### ISSUE TITLE
resource interpreted as stylesheet but transferred with mime type text/html

### ISSUE THREAD

**Issue by OFranke** [nginx/unit#146]
Hi,
I am getting above warning/error in Chrome when setting up a laravel php application that works seamlessly with other webserver setups.

I am using the official full docker image from here: https://hub.docker.com/r/nginx/unit/

It looks like in response header, the nginx unit is returning type html instead of css for .css files. Is there any way I can specify that the server should return "Content-Type: text/css; charset=UTF-8" for *.css files?

I did not find any config for that in the docs.

Cheers,
Oliver

**Comment by AkulovNV** [comment]
Because to process static you need to configure nginx before the unit

**Comment by tippexs** [comment]
Closed due to timeout.

It is implemented using static file sharing: https://unit.nginx.org/configuration/#static-files
