### ISSUE TITLE
Problem with ios18 with nginx reverse proxy

### ISSUE THREAD

**Issue by ajabir** [nginx/unit#1468]
Has anyone seen issue with nginx reverse proxy with latest iPhone iOS18?  We have a java app listening on http port 8080 behind nginx https.  Whenever a user logs in (by providing username and password), the mobile browser returns back to the login page even though the authentication is correct.  This issue is not happening in all other platform, including previous versions of iOS.  It would seem that the session token after the authentication was not received by iOS18, resulting in login page to be presented again.

Is there any startup flag for nginx that I can enable to capture more debugging info so that I can have more detailed info on the problem that I can report to the iOS18 people?

I thought, I would need to capture some related info before posting to related iOS18 pages.

Thank you, and apologies if this question is out of the scope of this forum.

Regards,
Abdullah

**Comment by ac000** [comment]
Do you mean NGINX Unit (this project) or really nginx the web server? Who can be found over [here](https://nginx.org/en/community.html).

**Comment by ajabir** [comment]
Sorry about that.  I will take this topic to the relevant forums as mentioned.  I will close this ticket then.  Apologies again.
