### ISSUE TITLE
Question: Error logs

### ISSUE THREAD

**Issue by OFranke** [nginx/unit#147]
Hi,

I am trying to run a PHP application that works on main page but keeps crashing on different other pages - its not a code issue, it must be something with the server setup. Ids there any way to debug? I would like to specify an error log file or something. In the docs, I found a way to specify access_log file via the JSON API, but nothing similar for error_log.d

Also I did not find much guidance on general debugging in the docs. Could some1 advise me?

I am using the full docker image from https://hub.docker.com/r/nginx/unit/ 

Cheers,
Oliver

**Comment by AkulovNV** [comment]
In your case, the log of the unit can be viewed in run docker container
`/var/log/unit.log`
or via stdout
`docker log unit`

**Comment by OFranke** [comment]
That’s where I was also checking but the logfile was totally empty ---- On Mi, 11 Jul 2018 08:47:22 +0200  Nikolai Akulov<notifications@github.com> wrote ----In your case, the log of the unit can be viewed in run docker container /var/log/unit.log or via stdout docker log unit  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AkulovNV** [comment]
check your application config
If one script is responsible for processing routes you need "script" in application configure, for example:

>     "applications": {
>         "blogs": {
>             "type": "php",
>             "user": "nobody",
>             "group": "nobody",
>             "root": "/path/application",
>             "index": "index.php",
>             **"script": "index.php"**
>         }
>     }

**Comment by VBart** [comment]
The error log in docker containers is redirected to log collector. It should be accessible via `docker log` command.

Here's a relevant part of Dockerfile:
```
# forward log to docker log collector
RUN ln -sf /dev/stdout /var/log/unit.log
```

**Comment by OFranke** [comment]
great guys, I got it running. Thank you! :-)
