### ISSUE TITLE
Fix failing wasm-wasi-component test

### ISSUE THREAD

**Issue by javorszky** [nginx/unit#1477]
The wasm-wasi-component test keeps failing for no apparent reason. This is an issue to track that we're working on it.

**Comment by ac000** [comment]
Was looking at this last night.

It runs fine on Fedora 40. Fails on Debian 11.

This thing seems generally pretty fragile...

**Comment by ac000** [comment]
The pytest wasm-wasi-component built on Ubuntu 24.04 does run under wasmtime v24 (on Fedora at least)

**Comment by callahad** [comment]
@ac000 If you have any other notes, might be worth dropping them here. I'll let @javorszky run with this as the assignee.

**Comment by ac000** [comment]
The hello_world component built under Ubuntu 24.04 does _not_ run under Unit on Fedora either. Same error I beleive

```
2024/10/29 03:31:00 [alert] 490364#490364 failed to create initial state

Caused by:
    0: failed to compile component
    1: WebAssembly translation error
    2: Invalid input WebAssembly code at offset 15939: zero byte expected
```

**Comment by ac000** [comment]
Now that I'm on Fedora 41, it's broken here also... (from pytests)

```
2024/11/06 21:08:50 [alert] 107196#107196 failed to create initial state

Caused by:
    0: failed to compile component
    1: WebAssembly translation error
    2: Invalid input WebAssembly code at offset 15936: zero byte expected
```

**Comment by ac000** [comment]
Looks like we may be hitting this https://github.com/bytecodealliance/wasmtime/issues/9130

Enabling the `gc` feature fixes it on Fedora 41, I'll test it on the GH stuff...

**Comment by ac000** [comment]
I wonder if we can just move to wasmtime 26.0.1...

Seems like it...
