### ISSUE TITLE
Image building proposal

### ISSUE THREAD

**Issue by metanovii** [nginx/unit#1488]
Hi, I have a question about building images. Is it possible to build images with tags like 1.33.0-php8.3.0 (the minor version is not specified now, which makes it difficult to keep the version up to date)

**Comment by callahad** [comment]
If you need a specific version, you can build it locally: Edit the Makefile in `pkg/docker/`, change the `VERSIONS_php` variable, and run `make dockerfiles` to generate a more specifically versioned Dockerfile.

You can then build an image from that with, e.g., `make build-php8.3.0` (which is just a shortcut for `docker build --pull --no-cache -t unit:1.33.0 -f Dockerfile.php8.3.0`)
