### ISSUE TITLE
python virtual environment configuration

### ISSUE THREAD

**Issue by mogui** [nginx/unit#15]
I think that for python  application type, there should be some sort of congfiguration to specify a virtual env to be used, since ther's no control now over which python executable should be used, I suppose system one is used. 
So if the application needs dependancies (sure it does! ) we have to install them system wide and it's not good !

**Comment by k4ml** [comment]
Adding the virtualenv dir from the app script seem to work for now:-

```python
import os
import sys

CWD = os.path.abspath(os.path.dirname(__file__))
sys.path.append(os.path.join(CWD, 'venv/lib/python2.7/site-packages'))

import requests

def application(environ, start_response):
    start_response('200 OK', [('Content-Type', 'text/plain')])
    resp = requests.get('https://httpbin.org/get')
    return [resp.content]
```
But of course having specific config is way much better.

**Comment by mogui** [comment]
Yes I know it could be done like this, but a config t's definitely better

**Comment by sboisson** [comment]
Is it part of a release yet? I don’t see any mention of virtualenv in documentation (just this ticket)?

**Comment by VBart** [comment]
@sboisson it is: https://www.nginx.com/blog/unit-0-3-beta-release-available-now/
The documentation is outdated a bit.
