### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AkulovNV** [nginx/unit#150]
Hi,
please add documentation for the application settings

Fox example, from 
http://localhost/config/settings/max_mody_size
what values do allow this parameter take: bytes, Kb, Mb, Gb ...
I mean

```
...
"max_body_size": 8388608
"max_body_size": 128Mb
"max_body_size": 1Gb
...
```

How options section works now and what options are available in "admin", "user", etc

```
      "options": {
          "file": "/php.ini",
          "admin": {
              "memory_limit": "128M",
              "post_max_size": "32M",
              "upload_max_filesize": "64M"
          },
```

Thanks

**Comment by joseph-pg** [comment]
Hi!

> Fox example, from
> http://localhost/config/settings/max_mody_size
> what values do allow this parameter take: bytes, Kb, Mb, Gb ...

It [takes bytes](https://mailman.nginx.org/pipermail/unit/2018-July/000075.html).

> How options section works now and what options are available in "admin", "user", etc

You can configure anything that's available in php.ini.
Here's a complete documentation of the feature, including an explanation for the difference between `admin` and `user` (taken from my pull request): https://github.com/joseph-pg/unit-docs/blob/unit-1.2/source/configuration.rst#php-application

**Comment by AkulovNV** [comment]
@joseph-pg thanks!

**Comment by artemkonev** [comment]
Better late than never, here's the detailed info: http://unit.nginx.org/configuration/#php-application
