### ISSUE TITLE
otel-enabled build fails on systems without openssl.pc

### ISSUE THREAD

**Issue by thresheek** [nginx/unit#1510]
Hello!

I've noticed the following on an operating system that doesn't have an openssl.pc:

```
checking for OTEL requirements:
  - checking for rust compiler ... found
  - checking for cargo ... found
  - checking for OpenSSL library ... found
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
```

On this OS, the .pc file is named openssl11.pc - but that doesnt really matter in this case I think.

Looking at the code, it comes the following part of `auto/otel`:

```
    nxt_feature="OpenSSL library"
    nxt_feature_run=yes
    nxt_feature_incs=
    nxt_feature_libs="-lssl -lcrypto"
    nxt_feature_test="#include <openssl/ssl.h>

                      int main(void) {
                          SSL_library_init();
                          return 0;
                      }"
    . auto/feature

    if [ ! $nxt_found = yes ]; then
        $echo
        $echo $0: error: OpenTelemetry support requires OpenSSL.
        $echo
        exit 1;
    fi

    NXT_OTEL_LIBS="-lssl -lcrypto"
    if [ $(which pkg-config) ]; then
        NXT_OTEL_LIBS="$(pkg-config openssl --cflags --libs)"
    fi
    cat << END >> $NXT_AUTO_CONFIG_H

```

Why do we even need this check when we have `auto/ssltls` ?  Given the fact that `auto/ssltls` is getting called in `configure` much earlier, cant we just reuse the knowledge we already gathered?

**Comment by ac000** [comment]
> Why do we even need this check when we have auto/ssltls ? Given the fact that auto/ssltls is getting called in configure much earlier, cant we just reuse the knowledge we already gathered?

They're really for two different things and you may want OTEL but not TLS/https support...

What OS was this?

**Comment by thresheek** [comment]
That's Amazon Linux 2 with openssl11-devel.

**Comment by ac000** [comment]
I think the simplest thing to do is to just drop the pkg-config check. If we got there we already successfully built wirh `-lssl -lcrypto`, so just go with that and it matches what we do in `auto/ssltls`.
