### ISSUE TITLE
create config failed by curl

### ISSUE THREAD

**Issue by yuntianming0613** [nginx/unit#152]
When I used command:
curl -X PUT -d @/usr/share/doc/unit-python3.5/examples/unit.config  \
       --unix-socket /var/run/control.unit.sock http://localhost/config/applications/testUnit

 It returned an error
{
                "error": "Invalid configuration.",
                "detail": "Application must have the \"type\" property set."
}

My unit.config file as below.

{
        "applications": {
                "example_python": {
                        "type": "python 3.5",
                        "user": "nobody",
                        "processes": 2,
                        "path": "/usr/share/doc/unit-python3.5/examples/python-app",
                        "module": "wsgi"
                }
        },

        "listeners": {
                "*:8400": {
                        "application": "example_python"
                }
        }
}

but when I used command with the same config file:
service unit loadconfig /usr/share/doc/unit-python3.5/examples/unit.config
it works! so the json file is right!

Dose anybody meet the same problem with me ? it really strange!

**Comment by VBart** [comment]
You are trying to PUT application object into configuration. The application object looks like this:
```json
 {
    "type": "python 3.5",
    "user": "nobody",
    "processes": 2,
    "path": "/usr/share/doc/unit-python3.5/examples/python-app",
    "module": "wsgi"
}
```
But your `unit.config` is different. It contains full configuration instead. If you want to upload full configuration, then the URI should be just `/config/`.

**Comment by yuntianming0613** [comment]
Thank you very much! it works!

By the way， how to start unit with debug level?
As the troubleshooting said, 
Debug verbosity level of the log is enabled during configuration time:
# ./configure --debug

Should I add  the  parameter in curl command line？
I just try the command as below, it dosen't work.
curl  -X PUT -d   @/usr/share/doc/unit-python3.5/examples/unit.config  --unix-socket /var/run/control.unit.sock http://localhost/config/   ./configure --debug

**Comment by VBart** [comment]
It's a compile-time flag. It used when you compile Unit from sources to make a debug build. If you have installed Unit from our packages, then there should be `unitd-debug` binary, which is a debug version of Unit demon built with this flag.

**Comment by yuntianming0613** [comment]
I get it, Thank You!
