### ISSUE TITLE
wsgi.py couldn't import models

### ISSUE THREAD

**Issue by yuntianming0613** [nginx/unit#153]
**I use the example wsgi.py(as below)  on unit, it works.**
_wsgi.py_:

import os
import datetime
import sys
#import testRunner 

def application(environ, start_response):
    output = datetime.datetime.now().strftime("%Y-%m-%d %I:%M:%S %p")
    output += "\n\nPython: "
    output += sys.version
    output += "\n\nENV Variables:\n\n"
    for param in os.environ.keys():
         output += param
         output += "\t"
         output += os.environ[param]
         output += "\n"
    start_response('200 OK', [('Content-type', 'text/plain')])
    return [s.encode('utf8') for s in output]_

**But if I import a extremly sample model(testRunner.py, as below) and  restrat the unit, it returned error.**

ner_collection3" application: [alert] 23587#23587 Python failed to import module "wsgi"
[alert] 23586#23586 failed to apply new conf
[alert] 23585#23585 failed to apply previous configuration

_testRunner.py:

def a()
  print('test')_

**The testRunner.py in the same folder with the wsgi.py. Maybe python couldn't find the testRunner, so I copy the testRunner.py to the same folder with the  sys.py/os.py， but still not working, errorinfo didn't change.**

**any ideals?**

**Comment by BrainGithub** [comment]
upupup

**Comment by yuntianming0613** [comment]
thank you！
