### ISSUE TITLE
Remove the version number from Server Response Header

### ISSUE THREAD

**Issue by josephapg** [nginx/unit#158]
It would be nice to have an option to remove Unit version number from the `Server` header, just like what nginx do when [`server_tokens`](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokensl) is set to `off`.

This will eliminate the need of manually removing it using HAProxy (`http-response replace-header Server                    (.*)(\/[\d\.]+) \1` — this turns `Server: Unit/[version]` to `Server: Unit`) or something similar in front of Unit.

**Comment by whardier** [comment]
It would be nice to allow overriding the header through the response as well.

**Comment by migster42** [comment]
Something like Nginx' `server_tokens` would be nice! Exposing the version is always a pentest finding for our projects with Unit.

**Comment by ac000** [comment]
The below patch adds a **global** config setting **"version_string"** that can be set to replace the version number usually returned in responses.

E.g

```json
"version_string": "",
```

Will produce

```
Server: Unit
```

Whereas

```json
"version_string": "0.0.0",
```

will produce

```
Server: Unit/0.0.0
```

```diff
diff --git a/src/nxt_conf_validation.c b/src/nxt_conf_validation.c
index 537a3fb7..c21781ef 100644
--- a/src/nxt_conf_validation.c
+++ b/src/nxt_conf_validation.c
@@ -285,6 +285,9 @@ static nxt_conf_vldt_object_t  nxt_conf_vldt_root_members[] = {
         .name       = nxt_string("access_log"),
         .type       = NXT_CONF_VLDT_STRING | NXT_CONF_VLDT_OBJECT,
         .validator  = nxt_conf_vldt_access_log,
+    }, {
+        .name       = nxt_string("version_string"),
+        .type       = NXT_CONF_VLDT_STRING,
     },
 
     NXT_CONF_VLDT_END
diff --git a/src/nxt_http_request.c b/src/nxt_http_request.c
index e78975aa..c734ce43 100644
--- a/src/nxt_http_request.c
+++ b/src/nxt_http_request.c
@@ -635,7 +635,13 @@ nxt_http_request_header_send(nxt_task_t *task, nxt_http_request_t *r,
         goto fail;
     }
 
-    nxt_http_field_set(server, "Server", NXT_SERVER);
+    if (nxt_version_string == NULL) {
+        nxt_http_field_set(server, "Server", NXT_SERVER);
+    } else {
+        nxt_http_field_name_set(server, "Server");
+        server->value = nxt_version_string;
+        server->value_length = nxt_strlen(nxt_version_string);
+    }
 
     if (r->resp.date == NULL) {
         date = nxt_list_zero_add(r->resp.fields);
diff --git a/src/nxt_main.h b/src/nxt_main.h
index b0cdc2d3..3f80b793 100644
--- a/src/nxt_main.h
+++ b/src/nxt_main.h
@@ -11,7 +11,8 @@
 #include <nxt_auto_config.h>
 #include <nxt_version.h>
 
-#define NXT_SERVER                   "Unit/" NXT_VERSION
+#define NXT_NAME                     "Unit"
+#define NXT_SERVER                   NXT_NAME "/" NXT_VERSION
 
 typedef struct nxt_port_s            nxt_port_t;
 typedef struct nxt_task_s            nxt_task_t;
diff --git a/src/nxt_router.c b/src/nxt_router.c
index baede83b..440be51a 100644
--- a/src/nxt_router.c
+++ b/src/nxt_router.c
@@ -250,6 +250,8 @@ extern const nxt_http_request_state_t  nxt_http_websocket;
 
 nxt_router_t  *nxt_router;
 
+u_char        *nxt_version_string;
+
 static const nxt_str_t http_prefix = nxt_string("HTTP_");
 static const nxt_str_t empty_prefix = nxt_string("");
 
@@ -1574,6 +1576,7 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
     static nxt_str_t  listeners_path = nxt_string("/listeners");
     static nxt_str_t  routes_path = nxt_string("/routes");
     static nxt_str_t  access_log_path = nxt_string("/access_log");
+    static nxt_str_t  version_string_path = nxt_string("/version_string");
 #if (NXT_TLS)
     static nxt_str_t  certificate_path = nxt_string("/tls/certificate");
     static nxt_str_t  conf_commands_path = nxt_string("/tls/conf_commands");
@@ -2050,6 +2053,31 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
         }
     }
 
+    if (nxt_version_string != NULL) {
+        nxt_free(nxt_version_string);
+    }
+
+    value = nxt_conf_get_path(root, &version_string_path);
+
+    if (value != NULL) {
+        size_t     len;
+        nxt_str_t  ver;
+
+        nxt_conf_get_string(value, &ver);
+
+        len = strlen(NXT_NAME) + ver.length + 2;
+
+        nxt_version_string = p = nxt_malloc(len);
+
+        p = nxt_cpystr(p, (const u_char *) NXT_NAME);
+        if (ver.length > 0) {
+            p = nxt_cpystr(p, (const u_char *) "/");
+            p = nxt_cpystrn(p, ver.start, ver.length + 1);
+        }
+    } else {
+        nxt_version_string = NULL;
+    }
+
     ret = nxt_tstr_state_done(rtcf->tstr_state, NULL);
     if (nxt_slow_path(ret != NXT_OK)) {
         goto fail;
diff --git a/src/nxt_router.h b/src/nxt_router.h
index 11094960..95f0ed37 100644
--- a/src/nxt_router.h
+++ b/src/nxt_router.h
@@ -257,5 +257,6 @@ void nxt_router_access_log_reopen_handler(nxt_task_t *task,
 
 extern nxt_router_t  *nxt_router;
 
+extern u_char        *nxt_version_string;
 
 #endif  /* _NXT_ROUTER_H_INCLUDED_ */
```

**Comment by ac000** [comment]
Slightly improved patch. Rather than using a global variable for the version string which may have race conditions, stick it in the router conf structure.

```diff
diff --git a/src/nxt_conf_validation.c b/src/nxt_conf_validation.c
index 537a3fb7..c21781ef 100644
--- a/src/nxt_conf_validation.c
+++ b/src/nxt_conf_validation.c
@@ -285,6 +285,9 @@ static nxt_conf_vldt_object_t  nxt_conf_vldt_root_members[] = {
         .name       = nxt_string("access_log"),
         .type       = NXT_CONF_VLDT_STRING | NXT_CONF_VLDT_OBJECT,
         .validator  = nxt_conf_vldt_access_log,
+    }, {
+        .name       = nxt_string("version_string"),
+        .type       = NXT_CONF_VLDT_STRING,
     },
 
     NXT_CONF_VLDT_END
diff --git a/src/nxt_http_request.c b/src/nxt_http_request.c
index e78975aa..11be5536 100644
--- a/src/nxt_http_request.c
+++ b/src/nxt_http_request.c
@@ -622,8 +622,9 @@ void
 nxt_http_request_header_send(nxt_task_t *task, nxt_http_request_t *r,
     nxt_work_handler_t body_handler, void *data)
 {
-    u_char            *p, *end;
-    nxt_http_field_t  *server, *date, *content_length;
+    u_char             *p, *end;
+    nxt_http_field_t   *server, *date, *content_length;
+    nxt_router_conf_t  *rtcf;
 
     /*
      * TODO: "Server", "Date", and "Content-Length" processing should be moved
@@ -635,7 +636,15 @@ nxt_http_request_header_send(nxt_task_t *task, nxt_http_request_t *r,
         goto fail;
     }
 
-    nxt_http_field_set(server, "Server", NXT_SERVER);
+    rtcf = r->conf->socket_conf->router_conf;
+
+    if (rtcf->version_string == NULL) {
+        nxt_http_field_set(server, "Server", NXT_SERVER);
+    } else {
+        nxt_http_field_name_set(server, "Server");
+        server->value = rtcf->version_string;
+        server->value_length = nxt_strlen(rtcf->version_string);
+    }
 
     if (r->resp.date == NULL) {
         date = nxt_list_zero_add(r->resp.fields);
diff --git a/src/nxt_main.h b/src/nxt_main.h
index b0cdc2d3..3f80b793 100644
--- a/src/nxt_main.h
+++ b/src/nxt_main.h
@@ -11,7 +11,8 @@
 #include <nxt_auto_config.h>
 #include <nxt_version.h>
 
-#define NXT_SERVER                   "Unit/" NXT_VERSION
+#define NXT_NAME                     "Unit"
+#define NXT_SERVER                   NXT_NAME "/" NXT_VERSION
 
 typedef struct nxt_port_s            nxt_port_t;
 typedef struct nxt_task_s            nxt_task_t;
diff --git a/src/nxt_router.c b/src/nxt_router.c
index baede83b..a87aa11f 100644
--- a/src/nxt_router.c
+++ b/src/nxt_router.c
@@ -1574,6 +1574,7 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
     static nxt_str_t  listeners_path = nxt_string("/listeners");
     static nxt_str_t  routes_path = nxt_string("/routes");
     static nxt_str_t  access_log_path = nxt_string("/access_log");
+    static nxt_str_t  version_string_path = nxt_string("/version_string");
 #if (NXT_TLS)
     static nxt_str_t  certificate_path = nxt_string("/tls/certificate");
     static nxt_str_t  conf_commands_path = nxt_string("/tls/conf_commands");
@@ -1606,6 +1607,24 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
         rtcf->threads = nxt_ncpu;
     }
 
+    value = nxt_conf_get_path(root, &version_string_path);
+
+    if (value != NULL) {
+        nxt_str_t  ver;
+
+        nxt_conf_get_string(value, &ver);
+
+        size = strlen(NXT_NAME) + ver.length + 2;
+
+        rtcf->version_string = p = nxt_mp_alloc(mp, size);
+
+        p = nxt_cpystr(p, (const u_char *) NXT_NAME);
+        if (ver.length > 0) {
+            p = nxt_cpystr(p, (const u_char *) "/");
+            p = nxt_cpystrn(p, ver.start, ver.length + 1);
+        }
+    }
+
     conf = nxt_conf_get_path(root, &static_path);
 
     ret = nxt_router_conf_process_static(task, rtcf, conf);
diff --git a/src/nxt_router.h b/src/nxt_router.h
index 11094960..0f32c0ae 100644
--- a/src/nxt_router.h
+++ b/src/nxt_router.h
@@ -54,6 +54,8 @@ typedef struct {
 
     nxt_router_access_log_t  *access_log;
     nxt_tstr_t               *log_format;
+
+    u_char                   *version_string;
 } nxt_router_conf_t;
 
 
```

**Comment by alejandro-colomar** [comment]
> Slightly improved patch. Rather than using a global variable for the version string which may have race conditions, stick it in the router conf structure.
> 
> ```diff
> diff --git a/src/nxt_conf_validation.c b/src/nxt_conf_validation.c
> index 537a3fb7..c21781ef 100644
> --- a/src/nxt_conf_validation.c
> +++ b/src/nxt_conf_validation.c
> @@ -285,6 +285,9 @@ static nxt_conf_vldt_object_t  nxt_conf_vldt_root_members[] = {
>          .name       = nxt_string("access_log"),
>          .type       = NXT_CONF_VLDT_STRING | NXT_CONF_VLDT_OBJECT,
>          .validator  = nxt_conf_vldt_access_log,
> +    }, {
> +        .name       = nxt_string("version_string"),

How about s/version_string/version/?

> +        .type       = NXT_CONF_VLDT_STRING,
>      },
>  
>      NXT_CONF_VLDT_END
> diff --git a/src/nxt_http_request.c b/src/nxt_http_request.c
> index e78975aa..11be5536 100644
> --- a/src/nxt_http_request.c
> +++ b/src/nxt_http_request.c
> @@ -622,8 +622,9 @@ void
>  nxt_http_request_header_send(nxt_task_t *task, nxt_http_request_t *r,
>      nxt_work_handler_t body_handler, void *data)
>  {
> -    u_char            *p, *end;
> -    nxt_http_field_t  *server, *date, *content_length;
> +    u_char             *p, *end;
> +    nxt_http_field_t   *server, *date, *content_length;
> +    nxt_router_conf_t  *rtcf;
>  
>      /*
>       * TODO: "Server", "Date", and "Content-Length" processing should be moved
> @@ -635,7 +636,15 @@ nxt_http_request_header_send(nxt_task_t *task, nxt_http_request_t *r,
>          goto fail;
>      }
>  
> -    nxt_http_field_set(server, "Server", NXT_SERVER);
> +    rtcf = r->conf->socket_conf->router_conf;
> +
> +    if (rtcf->version_string == NULL) {
> +        nxt_http_field_set(server, "Server", NXT_SERVER);
> +    } else {
> +        nxt_http_field_name_set(server, "Server");
> +        server->value = rtcf->version_string;
> +        server->value_length = nxt_strlen(rtcf->version_string);
> +    }
>  
>      if (r->resp.date == NULL) {
>          date = nxt_list_zero_add(r->resp.fields);
> diff --git a/src/nxt_main.h b/src/nxt_main.h
> index b0cdc2d3..3f80b793 100644
> --- a/src/nxt_main.h
> +++ b/src/nxt_main.h
> @@ -11,7 +11,8 @@
>  #include <nxt_auto_config.h>
>  #include <nxt_version.h>
>  
> -#define NXT_SERVER                   "Unit/" NXT_VERSION
> +#define NXT_NAME                     "Unit"
> +#define NXT_SERVER                   NXT_NAME "/" NXT_VERSION
>  
>  typedef struct nxt_port_s            nxt_port_t;
>  typedef struct nxt_task_s            nxt_task_t;
> diff --git a/src/nxt_router.c b/src/nxt_router.c
> index baede83b..a87aa11f 100644
> --- a/src/nxt_router.c
> +++ b/src/nxt_router.c
> @@ -1574,6 +1574,7 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
>      static nxt_str_t  listeners_path = nxt_string("/listeners");
>      static nxt_str_t  routes_path = nxt_string("/routes");
>      static nxt_str_t  access_log_path = nxt_string("/access_log");
> +    static nxt_str_t  version_string_path = nxt_string("/version_string");
>  #if (NXT_TLS)
>      static nxt_str_t  certificate_path = nxt_string("/tls/certificate");
>      static nxt_str_t  conf_commands_path = nxt_string("/tls/conf_commands");
> @@ -1606,6 +1607,24 @@ nxt_router_conf_create(nxt_task_t *task, nxt_router_temp_conf_t *tmcf,
>          rtcf->threads = nxt_ncpu;
>      }
>  
> +    value = nxt_conf_get_path(root, &version_string_path);
> +
> +    if (value != NULL) {
> +        nxt_str_t  ver;
> +
> +        nxt_conf_get_string(value, &ver);
> +
> +        size = strlen(NXT_NAME) + ver.length + 2;
> +
> +        rtcf->version_string = p = nxt_mp_alloc(mp, size);
> +
> +        p = nxt_cpystr(p, (const u_char *) NXT_NAME);
> +        if (ver.length > 0) {
> +            p = nxt_cpystr(p, (const u_char *) "/");
> +            p = nxt_cpystrn(p, ver.start, ver.length + 1);
> +        }
> +    }

I suggest setting unconditionally the string here (`rtcf->version[_string] = NXT_VERSION` if the configuration was omitted), and then we don't have a conditional in the request.

> +
>      conf = nxt_conf_get_path(root, &static_path);
>  
>      ret = nxt_router_conf_process_static(task, rtcf, conf);
> diff --git a/src/nxt_router.h b/src/nxt_router.h
> index 11094960..0f32c0ae 100644
> --- a/src/nxt_router.h
> +++ b/src/nxt_router.h
> @@ -54,6 +54,8 @@ typedef struct {
>  
>      nxt_router_access_log_t  *access_log;
>      nxt_tstr_t               *log_format;
> +
> +    u_char                   *version_string;
>  } nxt_router_conf_t;
>  
>  
> ```
