### ISSUE TITLE
Fixed test with random.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#159]
Hi.

```
diff -r 37912dfce67b src/test/nxt_tests.c
--- a/src/test/nxt_tests.c	Tue Aug 07 20:03:58 2018 +0300
+++ b/src/test/nxt_tests.c	Wed Aug 08 02:14:29 2018 -0400
@@ -70,9 +70,11 @@

 #endif

+#if (NXT_TESTS)
     if (nxt_random_test(thr) != NXT_OK) {
         return 1;
     }
+#endif

     if (nxt_term_parse_test(thr) != NXT_OK) {
         return 1;
```

Thanks.

**Comment by VBart** [comment]
To `make tests` you have to run `./configure --tests`.

**Comment by hongzhidao** [comment]
But I think it's better to run well after ./configure.

./configure && make tests

**Comment by hongzhidao** [comment]
``` ./configure && make tests```

```
cc1: warnings being treated as errors
src/test/nxt_tests.c: In function 'main':
src/test/nxt_tests.c:73: error: implicit declaration of function 'nxt_random_test'
make: *** [build/src/test/nxt_tests.o] Error 1
```

**Comment by VBart** [comment]
@hongzhidao The `--tests` option was introduced especially for configuring tests. If you make it optional and silently skip some tests, then Unit won't be properly tested. That may happen accidentally when someone will forget about the option.

**Comment by hongzhidao** [comment]
Get it, thanks for your explanation.
