### ISSUE TITLE
Fix recv EAGAIN after epoll_wait?

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#164]
Hi.

First of all, I'm not sure it's an issue since my poor experience in epoll event.
But please take a look the following patch.

I have one question about epoll.
Is it possible to happen that the first time to call recv returns EAGAIN involked after epoll_wait?

If it's possible, it seems nxt_conn_read should be fixed.
Because after epoll_wait, the state of read is NXT_EVENT_ACTIVE  indicates
nxt_fd_event_is_disabled is false, thus there isn't any chance to call nxt_fd_event_enable_read again.
Compare to nginx source code, it's handled well.

Thanks.

```
diff -r 1aab95ef70a6 src/nxt_conn_read.c
--- a/src/nxt_conn_read.c	Tue Sep 04 02:30:27 2018 +0300
+++ b/src/nxt_conn_read.c	Fri Sep 14 05:10:20 2018 -0400
@@ -64,13 +64,13 @@
             state = c->read_state;
         }

+        nxt_fd_event_block_read(engine, &c->socket);
+
         if (n > 0) {
             c->nbytes = n;

             nxt_recvbuf_update(c->read, n);

-            nxt_fd_event_block_read(engine, &c->socket);
-
             if (state->timer_autoreset) {
                 nxt_timer_disable(engine, &c->read_timer);
             }
@@ -84,7 +84,6 @@
         }

         if (n != NXT_AGAIN) {
-            nxt_fd_event_block_read(engine, &c->socket);
             nxt_timer_disable(engine, &c->read_timer);

             wq = &engine->fast_work_queue;
diff -r 1aab95ef70a6 src/nxt_controller.c
--- a/src/nxt_controller.c	Tue Sep 04 02:30:27 2018 +0300
+++ b/src/nxt_controller.c	Fri Sep 14 05:10:20 2018 -0400
@@ -471,7 +471,6 @@

     c->read = b;
     c->socket.data = r;
-    c->socket.read_ready = 1;
     c->read_state = &nxt_controller_conn_read_state;

     engine = task->thread->engine;
```

**Comment by igorsysoev** [comment]
> Is it possible to happen that the first time to call recv returns EAGAIN involked after epoll_wait?

Yes, it is possible.

> If it's possible, it seems nxt_conn_read should be fixed.
> Because after epoll_wait, the state of read is NXT_EVENT_ACTIVE indicates
> nxt_fd_event_is_disabled is false, thus there isn't any chance to call nxt_fd_event_enable_read again.

epoll is edge-triggered engine, socket is usually added to epoll once and then epoll will send notification on any new data part without enabling.

**Comment by hongzhidao** [comment]
Get it, thank you.
