### ISSUE TITLE
Excuse me, what method can I get detailed error information，Loading configuration file error: "error": "Invalid method."

### ISSUE THREAD

**Issue by pdudo** [nginx/unit#169]
Excuse me, what do I need to do to get detailed error information?The logs only start information

Operation is as follows:

# netstat -tulnp | grep unit
tcp        0      0 127.0.0.1:8224              0.0.0.0:*                   LISTEN      566/unit: main v1.4 
# 

# curl -X PUT -d@/etc/unit/start.json '127.0.0.1:8224'
{
	"error": "Invalid method."
}

# cat /etc/unit/start.json
{
    "listeners": {
        "*:8300": {
            "application": "blogs"
        }
    },

    "applications": {
        "blogs": {
            "type": "php",
            "processes": 2,
            "root": "/usr/local/nginx/php",
            "index": "index.php",
	    
	    "user": "php",
	    "group": "php",
	    
	    "options": {
	    	"file": "/usr/local/php7/lib/php.ini"
	    }
        }
    }
}
#

**Comment by VBart** [comment]
You can't use the PUT method with `127.0.0.1:8224`, that's why it says "Invalid method". You should PUT your configuration object to `127.0.0.1:8224/config/`.

`curl -X PUT -d@/etc/unit/start.json '127.0.0.1:8224/config/'`

**Comment by maksitop** [comment]
Hi!
I can not load the configuration.
netstat -tulnp | grep unit
tcp        0      0 127.0.0.1:8300              0.0.0.0:*                   LISTEN      29335/unit: main v1

cat /etc/unit/start.json
{
"listeners": {
"*:8300": {
"application": "blogs"
}
},

"applications": {
    "blogs": {
        "type": "php",
        "processes": 2,
        "root": "/usr/share/doc/unit-php/examples/phpinfo-app",
        "index": "index.php",

    "user": "nobody",
    "group": "nobody",

    }
    }
}
curl -X PUT -d@/etc/unit/start.json '127.0.0.1:8300/config/'
{
        "error": "Failed to apply new configuration."
}

**Comment by maksitop** [comment]
changed the address to "listeners": {
        "*:8301": {
"success": "Reconfiguration done."

**Comment by VBart** [comment]
@maksitop Please make sure that you have only one Unit daemon running.

**Comment by gh72029002** [comment]
curl -X PUT -d@conf/php.json  http://localhost:8433/config
"detail": "Application must have the \"type\" property set."
