### ISSUE TITLE
Flask application failed to load css file occasionally under DragonFlyBSD

### ISSUE THREAD

**Issue by lhmwzy** [nginx/unit#170]
unit 1.3 or unit1.4 all have this issue
I run Flask under nginx unit.
#uname -a
DragonFly lhm.com 5.1-DEVELOPMENT DragonFly v5.1.0.467.gb76875-DEVELOPMENT #0: Wed Dec 20 20:37:51 CST 2017     root@lhm.com:/usr/obj/usr/src/sys/lhmwzy  x86_64

Flask file:
# cat /home/pythontest/test.py 
```
from flask import Flask,request,Response,render_template,make_response

app = Flask(__name__)

@app.route("/test")
def test():
    r = render_template('test.tpl')
    return r
application = app
```

#cat /home/pythontest/templates/test.tpl 
```
<doCTYPE html>
<html lang="en">
<head>
        <!-- Title -->
        <title>test</title>

        <!-- Required Meta Tags Always Come First -->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <!-- CSS Unify -->
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/icon-line-pro/style.css">
        <link rel="stylesheet" href="/static/css/unify-core.css">
        <link rel="stylesheet" href="/static/css/unify-components.css">
        <link rel="stylesheet" href="/static/css/unify-globals.css">
        <link rel="stylesheet" href="/static/css/custom.css">
</head>
</html>

```
all css files are locate in "/home/pythontest/static/css"

unit configuration:
```
{
    "listeners": {
        "*:8400": {
            "application": "test"
        },
    },

    "applications": {
        "test": {
            "type": "python",
            "processes": 2,
            "path": "/home/pythontest",
            "module":"test",
            "user": "nobody",
            "group":"nobody"
        },
    }
}
```

run the application:
`curl -X PUT  -d @/usr/local/nginxunit/config/start.json --unix-socket /usr/local/nginxunit/control.unit.sock http://10.69.124.88/config`

when access "http://10.69.124.88:8400/test",the css can't load normally all, 1 or 2 or 3 failed to load,under chrome DevTools,the status is "failed",the reason is "net::ERR_CONTENT_LENGTH_MISMATCH"

unit.log has nothing.
Sorry for my poor english.

If need the css file,please let me know.

**Comment by lhmwzy** [comment]
if run under Flask,all go well.

**Comment by lhmwzy** [comment]
below is the css file which I use to test
[css.zip](https://github.com/nginx/unit/files/2414889/css.zip)

**Comment by lhmwzy** [comment]
under  FreeBSD 11.2-RELEASE ,no issue at all.

**Comment by lhmwzy** [comment]
Only under DragonFlyBSD will have this issue.
here is the debug log when access http://XXxxxx:8400/test
[log.zip](https://github.com/nginx/unit/files/2419552/log.zip)

**Comment by lhmwzy** [comment]
![1](https://user-images.githubusercontent.com/1417894/46143772-96bdd280-c28d-11e8-816b-0a3450be8eda.png)

**Comment by lhmwzy** [comment]
chrome devtools debug img:
![1](https://user-images.githubusercontent.com/1417894/46143834-c967cb00-c28d-11e8-82e2-8a7b90afbb08.png)

**Comment by VBart** [comment]
Thank you for so detailed report! We are currently working on this issue.

**Comment by lhmwzy** [comment]
If you need anything else,please let me know.

**Comment by VBart** [comment]
@lhmwzy please try the following patch:
```patch
# HG changeset patch
# User Igor Sysoev <igor@sysoev.ru>
# Date 1538058335 -10800
#      Thu Sep 27 17:25:35 2018 +0300
# Node ID 67b4faf60b540bbf3c20c400ef528e3c13ef26a4
# Parent  0de745fae82c5fc65722ca5a3852adf939263831
Fixed bug in socket write error handling introduced in e3972a4a9c73.

diff -r 0de745fae82c -r 67b4faf60b54 src/nxt_conn_write.c
--- a/src/nxt_conn_write.c      Thu Sep 20 16:34:19 2018 +0300
+++ b/src/nxt_conn_write.c      Thu Sep 27 17:25:35 2018 +0300
@@ -127,7 +127,9 @@ nxt_conn_io_write(nxt_task_t *task, void
         return;
     }
 
-    /* ret == NXT_ERROR */
+    if (ret != NXT_ERROR) {
+        return;
+    }
 
     nxt_fd_event_block_write(engine, &c->socket);
 ```

**Comment by lhmwzy** [comment]
I will test tomorrow and tell you the result

**Comment by VBart** [comment]
Thank you.

**Comment by lhmwzy** [comment]
Thank you for spotting this issue. The fix was committed.
Much appreciated @VBart

**Comment by VBart** [comment]
Thank you for testing. The fix has been committed: https://github.com/nginx/unit/commit/92da8dae1e4194698ace12e6a51df5d9431e00c4.
