### ISSUE TITLE
Clarify timer and epoll

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#173]
Hi.

1. In nxt_timer_add.
    We only need to check the timer has been added in rbtree.
    If the timer is in tree, its state is either WAITING or DISABLED, never be CHANGING.
2. It seems the diff is always more than the precision after nxt_timer_add.
    Because both of the timer->time and ch->time are immutable,
    and we have checked the diff in nxt_timer_add.

Thanks.

```
diff -r ba7bc97ad251 src/nxt_timer.c
--- a/src/nxt_timer.c	Fri Sep 28 15:12:47 2018 +0300
+++ b/src/nxt_timer.c	Fri Oct 05 15:30:46 2018 -0400
@@ -71,23 +71,20 @@

     time = engine->timers.now + timeout;

-    if (timer->state != NXT_TIMER_CHANGING) {
+    if (nxt_timer_is_in_tree(timer)) {

-        if (nxt_timer_is_in_tree(timer)) {
+        diff = nxt_msec_diff(time, timer->time);
+        /*
+         * Use the previous timer if difference between it and the
+         * new timer is less than required precision milliseconds: this
+         * decreases number of rbtree operations for fast connections.
+         */
+        if (nxt_abs(diff) < timer->precision) {
+            nxt_debug(timer->task, "timer previous: %M:%d",
+                      time, timer->state);

-            diff = nxt_msec_diff(time, timer->time);
-            /*
-             * Use the previous timer if difference between it and the
-             * new timer is less than required precision milliseconds: this
-             * decreases number of rbtree operations for fast connections.
-             */
-            if (nxt_abs(diff) < timer->precision) {
-                nxt_debug(timer->task, "timer previous: %M:%d",
-                          time, timer->state);
-
-                timer->state = NXT_TIMER_WAITING;
-                return;
-            }
+            timer->state = NXT_TIMER_WAITING;
+            return;
         }
     }

@@ -164,7 +161,6 @@
 static void
 nxt_timer_changes_commit(nxt_event_engine_t *engine)
 {
-    int32_t             diff;
     nxt_timer_t         *timer;
     nxt_timers_t        *timers;
     nxt_timer_state_t   state;
@@ -186,18 +182,6 @@

         case NXT_TIMER_ADD:
             if (nxt_timer_is_in_tree(timer)) {
-
-                diff = nxt_msec_diff(ch->time, timer->time);
-                /* See the comment in nxt_timer_add(). */
-
-                if (nxt_abs(diff) < timer->precision) {
-                    nxt_debug(timer->task, "timer rbtree previous: %M:%d",
-                              ch->time, timer->state);
-
-                    state = NXT_TIMER_WAITING;
-                    break;
-                }
-
                 nxt_debug(timer->task, "timer rbtree delete: %M:%d",
                           timer->time, timer->state);
```

**Comment by hongzhidao** [comment]
4. Improved error handler happened in changes commit.
    Because error may happen in nxt_epoll_change called by xxx_enable/disable/delete_xxx.
    But now the error is only handled in nxt_epoll_poll.

```
diff -r ba7bc97ad251 src/nxt_epoll_engine.c
--- a/src/nxt_epoll_engine.c	Fri Sep 28 15:12:47 2018 +0300
+++ b/src/nxt_epoll_engine.c	Mon Oct 08 05:57:54 2018 -0400
@@ -67,7 +67,7 @@
     nxt_fd_event_t *ev);
 static void nxt_epoll_change(nxt_event_engine_t *engine, nxt_fd_event_t *ev,
     int op, uint32_t events);
-static nxt_int_t nxt_epoll_commit_changes(nxt_event_engine_t *engine);
+static void nxt_epoll_commit_changes(nxt_event_engine_t *engine);
 static void nxt_epoll_error_handler(nxt_task_t *task, void *obj, void *data);
 #if (NXT_HAVE_SIGNALFD)
 static nxt_int_t nxt_epoll_add_signal(nxt_event_engine_t *engine);
@@ -593,7 +593,7 @@
               engine->u.epoll.fd, ev->fd, op, events);

     if (engine->u.epoll.nchanges >= engine->u.epoll.mchanges) {
-        (void) nxt_epoll_commit_changes(engine);
+        nxt_epoll_commit_changes(engine);
     }

     ev->changing = 1;
@@ -605,18 +605,16 @@
 }


-static nxt_int_t
+static void
 nxt_epoll_commit_changes(nxt_event_engine_t *engine)
 {
     int                 ret;
-    nxt_int_t           retval;
     nxt_fd_event_t      *ev;
     nxt_epoll_change_t  *change, *end;

     nxt_debug(&engine->task, "epoll %d changes:%ui",
               engine->u.epoll.fd, engine->u.epoll.nchanges);

-    retval = NXT_OK;
     change = engine->u.epoll.changes;
     end = change + engine->u.epoll.nchanges;

@@ -637,7 +635,7 @@
             nxt_work_queue_add(&engine->fast_work_queue,
                                nxt_epoll_error_handler, ev->task, ev, ev->data);

-            retval = NXT_ERROR;
+            engine->u.epoll.error = 1;
         }

         change++;
@@ -645,8 +643,6 @@
     } while (change < end);

     engine->u.epoll.nchanges = 0;
-
-    return retval;
 }


@@ -884,10 +880,13 @@
     struct epoll_event  *event;

     if (engine->u.epoll.nchanges != 0) {
-        if (nxt_epoll_commit_changes(engine) != NXT_OK) {
-            /* Error handlers have been enqueued on failure. */
-            timeout = 0;
-        }
+        nxt_epoll_commit_changes(engine);
+    }
+
+    if (engine->u.epoll.error) {
+        /* Error handlers have been enqueued on failure. */
+        timeout = 0;
+        engine->u.epoll.error = 0;
     }

     nxt_debug(&engine->task, "epoll_wait(%d) timeout:%M",
diff -r ba7bc97ad251 src/nxt_event_engine.h
--- a/src/nxt_event_engine.h	Fri Sep 28 15:12:47 2018 +0300
+++ b/src/nxt_event_engine.h	Mon Oct 08 05:57:54 2018 -0400
@@ -205,6 +205,8 @@
     nxt_epoll_change_t            *changes;
     struct epoll_event            *events;

+    uint8_t                       error;
+
 #if (NXT_HAVE_EVENTFD)
     nxt_work_handler_t            post_handler;
     nxt_fd_event_t                eventfd;
```

**Comment by hongzhidao** [comment]
5. The missed check of creating event engine pool.

```
diff -r ba7bc97ad251 src/nxt_event_engine.c
--- a/src/nxt_event_engine.c	Fri Sep 28 15:12:47 2018 +0300
+++ b/src/nxt_event_engine.c	Tue Oct 09 15:42:09 2018 -0400
@@ -43,15 +43,24 @@
     const nxt_event_interface_t *interface, const nxt_sig_event_t *signals,
     nxt_uint_t flags, nxt_uint_t batch)
 {
+    nxt_mp_t            *mp;
     nxt_uint_t          events;
     nxt_thread_t        *thread;
     nxt_event_engine_t  *engine;

-    engine = nxt_zalloc(sizeof(nxt_event_engine_t));
-    if (engine == NULL) {
+    mp = nxt_mp_create(1024, 128, 256, 32);
+
+    if (nxt_slow_path(mp == NULL)) {
         return NULL;
     }

+    engine = nxt_mp_zget(mp, sizeof(nxt_event_engine_t));
+    if (nxt_slow_path(engine == NULL)) {
+        return NULL;
+    }
+
+    engine->mem_pool = mp;
+
     nxt_debug(task, "create engine %p", engine);

     thread = task->thread;
diff -r ba7bc97ad251 src/nxt_runtime.c
--- a/src/nxt_runtime.c	Fri Sep 28 15:12:47 2018 +0300
+++ b/src/nxt_runtime.c	Tue Oct 09 15:42:09 2018 -0400
@@ -287,7 +287,6 @@
 #endif

     engine->id = rt->last_engine_id++;
-    engine->mem_pool = nxt_mp_create(1024, 128, 256, 32);

     nxt_queue_init(&rt->engines);
     nxt_queue_insert_tail(&rt->engines, &engine->link);
```

**Comment by hongzhidao** [comment]
6. **[Optional]** Introduce ae which means async event.
I tried to rename nxt_event_interface to nxt_ae_t, it does become more clear.
But it'll need great change.

nxt_event_interface :  nxt_ae_t
      * engine->event.io :  engine->ae.io
nxt_epoll_engine :  nxt_ae_epoll  
      * I think epoll is not an engine, it's an async event.
nxt_fd_event_enable_read :  nxt_ae_enable_read

Even more, we can enhance 'event'.
nxt_fd_event_t :  nxt_event_t
      * I'm not sure, because the structure includes a field 'fd'.
nxt_event_engine_t :  nxt_engine_t

Take a look, please. @igorsysoev @VBart

**Comment by VBart** [comment]
> Hi.
> 
>     1. In nxt_timer_add.
>        We only need to check the timer has been added in rbtree.
>        If the timer is in tree, its state is either WAITING or DISABLED, never be CHANGING.
> 

If the timer is in tree and nxt_timer_delete() was called then it will be CHANGING.

>     2. It seems the diff is always more than the precision after nxt_timer_add.
>        Because both of the timer->time and ch->time are immutable,
>        and we have checked the diff in nxt_timer_add.
> 

This assumption is also wrong, as the diff check in nxt_timer_add() might be skipped due to CHANGING state.

> 
> Thanks.
> 
> ```
> diff -r ba7bc97ad251 src/nxt_timer.c
> --- a/src/nxt_timer.c	Fri Sep 28 15:12:47 2018 +0300
> +++ b/src/nxt_timer.c	Fri Oct 05 15:30:46 2018 -0400
> @@ -71,23 +71,20 @@
> 
>      time = engine->timers.now + timeout;
> 
> -    if (timer->state != NXT_TIMER_CHANGING) {
> +    if (nxt_timer_is_in_tree(timer)) {
> 
> -        if (nxt_timer_is_in_tree(timer)) {
> +        diff = nxt_msec_diff(time, timer->time);
> +        /*
> +         * Use the previous timer if difference between it and the
> +         * new timer is less than required precision milliseconds: this
> +         * decreases number of rbtree operations for fast connections.
> +         */
> +        if (nxt_abs(diff) < timer->precision) {
> +            nxt_debug(timer->task, "timer previous: %M:%d",
> +                      time, timer->state);
> 
> -            diff = nxt_msec_diff(time, timer->time);
> -            /*
> -             * Use the previous timer if difference between it and the
> -             * new timer is less than required precision milliseconds: this
> -             * decreases number of rbtree operations for fast connections.
> -             */
> -            if (nxt_abs(diff) < timer->precision) {
> -                nxt_debug(timer->task, "timer previous: %M:%d",
> -                          time, timer->state);
> -
> -                timer->state = NXT_TIMER_WAITING;
> -                return;
> -            }
> +            timer->state = NXT_TIMER_WAITING;
> +            return;
>          }
>      }
> 

With this change you are introducing a bug. In situation when the timer is in tree and add() is called after a delete() call, the timer will be removed from the tree anyway.

**Comment by hongzhidao** [comment]
Thank you, I get the meaning of CHANGING now.

**Comment by VBart** [comment]
>     3. Remove duplicate code in epoll.
The change was committed: https://github.com/nginx/unit/commit/deeb276d2386b90e695fc0650bfb7e08806264ee

>     4. Improved error handler happened in changes commit.
>        Because error may happen in nxt_epoll_change called by xxx_enable/disable/delete_xxx.
>        But now the error is only handled in nxt_epoll_poll.
The change was committed: https://github.com/nginx/unit/commit/50dd54877dc88ade87f4259a74918ddfa4498880

Thanks.

**Comment by VBart** [comment]
>     1. Remove duplicate code in epoll.
> 
> 
> ```
> diff -r ba7bc97ad251 src/nxt_epoll_engine.c
> --- a/src/nxt_epoll_engine.c	Fri Sep 28 15:12:47 2018 +0300
> +++ b/src/nxt_epoll_engine.c	Sat Oct 06 06:17:53 2018 -0400
> @@ -942,8 +942,6 @@
>                      ev->read = NXT_EVENT_DISABLED;
>                  }
> 
> -                error = 0;
> -
>                  nxt_work_queue_add(ev->read_work_queue, ev->read_handler,
>                                     ev->task, ev, ev->data);
> 
> @@ -962,8 +960,6 @@
>                      ev->write = NXT_EVENT_DISABLED;
>                  }
> 
> -                error = 0;
> -
>                  nxt_work_queue_add(ev->write_work_queue, ev->write_handler,
>                                     ev->task, ev, ev->data);
> 
> @@ -972,11 +968,6 @@
>                  nxt_epoll_disable_write(engine, ev);
>              }
>          }
> -
> -        if (error) {
> -            ev->read_ready = 1;
> -            ev->write_ready = 1;
> -        }
>      }
>  }
> ```

This change appears to be wrong. Now in case of error both handlers are called (read and write), which results in double close of connection.

**Comment by hongzhidao** [comment]
Sorry for my fault. 

Please reset the commit. @igorsysoev 
https://github.com/nginx/unit/commit/deeb276d2386b90e695fc0650bfb7e08806264ee

I'll be more careful next time.
