### ISSUE TITLE
Signal handling

### ISSUE THREAD

**Issue by Jamim** [nginx/unit#174]
Hello,

I found some code at [src/nxt_worker_process.c](https://github.com/nginx/unit/blob/master/src/nxt_worker_process.c#L45-L46) that might be wrong:
```c
    nxt_event_signal(SIGQUIT, nxt_worker_process_sigterm_handler),
    nxt_event_signal(SIGTERM, nxt_worker_process_sigquit_handler),
```

Meanwhile at [src/nxt_main_process.c](https://github.com/nginx/unit/blob/master/src/nxt_main_process.c#L72-L73):
```c
    nxt_event_signal(SIGQUIT, nxt_main_process_sigquit_handler),
    nxt_event_signal(SIGTERM, nxt_main_process_sigterm_handler),
```

I suppose that handlers at `nxt_worker_process.c` were mixed up.
Could someone take a look at this?

Thank you!

**Comment by Jamim** [comment]
By the way, what is the preferred method to stop `unit`?

**Comment by VBart** [comment]
Thanks for noticing this. There's an older ticket about it: #99.

**Comment by VBart** [comment]
> By the way, what is the preferred method to stop `unit` (`unitd`)?

For graceful shutdown it should be SIGQUIT to the main process, but currently it works the same as SIGTERM.
