### ISSUE TITLE
Nginx use_temp_path=off won't work!

### ISSUE THREAD

**Issue by monthersabati** [nginx/unit#178]
We try both on and off value for the use_temp_path feature but it doesn't make any difference, and files are written in proxy_temp_path even in the off mode!

the nginx version is 1.14.0 (stable)

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: http://unit.nginx.org/ for details.

Please use nginx bug tracker for issues related to nginx: https://trac.nginx.org/nginx/
