### ISSUE TITLE
setting php disable_functions doesn't work correctly

### ISSUE THREAD

**Issue by grandtele** [nginx/unit#183]
unit v1.6
...
"applications": {
			"app-dns": {
				"user": "www-data",
				"group": "www-data",
				"type": "php",
				"root": "/grand_kernel/apps/dns",
				"script": "/app.php",
				"options": {
					"admin": {
						"disable_functions": "exec,shell_exec"
					}
				}
			}
		}
...

<img width="506" alt="screen-fwnu7" src="https://user-images.githubusercontent.com/22945890/48662895-63c7dc00-ea91-11e8-929d-3f79cbc32666.png">

but it doesn't disabled in realy
in app.php exec and shell_exec will be executed with stdout to /var/log/unit.log

**Comment by VBart** [comment]
Please try the following patch:
```diff
diff -r cb3595d83966 -r db83c7a95dd7 src/nxt_php_sapi.c
--- a/src/nxt_php_sapi.c        Thu Nov 15 21:50:00 2018 +0300
+++ b/src/nxt_php_sapi.c        Tue Nov 20 22:06:43 2018 +0300
@@ -15,16 +15,6 @@
 #include <nxt_unit_request.h>
 
 
-typedef struct nxt_php_run_ctx_s  nxt_php_run_ctx_t;
-
-static nxt_int_t nxt_php_init(nxt_task_t *task, nxt_common_app_conf_t *conf);
-
-static void nxt_php_str_trim_trail(nxt_str_t *str, u_char t);
-static void nxt_php_str_trim_lead(nxt_str_t *str, u_char t);
-nxt_inline u_char *nxt_realpath(const void *c);
-
-static void nxt_php_request_handler(nxt_unit_request_info_t *req);
-
 #if PHP_MAJOR_VERSION >= 7
 #   define NXT_PHP7 1
 #   if PHP_MINOR_VERSION >= 1
@@ -40,11 +30,31 @@ static void nxt_php_request_handler(nxt_
 #   endif
 #endif
 
+
+typedef struct nxt_php_run_ctx_s  nxt_php_run_ctx_t;
+
+#ifdef NXT_PHP7
+typedef int (*nxt_php_disable_t)(char *p, size_t size);
+#else
+typedef int (*nxt_php_disable_t)(char *p, uint TSRMLS_DC);
+#endif
+
+
+static nxt_int_t nxt_php_init(nxt_task_t *task, nxt_common_app_conf_t *conf);
+
+static void nxt_php_str_trim_trail(nxt_str_t *str, u_char t);
+static void nxt_php_str_trim_lead(nxt_str_t *str, u_char t);
+nxt_inline u_char *nxt_realpath(const void *c);
+
+static void nxt_php_request_handler(nxt_unit_request_info_t *req);
+
 static int nxt_php_startup(sapi_module_struct *sapi_module);
 static void nxt_php_set_options(nxt_task_t *task, nxt_conf_value_t *options,
     int type);
 static nxt_int_t nxt_php_alter_option(nxt_str_t *name, nxt_str_t *value,
     int type);
+static void nxt_php_set_disable(nxt_task_t *task, const char *type,
+    nxt_str_t *value, char **ptr, nxt_php_disable_t disable);
 static int nxt_php_send_headers(sapi_headers_struct *sapi_headers);
 static char *nxt_php_read_cookies(void);
 static void nxt_php_set_sptr(nxt_unit_request_info_t *req, const char *name,
@@ -359,6 +369,21 @@ nxt_php_set_options(nxt_task_t *task, nx
             if (nxt_php_alter_option(&name, &value, type) != NXT_OK) {
                 nxt_log(task, NXT_LOG_ERR,
                         "setting PHP option \"%V: %V\" failed", &name, &value);
+                continue;
+            }
+
+            if (nxt_str_eq(&name, "disable_functions", 17)) {
+                nxt_php_set_disable(task, "function", &value,
+                                    &PG(disable_functions),
+                                    zend_disable_function);
+                continue;
+            }
+
+            if (nxt_str_eq(&name, "disable_classes", 15)) {
+                nxt_php_set_disable(task, "class", &value,
+                                    &PG(disable_classes),
+                                    zend_disable_class);
+                continue;
             }
         }
     }
@@ -451,6 +476,52 @@ nxt_php_alter_option(nxt_str_t *name, nx
 
 
 static void
+nxt_php_set_disable(nxt_task_t *task, const char *type, nxt_str_t *value,
+    char **ptr, nxt_php_disable_t disable)
+{
+    char  c, *p, *start;
+
+    p = nxt_malloc(value->length + 1);
+    if (nxt_slow_path(p == NULL)) {
+        return;
+    }
+
+    nxt_memcpy(p, value->start, value->length);
+    p[value->length] = '\0';
+
+    *ptr = p;
+    start = p;
+
+    do {
+        c = *p;
+
+        if (c == ' ' || c == ',' || c == '\0') {
+
+            if (p != start) {
+                *p = '\0';
+
+#ifdef NXT_PHP7
+                if (disable(start, p - start)
+#else
+                if (disable(start, p - start TSRMLS_CC)
+#endif
+                    != SUCCESS)
+                {
+                    nxt_log(task, NXT_LOG_ERR,
+                            "failed to disable PHP %s \"%s\"", type, start);
+                }
+            }
+
+            start = p + 1;
+        }
+
+        p++;
+
+    } while (c != '\0');
+}
+
+
+static void
 nxt_php_str_trim_trail(nxt_str_t *str, u_char t)
 {
     while (str->length > 0 && str->start[str->length - 1] == t) {

```

**Comment by grandtele** [comment]
Hello,

path is working.

2018/11/26 21:48:42 [notice] 6223#6223 php message: PHP Warning:  exec() has been disabled for security reasons in /grand_kernel/apps/dns/app.php on line 13
2018/11/26 21:48:42 [notice] 6223#6223 php message: PHP Warning:  exec() has been disabled for security reasons in /grand_kernel/apps/dns/app.php on line 13

but was errors:

2018/11/26 21:45:26 [info] 4245#4245 (ABS_MODE) php script "/app.php" root: "/grand_kernel/apps/dns"
2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "dl"
2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "eval"
2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "source"

Thank's

**Comment by VBart** [comment]
Thank you for testing. The reasons for errors you see are explained below.

> 2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "dl"

This function was removed since PHP 5.3. See: http://php.net/manual/en/function.dl.php
So there's no function to disable.

> 2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "eval"

This is not a function, but a language construct (like "for", or "include").
See "Notes" here: http://php.net/eval#refsect1-function.eval-notes

Since it's not a function there's no way to disable it using "disable_functions", not only in Unit but in any other PHP server too. See this feature request: https://bugs.php.net/bug.php?id=62397


> 2018/11/26 21:45:26 [error] 4245#4245 failed to disable PHP function "source"

It seems there's no such function in PHP. At least I can't find it in the documentation: http://php.net/manual-lookup.php?pattern=source

Probably you meant "show_source" instead.

**Comment by grandtele** [comment]
Hello,
Yes looking it is my mistake with this functions.

Thank's for fix
