### ISSUE TITLE
unit fails to run with ZTS patch for unit-php 

### ISSUE THREAD

**Issue by osokin** [nginx/unit#188]
Hi,

a customer reported unit-php compatible with ZTS fails to run on a machine.
Detals are available https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233349

Could you please take a look.
Thanks.

**Comment by VBart** [comment]
That's a bug in PHP 7.1+. I've already made a pull request (https://github.com/php/php-src/pull/3670) and it was merged: https://github.com/php/php-src/commit/11ddf7669a58969ad9101032ce891b951819b3e1. The customer confirmed that it solved his problem: https://github.com/nginx/unit/issues/184#issuecomment-440994609. Also a workaround to Unit was committed: https://github.com/nginx/unit/commit/262578dc71e4c1aaad01656a9b0c78539b1e7371.

**Comment by osokin** [comment]
It's fixed for NGINX Unit, so let me close it.

Thank you.
