### ISSUE TITLE
Quick start using docker

### ISSUE THREAD

**Issue by xytis** [nginx/unit#19]
I believe that using docker to test-run any new software is really convenient.

I've made a debian based docker image and a simple readme to test it out:
https://github.com/xytis/docker-unit

Should I make a PR to include docker option to this repo's README?

**Comment by alessfg** [comment]
Hey @xytis an official Docker image is already in development! Thanks for the contribution though.

**Comment by paulredmond** [comment]
@xytis @alessfg Any thoughts around automating the creation of the configuration objects? When a container is stopped the configuration is gone. I have a basic working example, but every time I run the container I have to re-run creating the configuration.

I guess one way I could do so is through an entrypoint bash script, but I was curious what others were thinking.

**Comment by xytis** [comment]
At this point, I would consider using an external script, outside of docker infrastructure, to fill the container with configuration. For example a step in `Makefile`.

As I understood there are development plans to have some sort of startup configuration in the near future.

**Comment by alessfg** [comment]
@paulredmond @xytis For now my recommendation would be to use an entrypoint bash script.

**Comment by xytis** [comment]
@alessfg, should I invest time in this step or the official docker container is coming in the near future?

**Comment by VBart** [comment]
There's an official docker container planned. I expect it will be ready in October.

**Comment by VBart** [comment]
Configuration persistence is already committed: https://github.com/nginx/unit/commit/4953e5b5cba166bc12a92c686c5e000aaf272667

Also you can make configuration API socket accessible outside of a container. In this case you will be able to control how and what application run in the container.

**Comment by xytis** [comment]
I've updated https://hub.docker.com/r/xytis/docker-unitd/ with the latest build from the master branch.
It should support mounted folder for configuration persistence.

**Comment by mozgbrasil** [comment]
Hello good afternoon

Can you help me

How do I access the WEB server for PHP?

For now I only executed the following commands

docker pull nginx/unit
docker run -d nginx/unit

![captura de tela de 2019-02-05 10-14-54](https://user-images.githubusercontent.com/17202780/52272766-eb094b00-292e-11e9-9622-83cb30f1bbbc.png)

**Comment by thresheek** [comment]
@mozgbrasil you'll need to push the configuration to the docker container you launched, as well as make an actual application accessible from inside the container.

- create a file named index.php in the current directory with the contents of:

```
<?php
phpinfo();
?>
```

Create a Unit configuration file, named config.json:
```
{
  "listeners": {
    "*:8000": {
      "application": "default"
    }
  },
  "applications": {
    "default": {
      "type": "php",
      "workers": 10,
      "root": "/www",
      "index": "index.php"
    }
  }
}
```

- run unit and configure it to be accessible via port 8000:

```
export PORT=8000
export UNIT=$(docker run --rm -d -v $(pwd):/www -p $PORT:8000 nginx/unit:latest)
docker exec -ti $UNIT curl -X PUT -d @/www/config.json --unix-socket /var/run/control.unit.sock http://localhost/config
```

Now open http://localhost:8000/ in your browser - you should see the default phpinfo page.  Hope this helps you to understand the idea on how to set things up - we'll update the documentation to include the docker howto.

For more information on unit in general, please see http://unit.nginx.org/configuration/

Thanks

**Comment by defanator** [comment]
We are providing docker images for Unit and modules for some time already, I'm closing this issue.
