### ISSUE TITLE
unit 1.6 / php 7.2 / load config error

### ISSUE THREAD

**Issue by devinacosta** [nginx/unit#191]
I installed Unit 1.6 on CentOS 7.5 from the repo. I then compiled using Remi's PHP 7.2 using GCC 6.3.1 and then copied the module to /usr/lib64/unit/modules. 

When I try to load a configuration it errors out with the following, any ideas on what i'm doing wrong?

2018/11/25 21:59:40 [info] 5379#5379 discovery started
2018/11/25 21:59:40 [notice] 5379#5379 module: php 7.2.12 "/usr/lib64/unit/modules/remiphp720.unit.so"
2018/11/25 21:59:40 [notice] 5378#5378 process 5379 exited with code 0
2018/11/25 21:59:40 [info] 5380#5380 controller started
2018/11/25 21:59:40 [info] 5381#5381 router started
2018/11/25 21:59:40 [info] 5381#5381 OpenSSL 1.0.2k-fips  26 Jan 2017, 100020bf
2018/11/25 22:00:56 [info] 5565#5565 "script_index_php" application started
2018/11/25 22:00:56 [info] 5565#5565 (ABS_MODE) php script "/index.php" root: "/var/www/html"
2018/11/25 22:00:56 [alert] 5565#5565 ioctl(1207226904, !FIONBIO) failed (9: Bad file descriptor)
2018/11/25 22:00:56.234 [alert] 5565#5565 [unit] NXT_UNIT_INIT is not in the current environment
2018/11/25 22:00:56 [notice] 5378#5378 process 5565 exited with code 1
2018/11/25 22:00:56 [warn] 5381#5381 failed to start application "script_index_php"
2018/11/25 22:00:56 [alert] 5381#5381 failed to apply new conf

[root@localhost log]# cat /root/unit.cnf
{
    "listeners": {
        "0.0.0.0:8090": {
            "application": "script_index_php"
        },
        "0.0.0.0:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "apache",
            "group": "apache",
            "root": "/var/www/html",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "apache",
            "group": "apache",
            "root": "/var/www/html",
            "index": "index.php"
        }
    }
}

**Comment by mar0x** [comment]
Devin,

Please make sure you are using correct sources version (e.g. tagged as "1.6") when you configure and make your php module.

If the issue persists, please share your configuration options (both Unit and php module).

**Comment by mar0x** [comment]
Devin,

Starting from unit-1.7.1 you can install binary php72-unit-php module from Remi repository.

Hope you are no longer suffering from this issue. Feel free to re-open the issue if module does not work for you.
