### ISSUE TITLE
Need packages for more modern versions of Golang on Debian

### ISSUE THREAD

**Issue by plinss** [nginx/unit#192]
Currently unit-go packages for Debian are only available for Go 1.7 and 1.8, however Go has recently dropped support for Go 1.8 per their [release policy](https://golang.org/doc/devel/release.html#policy). As a result, a number of Go libraries are now relying on new language features from Go 1.9 (namely type aliases) and no longer compile with Go 1.7 or Go 1.8.

Most currently developed programs written in Go now need to use at least Go 1.9. Also note that Go 1.10 is available in [Stretch-backports](https://packages.debian.org/stretch-backports/golang) and [Buster](https://packages.debian.org/buster/golang).

A Debian package for unit-1.10 on Stretch would be most welcome, and frankly is now effectively required to use Unit with Go on Debian without having to build it yourself.

**Comment by defanator** [comment]
We are currently providing packages for Debian 10 "buster" (go 1.11), Ubuntu 18.04 (go 1.9, 1.10), Ubuntu 19.04 (go 1.10, 1.11). I'm closing this issue.
