### ISSUE TITLE
Error logs per app

### ISSUE THREAD

**Issue by avkarenow** [nginx/unit#197]
Hello,

one of the missing features is error log per app. It'll be useful to have log file specified in app configuration.

Any chance to implement it in the near future?

**Comment by mancubus77** [comment]
Just curious, what is a reason to have Unit logs per application? unit.log has basic information about lifecycle and access logs might be configured per application. I use logfiles per application to display/analyse a workflow.

**Comment by VBart** [comment]
It would be nice to see good reasoning for this feature.

Usually it's easier to have all errors in one place. In nginx you can configure error log files even per location and I've seen so many times when nginx users failed to find the right one.

**Comment by avkarenow** [comment]
I mean application logs - everything that app is writing to stderr, stdout and every error on startup could be logged to own app log.
For example error on startup for ruby application:
2019/01/16 01:06:05 [info] 89217#100090 "example_ruby" application started
2019/01/16 01:06:05 [alert] 89217#100090 Ruby: Failed to parse rack script
2019/01/16 01:06:05 [alert] 89217#100090 Ruby: /home/test0/public_ruby/config.ru:4:in `block in <main>': undefined local variable or method `test' for #<Rack::Builder:0x00000008047e1790> (NameError)
2019/01/16 01:06:05 [alert] 89217#100090 from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
2019/01/16 01:06:05 [alert] 89217#100090 from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
2019/01/16 01:06:05 [alert] 89217#100090 from /home/test0/public_ruby/config.ru:in `new'
2019/01/16 01:06:05 [alert] 89217#100090 from /home/test0/public_ruby/config.ru:in `<main>'
2019/01/16 01:06:05 [alert] 89217#100090 from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
2019/01/16 01:06:05 [alert] 89217#100090 from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
2019/01/16 01:06:05 [alert] 89217#100090 from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
2019/01/16 01:06:05 [notice] 88834#100476 process 89217 exited with code 1

It should be the option to log it in separate file. It will be very useful for many applications run at the same time.

**Comment by sdelling** [comment]
There are several areas where per-app error logs (or at least consistently listing the application name on every log entry) would be quite helpful:

- If web applications on the same host are managed by different people, there is currently no way to allow someone to view only the logs relevant to them.
- Identifying which application a log entry belongs to involves matching a process ID in the log entry to a prior log entry which listed the application name during startup, which is far from convenient when trying to pull all logs related to one particular application and would involve either manual correlation or writing a parsing script.
- Log entries generated by an applications's stderr appear not to be tagged with identifying information at all and thus cannot be easily correlated with any given application other than by guessing.

**Comment by filex** [comment]
The handling of application logs is especially interesting in docker setups. I want my docker containers to log via stdout/stderr. This makes it easier to use existing log facilities, and have those shipped to a log server. Furthermore no log _files_ should be allowed to grow inside the container.

In the official docker images, nginx unit symlinks its logfile to `/dev/stdout`. Let's say, I am running a PHP application. And I would like the application to print one or more lines in JSON format with information about the client (logged in? user name…) and actions (item deleted…). (I am not talking about a PHP "access log" like phpfpm_access).

What would be an advisable setup to produce such application log lines from PHP?

* Should I write to my own logfile (`/var/log/app.log`) and symlink that to `/dev/stdout`, too?
* Where is PHP's `error_log()` written to?

**Comment by msva** [comment]
Also, take my 5¢ for per-app error_log setup too.
It is really needed, and there is many cases "why", including already mentioned (different apps managed by different developers), and not mentioned ones (it can be the only way to distinguish which logs corresponds to which exact application in some setups).

**Comment by BrixSat** [comment]
I would also to know where is PHP's error_log() written to?

**Comment by JelleVanDerMeulen** [comment]
Is there any progress on this item? We have 3 instances of the same application (dev/test/staging) on 1 UNIT server. We use different http ports (80/81/82). In the access_log there is no way to identify the app. This make debugging issues very difficult.

**Comment by artemkonev** [comment]
@JelleVanDerMeulen hi! Not sure whether this is feasible in your case, but using a [custom log format](https://unit.nginx.org/configuration/#access-log) with something like the `X-Application-Name` headers may do the trick.

**Comment by artemkonev** [comment]
Roughly, having per-app headers would allow to use the `$header_*` variable in the log format, e.g.:
```json
{
    "access_log": {
        "path": "/var/log/unit/access.log",
        "format": "$header_X_Application_Name: $remote_addr - - [$time_local] \"$request_line\" $status $body_bytes_sent \"$header_referer\" \"$header_user_agent\""
    }
}
```
If you cannot modify the apps to produce different headers, you can put `nginx` in front of Unit to do just that as a temporary solution.

**Comment by tippexs** [comment]
Thanks bringing this back to out attention. I will push this to our next team meeting to find a solution for this issue.

cc: @alejandro-colomar @ac000

**Comment by ac000** [comment]
This has been merged, see https://github.com/nginx/unit/commit/45c45eaeb4443ff4af9cc49e716bbd9d65596b02 for details.

**Comment by msva** [comment]
by the way, and what about per-app **access**_log? :grinning: 

It is absolutelly good that unit now supports per-app error logs (even better - separate stdout/stderr), but it seems, `access_log` is still only configureable at global level :shrug: 



Also, by the way, regarding per-aplication logs:
IIRC, there was nginx CVE related to writing logs as worker user, so nginx switched to writing logs as root (and recomended to change the permissions of logs).
But it seems, like Unit now requires per-app error logs to be writeable by user that runs application.

May be it is worth to fix log-writing (even per-app) to be performed by master process (that runs with root privileges and nott wait for similar CVE that nginx already had?
