### ISSUE TITLE
Issues with listen address

### ISSUE THREAD

**Issue by gummiboll** [nginx/unit#20]
Hello!

Noticed that switching to or from using a wildcard (*:port) in listeners causes the re-configuration to fail[1]. Switching from a ip-adress to another does work however which makes me assume that unit tries to bind the new port(s) before unbinding the old one(s).

Also, listeners seem to require a ip-adress. Me (and I suspect many others) will instinctively try to use "localhost" instead of 127.0.0.1.

I'm running unit from apt on ubuntu xenial

[1]:
```
{
	"error": "Failed to apply new configuration."
}
```
From the log:
`listen socket error: {listener: "0.0.0.0:8300", code:"ListenerInUse", message: "bind(\"0.0.0.0:8300\") failed (98: Address already in use)"}`

**Comment by uprt** [comment]
> unit tries to bind the new port(s) before unbinding the old one(s).

Looks like that.
In src/nxt_router.c:1268

```
static nxt_int_t nxt_router_engine_conf_update(nxt_router_temp_conf_t *tmcf,
    nxt_router_engine_conf_t *recf) 
{
...
ret = nxt_router_engine_joints_create(tmcf, recf, &tmcf->creating,
                                          nxt_router_listen_socket_create); // <---
...

ret = nxt_router_engine_joints_create(tmcf, recf, &tmcf->updating,
                                          nxt_router_listen_socket_update); // <---
...

 ret = nxt_router_engine_joints_delete(tmcf, recf, &tmcf->deleting);
...
```

**Comment by igorsysoev** [comment]
> unit tries to bind the new port(s) before unbinding the old one(s).

Yes. Linux does not allow to bind simultaneously on wildcard and
particular addresses on the same port.

As to order of binding new sockets and closing old sockets, unit tries
to apply new configuration before deleting old one. If the new configuration
failed, unit continue to work with the previous configuration.
