### ISSUE TITLE
nginx proxy backend application error because of http1.0

### ISSUE THREAD

**Issue by bruceforlearn** [nginx/unit#203]
[package issues.zip](https://github.com/nginx/unit/files/2689296/package.issues.zip)
Hello All,

I used wireshark to get package from clients to applications

issues happened between nginx to applications

client used http1.1 to visit nginx

nginx used http1.0 to visit applications

but some application refused nginx 1.0 and some application connected nginx 1.0

all application are same .net application (I used some package) 

I want to ask why does it ?

I have uploading the wireshark package

please help me 

thank you very much

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx: http://nginx.org/en/support.html
