### ISSUE TITLE
Possibly memory leak in port socket.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#207]
Hi.

The bug happens in the case of receiving incomplete msg caused by sending incompletely, such as
```
stream  nf  mf
103      0   1
103      1   1
103      1   1
104      0   1
104      1   1
104      1   0
```

The msg frags corresponding to stream 103 will not be reused.

Thanks.

**Comment by mar0x** [comment]
Receiver assumes it always get correct data. No format nor data validation performed. If sender sends incorrect message sequences, sender should be fixed, not receiver.
