### ISSUE TITLE
chroot support

### ISSUE THREAD

**Issue by mvrhov** [nginx/unit#209]
Is there any plan to support chrooting the child processes that are run.
As this means that this would be better alternative for php-fpm.

**Comment by artemkonev** [comment]
Vote +1

**Comment by imaginal** [comment]
@VBart any news?

**Comment by tiago4orion** [comment]
@imaginal I'm working on it. No ETA yet, but it's very close to complete.

**Comment by artemkonev** [comment]
Wrapped up here: https://unit.nginx.org/configuration/#process-isolation
