### ISSUE TITLE
if http's reponse failed,don't send request another server

### ISSUE THREAD

**Issue by luowqn** [nginx/unit#210]
Hello!I have a quesion.
If original request is  failed,don't send request to mirror.

1、I try to use ngx_http_mirror_module,but it can't support it.
2、I try to post_action,but nginx config gets status failed,the configure:
`    location / {
               proxy_connect_timeout       300;
               proxy_send_timeout          300;
               proxy_read_timeout          300;
               send_timeout                300;
               proxy_buffer_size           64k;
               proxy_buffers               4 64k;
               proxy_busy_buffers_size     128k;
               proxy_temp_file_write_size  128k;
               proxy_pass http://tomcat1;
               if ($status != "200")
               {
                   post_action @test;
               }
               #mirror /mirror;
     }

    location @test {
                internal;
                proxy_connect_timeout       5;
                proxy_send_timeout          5;
                proxy_read_timeout          5;
                send_timeout                5;
                proxy_pass http://tomcat2$request_uri;
                }`
What should i do?

**Comment by VBart** [comment]
This is issue tracker for Unit web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
