### ISSUE TITLE
RFE: systemd improvement

### ISSUE THREAD

**Issue by remicollet** [nginx/unit#213]
For discussion (before PR)

* switch to simple Type, see PR #212 

* drop `/etc/sysconfig/unit` which is the old deprecated way, and distro specific, using `Environment` directive (and` systemctl edit unit` to change value) is the modern _systemd_ way (working on all distro)

* move log to `/var/log/unit `dedicated directory

* move run to `/run/unit`, which will be created by _systemd_ unit (using `RuntimeDirectory=unit` directive)
* change from `/run/control.unit.sock` to  `/run/unit/control.sock`

**Comment by defanator** [comment]
@remicollet thanks for your input on this.

We discussed briefly, and all the proposed changes look good except dedicated directory for logs. By default, unit produces single log file, and it is being opened as root, so no permissions-related issues should occur. I also failed to find any references in the FHS on this topic.

**Comment by remicollet** [comment]
>  I also failed to find any references in the FHS on this topic.

Using /var/log/<project> is not in FHS, this is only a good/common practice:
```
# find  /var/log -type d
/var/log
/var/log/samba
/var/log/php-fpm
/var/log/blivet-gui
/var/log/mariadb
/var/log/firebird
/var/log/nginx
/var/log/anaconda
/var/log/letsencrypt
/var/log/roundcubemail
/var/log/lightdm
/var/log/mysql
/var/log/horde
/var/log/audit
/var/log/sssd
/var/log/redis
/var/log/vbox
/var/log/rabbitmq
/var/log/www
/var/log/www/default
/var/log/ppp
/var/log/speech-dispatcher
/var/log/glpi
/var/log/exim
/var/log/tarantool
/var/log/zookeeper
/var/log/cups
/var/log/mongodb
/var/log/varnish
/var/log/gdm
/var/log/chrony
/var/log/httpd
/var/log/journal
/var/log/journal/2ab505746f0a44b9897746bf2638402d
/var/log/squid
/var/log/libvirt
/var/log/libvirt/lxc
/var/log/libvirt/uml
/var/log/libvirt/libxl
/var/log/libvirt/qemu
/var/log/swtpm
/var/log/swtpm/libvirt
/var/log/swtpm/libvirt/qemu
/var/log/ocsinventory-server
/var/log/glusterfs
/var/log/rstudio-server
/var/log/pluto
/var/log/pluto/peer
/var/log/cluster
/var/log/dirsrv
/var/log/dirsrv/slapd-builder
/var/log/ocsinventory-agent
/var/log/private
```

And if also make log rotation simpler (ok, not in this case, if a single file exists)

```
/var/log/<project>/*.log {
   ...
}
```

**Comment by defanator** [comment]
@remicollet I fully agree, and we do follow this practice in nginx, but for now it's not required in unit.

@VBart any additional input here?

**Comment by VBart** [comment]
If this is a common practice and useful for log rotation, then please proceed with the change.

**Comment by remicollet** [comment]
Do you prefer I separate PR for each change (BTW, this mean I probably will have to wait for each to be merged before creating another), of everythin in PR #212 (1 commit per feature)
