### ISSUE TITLE
Internal operational metrics

### ISSUE THREAD

**Issue by vasekboch** [nginx/unit#217]
Would be great to have access to some internal metrics. Like number of active workers (processes under) For example in PrometheusFormat (https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md) that is wide spead. This would allow to closely monitor usage of nginx unit processes. Similar to https://easyengine.io/tutorials/php/fpm-status-page. So we could start for example next instance on different server.

**Comment by robjr** [comment]
Yes, I also looking for collecting metrics similar to the ones available on PHP-FPM, mainly the number of active processes and memory usage. Thank you for adding to the roadmap @VBart @artemkonev.

**Comment by tippexs** [comment]
We did release our first implementation of metrics / statistics. https://unit.nginx.org/configuration/#usage-statistics

They are, at this point still rudimental but we will work on enhancements. Thanks for the link as this will be a great resource for a future dashboard we are working on right now.
