### ISSUE TITLE
Safe to use --state? Or how to load initial configurations?

### ISSUE THREAD

**Issue by michi88** [nginx/unit#218]
So I've been searching for a while on how to load initial configurations. I'd assume an option like `unitd --config /path/to/conf.json` or `unitd --initial-config /path/to/conf.json` so I can easily run this in things like supervisor or docker.

Now I did read here https://github.com/nginx/unit/issues/83 that we can set the `--state` parameter to some folder that basically, when I run unitd and apply the configuration with PUT, just holds my `conf.json` and an empty `cert` folder (as I don't have certificates).

I'm not planning to use any dynamic configuration changes, would this then be safe to use?

If this is safe to use I would add something in the documentation as I think I'm not the only one that just wants 1 initial configuration and that's it.

Thanks for building the web! :)

**Comment by VBart** [comment]
https://unit.nginx.org/installation/#configuring-sources - in the description of `--state` parameter:
> It can be copied as is when you migrate your Unit installation

Probably, we should add some howto for this. @artemkonev please look.

**Comment by tamarintech** [comment]
I put my conf.json in a `state` directory. In my case it's relative to the unitd binary that is part of my container entrypoint. `--state /path/to/other/state` also works. :+1:

**Comment by artemkonev** [comment]
https://unit.nginx.org/howto/source/#source-config-src-state
https://unit.nginx.org/configuration/#conf-replication
