### ISSUE TITLE
Replacement for php-fpm's fastcgi_finish_request

### ISSUE THREAD

**Issue by kirooshu** [nginx/unit#219]
Hello folks, the gist of my ask is if there is anything planned around supporting the same functionality as http://php.net/manual/en/function.fastcgi-finish-request.php
For us this is really important feature which helps us keep the end user latency low while doing in-request PHP work.

Let me know if you need more details on how we are using http://php.net/manual/en/function.fastcgi-finish-request.php

Thanks!

**Comment by VBart** [comment]
The details about your particular use case and possible requirements should help.

**Comment by komapa** [comment]
What we do is allow developers to register "shutdown" functions by adding callables to a global array. Those shutdown functions, as we call them, are assigned a certain priority by the developers so we can execute them in certain order at the end of the request. By default these shutdown functions are assumed to be non-blocking for the user, aka they are done after the response has been flushed to the user via a call to `fastcgi_finish_request()`. We are using nginx and fastcgi_pass to php-fpm to achieve this currently. Pretty standard setup for most PHP installations out there :)

The important part is that we can use these shutdown functions to do operations to external systems without causing any slowdown in those systems affect the perceived latency of the user request. We are talking metrics/logs collections, etc.

Let me know if this explains the use case well.

**Comment by VBart** [comment]
@komapa Yes, it explains well. Thanks.

**Comment by komapa** [comment]
Just checking if this might get some attention soon from the team. Thanks in advance!

**Comment by komapa** [comment]
Hello @i4ki, is this feature planned any time soon? Thank you!

**Comment by robjr** [comment]
I also need this feature. any release plan about this, guys?

**Comment by VBart** [comment]
Hi, I've implemented `fastcgi_finish_request()`. Please try [this patch](https://github.com/nginx/unit/files/5404187/fastcgi_finish_request.txt).
After thorough testing we will include it in the next release, that is highly likely to appear in November.

**Comment by robjr** [comment]
thank you, @VBart. Looking forward to the release.
