### ISSUE TITLE
 main v1.7.1 [unitd --control 127.0.0.1:8300]: [alert] 28169#28169 process 28858 exited on signal 11

### ISSUE THREAD

**Issue by maksitop** [nginx/unit#221]
Hi!
messages.log
Feb 12 14:05:14 srvdb004 kernel: unitd[28863]: segfault at b8 ip 00007f9a06680c9e sp 00007f9a01bc8b00 error 4 in unitd[7f9a0665d000+49000]
Feb 12 14:05:14 srvdb004 unit: main v1.7.1 [unitd --control 127.0.0.1:8300]: [alert] 28169#28169 process 28858 exited on signal 11
unit.log
2019/02/12 14:05:14.791 [warn] 28859#28859 [unit] failed to send shm to 28858: Broken pipe (32)
2019/02/12 14:05:14.791 [warn] 28859#28859 [unit] port_send(8, 16) failed: Broken pipe (32)
2019/02/12 14:05:14.791 [alert] 28859#28859 [unit] #4: last message send failed: Broken pipe (32)

Help!

**Comment by VBart** [comment]
Unfortunately, these messages have no information about the problem.

Could you provide your configuration, describe your setup and conditions when you experienced this crash? Also, enabling debug logging will help: http://unit.nginx.org/troubleshooting/#debug-log

**Comment by maksitop** [comment]
cat /etc/unit/start.json
{
    "listeners": {
        "*:8301": {
            "application": "sar"
        }
    },

    "applications": {
        "sar": {
            "type": "php",
            "processes": 2,
            "root": "/var/www/html/",
            "user": "nobody",
            "group": "nobody",
            "index": "index.php",
        "limits": {
        "timeout": 10
    },
        }
        }
    }

**Comment by maksitop** [comment]
[unit.log](https://github.com/nginx/unit/files/2856587/unit.log)
debug.log

**Comment by VBart** [comment]
@maksitop Thank you very much for the report. We are working on the fix.

**Comment by VBart** [comment]
@maksitop Could you show `unitd --version` as well?

**Comment by VBart** [comment]
@maksitop please try the following patch:
```diff
diff -r 6d72c218a055 -r db5b1fa66046 src/nxt_timer.c
--- a/src/nxt_timer.c   Mon Feb 11 15:42:16 2019 +0300
+++ b/src/nxt_timer.c   Tue Feb 12 22:12:09 2019 +0300
@@ -159,9 +159,9 @@ nxt_timer_change(nxt_event_engine_t *eng
 static void
 nxt_timer_changes_commit(nxt_event_engine_t *engine)
 {
-    nxt_timer_t         *timer, **add, **add_end;
+    nxt_timer_t         *timer;
     nxt_timers_t        *timers;
-    nxt_timer_change_t  *ch, *end;
+    nxt_timer_change_t  *ch, *end, *add, *add_end;
 
     timers = &engine->timers;
 
@@ -170,7 +170,7 @@ nxt_timer_changes_commit(nxt_event_engin
     ch = timers->changes;
     end = ch + timers->nchanges;
 
-    add = (nxt_timer_t **) ch;
+    add = ch;
     add_end = add;
 
     while (ch < end) {
@@ -185,7 +185,7 @@ nxt_timer_changes_commit(nxt_event_engin
 
             timer->time = ch->time;
 
-            *add_end++ = timer;
+            *add_end++ = *ch;
 
             if (!nxt_timer_is_in_tree(timer)) {
                 break;
@@ -209,7 +209,7 @@ nxt_timer_changes_commit(nxt_event_engin
     }
 
     while (add < add_end) {
-        timer = *add;
+        timer = add->timer;
 
         nxt_debug(timer->task, "timer rbtree insert: %M±%d",
                   timer->time, timer->bias);
```

**Comment by maksitop** [comment]
> unitd --version

 unitd --version
unit version: 1.7.1
configured as ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tests --openssl --modules=/usr/lib64/unit/modules --libdir=/usr/lib64 --cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -pie'

**Comment by VBart** [comment]
@maksitop Thanks. It looks like only CentOS 6 64-bit package is broken. We're working on preparing a new one. Also we've improved our release procedures to avoid this in future.

**Comment by defanator** [comment]
CentOS 6 x86_64 updated packages are coming soon, I'll post an update here.

**Comment by defanator** [comment]
@maksitop please upgrade to the 1.7.1-2 version which has just been added to our CentOS 6 64-bit repository, and let us know how it goes.

**Comment by maksitop** [comment]
#yum install unit
Resolving Dependencies
--> Running transaction check
---> Package unit.x86_64 0:1.7.1-1.el6.ngx will be updated
--> Processing Dependency: unit = 1.7.1-1.el6.ngx for package: unit-go-1.7.1-1.el6.ngx.x86_64
--> Processing Dependency: unit = 1.7.1-1.el6.ngx for package: unit-php-1.7.1-1.el6.ngx.x86_64
--> Processing Dependency: unit = 1.7.1-1.el6.ngx for package: unit-perl-1.7.1-1.el6.ngx.x86_64
--> Processing Dependency: unit = 1.7.1-1.el6.ngx for package: unit-python-1.7.1-1.el6.ngx.x86_64
---> Package unit.x86_64 0:1.7.1-2.el6.ngx will be an update
--> Running transaction check
---> Package unit.x86_64 0:1.7.1-1.el6.ngx will be updated
--> Processing Dependency: unit = 1.7.1-1.el6.ngx for package: unit-perl-1.7.1-1.el6.ngx.x86_64
---> Package unit-go.x86_64 0:1.7.1-1.el6.ngx will be updated
---> Package unit-go.x86_64 0:1.7.1-2.el6.ngx will be an update
---> Package unit-php.x86_64 0:1.7.1-1.el6.ngx will be updated
---> Package unit-php.x86_64 0:1.7.1-2.el6.ngx will be an update
---> Package unit-python.x86_64 0:1.7.1-1.el6.ngx will be updated
---> Package unit-python.x86_64 0:1.7.1-2.el6.ngx will be an update
--> Finished Dependency Resolution
Error: Package: unit-perl-1.7.1-1.el6.ngx.x86_64 (@unit)
           Requires: unit = 1.7.1-1.el6.ngx
           Removing: unit-1.7.1-1.el6.ngx.x86_64 (@unit)
               unit = 1.7.1-1.el6.ngx
           Updated By: unit-1.7.1-2.el6.ngx.x86_64 (unit)
               unit = 1.7.1-2.el6.ngx
           Available: unit-0.3-1.el6.ngx.x86_64 (unit)
               unit = 0.3-1.el6.ngx
           Available: unit-0.4-1.el6.ngx.x86_64 (unit)
               unit = 0.4-1.el6.ngx
           Available: unit-0.5-1.el6.ngx.x86_64 (unit)
               unit = 0.5-1.el6.ngx
           Available: unit-0.6-1.el6.ngx.x86_64 (unit)
               unit = 0.6-1.el6.ngx
           Available: unit-0.7-1.el6.ngx.x86_64 (unit)
               unit = 0.7-1.el6.ngx
           Available: unit-1.0-1.el6.ngx.x86_64 (unit)
               unit = 1.0-1.el6.ngx
           Available: unit-1.1-1.el6.ngx.x86_64 (unit)
               unit = 1.1-1.el6.ngx
           Available: unit-1.2-1.el6.ngx.x86_64 (unit)
               unit = 1.2-1.el6.ngx
           Available: unit-1.3-1.el6.ngx.x86_64 (unit)
               unit = 1.3-1.el6.ngx
           Available: unit-1.4-1.el6.ngx.x86_64 (unit)
               unit = 1.4-1.el6.ngx
           Available: unit-1.4-2.el6.ngx.x86_64 (unit)
               unit = 1.4-2.el6.ngx
           Available: unit-1.5-1.el6.ngx.x86_64 (unit)
               unit = 1.5-1.el6.ngx
           Available: unit-1.6-1.el6.ngx.x86_64 (unit)
               unit = 1.6-1.el6.ngx
           Available: unit-1.7-1.el6.ngx.x86_64 (unit)
               unit = 1.7-1.el6.ngx
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by maksitop** [comment]
oops

**Comment by defanator** [comment]
@maksitop CentOS 6 has perl 5.10 which is not supported by Unit, so we excluded that package.

**Comment by maksitop** [comment]
#yum remove unit
Feb 15 11:20:23 srvdb004 yum[10975]: Erased: unit-go
Feb 15 11:20:23 srvdb004 yum[10975]: Erased: unit-python
Feb 15 11:20:23 srvdb004 yum[10975]: Erased: unit-php
Feb 15 11:20:23 srvdb004 yum[10975]: Erased: unit-perl
Feb 15 11:20:23 srvdb004 yum[10975]: Erased: unit

Ok
##yum install unit
#rpm -q unit
unit-1.7.1-2.el6.ngx.x86_64
Ok
#yum[11719]: Installed: unit-php-1.7.1-2.el6.ngx.x86_64
#rpm -q unit-php
unit-php-1.7.1-2.el6.ngx.x86_64
Ok
#/etc/init.d/unit start
Starting unitd: 2019/02/15 11:50:01 [info] 12827#12827 unit started
                                                           [  OK  ]
#/etc/init.d/unit stop
Stopping unitd:                                            [  OK  ]

# unitd --control 127.0.0.1:8300
2019/02/15 12:01:06 [info] 13326#13326 unit started

# /etc/init.d/unit stop
Stopping unitd:                                            [  OK  ]

unit.log
2019/02/15 12:01:06 [notice] 13327#13327 process 13328 exited with code 0
2019/02/15 12:01:06 [info] 13330#13330 OpenSSL 1.0.1e-fips 11 Feb 2013, 1000105f
2019/02/15 12:01:57 [alert] 13327#13327 sendmsg(12, -1, 1) failed (32: Broken pipe)
2019/02/15 12:01:57 [alert] 13327#13327 sendmsg(13, -1, 1) failed (32: Broken pipe)
2019/02/15 12:01:57 [notice] 13327#13327 process 13329 exited with code 0

messages.log
Feb 15 12:01:57 srvdb004 unit: main v1.7.1 [unitd --control 127.0.0.1:8300]: [alert] 13327#13327 sendmsg(12, -1, 1) failed (32: Broken pipe)
Feb 15 12:01:57 srvdb004 unit: main v1.7.1 [unitd --control 127.0.0.1:8300]: [alert] 13327#13327 sendmsg(13, -1, 1) failed (32: Broken pipe)

**Comment by VBart** [comment]
@maksitop That's ok. Some alerts may appear while shutting down. They are harmless.

**Comment by maksitop** [comment]
thanks It works. Спасибо!

> @maksitop That's ok. Some alerts may appear while shutting down. They are harmless.

**Comment by maksitop** [comment]
thanks It works. Спасибо!

**Comment by maksitop** [comment]
Version unit-perl-1.7.1-2.el6.ngx.x86_64 will not be?

**Comment by VBart** [comment]
@maksitop Unit supports Perl versions 5.12 or later. Unfortunately, CentOS 6 provides Perl version 5.10, that was released more than 11 years ago. It has multiple incompatibilities with later versions and we cannot give any assurances if it works properly in Unit with Perl applications.

The unit-perl module on CentOS 6 has been built by mistake. You can try to [build it yourself](https://unit.nginx.org/installation/#source-code), but for multiple reasons I suggest to avoid using so old software versions.

**Comment by maksitop** [comment]
thanks It works. Спасибо!
