### ISSUE TITLE
How do you override wsgi.url_scheme?

### ISSUE THREAD

**Issue by tamarintech** [nginx/unit#223]
I can't sort out how to do this. It looks like it's fixed to `http` in the source, but it also seems like I should be able to set environ strings here: https://github.com/nginx/unit/blob/master/src/nxt_python_wsgi.c#L839

I'm doing this right now on the app side, but it's kind of hacky:
```
class UnitdProxy(object):
  def __init__(self, app):
    self.app = app

  def __call__(self, environ, start_response):
    environ['wsgi.url_scheme'] = 'https'
    return self.app(environ, start_response)

application = UnitdProxy(myapplication)
```

**Comment by mar0x** [comment]
You are right, it is hard-coded as 'http' now.  We will add https-awareness to all language modules, it is little bit behind.
