### ISSUE TITLE
Always pass QUERY_STRING?

### ISSUE THREAD

**Issue by michi88** [nginx/unit#226]
When migrating from uwsgi I've noticed a difference in how 'QUERY_STRING' is handled.

unit does not pass 'QUERY_STRING' when it is empty. This is a change in behavior from uwsgi, for example, as that does pass it with an empty string.

This can easily break Django implementations that use `request.META['QUERY_STRING']`. I would argue always passing it with an empty string is preferable.

**Comment by VBart** [comment]
I agree. It will be changed this in the following release.
