### ISSUE TITLE
missing header nxt_go_gen.h

### ISSUE THREAD

**Issue by Boiler** [nginx/unit#23]
I'm trying to build Go application with "unit" library and I get this error:
```
$ go build unit-app.go
# unit
../go/src/unit/nxt_go_lib.c:62:24: fatal error: nxt_go_gen.h: No such file or directory
compilation terminated.
```
Where to find this file ?

**Comment by mar0x** [comment]
Direct answer to your question is: the file is located in unit go package source directory.

To get a more useful answer, please describe your environment:
- OS;
- unit install method (packages, built from sources);
- your GOPATH environment variable value;

If you installed unit from sources, consider reading README.md, Configuring go packages, Compiling sources.

**Comment by Boiler** [comment]
Ubuntu 16.04
apt-get install unit unit-dev (http://nginx.org/packages/mainline/ubuntu/ repo)
GOPATH=/home/boiler/go:/usr/lib/go:/usr/lib/go-1.6

make go-install solves this issue, but how to get headers without compiling sources?
