### ISSUE TITLE
NXT_UNIT_INIT is not in the current environment

### ISSUE THREAD

**Issue by academici** [nginx/unit#230]
Unit version: 1.8.0 
unit-http version: 1.8.0 
nodejs: 10.10

● unit.service - NGINX Unit
   Loaded: loaded (/usr/lib/systemd/system/unit.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-03-13 17:07:48 MSK; 2s ago

server.js
```js
#!/usr/bin/env node

var unit = require('unit-http');

var server = unit.createServer(function(request, response) {
    response.writeHead(200, {"Content-Type": "text/html"});
    response.end("Read more at unit.nginx.org");
});
server.listen();
```

When run: node server.js, get an error:

2019/03/13 17:07:59.784 [alert] 26402#26402 [unit] NXT_UNIT_INIT is not in the current environment
/usr/lib/node_modules/unit-http/http_server.js:348
    this.unit.createServer();
              ^

Error: Failed to create Unit object
    at new Server (/usr/lib/node_modules/unit-http/http_server.js:348:15)
    at Object.createServer (/usr/lib/node_modules/unit-http/http.js:13:12)
    at Object.<anonymous> (/var/www/cd10014846/www/autosalon/frontend/server.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

**Comment by mar0x** [comment]
Modified nodejs application should be started by unit which is responsible for environment configuration. Prepare unit configuration with application type 'external' and executable referred to your server.js.

Please read the [documentation](http://unit.nginx.org/configuration/#go-node-js-applications) for more information. Don't hesitate to update this issue if something does not work for you.

**Comment by academici** [comment]
@mar0x, thanks. Works!
You can ask how to organize the processing of the backend and the frontend on the same domain name?

unit.json
```json
{
    "applications": {
    	"site_frontend": {
    		"type": "external",
		"working_directory": "/var/www/site/frontend",
		"executable": "server.js"
    	},
        "site_backend": {
            "type": "php 7.2",
            "processes": 2,
            "root": "/var/www/site/backend",
            "index": "index.php"
        }
    },
    "listeners": {
        "*:8085": {
            "pass": "applications/site_frontend"
        },
        "*:8086": {
            "pass": "applications/site_backend"
        }
    }
}
```
site.conf
```nginx
stream site_backend {
    server 127.0.0.1:8085;
}

upstream site_frontend {
    server 127.0.0.1:8086;
}

server {
    listen              127.0.0.1:8084;
    
    include             /etc/nginx/default.d/*.conf;

    set $root_path	'/var/www/site/frontend';
    root                $root_path;
    index               index.php;
    charset             utf-8;

    location ^~ /back/ {
        try_files $uri $uri/ /index.php?$query_string;
        root '/var/www/site/backend';
    }

    location / {
        proxy_pass http://site_frontend;
        proxy_set_header Host $host;
    }

    location ~ \.php$ {
        proxy_pass http://site_backend;
        proxy_set_header Host $host;
    }

    location ~ /\.(ht|svn|git) {
        deny            all;
    }
}

```
Rewrite works, but static files proccessed by unit.
How best to set up?

**Comment by mar0x** [comment]
As for now, direct static files serving by Unit is not implemented.
For production the only option is to use nginx for static files.
For development and testing you may consider using your application ability to serve static files (for instance, PHP).

Next, try to use Unit routing (see http://unit.nginx.org/configuration/#routes) to simplify (or eliminate) nginx confguration:

```
{                                                                               
    "applications": {                                                           
        "site_frontend": {                                                      
            "type": "external",                                                 
            "working_directory": "/var/www/site/frontend",                              
            "executable": "server.js"                                           
        },                                                                      
        "site_backend": {                                                       
            "type": "php",                                                      
            "processes": 2,                                                     
            "working_directory": "/var/www/site/backend",                               
            "root": "."                                                         
        }                                                                       
    },                                                                          
                                                                                
    "listeners": {                                                              
        "*:8084": {                                                             
            "pass": "routes"                                                    
        }                                                                       
    },                                                                          
                                                                                
    "routes": [                                                                 
        {                                                                       
            "match": {                                                          
                "uri": "/back/*"                                                
            },                                                                  
            "action": {                                                         
                "pass": "applications/site_backend"                             
            }                                                                   
        },                                                                      
        {                                                                       
            "action": {                                                         
                "pass": "applications/site_frontend"                            
            }                                                                   
        }                                                                       
    ]                                                                           
}
```

**Comment by academici** [comment]
@mar0x, frontend works. But, when go to page site.test/back/page, get an error:

019/03/14 18:07:35 [notice] 5207#5207 php message: PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
2019/03/14 18:07:35 [notice] 5207#5207 php message: PHP Fatal error:  Unknown: Failed opening required '/home/dev/site/backend/back/page' (include_path='.:/usr/share/php') in Unknown on line 0

Whats is behavior?

**Comment by mar0x** [comment]
Looks like '/home/dev/site/backend/back/page' is a directory. If so, please try to same URL, but with trailing '/': "http://site.test/back/page/".
Redirect to URL with trailing '/' is not implemented in PHP module, need to investigate.

**Comment by academici** [comment]
@mar0x , no folder not exist, and i change backend prefix and get same error.
Rewriting on php does not work.

maybe problem in the config?
```nginx
upstream site_unit {
    server 127.0.0.1:8084;
}

server {
    listen              127.0.0.1:8081;

    include             /etc/nginx/default.d/*.conf;

    charset             utf-8;

    location / {
      proxy_pass http://site_unit;
      proxy_set_header Host $host;
    }

    location ~ /\.(ht|svn|git) {
      deny            all;
    }
}
```

**Comment by mar0x** [comment]
Rewriting is not implemented in Unit.
There is a possibility to configure application to handle ALL requests by single PHP script. Use PHP application option 'script':
```
"script": "index.php"
```

**Comment by academici** [comment]
@mar0x, thanks!!!
