### ISSUE TITLE
php SERVER_PORT not configurable

### ISSUE THREAD

**Issue by Jean-Daniel** [nginx/unit#231]
I'm trying to run wordpress behind unit following the documentation, but ran into an issue.

My wordpress site is distributed by NGINX using HTTPS, but Unit keep telling the PHP script that SERVER_PORT is 80. As Wordpress uses 'SERVER_PORT' to determine the actual URL scheme, it think the client tried to access the server using http instead of https, and send a 301 redirect to fix that. 

As there is no way to specify SERVER variable in the configuration, I can't access my wordpress instance.

```json
{
	"listeners": {
		"127.0.0.1:8090": {
			"pass": "applications/wp_index"
		},

		"127.0.0.1:8091": {
			"pass": "applications/wp_direct"
		}
	},

	"applications": {
		"wp_index": {
			"type": "php",
			"user": "www",
			"group": "www-data",
			"root": "/var/www/wordpress/",
			"script": "index.php"
		},

		"wp_direct": {
			"type": "php",
			"user": "www",
			"group": "www-data",
			"root": "/var/www/wordpress/",
			"index": "index.php"
		}
	}
}
```

```
server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;

  server_name wordpress.example.com;

  root /var/www/wordpress;

  ssl on;

  ssl_certificate /var/lib/acme/wordpress/rsa/cert.pem;
  ssl_certificate_key /var/lib/acme/wordpress/rsa/keys/key.pem;

  ssl_certificate /var/lib/acme/wordpress/ecdsa/cert.pem;
  ssl_certificate_key /var/lib/acme/wordpress/ecdsa/keys/key.pem;

  ssl_dhparam /var/lib/acme/wordpress/params.pem;

  # This order might seem weird - this is attempted to match last if rules below fail.
  # http://wiki.nginx.org/HttpCoreModule
  location / {
    try_files $uri @index_php;
  }

  location @index_php {
    proxy_pass http://unit_wp_index;
    proxy_set_header Host $host;
  }

  location /wp-admin {
    index index.php;
  }

  location ~* \.php$ {
    try_files        $uri =404;
    proxy_pass       http://unit_wp_direct;
    proxy_set_header Host $host;
  }
}
```

**Comment by tamarintech** [comment]
I ended up overriding SERVER_PORT via wp-config alongside WP_HOME and WP_SITEURL. It might not be the best way. My configuration is slightly different than yours because I am not terminating TLS at nginx.

In nginx-unit 1.8.0 you can use the new routes functionality.

**Comment by mar0x** [comment]
Yes, for now SERVER_PORT is hard-coded to 80. You may temporary change the constant in sources while we will made it configurable or propose something else (don't know exactly what).

**Comment by oneumyvakin** [comment]
I've got the same issue with `SERVER_PORT` with Laravel.
Laravel's routes uses `SERVER_PORT` for rendering assets.
Unfortunately I've no workaround for this and recompiling Unit is not an option.

**Comment by tamarintech** [comment]
Here's exactly what I ended up doing at the end of wp-config.php.

My nginx is set up on port 80 with proxy to unitd on port 8080. TLS is terminated by a cloud load balancer.

```
    define('WP_HOME', 'https://<SITE>');
    define('WP_SITEURL', 'https://<SITE>');

    $_SERVER['HTTP_HOST'] = '<SITE>';
    $_SERVER['HTTPS']='on';
    $_SERVER['PORT']='8080';
```

**Comment by isdn** [comment]
Hello,

Unfortunately, I have faced the same issue with another PHP app.
Lots of PHP apps rely on the `$_SERVER` variables, such as:

```
$_SERVER['SERVER_PROTOCOL'] 
$_SERVER['REMOTE_ADDR'] 
$_SERVER['SERVER_PORT'] 
$_SERVER['SERVER_ADDR'] 
$_SERVER['HTTPS'] 
$_SERVER['REQUEST_SCHEME']  
```

So, it would be nice if we could set the `$_SERVER` vars via the config.

**Comment by dbuelow** [comment]
+1 This would be a nice feature.

**Comment by snowirbis** [comment]
Solution is 
--- nxt_php_sapi.c.orig 2020-04-19 18:30:31.030270000 +0300
+++ nxt_php_sapi.c      2020-04-19 18:28:51.152030000 +0300
@@ -1117,7 +1117,11 @@

     nxt_php_set_sptr(req, "SERVER_NAME", &r->server_name, r->server_name_length,
                      track_vars_array TSRMLS_CC);
-    nxt_php_set_cstr(req, "SERVER_PORT", "80", 2, track_vars_array TSRMLS_CC);
+    if (r->tls) {
+       nxt_php_set_cstr(req, "SERVER_PORT", "443", 3, track_vars_array TSRMLS_CC);
+    } else {
+       nxt_php_set_cstr(req, "SERVER_PORT", "80", 2, track_vars_array TSRMLS_CC);
+    }

     if (r->tls) {
         nxt_php_set_cstr(req, "HTTPS", "on", 2, track_vars_array TSRMLS_CC);

then configure your NGINX to communicate to your Unit over TLS (certifiacte required on Unit side).

**Comment by iron-udjin** [comment]
Hello,

Are there any news about this issue? I'm tired each unit update to edit SERVER_PORT and HTTPS in the source code :(
Please add possibility to override env variables for each application.

P.S: to override env variables on the web-engine side is not an option. Sometimes there is no possibility to edit the code.

**Comment by hongzhidao** [comment]
Hi,

We are supporting the feature of client protocol replacement.
#592
