### ISSUE TITLE
NodeJS app as only worker?!

### ISSUE THREAD

**Issue by jsieler** [nginx/unit#238]
Is it possible to create an app with nodejs without using http server? Let's say i need some kind of background worker which will run and scan some directory for new files and process them. Or is Unit only intended to be a http/web server?!

Thanks!

**Comment by mar0x** [comment]
Unit starts applications to serve requests.  Application process may have other background threads or sub-processes, but primary goal for Unit application is request processing.

Please provide more details why do you need Unit to start non-server processes.

Thanks in advance.

**Comment by jsieler** [comment]
Like i've described before, NodeJS is not only used to server requests, but also as an background worker. For example it could be used as some "parser/scraper" to get data from some kind of websites and to store those in database. Also it could be used to do some analytics in background too, also real "background worker".

So, for that work i will have to install "pm2" or other process management system. Which sense will it make to install "unit" to only process requests when with "pm2" i could achieve both, requests and background processing?

**Comment by VBart** [comment]
pm2 is a generic process management for Node.js, it doesn't handle connections. All the requests are served by Node.js instances in this case. Usually you need a reverse proxy (like nginx) in front for robustness and scalability.

Unit is more like an effective proxy and accelerator for Node.js (that comparing to nginx integrates more tightly and thus can do process management as well). It handles all the connections, parses requests and distributes work between Node.js processes using shared memory. It's robust and scales well. You can update your code, update Node.js without loosing connections, route requests between different Node.js applications. Besides that, it works the same way with other languages (Python, Ruby, PHP, Java, Perl, Go) and unifies your web-stack.

If you need more generic process manager based on Node.js, than pm2 is a good choice. If you are interested in handling web connections, than Unit is a good choice. With each release it gets more and more web server features.

**Comment by jsieler** [comment]
I wonder if "unit" can also manage nodejs processes (applications in this case), why it should be bind to a listener? It would be much better/easier to build full stack of application (with for example one listener and 3-5 applications) with only Unit, without a need of pm2, because Unit can do the same as well...

As an workaround it would be probably to make a listener without exposing port or binding to local interface (127.0.0.1) and let it run as an background worker.

**Comment by VBart** [comment]
@jsieler In fact it shouldn't be bind to a listener. You can already add an application object to Unit configuration without any listener pointing to it. 🙂

**Comment by jsieler** [comment]
Hm... But the application itself (app.js) should have server instance running (http+createServer), right?

**Comment by VBart** [comment]
@jsieler right, this way it initialises a communication interface with Unit daemon.

**Comment by jsieler** [comment]
Okay. Thanks for your reply! Have a nice day!

**Comment by freerider7777** [comment]
Is it on the roadmap of Unit? As it would be an obvious and very useful feature. In many app servers there are background worker proceses
