### ISSUE TITLE
Nginx u2f auth support

### ISSUE THREAD

**Issue by hamzamp** [nginx/unit#245]
Hello, 
Please does Nginx support u2f authentication.
I want to use a yubikey u2f to authenticate to a service behind a Nginx reverse proxy without login or password, only the key.
Thank you

**Comment by VBart** [comment]
This is issue tracker for Unit web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
