### ISSUE TITLE
being able to redirect logs to stderr

### ISSUE THREAD

**Issue by docteurklein** [nginx/unit#25]
I'd like to run

    unitd --log /dev/stderr

but currently it says:

    2017/09/11 09:13:19 [crit] 12#12 epoll_ctl(3, 3, 9) failed (2: No such file or directory)

Is it something doable?
thanks.

**Comment by igorsysoev** [comment]
It should work. The message about "epoll_ctl()" is not relevant to this.

You can try to build unitd with --debug: "./configure --debug && make", then run "unitd --log /dev/stderr 2>err". All logging will be redirected to the file "err".

**Comment by docteurklein** [comment]
it works indeed! my bad. thanks :)
