### ISSUE TITLE
python37 on Ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by michi88** [nginx/unit#251]
Will the precompiled python 3.7 unit plugin be released for 18.04? If not, what is the recommended way to install/compile from sources?

I'm now doing something like this in 18.04 based docker:
```bash
ENV UNIT_VERSION 1.8.0-1~bionic

# TODO: build unit-python3.7 instead of unit-python3.6 somehow
RUN set -x \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 apt-transport-https ca-certificates \
    && apt-key adv --keyserver "hkp://keyserver.ubuntu.com:80" --keyserver-options timeout=10 --recv-keys "573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62"; \
    unitPackages="unit=${UNIT_VERSION} unit-python3.6=${UNIT_VERSION}"; \
    echo "deb https://packages.nginx.org/unit/ubuntu/ bionic unit" >> /etc/apt/sources.list.d/unit.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y $unitPackages \
    && apt-get remove --purge --auto-remove -y apt-transport-https gnupg1 \
    && rm -rf /var/lib/apt/lists/*
```
 Could I just change `bionic` to `cosmic` as 18.10 does have the 3.7 version?

Thanks a lot!

**Comment by rectalogic** [comment]
Python 3.7 has been available for bionic for a while https://packages.ubuntu.com/bionic/python3.7

**Comment by michi88** [comment]
Any updates on this? As @rectalogic mentioned, Python 3.7 is available in bionic.

Would be great if you guys can publish this. Thanks!

**Comment by defanator** [comment]
@michi88 @rectalogic thanks for reporting this, unit-python3.7 is now available on bionic.
