### ISSUE TITLE
nginx/unit.nxt_go_request_handler.func1(0x0, 0x0, 0xc0001cfc20)

### ISSUE THREAD

**Issue by stoneloney** [nginx/unit#253]
go 1.12   unit 1.8
goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0x7fe1048cd278, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00024f718, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00024f700, 0xc000306000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00024f700, 0xc000306000, 0x1000, 0x1000, 0x1, 0x43267c, 0xc000054b88)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010860, 0xc000306000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc0002807e0, 0xc000306000, 0x1000, 0x1000, 0xc000054c88, 0x408725, 0xc000310000)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc00025ecc0)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00025ecc0, 0x1, 0x0, 0x0, 0x1, 0xc000375000, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0002807e0)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xadb

goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc0002807e0)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb00
2019/05/21 17:37:07 [notice] 8681#8681 process 10008 exited with code 2
2019/05/21 17:37:07 [info] 10017#10017 "recommend_1558459458" application started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa44b06]
goroutine 69 [running]:
nginx/unit.nxt_go_request_handler.func1(0x0, 0x0, 0xc0001cfc20)
	/data/app/src/nginx/unit/request.go:134 +0x36
created by nginx/unit.nxt_go_request_handler
	/data/app/src/nginx/unit/request.go:133 +0x56
2019/05/21 17:37:09 [notice] 8681#8681 process 10017 exited with code 2
2019/05/21 17:37:09 [info] 10046#10046 "recommend_1558459458" application started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xc8]

goroutine 71 [running]:
nginx/unit.nxt_go_request_handler.func1(0xc0000a4630, 0xc0000a4630, 0xc000094ea0)
	/data/app/src/nginx/unit/request.go:135 +0x62
created by nginx/unit.nxt_go_request_handler
	/data/app/src/nginx/unit/request.go:133 +0x56
2019/05/21 17:37:10 [notice] 8681#8681 process 10046 exited with code 2
2019/05/21 17:37:10 [info] 10055#10055 "recommend_1558459458" application started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa44b06]

**Comment by mar0x** [comment]
Hello @stoneloney !

Thanks for your detailed report. Would it be the audacity to ask a bit more information about your installation? This is required to investigate/reproduce the issue :
- What OS you are using?
- How Unit and Go module were installed (from sources, packages, etc.)?
- Could you please share details about your application (framework used, sources would be perfect)?

**Comment by stoneloney** [comment]
Hello  max
1.OS is linux (centos)
2. unit install by source.  How install go module?
3. framework is gin.




------------------ 原始邮件 ------------------
发件人: "Max"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午4:54
收件人: "nginx/unit"<unit@noreply.github.com>;
抄送: "Windforce"<33948561@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nginx/unit] nginx/unit.nxt_go_request_handler.func1(0x0, 0x0,0xc0001cfc20) (#253)




Hello @stoneloney !
 
Thanks for your detailed report. Would it be the audacity to ask a bit more information about your installation? This is required to investigate/reproduce the issue :
  
What OS you are using?
 
How Unit and Go module were installed (from sources, packages, etc.)?
 
Could you please share details about your application (framework used, sources would be perfect)?

**Comment by stoneloney** [comment]
package main

import (
	"fmt"
	"net/http"
	"nginx/unit"
)

func gotest(w http.ResponseWriter, r *http.Request) {
	fmt.Println("go test")
}

func main() {
	http.HandleFunc("/go/mloltest/test", gotest)
	unit.ListenAndServe(":14001", nil)
}

**Comment by mar0x** [comment]
1. Please confirm simple test Go application works with Unit in your installation.
2. Have you modified gin framework to enable Unit support?
    a. If "yes", please share the patch.
    b. If "no", please clarify how application establishes communication with Unit.

**Comment by stoneloney** [comment]
1. Unit normal test is no problem, but in the case of high concurrency, such problems will occur。
2. yes.
Unit reported such an error in gin：
`Handle ResponseWriters that don't implement CloseNotifier `
amend as below：
github.com/gin-gonic/gin/response_writer.go
`func (w *responseWriter) CloseNotify() <-chan bool {
    //return w.ResponseWriter.(http.CloseNotifier).CloseNotify() 
    closeNotifier, ok := w.ResponseWriter.(http.CloseNotifier)
    if ok {
        return closeNotifier.CloseNotify()
    }
    // 不返回结果
    return make(chan bool)
}`

**Comment by mar0x** [comment]
1. Simple Go application is also crashed under high concurrency. Correct?
2. Have you changed gin.go Run(..) method to use unit.ListenAndServe(...) or did something else?

**Comment by stoneloney** [comment]
1. yes.   Ab pressure measurement must appear。
![image](https://user-images.githubusercontent.com/29155504/58219838-e54d3f00-7d3e-11e9-8294-7ce5cd392f95.png)
2. Will appear without using gin。


Maybe there is a problem with my installation or configuration?
