### ISSUE TITLE
Bad gateway (502) when proxying API

### ISSUE THREAD

**Issue by m-holt** [nginx/unit#254]
Using http://unit.nginx.org/howto/integration/#securely-proxying-unit-api as a reference, a bad gateway message is received when attempting to access the NGINX listener address defined.
In order to troubleshoot, I stripped away all of the SSL, ACL, and auth directives and left just the following:

server {
  listen 8100;

  location / {
    proxy_pass http://unix:/var/run/control.unit.sock;
  }
}

NGINX error.log returns the following after a connection attempt:

connect() to unix:/var/run/control.unit.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/control.unit.sock:/", host: "10.0.0.2:8100"

Permissions for the Unix socket:

srw------- 1 root root 0 May 23 07:19 /var/run/control.unit.sock

Since root owns this process, curl commands via the Unix socket also require a root or sudo. My question is, should this process be owned by the same user running NGINX (www-data on Ubuntu), if proxying the API via HTTP going to be possible?

I've also attempted to start unitd using --user www-data --group www-data, but the resulting socket still has the same ownership and permissions, and nothing appears to change in the behavior.

**Comment by VBart** [comment]
Because of security reasons the control API socket is created by the main process with strict permissions and privileged user. In order to allow access the socket from non-privileged nginx worker processes you have to change socket permissions with chown/chmod commands. Other option can be opening control socket on an IP address (127.0.0.1 for example), but please take into account the security considerations.

There are also plans to introduce an unitd option to specify control socket permissions from command-line.

> I've also attempted to start unitd using --user www-data --group www-data, but the resulting socket still has the same ownership and permissions, and nothing appears to change in the behavior.

These command options set user and group for non-privileged process and don't affect privileged user and group.

**Comment by m-holt** [comment]
I see, so the instructions provided in http://unit.nginx.org/howto/integration/#securely-proxying-unit-api are not possible at this time, without manually chown/chmod'ing the socket each time there is a restart?

I'm curious about the statement of opening control socket on an IP address -- is that something that can be set via configuration, so as to enable when the daemon starts?

**Comment by VBart** [comment]
> I see, so the instructions provided in http://unit.nginx.org/howto/integration/#securely-proxying-unit-api are not possible at this time, without manually chown/chmod'ing the socket each time there is a restart?

It will work even without chown/chmod if unitd is running from the same user as nginx workers. But in this case Unit won't be able to open lower ports that requires privileged permission and won't be able to change users/group for it's application processes, unless you have set all the needed capabilities. See ticket https://github.com/nginx/unit/issues/228 for example of how capabilities can be configured.

> I'm curious about the statement of opening control socket on an IP address -- is that something that can be set via configuration, so as to enable when the daemon starts?

You can configure it with `--control` unitd option, e.g.: `unitd --control 127.0.0.1:4444`

**Comment by m-holt** [comment]
Cool, thank you!
