### ISSUE TITLE
Unable to run Java web app with `javax.crypto`

### ISSUE THREAD

**Issue by incube8r** [nginx/unit#255]
Unable to run Java web app with `javax.crypto`

When running a web app using this package Unit throws this error:

```
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:120)
	... 76 more
Caused by: java.lang.SecurityException: Couldn't parse jurisdiction policy files in: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:357)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:111)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:108)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:107)
	... 76 more
```

**Comment by incube8r** [comment]
Here's the complete log: https://paste.ngx.cc/12

**Comment by mar0x** [comment]
@incube8r please share unit.log as well.
Is it open source app? It would be nice to reproduce it for investigation.

**Comment by incube8r** [comment]
@mar0x  the complete `unit.log` file is this:
https://paste.ngx.cc/d2

**Comment by mar0x** [comment]
@incube8r thanks for the log.
Please let me know what OS/version you are using?

I'm trying to reproduce the issue using sample Restlet application (attached, see https://restlet.com/open-source/documentation/user-guide/2.3/editions/jee/overview). If you have some time, please try to build and run it in Unit and let me know the result/logs.
Thanks is advance!

**Comment by incube8r** [comment]
@mar0x Using Ubuntu 16.04.

Okay, I will try to run the framework, may I ask which specific example code you want me to test out?

**Comment by mar0x** [comment]
According to the log, unhandled exception happens during initialisation step. Unfortunately, original exception details not exposed to log. So, the idea with sample application (here it is, btw: ([firstSteps.zip](https://github.com/nginx/unit/files/3223293/firstSteps.zip) ) was to start it and process test request 'hello'. For me it is easier to investigate the issue when I'm able to reproduce it. If sample application will crash for you the same way, I will try to replicate your environment and investigate sample application crash.

**Comment by incube8r** [comment]
@mar0x I was able to run a complete backend server with 100+ JUnit tests with NGINX Unit using the same framework, so I think the issue is not with the framework but rather isolated to the cryptography module perhaps?

**Comment by mar0x** [comment]
@incube8r It is hard to tell what caused the exception (because original exception message is not exposed in log). I'm failed to reproduce the issue using basic sample application.

If you can share your application, I can try to reproduce and investigate (and perhaps fix) the issue.

**Comment by ma1uta** [comment]
There is a problem with jre, you didn't configure the unlimited security policy. Please, check that you have jdk8 151 and higher and that you have the policy file in <jre>/lib/security.
See https://github.com/open-eid/cdoc4j/wiki/Enabling-Unlimited-Strength-Jurisdiction-Policy

**Comment by tippexs** [comment]
closed due to timeout
