### ISSUE TITLE
Unit not reconfiguring Java app 

### ISSUE THREAD

**Issue by incube8r** [nginx/unit#258]
Running

`curl -X PUT -d@start.json '127.0.0.1:8443/config/'
`
works for the first deploy, but it does actually update on the second run unless the war file is renamed even if the actual war file has been modified, it seems Unit does check only the filename when deciding to redeploy/reconfigure again. If the file has the same filename as what was loaded then it won't redeploy/reconfigure.

**Comment by VBart** [comment]
That is expected behaviour. Here is a quote from [the documentation](https://unit.nginx.org/configuration/#configuration-management):
> Before a change, Unit evaluates the difference it causes in the entire configuration; if there’s none, nothing is done. For example, you can’t restart an app by uploading the same configuration it already has.

This allows to not care about the way you change configuration, either by uploading the entire configuration object or by changing some parts selectively. In both cases effect is the same and only the changes are processed.

See also: #17

**Comment by cyberquarks** [comment]
@VBart how about then you do ` curl -X PUT -d@start.json '127.0.0.1:8443/config/'` then it does not return

And checking `htop` there's not CPU load at all, how can this case be debugged to find why it's not reconfiguring?

**Comment by VBart** [comment]
> @VBart how about then you do ` curl -X PUT -d@start.json '127.0.0.1:8443/config/'` then it does not return
> 
> And checking `htop` there's no CPU load at all, how can this case be debugged to find why it's not reconfiguring?

What's in the log? This usually indicates some problem with starting the app and possible a bug in the Unit.

**Comment by mar0x** [comment]
@cyberquarks please provide detailed information about your 'does not return' case: configuration file, log file, application (if possible) etc.

**Comment by tippexs** [comment]
closed due to timeout
