### ISSUE TITLE
router process hangs when repeat PUT and DELETE

### ISSUE THREAD

**Issue by bobunderson** [nginx/unit#26]
I wrote simple python WSGI app and uploaded as follows:

wsgi.py:

    def get_response():
        return 'foo\n'.encode('utf-8')
    
    def application(environ, start_response):
        start_response('200 OK', [('Content-Type', 'text/plain')])
        response = get_response()
        return [response]'

conf.json:

    {
        "listeners": {
            "*:9999": {
                "application": "foo"
            }
        },
        "applications": {
            "foo": {
                "type": "python",
                "workers": 2,
                "path": "/var/tmp/bobunderson/nginx_unit/test/app",
                "module": "wsgi",
                "user": "bobunderson",
                "group": "bobunderson"
            }
        }
    }

and I uploaded conf.json and executed 'curl -D - http://localhost:9999/', then it looked working well.
I deleted all of listeners and applications and re-uploaded the same conf.json immediately, then unitd does not respond.
2 DELETE methods were worked successfully, but when I send 2nd PUT method, unitd router process hanged and the process were using 100% of CPU resource.
so I did 'kill -KILL [pid of router]' then, unitd output core file.
backtrace is as follows:

    (gdb) bt
    #0  0x00007fc8092985db in raise () from /lib64/libpthread.so.0
    #1  0x000000000040aa20 in nxt_port_mp_cleanup (task=<value optimized out>, obj=0x1d14a00, 
        data=0x1d0eb10) at src/nxt_port.c:34
    #2  0x000000000040b7a4 in nxt_mp_destroy (mp=0x1d0eb10) at src/nxt_mp.c:300
    #3  0x000000000040b83c in nxt_mp_release (mp=0x1d0eb10, p=<value optimized out>)
        at src/nxt_mp.c:964
    #4  0x000000000040a624 in nxt_port_release (port=0x1d14a00) at src/nxt_port.c:103
    #5  0x00000000004105fc in nxt_runtime_process_remove (rt=0x1d02850, process=0x1d0cd80)
        at src/nxt_runtime.c:1780
    #6  0x0000000000410e78 in nxt_runtime_exit (task=<value optimized out>, obj=0x1d02850, 
        data=<value optimized out>) at src/nxt_runtime.c:553
    #7  0x000000000040f570 in nxt_event_engine_start (engine=0x1d03290)
        at src/nxt_event_engine.c:517
    #8  0x000000000040669e in main (argc=<value optimized out>, argv=<value optimized out>)
        at src/nxt_main.c:35

unitd.log:

    2017/09/12 12:36:03 [info] 21043#21043 discovery started
    2017/09/12 12:36:03 [notice] 21043#21043 module: python 3.4.3 "build/python3.unit.so"
    2017/09/12 12:36:03 [info] 21044#21044 controller started
    2017/09/12 12:36:03 [crit] 21044#21044 epoll_ctl(3, 3, 9) failed (2: No such file or directory)
    2017/09/12 12:36:03 [info] 21045#21045 router started
    2017/09/12 12:36:03 [notice] 21042#21042 process 21043 exited with code 0
    2017/09/12 12:36:03 [crit] 21045#21045 epoll_ctl(3, 3, 9) failed (2: No such file or directory)
    2017/09/12 12:36:06 [info] 21052#21052 "foo" application started
    2017/09/12 12:36:06 [crit] 21052#21052 epoll_ctl(3, 3, 9) failed (2: No such file or directory)
    2017/09/12 12:36:08 [notice] 21042#21042 process 21052 exited with code 0
    2017/09/12 12:37:04 [alert] 21044#21044 src/nxt_port.c:34 assertion failed: nxt_lvlhsh_is_empty(&port->rpc_streams)
    2017/09/12 12:37:05 [crit] 21042#21042 process 21044 exited on signal 6 (core dumped)

environment:

    Linux (hostname) 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    CentOS release 6.6 (Final)
    Python 3.4.3

**Comment by igorsysoev** [comment]
The bug should be fixed in https://github.com/nginx/unit/commit/309ba5abf2aa51a35c744e7cfe7cb537b3074b42.

**Comment by mar0x** [comment]
Not reproduced in 309ba5abf2aa51a35c744e7cfe7cb537b3074b42
