### ISSUE TITLE
Unable to sychronize cache for repo unit

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#260]
Tried to install on fedora 30

Fails with: "Unable to synchronize cache for repo unit"

Built the unit.repo file in /etc/yum.repos.d
sudo yum install unit - Fails

Seems that the repo baseurl is down, or is it that I am using fedora 30 (Not sure if that would make a difference)

**Comment by Tricky-Ricky** [comment]
May be related to #87 

Followed this users comments: https://github.com/lcts (couldn't tag him)
from #87 and succesfully downloaded and installed Unit on Fedora 30.

Is it possible to add his copr to the Community Repositories builds?

**Comment by artemkonev** [comment]
Hello, Richard,

Unfortunately, we have no packages for Fedora 30 available yet. I'll see if the fork you suggest is OK to go into the docs.

**Comment by artemkonev** [comment]
Hi again,

Now the official packages for Fedora 30 are available, please try and let us know if it works for you.

**Comment by Tricky-Ricky** [comment]
Uninstalled Unit from the repo I posted above and re-installed from the official package. Installed fine that time, found another issue which I'll raise another ticket for
