### ISSUE TITLE
Unable to install unit-http

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#261]
Going through the configuration and Installation guide here:
 [https://unit.nginx.org/installation/#node-js-package](url) 

When it comes to installing unit-http, It terminates with: 

> fatal error: nxt_napi.h: No such file or directory 9 | #include "nxt_napi.h"

Node version: 12.4.0
npm version: 6.9.0
Also have node-gyp installed.

Going through the file directories: /usr/local/lib/node_modules there is no unit-http folder, but there is an http and a seperate unit folder, Has there been a crossover due to updates or am I missing it entirely?

**Comment by artemkonev** [comment]
Hi,

Most probably, this step went missing:
> First, install the unit-dev/unit-devel package; it’s used by unit-http.

**Comment by Tricky-Ricky** [comment]
Hey @artemkonev - I did install the devel-package, and again it was throwing that error, I shall check later today to see if there has been an error in the installation and get back to you.

**Comment by artemkonev** [comment]
Hi,

I have reproduced the issue, we're looking into that as well.

**Comment by Tricky-Ricky** [comment]
Hey

Any update on this at all?

Was it a crossover with the installation - Perhaps a file directory path doesn't line up right for installation or after?

**Comment by igorclark** [comment]
Hello! I'm having the same problem, trying to install on debian 9 with the same node version (12.4.0), unit-dev installed, trying to install the latest/default version (1.9.0), and node-gyp can't find `nxt_napi.h`, either with yarn or npm.

The file's not present in the unit-http package or build folder, or as far as I can tell in the unit-dev source package (neither `dpkg -L unit-dev` nor `dpkg -c /var/cache/apt/archives/unit-dev_1.9.0-1~stretch_amd64.deb` show it). Trying to install previous versions of the npm package gives `#error "libunit version mismatch"`.

I made a [gist](https://gist.github.com/igorclark/57da79e5475daa7daf7c93a78ee63ac1) of the full output.

Any thoughts would be very welcome, thanks!

**Comment by VBart** [comment]
> trying to install the latest/default version (1.9.0), and node-gyp can't find nxt_napi.h, either with yarn or npm

It's missing in the `package.json` file. The patch below should fix the issue:
```diff
diff --git a/src/nodejs/unit-http/package.json b/src/nodejs/unit-http/package.json
--- a/src/nodejs/unit-http/package.json
+++ b/src/nodejs/unit-http/package.json
@@ -10,6 +10,7 @@
         "unit.cpp",
         "http.js",
         "http_server.js",
+        "nxt_napi.h",
         "package.json",
         "socket.js",
         "binding.gyp",
```

**Comment by igorclark** [comment]
Thanks Valentin! Away from computer at the mo but will try later. Will apply the patch to the downloaded version and try again. Will the package be updated in npm to reflect it?

**Comment by igorclark** [comment]
Hi again, not sure where to do this, I applied it to the package.json in the `node_modules/unit-http/package.json` and then ran `yarn add unit-http` (and just plain `yarn`) but it must be regenerating the file because it fails with the same error and then looking afterwards at the `package.json` the `nxt_napi.h` line isn't there any more. Do you mean this should be applied to the `unit` sources? I've installed both `unit` and `unit-dev` via `apt` on debian, so I don't know where to add this. Also the file `nxt_napi.h` file doesn't exist anywhere on my disk, so unless the patch should be applied in the source of something else which builds either `unit` or `unit-http` then I don't understand how it will fix the missing file...

How do I apply this patch on a `.deb`-installed `unit` installation?

Thanks!

**Comment by catalinconstant** [comment]
@igorclark  
Now even if you try it f from unit sources you will get an error, it is missing the version.h :)

**Comment by VBart** [comment]
@igorclark The `unit-http` package is generated from sources and then uploaded to npm repository. We are going to update the npm package on Monday. Till then you can apply the patch to Unit sources and generate the package on your own. Here's how I've just done it on a Debian 9 system:
```
% hg clone https://hg.nginx.org/unit
% cd unit
% hg up -r 1.9.0
% patch -p1 
diff --git a/src/nodejs/unit-http/package.json b/src/nodejs/unit-http/package.json
--- a/src/nodejs/unit-http/package.json
+++ b/src/nodejs/unit-http/package.json
@@ -10,6 +10,7 @@
         "unit.cpp",
         "http.js",
         "http_server.js",
+        "nxt_napi.h",
         "package.json",
         "socket.js",
         "binding.gyp",
% ./configure
% ./configure nodejs
% make
% sudo make node-install
```

**Comment by VBart** [comment]
> @igorclark
> Now even if you try it f from unit sources you will get an error, it is missing the version.h :)

The `version.h` file is generated during `make`. Probably, you've run `make node-install` right after `./configure` command.

**Comment by VBart** [comment]
> @igorclark
> Now even if you try it f from unit sources you will get an error, it is missing the version.h :)

In order to create a Node.js module from Unit sources, you have to `./configure`  the sources and then `make` the module. See the documentation here: https://unit.nginx.org/installation/#source-code or the instruction above.

**Comment by igorclark** [comment]
Hi @VBart, thanks very much, I built it using your patch and instructions and it works great! Excited to run node apps using unit. Looking forward to the npm update. Thank you! 😀

**Comment by igorclark** [comment]
Hi again @VBart, sorry to bug you, do you think it will be possible to update the npm package today, or when it might be possible, if not today? I'm working on an automated VM builder of my own and it'd be great to be able to pull in `unit-http` automatically with `yarn`. Thanks 👍

**Comment by VBart** [comment]
> Hi again @VBart, sorry to bug you, do you think it will be possible to update the npm package today

I hope so. @defanator is working on it.

**Comment by VBart** [comment]
@igorclark Fixed npm package has been uploaded as unit-http 1.9.2.
https://www.npmjs.com/package/unit-http/v/1.9.2

**Comment by igorclark** [comment]
Wonderful, thanks @VBart & @defanator! Probably won’t be get to it til the morning now but will report back then. Thank you 🙏🏼

**Comment by igorclark** [comment]
Seems to work perfectly. Going to try it in earnest. Thanks again!

**Comment by monteeya** [comment]
I'm having a similar problem on Debian 11 and Node v18.14.0:

```
...
npm ERR! In file included from ../unit.h:9,
npm ERR!                  from ../unit.cpp:6:
npm ERR! ../nxt_napi.h:20:2: error: #error "libunit version mismatch."
npm ERR!    20 | #error "libunit version mismatch."
npm ERR!       |  ^~~~~
npm ERR! ../unit.cpp: In member function ‘napi_value__* Unit::create_socket(napi_value, nxt_unit_request_info_t*)’:
npm ERR! ../unit.cpp:660:48: error: ‘nxt_unit_request_t’ {aka ‘struct nxt_unit_request_s’} has no member named ‘local_addr’
npm ERR!   660 |     set_named_property(res, "localAddress", r->local_addr,
npm ERR!       |                                                ^~~~~~~~~~
npm ERR! ../unit.cpp:661:27: error: ‘nxt_unit_request_t’ {aka ‘struct nxt_unit_request_s’} has no member named ‘local_addr_length’; did you mean ‘local_length’?
npm ERR!   661 |                        r->local_addr_length);
npm ERR!       |                           ^~~~~~~~~~~~~~~~~
npm ERR!       |                           local_length
npm ERR! make: *** [unit-http.target.mk:110: Release/obj.target/unit-http/unit.o] Error 1
```

**Comment by tippexs** [comment]
Hi @monteeya This looks like you have update the Version of Unit but not the node module?

Have you tried `npm update -g --unsafe-perm unit-http`? Please let me know if you have any more issues.

**Comment by monteeya** [comment]
Thank you for the quick reply. This happened when I tried to install the latest unit-http (v1.29.0), and the same is with 1.28.0. 

The latest version that I can install is 1.27.0.

**Comment by tippexs** [comment]
Would you mind to open a new issue providing the node version and operating system you are using? 

Will provide steps to install then. Thank you

**Comment by monteeya** [comment]
I included the Node version and OS in the first comment. Do you need some additional details?

**Comment by tippexs** [comment]
… okay … to late on a Saturday 🙈 will have a look and let you know. No need for any other action

**Comment by tippexs** [comment]
Hi @monteeya 

My environment:

```shell
docker run --rm -it node:18.14.0 /bin/bash
root@8ce71a958f3a:/#
root@8ce71a958f3a:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@8ce71a958f3a:/#
```
Remove all OLD packages!
```shell
root@8ce71a958f3a:/# apt remove unit unit-dev unit-devel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package unit
E: Unable to locate package unit-dev
```

Remove the old `unit-http` module if there is any
```shell
npm remove -g unit-http
```
Install the repository if needed.
```shell
wget https://raw.githubusercontent.com/nginx/unit/master/tools/setup-unit && chmod +x setup-unit
sudo ./setup-unit repo-config

```
Install `unit` and `unit-dev`. `unit-dev` will be used to build the node-module using `gyp`. 
```shell
apt install unit unit-dev
```
Install the node-module in your project dir.

```
npm install unit-http
```

This just worked on my box. Let me know if that works for you as well.

**Comment by monteeya** [comment]
OK, I tried to install everything for the scratch in a clean Debian 11 chroot and it works fine, so the problem is obviously somewhere on my current installation. I'll try to remove everything and reinstall it again. Thank you very much for your help.

**Comment by tippexs** [comment]
@monteeya glad it worked. Let me know if you need any help on your current system. Have a great rest of your weekend.
