### ISSUE TITLE
Running sudo commands from web server running on NGINX Unit

### ISSUE THREAD

**Issue by incube8r** [nginx/unit#262]
This is more of a question than an issue,

In what way we can make Java web running on NGINX Unit be able to execute _sudo_ command. 
Example in Tomcat you can add tomcat user to sudoers and Java web app can then execute _sudo_ commands. 

With NGINX Unit how can something similar be achieved?

**Comment by mar0x** [comment]
Hello.

Yes. You may configure effective user and group for all applications including Java. Please read the [Configuration->Applications](http://unit.nginx.org/configuration/#applications) section in Unit documentation.
