### ISSUE TITLE
I have a problem with HTTP/2

### ISSUE THREAD

**Issue by AlexBerdnikow** [nginx/unit#263]
Hello everyone.
First of all I want to thank the developers of Nginx Unit for creating a great product. I used Unit in two working web services and am happy with the result.

I have a question. 
I use Nginx Web Server to process requests. Requests starting with /stylesheets, /javascripts, and /images Nginx sends files, and all other requests are proxied to Unit. A few days ago I enabled HTTP/2 in Nginx Web Server settings. I started to test the utility curl and get this result.

All requests that nginx Web Server processes on its own return a response:

```
sudo curl -IL http://www.malinavisa.ru/stylesheets/common.css

HTTP/2 200
server: nginx/1.17.0
date: Fri, 14 Jun 2019 10:27:06 GMT
content-type: text/css
content-length: 15183
last-modified: Wed, 12 Jun 2019 14:08:57 GMT
etag: "5d010779-3b4f"
strict-transport-security: max-age=15768000
accept-ranges: bytes
```

However, requests that Nginx Web Server proxies to Unit return a response:
```
sudo curl -IL http://www.malinavisa.ru/

HTTP/2 404
server: nginx/1.17.0
date: Fri, 14 Jun 2019 10:29:29 GMT
content-type: text/html
content-length: 67
strict-transport-security: max-age=15768000
```

At the same time, the page opens correctly in the browser. 

Tell please, this problem has to do with Unit?

**Comment by mar0x** [comment]
Hello.

Thanks for using Unit and for positive feedback!

The key difference in your curl request and normal browser requests is HEAD method. Maybe Nginx Web Server does not pass HEAD requests to your application or application itself respond with 404 for HEAD request.

You may try to send direct HEAD request to Unit. If it works - check the Nginx Web Server configuration.

**Comment by AlexBerdnikow** [comment]
You're right. Unit processes only GET requests coming for applications. This is specified in the Unit settings.

Thank you very much for your answer.
