### ISSUE TITLE
Running the Flask application on the unit and virtualenv error

### ISSUE THREAD

**Issue by skillslasher** [nginx/unit#267]
There was a problem. Some days I can not start the python flask application on unit.

The application is located in the following way:

> /srv/site.com/public

Application structure:

```
static/
flask/
       main.py
       app.py
       config.py
venv/
```

At the app.py point, the call goes:
```
if __name __ == "__ main__":
        application.run ()
```

unit configuration:
```
{
	"applications": {
		"flask": {
			"type": "python",
                         "processes": 2,
                         "user": "alist",
                         "group": "www-data",
                         "working_directory": "/srv/site.com/public/",
                         "path": "/srv/site.com/public/flask/",
			 "home": "/srv/site.com/public/venv/
                         "module": "app"
		}
	},

	"listeners": {
		"*:8300": {
			"pass": "applications/flask"
		}
	}
}
```
When trying to add a configuration:

> curl -X PUT --data-binary @ / home / alist / Documents / flask.json \ 
> --unix-socket /run/control.unit.sock \
> http: // localhost / config

I get the error:
> {
> "error": "Failed to apply new configuration."
> }

In the logs it is:
> Fatal Python error: Py_Initialize: Unable to get the locale encoding
> ImportError: No module named 'encodings'
> 
> Current thread 0x00007fcfdbda3940 (most recent call first):
> 2019/06/21 01:40:26 [alert] 13994#13994 process 14411 exited on signal 6 (core d
> umped)

I understand the error because of not connected virtualenv.
Tell me, please, how to connect virtualenv? Documentation does not help.

**Comment by artemkonev** [comment]
Hello,

Which Python version are you using in your system and for your venv?

**Comment by skillslasher** [comment]
The system has python 2.7.12 and python 3.5.2 installed. The system itself 16.04.6 LTS (Xenial Xerus).
In virtualenv (venv/bin/) python, python3 and python3.6.

From virtualenv Python3 (3.5.2) is launched. Python3.6 is not.
In venv / lib / python3.6 there is.

Since the application of another developer can not exclude that he wrote using python 3.6. Do I need to install python 3.6 into the system?

**Comment by VBart** [comment]
@skillslasher Unit doesn't use command-line Python interpreter. For performance reason it uses its own Python modules. If Unit was installed from our packages, then please check that you have "unit-python3.5" module as well.

It's also possible that this particular application requires Python version 3.6+. In this case, you need a corresponding module to run the app in Unit.

**Comment by skillslasher** [comment]
Thanks for the tip. The error was in virtualenv. Something went wrong with the transfer.

Not to create new thread I will ask here.

Is there php7.2 support? If I use the "type": "php 7.2" in the Unit configuration, it does not work.

**Comment by VBart** [comment]
Absolutely similar to Python. In order to use PHP 7.2, it have to be compiled as a module for Unit.

**Comment by skillslasher** [comment]
And where to read the information on how to compile modules for a unit?

**Comment by VBart** [comment]
@skillslasher https://unit.nginx.org/installation/#source-code

**Comment by VBart** [comment]
But usually it's a bad idea to combine outdated operating system with a newer software. I suggest to update the OS to the version, where PHP 7.2 is native and comes out of the box.

**Comment by skillslasher** [comment]
Tell me, please, what is the problem.
System version: 16.04.5 LTS (Xenial Xerus)
Linux version 2.6.32-042stab138.1

When attempting to update the configuration the following error:

> {
>         "error": "Memory allocation failed."
> }

In the log it is:

> [alert] 3482#3482 *6 memfd_create(/unit.3482.691e6c0b) failed (38: Function not implemented)

Free RAM = 800MB
Swp = free
Free HDD = 83%

In addition to unit, unit-python3.5 is also installed. 
Unit itself starts normally. But I can not update the configuration.

**Comment by VBart** [comment]
@skillslasher You kernel and environment doesn't match. The Ubuntu 16.04.5 LTS distribution is based on Linux kernel version 4.4.0, but your kernel has version 2.6.32 (released in 2009).

As a result, Unit is built to use `memfd_create()` syscall (which is available since 3.7.0) and can't work with 2.6.32. If you rebuild Unit without `memfd_create()` syscall, then it may work. But the right solution would be to fix your Ubuntu installation. Otherwise, you will experience various problems in other software as well.

**Comment by skillslasher** [comment]
Thank you very much for the help.
I can not update because of the hosting. Virtualization OVZ core which they do not update.

**Comment by VBart** [comment]
You can use `--cc-opt='-DNXT_HAVE_MEMFD_CREATE=0'` configure option in order to compile without `memfd_create()`. Please, see issue https://github.com/nginx/unit/issues/256 with similar problem.

**Comment by skillslasher** [comment]
Thanks for the tip.
