### ISSUE TITLE
node.js state.pipesCount === 0 TypeError

### ISSUE THREAD

**Issue by freerider7777** [nginx/unit#268]
Hi,

I've configured docker image with unit to run node.js express app, but at last it's giving an error
(I've packed all the contents of www folder in docker config.json, application and so on
https://drive.google.com/open?id=1nXQkxJYXlUC3GdeOzDvlB19b1Sm2nxj6
)

GET / - - ms - -
!!!!!!!!!!!!!! ->
_stream_readable.js:792
  if (state.pipesCount === 0)
            ^
2019-06-21T07:51:55.115296600Z 
TypeError: Cannot read property 'pipesCount' of undefined
    at ServerRequest.Readable.unpipe (_stream_readable.js:792:13)
    at unpipe (/www/myapp/node_modules/unpipe/index.js:47:12)
    at send (/www/myapp/node_modules/finalhandler/index.js:306:3)
    at Immediate.<anonymous> (/www/myapp/node_modules/finalhandler/index.js:133:5)
    at Immediate.<anonymous> (/www/myapp/node_modules/express/lib/router/index.js:635:15)
    at processImmediate (internal/timers.js:441:21)
2019/06/21 07:51:55 [notice] 1#1 process 9 exited with code 1
2019/06/21 07:51:55 [info] 33#33 "node1" application started

**Comment by VBart** [comment]
Please notice the step 4 in Express howto: https://unit.nginx.org/howto/express/

With Express apps, apart from using CreateServer from unit-http, you also have to replace ServerResponse and IncomingMessage in http module.

**Comment by freerider7777** [comment]
Aha... thanks, I'll try!
I followed
https://unit.nginx.org/installation/
->
https://unit.nginx.org/installation/#node-js-package
After that, use the package in your Node.js 
->
https://unit.nginx.org/configuration/#configuration-external-nodejs
And it's not obvious that there are additional changes

**Comment by VBart** [comment]
@freerider7777 Thanks for the feedback. The docs has been updated to emphasize additional changes for Express applications, see step 3: https://unit.nginx.org/installation/?1561121253#node-js-package

**Comment by freerider7777** [comment]
@VBart  Thanks for quick help! Now it's working ok.
