### ISSUE TITLE
Unable to install unit-http - Ubuntu 18.04 Beaver

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#269]
Following through the documentation to install on Ubuntu, Got as far as trying to install unit-http.

Exited with this:

> @Server:~$ sudo npm install -g --unsafe-perm unit-http
> 
> > unit-http@1.9.2 install /usr/local/lib/node_modules/unit-http
> > node-gyp configure build
> 
> make: Entering directory '/usr/local/lib/node_modules/unit-http/build'
>   CXX(target) Release/obj.target/unit-http/unit.o
> In file included from ../unit.h:9:0,
>                  from ../unit.cpp:6:
> ../nxt_napi.h: In member function ‘napi_value__* nxt_napi::make_callback(napi_async_context, napi_value, napi_value, int, napi_value__* const*)’:
> ../nxt_napi.h:390:22: error: ‘napi_fatal_exception’ was not declared in this scope
>              status = napi_fatal_exception(env_, ex);
>                       ^~~~~~~~~~~~~~~~~~~~
> ../nxt_napi.h:390:22: note: suggested alternative: ‘napi_fatal_error’
>              status = napi_fatal_exception(env_, ex);
>                       ^~~~~~~~~~~~~~~~~~~~
>                       napi_fatal_error
> ../nxt_napi.h: At global scope:
> ../nxt_napi.h:652:5: error: ‘napi_callback_scope’ does not name a type; did you mean ‘nxt_callback_scope’?
>      napi_callback_scope  scope_;
>      ^~~~~~~~~~~~~~~~~~~
>      nxt_callback_scope
> ../nxt_napi.h: In constructor ‘nxt_callback_scope::nxt_callback_scope(nxt_async_context&)’:
> ../nxt_napi.h:635:66: error: ‘scope_’ was not declared in this scope
>          status = napi_open_callback_scope(env(), resource, ctx, &scope_);
>                                                                   ^~~~~~
> ../nxt_napi.h:635:66: note: suggested alternative: ‘bcopy’
>          status = napi_open_callback_scope(env(), resource, ctx, &scope_);
>                                                                   ^~~~~~
>                                                                   bcopy
> ../nxt_napi.h:635:18: error: ‘napi_open_callback_scope’ was not declared in this scope
>          status = napi_open_callback_scope(env(), resource, ctx, &scope_);
>                   ^~~~~~~~~~~~~~~~~~~~~~~~
> ../nxt_napi.h:635:18: note: suggested alternative: ‘napi_open_handle_scope’
>          status = napi_open_callback_scope(env(), resource, ctx, &scope_);
>                   ^~~~~~~~~~~~~~~~~~~~~~~~
>                   napi_open_handle_scope
> ../nxt_napi.h: In destructor ‘nxt_callback_scope::~nxt_callback_scope()’:
> ../nxt_napi.h:645:51: error: ‘scope_’ was not declared in this scope
>          status = napi_close_callback_scope(env(), scope_);
>                                                    ^~~~~~
> ../nxt_napi.h:645:51: note: suggested alternative: ‘bcopy’
>          status = napi_close_callback_scope(env(), scope_);
>                                                    ^~~~~~
>                                                    bcopy
> ../nxt_napi.h:645:18: error: ‘napi_close_callback_scope’ was not declared in this scope
>          status = napi_close_callback_scope(env(), scope_);
>                   ^~~~~~~~~~~~~~~~~~~~~~~~~
> ../nxt_napi.h:645:18: note: suggested alternative: ‘napi_close_handle_scope’
>          status = napi_close_callback_scope(env(), scope_);
>                   ^~~~~~~~~~~~~~~~~~~~~~~~~
>                   napi_close_handle_scope
> unit-http.target.mk:98: recipe for target 'Release/obj.target/unit-http/unit.o' failed
> make: *** [Release/obj.target/unit-http/unit.o] Error 1
> make: Leaving directory '/usr/local/lib/node_modules/unit-http/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:190:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.15.0-52-generic
> gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
> gyp ERR! cwd /usr/local/lib/node_modules/unit-http
> gyp ERR! node -v v8.10.0
> gyp ERR! node-gyp -v v5.0.1
> gyp ERR! not ok
> npm ERR! Linux 4.15.0-52-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "unit-http"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! unit-http@1.9.2 install: `node-gyp configure build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the unit-http@1.9.2 install script 'node-gyp configure build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the unit-http package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp configure build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs unit-http
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls unit-http
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ricky/npm-debug.log

Not sure what is causing this?

**Comment by VBart** [comment]
Please note [here](https://unit.nginx.org/installation/#prerequisites) that only Node.js 8.11 or later versions are supported. Node.js 8.10 has different nAPI and it's deprecated long time ago.

**Comment by VBart** [comment]
To install actual version of Node.js, please consult with official instructions: https://nodejs.org/en/download/package-manager/

**Comment by Tricky-Ricky** [comment]
Ah - Thanks, I had 8.10 installed, That was my problem - Thank you
