### ISSUE TITLE
[php] SCRIPT_FILENAME is not parsed correctly

### ISSUE THREAD

**Issue by docteurklein** [nginx/unit#27]
my config looks like that:

```
% curl --unix-socket /usr/src/app/control.unit.sock http://localhost/
{
        "listeners": {
                "*:8300": {
                        "application": "api"
                }
        },

        "applications": {
                "api": {
                        "type": "php",
                        "workers": 20,
                        "root": "/usr/src/app/web",
                        "index": "app.php"
                }
        }
}
```

I'd like being able to call URLs like `/app.php/en/contents` or `/en/contents`, but none of them works:

```
% curl localhost:8300/app.php/en/contents

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required '/usr/src/app/web/app.php/en/contents' (include_path='.:/usr/share/php') in Unknown on line 0
```

The problem apparently lies in the detection of the `SCRIPT_FILENAME`. It should parse the url and extract the filename, or maybe the `index` option of the config should be populating the `SCRIPT_FILENAME` all the time.

Any idea how to achieve that?
Thanks!

**Comment by mar0x** [comment]
"index" value used when file name is empty (e.g. URL ends on '/').
If you want to process ALL requests by app.php, you need to use "script": "app.php" (see https://github.com/nginx/unit#php-application )

**Comment by docteurklein** [comment]
i'm so sorry… I didn't see that option even tho I searched for it in the docs! That makes me a bad reader :) thanks. closing.
