### ISSUE TITLE
PHP: failed to disable "eval": no such function

### ISSUE THREAD

**Issue by grandtele** [nginx/unit#271]
unit v1.9

2019/06/24 15:37:28 [error] 19829#19829 PHP: failed to disable "dl": no such function
2019/06/24 15:37:28 [error] 19829#19829 PHP: failed to disable "eval": no such function
2019/06/24 15:37:28 [error] 19829#19829 PHP: failed to disable "source": no such function

**Comment by VBart** [comment]
There are no such functions in PHP 7.

`dl()` was removed in PHP 7.0.0;
`eval()` isn't a function, but a language construction like `if` or `for` (so it can't be disabled via `disable_functions` option);
`source()` it seems a function with such name has never existed: https://www.php.net/manual-lookup.php?pattern=source
