### ISSUE TITLE
Can we get an example of a Node.js through Unit

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#273]
Trying to go throught the documentation to find an example of how to tie node through unit, is a Nightmare - It leads you through a maze and often gives you examples with Python.

I'm learning as I go - But I can not make heads or tales of the documentation and think it is a real put off for others that may want to try.

Not being negative, I like the project - But it is so hard to try and piece everything together.

Like, where do I store the app - Then where is the Unit config files similar to nginx.conf - To set up the Unit server - Do I need to set a Node server up first? Do I have to use Express or Docker?

Has anyone got a Node server up through Unit yet and able to help?

**Comment by artemkonev** [comment]
Hi, 

Sure. Please take a look at this Docker sample: http://unit.nginx.org/howto/docker/#containerizing-apps

The samples list all actions necessary to run a Node.js app in Unit (you can drop Express-related stuff if you don't need it).

**Comment by Tricky-Ricky** [comment]
Thank you for this.
