### ISSUE TITLE
 [emerg] no port in upstream 

### ISSUE THREAD

**Issue by AncalagonTheBlack** [nginx/unit#275]
I haven't changed anything except updated the packages. But when i now try to start nginx i get this error message:

nginx: [emerg] no port in upstream "php-handler" in /etc/nginx/sites-enabled/dragoncloud:107

PHP-FPM is up and running the port is also the right one 127.0.0.1

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
