### ISSUE TITLE
Unit cannot simultaneously execute Method (Java)

### ISSUE THREAD

**Issue by incube8r** [nginx/unit#278]
I have this code 

```
JarByteClassloader loader = new JarByteClassloader(jar);
Class c = loader.loadClass(classToLoad);
Thread.currentThread().setContextClassLoader(loader);
JarEntryObject jarEntry = (JarEntryObject) c.newInstance();
Method method = jarEntry.method();
method.execute(); 
```
What this does essentially is to dynamically execute methods called through the REST API. 

On local Jetty server, it can execute simultaneously, meaning if 10 request came, it will execute the 10 methods concurrently, but when running on Nginx Unit, it seems that until the first method is not done, the second request will not execute (waiting), thus not simultaneously.

Is this a normal behavior of Unit?

**Comment by incube8r** [comment]
@mar0x @VBart 

```
ExecutorService executor = Executors.newCachedThreadPool();
Callable < Map < String, ? >> task = new Callable < Map < String, ? >> () {
    @Override
    public Map < String, ? > call() throws Exception {
        Map < String, ? > result = cc.execute();
        while (true) {} // notice this
        return result;
    }
};
Future < Map < String, ? >> futureResult = executor.submit(task);
Map < String, ? > result = futureResult.get(timeoutInSeconds, TimeUnit.SECONDS);
```

The code above gets executed by Unit but apparently, it is unable to timeout causing the server to peak at 100% all the time, the `while(true) {}` is a test code as we all know to simulate such code that does not terminate inside the task so the `Future` does have a timeout to kill it in case, `timeoutInSeconds` in this case is 10 seconds, again the same code works fine in Jetty, and terminates within 10 seconds.

**Comment by mar0x** [comment]
Hello @incube8r ,
Yes, request processed in Java application in a single thread. It is normal for current version of Unit. We have plans to improve this in future.

Regarding the behaviour of Future, according to [the spec](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#get(long,%20java.util.concurrent.TimeUnit)), get(..) method should not interrupt the task you should only obtain the result, but there is no code above to interrupt the executor thread. Please explain how do you use such code in request processing?

**Comment by incube8r** [comment]
@mar0x so meaning if we use Unit our Servlet will be limited to be a single-threaded application and if our application receives thousands to millions of requests then all will be executed one by one? So if we have a resource that executes at about 1 sec, then for the one-millionth request would wait about 2 weeks to be executed? (Although obviously, the client will terminate the request already) Thus, using Unit is not ideal for a Servlet application?

 About the `Future`, I am not sure if I understand your question correctly but that code works in that in 10 seconds the `while(true)` loop gets terminated.

**Comment by mar0x** [comment]
@incube8r as I said before, current single thread request processing limitation is _temporary_. The application still able to spawn it's own threads and this it not a "_single-threaded application_" limitation.

All these marketing calculations are just a buzzwords: we understand that 1 thread request processing is a limitation, you understand that 1 second is too long for average request processing time etc.

Do you have understanding how this 'while()' loop terminated? Or could you please provide a servlet sample which works in Jetty as expected and does not works in Unit. With this sample I can reproduce the issue and try to fix it.

**Comment by incube8r** [comment]
@mar0x I created a showcase for the ExecutorService here: https://github.com/incube8r/ExecutorServlet

Just run it with `mvn jetty:run` all details are in the README

Test with `$curl http://localhost:8080/executor/{timeout}`

Replace timeout with seconds in integer format, e.g `$curl http://localhost:8080/executor/10`

The response should look like this `ERROR - Total Time: {timeout}`

I have tested this just now and timeout text matches the timeout passed in the HTTP request

**Comment by mar0x** [comment]
@incube8r Thank you for the sample!
I've running as you suggested, with `mvn jetty:run`. As expected, curl gets error response, but loop continue to run, one CPU core loaded 100%. After executing next request, one more CPU core loaded 100% and so on.
I'm unable to test produced war in Unit and Tomcat because no servlets registered.

**Comment by mar0x** [comment]
I've changed `pom.xml` and built proper war file which is able to handle requests in Unit. Patch:
```
diff --git a/pom.xml b/pom.xml
index 3d781a3..90acf85 100644
--- a/pom.xml
+++ b/pom.xml
@@ -65,10 +65,6 @@
 			<plugin>
 				<artifactId>maven-war-plugin</artifactId>
 				<version>2.6</version>
-				<configuration>
-					<warSourceDirectory>WebContent</warSourceDirectory>
-					<failOnMissingWebXml>false</failOnMissingWebXml>
-				</configuration>
 			</plugin>
 			<plugin>
 				<groupId>org.eclipse.jetty</groupId>
```
Request is timed out same as under Jetty. While loop keep running. The bad and inconvenient thing is application failed to stop by Unit, it keep running until manually killed. I will have a look what we can do in Unit for such apps.

**Comment by mar0x** [comment]
@incube8r Can you confirm CPU core loaded 100% after first request on Jetty in your environment?

**Comment by tippexs** [comment]
Closed due to implementation.
