### ISSUE TITLE
proxy server,slice+limit_rate，keepalive connection will be delayed recv

### ISSUE THREAD

**Issue by kuninchengdu** [nginx/unit#279]
slice 512k;
limit_rate 512k;
proxy_pass ...

above configuration，ngx_http_write_filter will delay when sending last data，but request is main request，then ngx_http_slice_body_filter will exec ‘ngx_http_send_special(r, NGX_HTTP_LAST)’，and
ngx_http_write_filter will exec as following：
    if (c->write->delayed) {
        c->buffered |= NGX_HTTP_WRITE_BUFFERED;
        return NGX_AGAIN;
    }

then ngx_http_writer will return because c->buffered is not zero
 if (r->buffered || r->postponed || (r == r->main && c->buffered)) {
        if (!wev->delayed) {
            ngx_add_timer(wev, clcf->send_timeout);
        }
        if (ngx_handle_write_event(wev, clcf->send_lowat) != NGX_OK) {
            ngx_http_close_request(r, 0);
        }
        return;
    }

so，client reuse this connection to send a new request，but r->read_event_handler is ngx_http_test_reading，it only peek， after delay ms，old request will close and exec 
ngx_http_set_keepalive and ngx_http_process_request_line，and new request can be recived

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html

**Comment by kuninchengdu** [comment]
> This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.
> 
> Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html

tks,i have reported this at https://trac.nginx.org/nginx/ticket/1811
