### ISSUE TITLE
[php] passing env variables to the workers

### ISSUE THREAD

**Issue by docteurklein** [nginx/unit#28]
Is it possible to make the workers inherit from the environment variables of the main process?

**Comment by igorsysoev** [comment]
On 12 Sep 2017, at 14:14, Florian Klein <notifications@github.com> wrote:

> Is it possible to make the workers inherit from the environment variables of the main process?
> 
The variables should be inherited by default.


-- 
Igor Sysoev
http://nginx.com

**Comment by docteurklein** [comment]
thanks for the quick answer!
Indeed they are but only via `$_ENV`. which is fine by me!
It differs however of the fcgi implementation (see http://php.net/manual/en/ini.core.php#ini.variables-order):

```

**Comment by igorsysoev** [comment]
On 12 Sep 2017, at 14:41, Florian Klein <notifications@github.com> wrote:
> thanks for the quick answer!
> Indeed they are but only via $_ENV. which is fine by me!
> It differs however of the fcgi implementation (see http://php.net/manual/en/ini.core.php#ini.variables-order):
> 
Thank you, we will look at variables_order.


-- 
Igor Sysoev
http://nginx.com

**Comment by bbak** [comment]
IHMO there should also be an option to set ENV Variables per application. 

Use case: When running multiple Symfony Applications (one for dev and one for testing) in one Instance of unit, you have to set the Environment Variable SYMFONY_ENV accordingly.

Additionally just making all Environment Variables from the master process available to all applications may lead into either massive overhead or a security problem.

**Comment by VBart** [comment]
@bbak Such option is already there. Please see Unit 1.2 release notes: http://mailman.nginx.org/pipermail/unit/2018-June/000055.html

**Comment by yannickgranger** [comment]
Hello,

In my conf i setup env var :

```
"app": {
      "type": "php8.0",
      "user": "user",
      "group": "user",
      "environment": {
        "APP_ENV": "prod",
        "DATABASE_URL": ""
      },
      "options": {
        "admin": {
          "memory_limit": "256M",
          "variables_order": "EGPCS"
        }
      },
      "targets": {
        "direct": {
          "root": "/srv/app/app/public/",
          "script": "index.php"
        },
        "index": {
          "root": "/srv/app/app/public/",
          "script": "index.php"
        }
      }
    }
```

But the symfony app just read the one from .env file. I pushed them correctly via socket :

```
{
    "DATABASE_URL": "postgresql://db_user:db_password@127.0.0.1:5432/db_name?serverVersion=13&charset=utf8}"
}

```
An idea please :)

**Comment by yannickgranger** [comment]
> thanks for the quick answer!
> Indeed they are but only via `$_ENV`. which is fine by me!
> It differs however of the fcgi implementation (see http://php.net/manual/en/ini.core.php#ini.variables-order):
> 
> ```
> In both the CGI and FastCGI SAPIs, $_SERVER is also populated by values from the environment; S is always equivalent to ES regardless of the placement of E elsewhere in this directive.
> ```
> 
> Maybe it would worth add it in the docs to avoid potential head scratching?

@docteurklein when they are in $_ENV how do I get them used in the app ?

**Comment by VBart** [comment]
@yannickgranger  since previously you've asked about Symphony, then I assume that your question is about how to use such variables with Symphony: https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables

**Comment by yannickgranger** [comment]
Yes and no. I followed here this thread and thought it was ok to have it in $_ENV.  And looking at discussions in symfony pages, it's an old PHP issue.

Maybe i misconfigured Unit but I don't see how to grab the variable in config. If i set variable_orders: "ES" there's only $_ENV populated. The orm does not seems to "see" the env var DATABASE_URL in it's conf file when I pass it via unit json config.

```
      "environment": {
        "APP_ENV": "prod",
        "DATABASE_URL": "sqlite:///%kernel.project_dir%/var/data.db"
      },
```

**Comment by VBart** [comment]
@yannickgranger I guess it doesn't interpolate it twice (i.e. recursive), so it sets your database url to `sqlite:///%kernel.project_dir%/var/data.db` without replacing `%kernel.project_dir%` to the actual path.

**Comment by VBart** [comment]
Though it provides the `resolve` processor that will interpolate the value of $_ENV: https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors
