### ISSUE TITLE
404 not found wordpress

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#280]
Followed the guide here: https://www.nginx.com/blog/installing-wordpress-with-nginx-unit/

To start with there was a database error, due to PHP 7 not supporting mySql or something like that, so I ended up having to do this:
 
`sudo apt-get install php-mysql`

That fixed the database error I was getting, However now, I get a 404 Not found, when trying to install wordpress. Other than that line above, I followed the guide to a T, and everything seems to check out - So I am unsure why I am getting this error.

The page it is trying to load by default is:
http://server_IP/wp-admin/install.php

But it won't progress past that point.

**Comment by Tricky-Ricky** [comment]
Just to update this - I no longer get the 404 Error, Instead I am getting error 500 Internal Server Error...

I am not quite sure what is causing this, But suspect it may be the Nginx configuration in regards to dealing out static sites.

I'll uninstall all of it shortly, and go through the guides again, to see if I can re-produce and/or fix the issue

**Comment by VBart** [comment]
@Tricky-Ricky There is official HowTo on WordPress: http://unit.nginx.org/howto/wordpress/ The blog post you are referring can be outdated.

**Comment by Tricky-Ricky** [comment]
I think I know what the issue is.

Upon installing Nginx there is no default.conf found in /etc/nginx/conf.d - Which most guides seem to point too.

Instead nginx seems to use nginx.conf found in /etc/nginx
Which also in term uses sites-available and sites-enabled for static sites.

I've done a fresh install of Nginx downloaded from the repository as per the guide, and also a fresh install of Unit as per the guide.

**Comment by Tricky-Ricky** [comment]
Just to update this - Resolved the issue.

It isn't directly an Nginx problem - Apologies.

The PHP 7.2 that comes with Ubuntu 18.04 is partially broken - So you have ton sudo apt purge php7.2 and php7.2-mysql - Then re-install it.

But for some reason, it only worked for me, Once everything was configured and ready to go beforehand, You then obvs have to restart Nginx.
