### ISSUE TITLE
Installing SSL Certificate on Wordpress breaks Upstream

### ISSUE THREAD

**Issue by Tricky-Ricky** [nginx/unit#282]
I have updated the php7.2-fpm to increase the max file size
I have updated the wp-config to increase the max file size
I have updated my server file to increase the max file size

Wordpress still shows as a 2MB upload limit from host, I checked the logs and I get:

> sendfile() failed (32: broken pipe) While sending request to upstream

This has only happened since I installed an SSL Certificate from letsencrypt - Before the certificate was issued I had 64MB Max file size. As far as I am aware, Everything has been configured correctly (Spent the last 5 hours sorting stuff because of that SSL Certificate)

I only have 1 plug-in on the site - Which is not the problem.

From what I have read it appears the upstream sends the file in parts to the back-end (Unit) - Which then returns it back to Nginx before it expects it, and throws a 502 error...

Only thing that I have found which makes any sense is this: [https://blog.bigbinary.com/2016/01/07/not-using-https-might-be-breaking-file-uploads.html]

Otherwise has anyone come across this issue?
(https://blog.bigbinary.com/2016/01/07/not-using-https-might-be-breaking-file-uploads.html)

**Comment by Tricky-Ricky** [comment]
Update:
I ran phpinfo.php - The file size issue was that my Wordpress decided to use the embed php.ini file rather than the fpm php.ini file... Now file size has updated correctly.

However still getting:

> sendfile() failed (32: broken pipe) while sending request to upstream

I have re-checked all my configs, and they look fine

**Comment by VBart** [comment]
@Tricky-Ricky What is size of file you are uploading? Please note the max_body_size configuration option: https://unit.nginx.org/configuration/#settings

**Comment by Tricky-Ricky** [comment]
It is a compressed zipped file for a theme, The file size does not exceed 8,207 KB...

If it is any consolation - This particular theme uploaded properly yesterday, But does now not want to upload.

While I think about it, It may be due to a duplicate file name - Let me check...

**Comment by Tricky-Ricky** [comment]
Can confirm file name is not causing the issue.
I tried uploading an 8MB Image file for Media aswel, And got passed an HTTP Error - Pointing again to the SSL from LetsEncrypt which was installed through Certbot.

Looking at Sitehealth under the WP dashboard i get:
> "The rest api has encountered an error" - cURL error 28

So far, I have followed this guide here: 
[https://wpquark.com/kb/misc/server-management/fixing-curl-ssl-connection-issue-php-ini/](https://wpquark.com/kb/misc/server-management/fixing-curl-ssl-connection-issue-php-ini/)

And also made the following changes in the server config, as recommended here:
[https://wordpress.stackexchange.com/questions/250730/rest-api-parameters-not-working-with-nginx](https://wordpress.stackexchange.com/questions/250730/rest-api-parameters-not-working-with-nginx)

Those changes there seem to be the most recommended but still doesn't resolve the issue for myself.
Here is my server config:
`
upstream unit_wp_index {
    server 127.0.0.1:8090; # NGINX Unit backend address for index.php with
                           # 'script' parameter
}
upstream unit_wp_direct {
    server 127.0.0.1:8091; # NGINX Unit backend address for generic PHP file handling
}
server {
    client_max_body_size 120M;
    server_name localhost;
    root        /var/www/sitename/;

    location / {
        try_files $uri /index_php$is_args$args;
    }
    location @index_php {
        proxy_pass       http://unit_wp_index;
        proxy_set_header Host $host;
    }
    location /wp-admin {
        index index.php;
    }
    location ~* \.php$ {
        try_files        $uri =404;
        proxy_pass       http://unit_wp_direct;
        proxy_set_header Host $host;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sitename/fullchain.pem; # managed by $
    ssl_certificate_key /etc/letsencrypt/live/sitename/privkey.pem; # managed b$
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    }
server {
    if ($host = www.sitename.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = sitename.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen      80;
    server_name sitename.co.uk www.sitename.co.uk;
    return 404; # managed by Certbot
    }
`
It's pretty much identical to the nginx / wordpress set-up from the docs and the blogs - Albeit with the change mentioned above and the `client_max_body_size` - Which has to be put in here for it to update correctly, regardless of the php.ini files

**Comment by Tricky-Ricky** [comment]
So I re-installed wordpress, nginx and Unit over the weekend - It still gives me the same problem with any file around 8M or above - Heres my config files to rule out issues with the config on the new set-up (This set-up seems to give better site health overall):
*** Server Conf***
```
upstream index_php_upstream {
        server 127.0.0.1:8090; # Nginx Backend with Script parameter
}
upstream direct_php_upstream {
        server 127.0.0.1:8091; # Nginx backend for general PHP handling
}
server {
        listen 443 ssl;

        root /var/www/****/wordpress/;
        index index.php;
        error_log /var/log/nginx/****-error.log;

        server_name **** ****;

        client_max_body_size 64M;

        location / {
                try_files $uri @index_php;
        }

        location @index_php {
                proxy_pass              http://index_php_upstream;
                proxy_set_header        Host $host;
        }

        location /wp-admin {
                index index.php;
        }

        location ~* .php$ {
                try_files               $uri =404;
                proxy_pass              http://direct_php_upstream;
                proxy_set_header        Host $host;
        }

        ssl_certificate /etc/letsencrypt/live/****/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/****/privkey.pem; # managed by Certbot
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers off;
}
server {
    if ($host = www.****) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = ****) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;

    server_name **** ****;
    return 404; # managed by Certbot
}

```
*** wordpress.config***
```
{
    "listeners": {
        "127.0.0.1:8090": {
            "application": "script_index_php"
        },
        "127.0.0.1:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "***",
            "group": "www-data",
            "root": "/var/www/*****/wordpress",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "***",
            "group": "www-data",
            "root": "/var/www/****/wordpress",
            "index": "index.php"
        }
    }
}

```
*** wp-config.php ***
```
<?php
// Fix redirect issues
define( 'WP_HOME', 'https://pagephoenix.co.uk');
define( 'WP_SITEURL', 'https://pagephoenix.co.uk');

// SSL Settings
define('FORCE_SSL_ADMIN', true);
 if ( true !== strpos( $_SERVER['HTTP_X_FORWARDED_PROTO'], 'https')){
        $_SERVER['HTTPS']='on';
}
// Enable Caching
define( 'WP_CACHE', true );

// DB Settings
define( 'DB_NAME', '****' );
define( 'DB_USER', '*****' );
define( 'DB_PASSWORD', '*****' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );
define( 'AUTH_KEY',         '****' );
define( 'SECURE_AUTH_KEY',  '****' );
define( 'LOGGED_IN_KEY',    '****' );
define( 'NONCE_KEY',        '****' );
define( 'AUTH_SALT',        '****' );
define( 'SECURE_AUTH_SALT', '****' );
define( 'LOGGED_IN_SALT',   '****' );
define( 'NONCE_SALT',       '****' );
$table_prefix = 'wp_';

// Debugging
define( 'WP_DEBUG', false );
define( 'WP_DEBUG_DISPLAY', false); // Don't show on front end
define( 'WP_DEBUG_LOG', true); // Show debug log in wp-content

// Memory Limit Increase
define( 'WP_MEMORY_LIMIT', '256M' );

// Stop Editing
if ( ! defined( 'ABSPATH' ) ) {
        define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}

/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );

```
** Error Logs **

> SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking

> sendfile() failed (32: Broken pipe) while sending request to upstream, client: ****, server: ****, request: "POST /wp-admin/async-upload.php HTTP/1.1", upstream: "http://127.0.0.1:8091/wp-admin/async-upload.php", host: "****", referrer: "https://****/wp-admin/media-new.php"

** Errors in Wordpress **

> HTTP Error

> The REST API request failed due to an error.
> ERROR: [] cURL error 28: Connection timed out after 10001 millisecond

**Comment by VBart** [comment]
@Tricky-Ricky If you'd like to upload 8Mb+ files, then you need to increase the `max_body_size` value in Unit. For example:
```json
{
    "settings": {
        "http": {
            "max_body_size": 67174400
        }
    },

    "listeners": {
        "127.0.0.1:8090": {
            "pass": "applications/script_index_php"
        },
        "127.0.0.1:8091": {
            "pass": "applications/direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "***",
            "group": "www-data",
            "root": "/var/www/*****/wordpress",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "***",
            "group": "www-data",
            "root": "/var/www/****/wordpress",
            "index": "index.php"
        }
    }
}
```

**Comment by Tricky-Ricky** [comment]
@VBart - I shall try that - Although the way it is set-up now, It worked before SSL was installed

I'm more concerned of the Rest API not working - Is that an issue with Nginx or Wordpress?

**Comment by Tricky-Ricky** [comment]
That still didn't allow me to upload - Same errors minus the SSL Handshake - Here are the error logs:
[Logs](https://hastebin.com/aravenejih.m)

**Comment by VBart** [comment]
This `if` condition in your `wp-config.php` looks wrong:
```
if ( true !== strpos( $_SERVER['HTTP_X_FORWARDED_PROTO'], 'https')){
        $_SERVER['HTTPS']='on';
}
```
try to use just:
```
$_SERVER['HTTPS']='on';
```

**Comment by VBart** [comment]
Or you have to pass the `X-Forwarded-Proto` header from nginx:
```
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by Tricky-Ricky** [comment]
If I don't use that `if` statement - The site goes into an endless loop with 
> ERR_TOO_MANY_REDIRECTS

But yes you are correct - From Server Fault and various other places they state to use `false` - again if I use false, I end up in a constant loop, so set it to true, and the site displays and "Works" - But just to be clear, with or without that statement I still get.
> REST API ERROR 
and 
> CURL Error 28 (Failed: 32 Broken Pipe)

This is from following the guides linked above, and the one you provided on a default installation of the latest wordpress.

Would I put this: `proxy_set_header X-Forwarded-Proto $scheme;` in with the nginx.conf or server file?
I'm happy to try this

**Comment by VBart** [comment]
That error can be caused by some broken WordPress plugin. See: https://wordpress.org/support/topic/rest-api-error/

**Comment by VBart** [comment]
I think you can just ignore these `REST API ERROR` and `CURL Error 28` errors. It tries to health-check with an old version of SSL protocol, which isn't supported by your nginx configuration.

**Comment by Tricky-Ricky** [comment]
@VBart - It happens from a fresh installation with no plug-ins.
It's not supported by my configurations or nginx's configurations?

Not being able to use the REST API and with the cURL error I'm unable to fulfill loopback requests for scheduled events some plug-ins and possibly built in editors... So full functionality doesn't appear to work.

As a workaround - I can upload themes or plug-ins via SFTP and install them that way - I'll raise this as a bug with wordpress - Can the documents possibly get updated to reflect this? - I've spent the best part of a week trying to figure it out, If it's to do with an issue on wordpress side that's fine, Would save some people a lot of time wastage if they are aware before hand?

**Comment by VBart** [comment]
@Tricky-Ricky It's not clear whether the REST API isn't working or just the health-check plugin that shows the error.

The line from nginx log, you're mentioned above:
```SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking```
clearly states, that the client (I assume Wordpress health-check plugin) tries to connect using ancient insecure version of SSL protocol.

That is prohibited by your nginx configuration:
```ssl_protocols TLSv1 TLSv1.1 TLSv1.2;```

**Comment by VBart** [comment]
Could you also enable `access_log` in Unit in order to match the lines from various logs?
https://unit.nginx.org/configuration/#access-log

**Comment by Tricky-Ricky** [comment]
@VBart - After inputting the logs - I got this output:
```
ricky@Server:/var/log$ sudo curl -X PUT -d '"/var/log/access_log"' @/var/www/pagephoenix.co.uk/wordpress/wordpress.config --unix-socket /run/control.unit.sock 
http://localhost/config/access_log
{
        "error": "Value doesn't exist."
}
{
        "success": "Reconfiguration done."
}
```
However - I don't seem to be getting the SSL error now and I am able to upload files bigger than 8M -
Still get the Curl error though...

Heres the access logs from this morning:
[Logs](https://hastebin.com/girawevani.pl)

I suspect, after re-running the curl command above - It reconfigured the config - So the changes I made were not automated, 

If so, this was user error as I was unaware that we would have to re-run the config aswell as restarting Unit. If this is the case - Is there a chance in later updates to get this to automatically update like the server configs with nginx?

**Comment by VBart** [comment]
> Heres the access logs from this morning:
> Logs

These logs don't contain any error responses neither in Unit, nor in nginx. So, from the server point of view now everything seems fine.

> I suspect, after re-running the curl command above - It reconfigured the config - So the changes I made were not automated,
> 
> If so, this was user error as I was unaware that we would have to re-run the config aswell as restarting Unit. If this is the case - Is there a chance in later updates to get this to automatically update like the server configs with nginx?

You don't need to restart Unit to apply the configuration. This is one of the key advantages over nginx and other web-servers. It's reconfigured on the fly without restarting, but in order to inform Unit about the configuration change you need to send a command.

Unit doesn't care about config files you have on a disk. Unit is configured via HTTP RESTful API. That means all reconfigurations involve sending HTTP requests to control API socket.

Please read the documentation about configuration management: https://unit.nginx.org/configuration/#configuration-management

**Comment by mostafahussein** [comment]
@VBart why we don't have the ability to set `$_SERVER['HTTPS']='on';` this through `unit` itself ? or maybe make unit aware of it by default based on `X-FORWARDED-PROTO`. I know `unit` does not support server variables. but i read in an issue before that there are some server variables populated automatically like `SCRIPT_FILENAME` which appear when we use `script` in unit's config. so why not HTTPS based on `X-Forwarded-Proto` ?

**Comment by VBart** [comment]
@mostafahussein It's not that simple. We can't arbitrary populate variables from HTTP headers as it will create security flaw. All `X-Forwarded-*` headers should be processed only from trusted sources. Therefore we need a way to specify such trusted sources in the configuration. This feature and configuration for request environment variables are in our todo list

**Comment by mostafahussein** [comment]
@VBart, if we set a self-signed ssl certificate under unit, will this solve the issue (until we have an official support for this case) ? So we will have nginx with valid certificate for the browser and unit with self signed certificate. what do you think ?

**Comment by tippexs** [comment]
closed due to timeout
