### ISSUE TITLE
Failed to apply new configuration.

### ISSUE THREAD

**Issue by GerrSwin** [nginx/unit#283]
Clear install `apt install unit-php`

> Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  unit
The following NEW packages will be installed:
  unit unit-php
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 243 kB of archives.
After this operation, 904 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.nginx.org/unit/debian stretch/unit amd64 unit amd64 1.9.0-1\~stretch [208 kB]
Get:2 https://packages.nginx.org/unit/debian stretch/unit amd64 unit-php amd64 1.9.0-1\~stretch [34,9 kB]
Fetched 243 kB in 0s (445 kB/s)     
Selecting previously unselected package unit.
(Reading database ... 67738 files and directories currently installed.)
Preparing to unpack .../unit_1.9.0-1~stretch_amd64.deb ...

Use to check sample 
> /usr/share/doc/unit-php/examples # curl -X PUT --data-binary @unit.config --unix-socket /var/run/control.unit.sock http://localhost/config

But get 
> {
	"error": "Failed to apply new configuration."
}

In log file 
>2019/07/22 15:18:39 [info] 18077#18077 controller started
2019/07/22 15:18:39 [notice] 18075#18075 process 18076 exited with code 0
2019/07/22 15:18:39 [info] 18078#18078 router started
2019/07/22 15:18:39 [info] 18078#18078 OpenSSL 1.1.1c  28 May 2019, 1010103f
2019/07/22 15:19:10 [info] 18161#18161 "example_php" application started
2019/07/22 15:19:10 [info] 18161#18161 (non ABS_MODE) php root: "/usr/share/doc/unit-php/examples/phpinfo-app"
Mon Jul 22 15:19:10 2019 (18161): Fatal Error Unable to create lock file: Bad file descriptor (9)
2019/07/22 15:19:10 [notice] 18075#18075 process 18161 exited with code 254
2019/07/22 15:19:10 [warn] 18078#18078 failed to start application "example_php"
2019/07/22 15:19:10 [alert] 18078#18078 failed to apply new conf

And same with all php projects

**Comment by VBart** [comment]
Could you show `ls -ld /tmp`?

**Comment by Tricky-Ricky** [comment]
@GerrSwin - Run this command as sudo:
`curl -X PUT --data-binary @unit.config --unix-socket /var/run/control.unit.sock http://localhost/config`
So
`sudo curl -X PUT --data-binary @unit.config --unix-socket /var/run/control.unit.sock http://localhost/config`

I got the same error a couple of times - For some reason, the default install, installs as root and not as user

**Comment by Tricky-Ricky** [comment]
@GerrSwin - Run this command as sudo:
`curl -X PUT --data-binary @unit.config --unix-socket /var/run/control.unit.sock http://localhost/config`
So
`sudo curl -X PUT --data-binary @unit.config --unix-socket /var/run/control.unit.sock http://localhost/config`

I got the same error a couple of times - For some reason, the default install, installs as root and not as user

**Comment by GerrSwin** [comment]
`drwxr-xr-x 2 root root 69632 лип 23 06:39 /tmp`

**Comment by GerrSwin** [comment]
Hmmm after reboot all worked
