### ISSUE TITLE
My nginx is dying in every  min on ubuntu 18.04 server 

### ISSUE THREAD

**Issue by kshtzkr** [nginx/unit#285]
Journal file /var/log/journal/5df8abb3d4fb496d92ff8175ec81e95f/user-1000.journal is truncated, 

> ignoring file.
> -- Support: http://www.ubuntu.com/support
> -- 
> -- Unit nginx.service has failed.
> -- 
> -- The result is RESULT.
> Jul 25 06:20:29 staging.communityx.api-build-release.com sudo[19590]:     root : TTY=unknown ; PWD=/home/admin ; USER=root ; COMMAND=/usr/local/vesta/bin/v-list-sys-config json
> Jul 25 06:20:29 staging.communityx.api-build-release.com sudo[19590]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 25 06:20:29 staging.communityx.api-build-release.com sudo[19590]: pam_unix(sudo:session): session closed for user root
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
> -- Subject: Unit nginx.service has failed
> -- Defined-By: systemd
> -- Support: http://www.ubuntu.com/support
> -- 
> -- Unit nginx.service has failed.
> -- 
> -- The result is RESULT.
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
> Jul 25 06:20:30 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
> -- Subject: Unit nginx.service has failed
> -- Defined-By: systemd
> -- Support: http://www.ubuntu.com/support
> -- 
> -- Unit nginx.service has failed.
> -- 
> -- The result is RESULT.
> Jul 25 06:20:30 staging.communityx.api-build-release.com sudo[19767]:     root : TTY=unknown ; PWD=/home/admin ; USER=root ; COMMAND=/usr/local/vesta/bin/v-list-sys-config json
> Jul 25 06:20:30 staging.communityx.api-build-release.com sudo[19767]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 25 06:20:30 staging.communityx.api-build-release.com sudo[19767]: pam_unix(sudo:session): session closed for user root
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
> -- Subject: Unit nginx.service has failed
> -- Defined-By: systemd
> -- Support: http://www.ubuntu.com/support
> -- 
> -- Unit nginx.service has failed.
> -- 
> -- The result is RESULT.
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
> Jul 25 06:20:31 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
> -- Subject: Unit nginx.service has failed
> -- Defined-By: systemd
> -- Support: http://www.ubuntu.com/support
> -- 
> -- Unit nginx.service has failed.
> -- 
> -- The result is RESULT.
> Jul 25 06:20:31 staging.communityx.api-build-release.com sudo[19942]:     root : TTY=unknown ; PWD=/home/admin ; USER=root ; COMMAND=/usr/local/vesta/bin/v-list-sys-config json
> Jul 25 06:20:31 staging.communityx.api-build-release.com sudo[19942]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jul 25 06:20:31 staging.communityx.api-build-release.com sudo[19942]: pam_unix(sudo:session): session closed for user root
> Jul 25 06:20:31 staging.communityx.api-build-release.com sudo[15996]: pam_unix(sudo:session): session closed for user root
> Jul 25 06:20:31 staging.communityx.api-build-release.com CRON[15979]: pam_unix(cron:session): session closed for user admin
> Jul 25 06:20:34 staging.communityx.api-build-release.com sudo[19980]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/sbin/service nginx status
> Jul 25 06:20:34 staging.communityx.api-build-release.com sudo[19980]: pam_unix(sudo:session): session opened for user root by root(uid=0)
> Jul 25 06:20:34 staging.communityx.api-build-release.com sudo[19980]: pam_unix(sudo:session): session closed for user root
>

**Comment by kshtzkr** [comment]
this is what I am getting eveytime 

Jul 25 06:30:17 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
Jul 25 06:30:17 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
Jul 25 06:30:17 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
Jul 25 06:30:17 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: nginx.service: Start request repeated too quickly.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: nginx.service: Failed with result 'start-limit-hit'.
Jul 25 06:30:18 staging.communityx.api-build-release.com systemd[1]: Failed to start nginx - high performance web server.

**Comment by mar0x** [comment]
This is issue tracker for **Unit** web and application server. See https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
