### ISSUE TITLE
Best way to determine number of processes

### ISSUE THREAD

**Issue by joanhey** [nginx/unit#286]
I understand that if you have n applications you need to distribute the processes.

But if you have only one app in your server, how to determine the number of processes for best performance?
The information is not clear.

In Nginx we have:

- Worker_processes = number of cpus (or HTs) or a little more.
- Worker_connections = limiting for not use all the Ram,...

Could you explain a little better how to use or limit the processes in unit ?
Thank you

**Comment by VBart** [comment]
nginx has [definite async architecture](https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/) that as we know works best with one process per core. Similar architecture has Unit router process, so it runs one thread per core to handle requests (and this currently even can't be controlled).

But it's not the case with arbitrary applications that Unit can run. We can't make any assumptions about a 3-rd party application, as only developers of the application may know how it scales under various load. As most of such applications aren't async, the number of processes usually should be much bigger than CPU cores. There's no formula, you should test and tune settings depending on your particular workload and available resources. You can either configure certain number of processes or only set limits and Unit will dynamically scale application processes depending on current load. Please see the documentation for particular configuration options: https://unit.nginx.org/configuration/#process-management

**Comment by joanhey** [comment]
The initial benchmark is really good https://github.com/TechEmpower/FrameworkBenchmarks/pull/4956#issuecomment-519018850

Before tune the processes number.

**Comment by VBart** [comment]
@joanhey Thank you for testing and sharing the results.

**Comment by tippexs** [comment]
@joanhey we will chat about the new issue. Will close this one due to timeout.
