### ISSUE TITLE
Failed to apply new configuration - php.ini vars

### ISSUE THREAD

**Issue by Alexufo** [nginx/unit#292]
This code works as expected, but

	"listeners": {
		"192.168.1.13:8090": {
			"pass": "applications/wp_index"
		},
		"127.0.0.1:8092": {
			"pass": "applications/wp_index"
		}
	},
	"applications": {
		"wp_index": {
			"type": "php",
			"user": "alexufo",
			"group": "www-data",
			"root":  "/home/alexufo/public/",
			"script": "index.php",
			"options": {
				"file": "/etc/php/7.3/embed/php.ini",
				"admin": {
					
				},				
			}			
		}
	}

If i add any variable to admin section `"expose_php": "1"` , for example, I got

    "error": "Failed to apply new configuration."

ubuntu 16

**Comment by VBart** [comment]
@Alexufo What's in the unit.log?

**Comment by Alexufo** [comment]
2019/08/22 02:08:42 [info] 5717#5717 "wp_index" application started
2019/08/22 02:08:42 [info] 5717#5717 (ABS_MODE) php script "/index.php" root: "/home/alexufo/public"
2019/08/22 02:08:42 [notice] 5717#5717 php message: PHP Warning:  PHP Startup: Unable to load dynamic library 'phpdEngine.so' (tried: /usr/lib/php/20180731/phpdEngine.so (/usr/lib/php/20180731/phpdEngine.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/phpdEngine.so (/usr/lib/php/20180731/phpdEngine.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
2019/08/22 02:08:42 [alert] 5707#5707 process 5717 exited on signal 11 (core dumped)
2019/08/22 02:08:42 [warn] 5710#5710 failed to start application "wp_index"
2019/08/22 02:08:42 [alert] 5710#5710 failed to apply new conf

**Comment by VBart** [comment]
I've just tried your config with php 7.3 and have no problems.
How did you install php and Unit and its php module on your system?

**Comment by Alexufo** [comment]
Yes. I install php from ppa:ondrej/php

**Comment by VBart** [comment]
Unfortunately PHP library uses the same shared object name for any 7.x version. We can try to add some additional checks here, but that must be fixed on the PHP side.

**Comment by Alexufo** [comment]
ubintu 16 with php 7.0 from ubuntu repo with error
` "detail": "The module to run \"php\" is not found among the available application modules."`
Is it problem with old 7.0 version?

**Comment by tippexs** [comment]
closed due to timeout.
