### ISSUE TITLE
JSC module not working on Amazon linux

### ISSUE THREAD

**Issue by incube8r** [nginx/unit#293]
```
$ sudo yum install unit-jsc8
Loaded plugins: priorities, update-motd, upgrade-helperPackage unit-jsc8-1.9.0-1.amzn1.ngx.x86_64 already installed and latest versionNothing to do
```

Then do

```
$ curl -X PUT -d@start.json '127.0.0.1:8443/config/'
{"error": "Invalid configuration.","detail": "The module to run \"java 8\" is not found among the available application modules."}
```

**Comment by incube8r** [comment]
@VBart yes I have tried both,

```
$ curl -X PUT -d@start.json '127.0.0.1:8443/config/'

{"error": "Invalid configuration.","detail": "The module to run \"java 1.8\" is not found among the available application modules."}
```

**Comment by defanator** [comment]
@incube8r what exact version of Amazon Linux are you using?

**Comment by defanator** [comment]
@incube8r I've just tested the entire process on the following system:

```
-bash-4.2$ cat /etc/os-release 
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

Everything works just fine. Proper application type for Java 8 at `amzn1` is `java 1.8.0`, see the following example: https://github.com/nginx/unit/blob/master/pkg/rpm/rpmbuild/SOURCES/unit.example-jsc8-config

**Comment by defanator** [comment]
We were able to find at least one possible case when the described behavior may be observed. It was fixed here: https://github.com/nginx/unit/commit/6f1f3b48b2af56c96825dbcd149771ace67404ee

I'm closing this issue for now.
