### ISSUE TITLE
go module support

### ISSUE THREAD

**Issue by martinr92** [nginx/unit#294]
Currently go applications using the new module support (introduced in golang 1.11 last year) can't compile with nginx unit.

How to reproduce:
Create a new go application using the following code
```golang
package main

import (
	"net/http"
	"nginx/unit"
)

func main() {
	http.HandleFunc("/", handler)
	unit.ListenAndServe(":8080", nil)
}

func handler(response http.ResponseWriter, request *http.Request) {
	response.Write([]byte("Hey!"))
}
```
This code will compile and run as usual.

Now I enable the go module handling
```
go mod init gitlab.com/my/repo
```
and compile the application again with
```
go build .
build gitlab.com/my/repo: cannot load nginx/unit: cannot find module providing package nginx/unit
```

It seems that all modules (dependencies, including nginx/unit) are now fetched directly from the server. The local $GOPATH/src is completely ignored.
Also golang 1.13 has go modules enabled by default, then you would need to disable them manually using a environment variable.

Is there already a known workaround to use go modules with nginx unit?
When will be go-modules supported?

**Comment by mar0x** [comment]
Go module name changed to 'unit.nginx.org/go' in 693a458b4ea87b7b387bd9d094de2b42be7ecdbd commit and it can be used as a module. Please note, you need to have **unit-dev** package (with libunit.a and header files) installed.
