### ISSUE TITLE
"Generic" language support

### ISSUE THREAD

**Issue by rwhaling** [nginx/unit#30]
There are many languages now, much like Golang, that compile down to native binaries and feature robust C interop -- Rust, D, Scala Native, and quite a few others could probably re-use most of the same code as nxt_go uses currently.  Is there any plan to support this kind of functionality?

**Comment by VBart** [comment]
Yes. There are such plans.

**Comment by wxd237** [comment]
C language should be support ?

**Comment by artemkonev** [comment]
In addition, please see the outline here: https://www.nginx.com/blog/nginx-unit-adds-assembly-language-support/
