### ISSUE TITLE
Help understand what can be way for fix issue when we have high requests per second

### ISSUE THREAD

**Issue by KursLabIgor** [nginx/unit#304]
I have installed nginx unit on AWS ECS FARGATE cluster type
I dont have access to root file system for increase kernel settings for increase socket connection. 
During simple load testing I see that application crash some where after 650 req/m. How i can increase connection limit. CPU is not under high load during simple tests. 
set up nginx as reverse proxy or ? 
thanks

**Comment by VBart** [comment]
What's in the logs when the application crashes?

**Comment by KursLabIgor** [comment]
[alert] 104#109 *1070 socket close(-1) failed (9: Bad file descriptor)
info] 11#16 *464 shutdown(59, 2) failed (107: Socket not connected)

**Comment by VBart** [comment]
> [alert] 104#109 *1070 socket close(-1) failed (9: Bad file descriptor)
> info] 11#16 *464 shutdown(59, 2) failed (107: Socket not connected)

That doesn't look like a problem. How do you determine that application crashes?

**Comment by KursLabIgor** [comment]
@VBart I apologize maybe I was wrong. Yesterday tried make another load testing and didn't see such problem. Why I decided that service crash because we started get 500 errors and loadbalancer replace task due unhealthy threshold.  Let me double check it again. I'll update ticket once i have results. 
keep this ticket open until now.
Thanks.

**Comment by KursLabIgor** [comment]
dont have updates yet. closing issue in case if I find problem again.
