### ISSUE TITLE
Web socket Load Balancing to specific upstream server

### ISSUE THREAD

**Issue by madabhaviamit** [nginx/unit#305]
Dear Team,

Apologies for raising this as an issue.

I am well aware of the present load balancing methods that are there in nginx. I have a certain requirement which is not catered with the methods already present.

I have a client who wants to make a websocket connection to the nodejs server via nginx server.
I have 10 nodejs servers running behind nginx server and all the private ips of these servers are mentioned in the upstream load balancing conf of nginx.

I want a custom load balancer in nginx, which will forward the request of this websocket connection to a specific upstream server say server 4 and when a client makes a socket request to the nginx, the request will also have the server ip of server 4 with which nginx needs to determine on backend server 4 it needs to forward the socket connection. 

Please suggest me something, with which i can achieve this..

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
