### ISSUE TITLE
Controlling response headers

### ISSUE THREAD

**Issue by lubo** [nginx/unit#313]
Hi. It looks like Unit can't set custom response headers. Setting custom headers, for example, would be extra useful when serving static files. Often, one would like to set `Cache-Control: public, max-age=31536000` when file exists or `Cache-Control: no-cache` when it doesn't. Furthermore, one might want to set `X-Content-Type-Options: nosniff` for both application responses and static files.

**Comment by misaon** [comment]
+1 
In my company we like to use Nginx unit but we desperately need a cache for static files at the moment.

**Comment by Mikopet** [comment]
This is crucial in our case too.
Any news here?

**Comment by baksdev** [comment]
I join, very important for static files

**Comment by glukkkk** [comment]
Need this feature as well

**Comment by hongzhidao** [comment]
committed in https://github.com/nginx/unit/commit/a28bef097cd63da3bbb375ef0283e65be41a88ff
