### ISSUE TITLE
failed to create process pipe for passing rpid

### ISSUE THREAD

**Issue by 532910** [nginx/unit#322]
There are two hosts:  the `hostA` runs nginx with ssl that proxies to the `hostB` that runs unit (1.11.0-2~buster) with php.

After unit restart all works fine, but some time later unit starts report `failed to create process pipe for passing rpid` into `/var/log/unit.log` for each request. The number of `CLOSE_WAIT` sockets grows, and when open file limit reached it starts report `accept4(11) failed (24: Too many open files), new connections are not accepted within 1s`.

The only was is to restart unit, but due to #321 I can only reboot the `hostB`.

<details>
<summary>

```
# curl --unix-socket /var/run/control.unit.sock http://localhost:8000/config
```
</summary>

```
{
	"listeners": {
		"*:80": {
			"pass": "routes"
		}
	},

	"routes": [
		{
			"match": {
				"uri": [
					"*.css",
					"*.html",
					"*.ico",
					"*.jpg",
					"*.js",
					"*.pdf",
					"*.svg",
					"*.tiff",
					"*.woff",
					"*.woff2",
					"*.webp",
					"*.mp3",
					"*.wav",
					"*.ttf",
					"*.gif",
					"*.png"
				]
			},

			"action": {
				"share": "/srv/www/roundcubemail"
			}
		},
		{
			"match": {
				"uri": [
					"*.php",
					"*/"
				]
			},

			"action": {
				"pass": "applications/roundcube"
			}
		}
	],

	"applications": {
		"roundcube": {
			"processes": {},
			"type": "php",
			"user": "www-data",
			"root": "/srv/www/roundcubemail",
			"script": "index.php",
			"index": "index.php"
		}
	}
}
```
</details>

**Comment by VBart** [comment]
Could you try to set constant number of processes: `"processes": 1` instead of `{}`?

**Comment by 532910** [comment]
It is one of several reconfigurations I've done before unit works fine, so sure it will work fine with `"processes": 1`.

I set `processes` to `1`, I'll confirm the result one day later.

**Comment by 532910** [comment]
Looks like it works fine with `"processes": 1`.

**Comment by VBart** [comment]
The patch below should fix the issue with descriptors leak on process creation:
```diff -r bb6242d1dc5f src/nxt_process.c
--- a/src/nxt_process.c Wed Sep 25 17:33:02 2019 +0300
+++ b/src/nxt_process.c Wed Sep 25 17:36:04 2019 +0300
@@ -230,6 +230,10 @@ nxt_process_create(nxt_task_t *task, nxt
         goto fail_cleanup;
     }
 
+    if (nxt_slow_path(close(pipefd[1]) != 0)) {
+        nxt_alert(task, "failed to close pipe: %E", nxt_errno);
+    }
+
     process->pid = pid;
 
     nxt_runtime_process_add(task, process);
```

**Comment by 532910** [comment]
Should I test it or it will be applied in the next release?

**Comment by VBart** [comment]
@532910 It will be applied before the next release, but if you can test and confirm that it fixes the issue, then we will be sure that there are no other leaks in your case.

**Comment by 532910** [comment]
OK. I installed patched unit on my three hosts and switched `processes` to `{}` for all of them.

**Comment by mightydes** [comment]
@VBart 
Hello! When is a rpm release planned with this fix?

**Comment by VBart** [comment]
@mightydes Hello. It's planned on 3rd of October.

**Comment by mightydes** [comment]
@VBart Thanks!

**Comment by 532910** [comment]
Still works fine with the patch above.

**Comment by VBart** [comment]
Thank you for testing.
