### ISSUE TITLE
configuration by official doc,why unknown parameter

### ISSUE THREAD

**Issue by lawsong** [nginx/unit#326]
config.json :
`
{
    "listeners": {
        "*:8080": {
            "pass": "applications/flask_app"
        }
    },
    "applications": {
        "flask_app": {
            "type": "python 3",
            "path": "/home/flask/flask_app/",
            "home": "/home/flask/venv/",
            "module": "wsgi"
        }
    }
}
`

when i put,result:

`
{
"error": "Invalid configuration.",
"detail": "Unknown parameter \"pass\"."
}
`

waiting for reply. thanks!

**Comment by VBart** [comment]
What version of Unit do you use?

**Comment by lawsong** [comment]
laster version on Manjaro,build archlinux mode

**Comment by VBart** [comment]
Could you clarify please, which version is currently the latest on Manjaro? As we don't provide packages for Manjaro, I can only guess.

**Comment by lawsong** [comment]
Arch Linux§
To install Unit using the Arch User Repository (AUR):

`
# pacman -S git
$ git clone https://aur.archlinux.org/nginx-unit.git
$ cd nginx-unit
`

**Comment by lawsong** [comment]
OK,When I built it on debian, it worked.
I think maybe it's the community version of archlinux BUG.
thanks！

**Comment by VBart** [comment]
> https://aur.archlinux.org/nginx-unit.git

This package contains version 1.7.1, which is too old. There was no "pass" option in that version.

**Comment by lawsong** [comment]
ok,i got,thanks!
