### ISSUE TITLE
Question about use of nginx unit

### ISSUE THREAD

**Issue by Andreyooo** [nginx/unit#329]
I´ve built a Rest API with express and http/https Server.
Is it useful to integrate nginx unit here?

**Comment by VBart** [comment]
Yes, see the relevant HowTo: https://unit.nginx.org/howto/express/

**Comment by Andreyooo** [comment]
I use only one language and dynamic configuration is not important to me. SSL/TLS is allready integrated.
What use would ngynx unit have in this case?

**Comment by tiago4orion** [comment]
If not using Unit, what is going to be your approach for supervising the server? Is there plenty of other things that Unit can help, but sure it depends on your app. Tell us about your deploy plan.
