### ISSUE TITLE
Problem with building from source with Python 3.8

### ISSUE THREAD

**Issue by tonyafanasyev** [nginx/unit#331]
Hi,

I'm trying compiling Unit's (v. 1.12) cource code with Python (3.8) language module, but had an error at module configuration step:

`./configure python --config=python3.8-config` 

gets

configuring Python module
checking for Python ... not found
./configure: error: no Python found.

My machine is Ubuntu 18.04.3 (x64), kernel 4.15.0-58-generic

**The command**

`tail -100 build/autoconf.err`

gets

configuring Python module ...
/usr/local
checking for Python
/tmp/ccZ1SCGE.o: In function `main':
/root/unit/build/autotest.c:5: undefined reference to `Py_Initialize'
collect2: error: ld returned 1 exit status

        #include <Python.h>

        int main() {
            Py_Initialize();
            return 0;
        }
cc -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes -Werror -g -I/usr/local/include/python3.8 -I/usr/local/include/python3.8 -o build/autotest build/autotest.c -L/usr/local/lib -lcrypt -lpthread -ldl -lutil -lm -lm

**The command**

`python3.8-config --includes`

gets

-I/usr/local/include/python3.8 -I/usr/local/include/python3.8

**The command**

`python3.8-config --libs`

gets

-lcrypt -lpthread -ldl  -lutil -lm -lm

**Full steps to reproduce error:**
1. Clean virtual machine (DigitalOcean) with Ubuntu 18.04.3 (x64)
2. apt-get update
3. apt-get upgrade
4. apt-get install libsqlite3-dev zlib1g-dev libssl-dev gcc make libffi-dev libbz2-dev
5. wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
6. tar -xzf Python-3.8.0.tgz
7. In Python directory execute ./configure --enable-shared --enable-loadable-sqlite-extensions
8. make && make install
8b. ldconfig
9. git clone https://github.com/nginx/unit
10. In Unit directory execute ./configure
11. **./configure python --config=python3.8-config**

Exactly the same steps give no errors with Python 3.7.4.

Any ideas what can be wrong?

**Comment by mar0x** [comment]
Hello,

Your `python3.8-config --libs` returns incomplete list of libraries. It should include `libpython`, but it don't.

I will try to reproduce the issue and let you know if I find something.

**Comment by mar0x** [comment]
According to [What’s New In Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html) :
> To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.

I would suggest you to modify configure module command like this:

`./configure python --config="python3.8-config --embed"`

**Comment by tonyafanasyev** [comment]
> 
> 
> Hello,
> 
> Your `python3.8-config --libs` returns incomplete list of libraries. It should include `libpython`, but it don't.
> 
> I will try to reproduce the issue and let you know if I find something.

Thank you for your participation!

You are absoultely right about output of python3.8-config command. As seen below python3.8-config doesn't return lpython3.8:

`python3.7-config --libs`
-lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm

`python3.8-config --libs`
 -lcrypt -lpthread -ldl  -lutil -lm -lm

**Comment by tonyafanasyev** [comment]
> 
> 
> According to [What’s New In Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html) :
> 
> > To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.
> 
> I would suggest you to modify configure module command like this:
> 
> `./configure python --config="python3.8-config --embed"`

Thank you! It works.

`./configure python --config="python3.8-config --embed"`

**Comment by tiago4orion** [comment]
@tonyafanasyev Could you confirm if Unit compiles the libpython.so module for python3.8? Just asking because last time I tried (before the 3.8 release, using development version), I had other problems. I managed to build it but only by patching Unit.

**Comment by tonyafanasyev** [comment]
> 
> 
> @tonyafanasyev Could you confirm if Unit compiles the `python.unit.so` module for python3.8? Just asking because last time I tried (before the 3.8 release, using development version), I had other problems. I managed to build it but only by patching Unit.

Unfortunately I had a problem with compiling a python 3.8 module. At compile time the make command gives the following error message:

-o build/src/nxt_python_wsgi-python3.8.o src/nxt_python_wsgi.c
src/nxt_python_wsgi.c:182:1: error: missing initializer for field ‘tp_vectorcal                  ’ of ‘PyTypeObject {aka struct _typeobject}’ [-Werror=missing-field-initializer                  ]
 };
 ^
In file included from /usr/local/include/python3.8/object.h:746:0,
                 from /usr/local/include/python3.8/pytime.h:6,
                 from /usr/local/include/python3.8/Python.h:85,
                 from src/nxt_python_wsgi.c:9:
/usr/local/include/python3.8/cpython/object.h:257:20: note: ‘tp_vectorcall’ decl                 ared here
     vectorcallfunc tp_vectorcall;
                    ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
build/Makefile:1620: recipe for target 'build/src/nxt_python_wsgi-python3.8.o' f                 ailed
make: *** [build/src/nxt_python_wsgi-python3.8.o] Error 1

**Comment by tonyafanasyev** [comment]
One possible solution to the problem i'd described earlier is to modify the file nxt_python_wsgi.c by adding this code to the definition of _static PyTypeObject nxt_py_input_type_ (after tp_finalize): 

```
#if PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION > 7
    0,                                  /* tp_vectorcall */
    0,					/* tp_print */
#endif
```

This is necessary due to recent changes in the Python 3.8 source code (see PEP 590).
Also this page (https://docs.python.org/3.8/whatsnew/3.8.html) states:

> The interpreter does not pretend to support binary compatibility of extension types across feature releases, anymore. A PyTypeObject exported by a third-party extension module is supposed to have all the slots expected in the current Python version, including tp_finalize (Py_TPFLAGS_HAVE_FINALIZE is not checked anymore before reading tp_finalize).

**Comment by tiago4orion** [comment]
Hi @tonyafanasyev 

Yes, that's exactly what I did. But I'm not sure this is the right value for these fields. @mar0x ?

**Comment by mar0x** [comment]
Since I was unable to found usages of `tp_vectorcall` nor `tp_print` in Python 3.8 sources, I think it is Ok to have `0` for both.
