### ISSUE TITLE
Fixed nxt_runtime_close_idle_connections().

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#334]
Hi. 

It seems this is an issue since nxt_queue_head(idle) is the same as nxt_queue_tail(idle).

```
diff --git a/src/nxt_runtime.c b/src/nxt_runtime.c
--- a/src/nxt_runtime.c
+++ b/src/nxt_runtime.c
@@ -459,7 +459,7 @@ nxt_runtime_close_idle_connections(nxt_e

     idle = &engine->idle_connections;

-    for (link = nxt_queue_head(idle);
+    for (link = nxt_queue_first(idle);
          link != nxt_queue_tail(idle);
          link = next)
     {
```

BTW, is it better to use nxt_queue_each() and nxt_queue_loop() in such loops?

**Comment by mar0x** [comment]
Hello,
Nice finding! Thanks you!

**Comment by hongzhidao** [comment]
@mar0x 

There are two points I can't understand.
1. Just about unix program.
If we kill a process like controller or router process, and there are opening connections.
Do we need to close these opening connections? I don't is it OK that just do exit() with the process?
2. Why ignore sockets that are read ready? See (i)
```
    for (link = nxt_queue_head(idle);
         link != nxt_queue_tail(idle);
         link = next)
    {
        next = nxt_queue_next(link);
        c = nxt_queue_link_data(link, nxt_conn_t, link);

        if (!c->socket.read_ready) {  // **i**
            nxt_queue_remove(link);
            nxt_conn_close(engine, c);
        }
    }
```
If there are opening connections and they are read ready, don't they need to be close?

I was thinking that if UNIT supports proxing, and I think connection pool will be introduced.
How these connections will be processed while the process is killed?
Can you share your experience?

**Comment by mar0x** [comment]
1. All connections will be closed (aborted) by OS. Client will get RST. 'Graceful shutdown' is not implemented in Unit yet, now it just exits.
2. Second question is better to address to @igorsysoev as a Senior Architect and author of this code :)
