### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#338]
How could I look at detailes when UNIT say "error": "Failed to apply new configuration"?

**Comment by VBart** [comment]
You can check the `unit.log` for details.

**Comment by pilot87** [comment]
Thank you, log is nice

**Comment by fchenGT** [comment]
What do we do if we get:

$ unitd --log /var/log/unit.log
2023/09/28 20:30:21 [warn] 5924#5924 Unit is running unprivileged, then it cannot use arbitrary user and group.
2023/09/28 20:30:21 [alert] 5924#5924 bind(6, unix:/var/run/control.unit.sock.tmp) failed (13: Permission denied)

**Comment by lcrilly** [comment]
@fchenGT this is unrelated to the original (and closed) issue. It would be better as a new issue, or a question in the [community Slack](https://community.nginx.org/joinslack).

The first line means the user starting `unitd` is not root (unprivileged) and so cannot user the `user` and `group` configuration settings for applications to run their processes as a specific user/group/

The second line means the user starting `unitd` does not have permissions over the default control socket. You can solve this in one of three ways:

1. Start unit as a privileged user, e.g. `sudo unitd --log /var/log/unit.log`
2. Use a control socket file you have permission for, e.g. `unitd --log /var/log/unit.log --control unix:$HOME/control.unit.sock`
3. Use a (high) TCP port for the control socket, e.g. `unitd --log /var/log/unit.log --control 0.0.0.0:8080`
