### ISSUE TITLE
Can't ./configure with Python 3.8 module

### ISSUE THREAD

**Issue by samthesuperhero** [nginx/unit#341]
[http://unit.nginx.org/installation/#configuring-modules](http://unit.nginx.org/installation/#configuring-modules)

`./configure python --config=/usr/local/bin/python3.8-config --lib-path=/usr/local/lib`

The result:
`[pfn@ya2 unit-1.9.0]$ sudo ./configure python --config=/usr/local/bin/python3.8-config --lib-path=/usr/local/lib`
`configuring Python module`
`checking for Python ... not found`
`./configure: error: no Python found.`

**BUT**: there **is** python3.8-config at the path **/usr/local/bin/**:
`[pfn@ya2 unit-1.9.0]$ /usr/local/bin/python3.8-config --help`
`Usage: /usr/local/bin/python3.8-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed`

and libraries are at **/usr/local/lib/**

Can you please help.

**Comment by mar0x** [comment]
Hello,

There was a similar #331 issue. Make sure you are using latest sources from repo or manually apply patches e54f5f3 and ad518ae .

Please share your `build/autoconf.err` it should contain compiler/linker error messages.

What is the purpose to run configure with `sudo`?

**Comment by samthesuperhero** [comment]
OK, I'll try and reply here!

> What is the purpose to run configure with sudo?
- I started w/o sudo, was the same result, - thought maybe ./configure can not access something... who knows; main configuration done successfully w/o sudo from the 1st attempt

**Comment by samthesuperhero** [comment]
Hi, this worked for me fine, [e54f5f3](https://github.com/nginx/unit/commit/e54f5f3dc8ec281bbc17e4092d168ea32ae099d7) - thank you!
