### ISSUE TITLE
Python unexpected behavior

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#345]
I use my own Python application and when I try to repair unicode input like this 
```python
b'message=+%D0%B1%D0%B5%D0%B7+%D1%8D%D1%82%D0%BE%D0%B9%2B' 
```
via
```python
request_body = re.sub(b'\+', b' ', request_body)
request_body = re.sub(r'%', r'\\x', request_body.decode('utf-8'))
command = "request_body = b'" + request_body + "'"
exec(command)
```
request_body is still have string class so I could not decode('utf-8') one:
```python
return(str(request_body.__class__).encode('utf-8'))
```
and I have<class 'str'> in my browser.
But when I run this code in the same Python interpreter by console script:
```python
request_body = 'message=+%D0%B1%D0%B5%D0%B7+%D1%8D%D1%82%D0%BE%D0%B9%2B'
request_body = re.sub(b'\+', b' ', request_body)
request_body = re.sub(r'%', r'\\x', request_body.decode('utf-8'))
command = "request_body = b'" + request_body + "'"
exec(command)
print(request_body.__class__)
```
I have <class 'bytes'> in console output  so I could make 
```python
s = re.sub(r'message=', r'', request_body.decode('utf-8'))
print(s)
```
and get " без этой+" string.

I use Python3.5: 
```console
admin@ip-172-26-3-162:~$ apt-cache show python3.5
Package: python3.5
Version: 3.5.3-1+deb9u1
Installed-Size: 319
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Depends: python3.5-minimal (= 3.5.3-1+deb9u1), libpython3.5-stdlib (= 3.5.3-1+deb9u1), \
mime-support
Suggests: python3.5-venv, python3.5-doc, binutils
Description-en: Interactive high-level object-oriented language (version 3.5)
 Python is a high-level, interactive, object-oriented language. Its 3.5 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
Description-md5: 60fa91d6230cd3da883a5ad1ad625632
Multi-Arch: allowed
Section: python
Priority: optional
Filename: pool/main/p/python3.5/python3.5_3.5.3-1+deb9u1_amd64.deb
Size: 228778
MD5sum: 570fba1adf0729a2f3ec58fd41662d4b
SHA256: 4cd0fbbc04529e055c7b403ff31c327955312c8b5f9227a3634facd1d2717541
```
even if I use request_body = 'message=+%D0%B1%D0%B5%D0%B7+%D1%8D%D1%82%D0%BE%D0%B9%2B' in my UNIT app result is the same.
May be it is UNIT or WSGI feature but I have 2 different behavior on the same code:
```python
request_body = b'message=+%D0%B1%D0%B5%D0%B7+%D1%8D%D1%82%D0%BE%D0%B9%2B'
request_body = re.sub(b'\+', b' ', request_body)
request_body = re.sub(r'%', r'\\x', request_body.decode('utf-8'))
command = "request_body = b'" + request_body + "'"
exec(command)
```
It is strange situation with Python but could you make me some suggests how to fix this?

I have no problem without using frameworks and micro frameworks excluding multi language input (output is OK)

**Comment by pilot87** [comment]
In case `request_body = b'\xD0\xB1'` it is <class 'bytes'> in both case so it is `exec()` issue

**Comment by mar0x** [comment]
Hello,

It seems you have a "traditional" Python 2/3 "utf8 vs bytes" issue. To understand what is wrong I would suggest to use same Python version for console tool and web server; control the type of the `request_body` on every step and read carefully [Unicode HOW TO](https://docs.python.org/3.5/howto/unicode.html).

As I understand, you need to decode URL-encoded string and use `exec()` to do this is not a best approach. Consider using [urllib.parse](https://docs.python.org/3.5/library/urllib.parse.html):

```python
import urllib.parse
request_body = 'message=+%D0%B1%D0%B5%D0%B7+%D1%8D%D1%82%D0%BE%D0%B9%2B'
print(urllib.parse.unquote_plus(request_body))
```

...  or find another robust method in Google.
