### ISSUE TITLE
Nginx as reverse proxy for https

### ISSUE THREAD

**Issue by dhineshbabuelango** [nginx/unit#347]
Hi All, we are trying to use nginx as reverse proxy to redirect traffic to AWS s3 bucket, we have installed a self signed certificate and used for accessing nginx using https.

This is how our conf file looks like.

server {

    listen 443;
    server_name 13.77.234.93;

    ssl_certificate           /etc/nginx/cert.crt;
    ssl_certificate_key       /etc/nginx/cert.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/jenkins.access.log;
    location /skservice {
        proxy_pass https://XXXXXXXXXXXX.s3-ap-southeast-1.amazonaws.com/skservice/test.html;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

  }

when we try to access nginxhost/skservice, it is showing bucket not found but when we try to directly access the url mentioned in the proxy pass it is working. Are we missing something here.

Error

<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>skservice</BucketName>
<RequestId>4E4EFDF468D8BE17</RequestId>
<HostId>
ZenRQO03tDo0jlIrvjcJOzWOB6GmljrB71xSbutUxdjcnaPsPaQ4utGIRxwnUB10QXVjsavt4=
</HostId>
</Error>

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
