### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#352]
I am trying to use SSL
```
> cat kernelexplorer.site.crt kernelexplorer_site_key.txt > boundle.pem
>  ls -l
total 35012
-rw-r--r--  1 admin admin     3878 Dec  2 12:25 boundle.pem
```
but when I try to load one:
```
> curl -X PUT --data-binary @bundle.pem 'http://localhost:8080/certificates/<bundle>'
Warning: Couldn't read data from file "bundle.pem", this makes an empty POST.
{
        "error": "Invalid certificate."
}
```
I try different combination of .crt .ca-boundle and key files, but result is the same, what I am doing wrong?

**Comment by VBart** [comment]
Note that your fila name is `bOUndle.pem`, while you're trying to upload `bUndle.pem`.

**Comment by pilot87** [comment]
Thank you, it is my fault.
But what cert.pem ca.pem files means in command of guide:
```
$ cat cert.pem ca.pem key.pem > bundle.pem
```
Cause I have different file names from ssls.com: 
```
admin@ip-172-26-3-162:~$ ls kernelexplorer.site/
kernelexplorer.site.ca-bundle  kernelexplorer.site.crt  kernelexplorer.site.p7b
```
I mean - what cert.pem ca.pem files should contain? So then I could ask ssls.com support.

**Comment by pilot87** [comment]
Error was happens cause empty line in the end of key file

**Comment by VBart** [comment]
`cert.pem` means your certificate in PEM format.
`key.pem` means your private key in PEM format.
`ca.pem` means CA (Certificate Autority) in PEM format of your issuer.
See: https://en.wikipedia.org/wiki/Certificate_authority

**Comment by pilot87** [comment]
Thank you for your help
