### ISSUE TITLE
HTTPS redirection

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#353]
Could I redirect http requests to https page version?

**Comment by pilot87** [comment]
I've made redirection using my application (code 308), but could I do one by UNIT?

**Comment by tiago4orion** [comment]
Unit doesn't support this kind of redirect yet. The way you did is how people commonly do.

Example: 

Config: https://github.com/madlambda/madlambda.io/blob/master/unit/config.json#L3
App (Using 301): https://github.com/madlambda/madlambda.io/blob/master/apps/redirect-to-https/wsgi.py

**Comment by jelen07** [comment]
Any plan to implement something like @pilot87 mentioned? Or non-www to www etc.
