### ISSUE TITLE
Re-building Unit from source with changing ./config settings

### ISSUE THREAD

**Issue by samthesuperhero** [nginx/unit#355]
Dear support,

is there anything that I should know to safely **re-build** the Unit?

**I have to change the ./config settings, AND:**
- keep applications and listeners,
- have the trouble-free launch after rebuilding related downtime.

Which should be my proper actions to do that?

Thank you much!!

Initially built as:
```
./configure --prefix=/usr/local/ --control=127.0.0.1:38080 --no-ipv6 --no-unix-sockets --debug --user=uunit --group=gunit

Unit configuration summary:

  bin directory: ............. "/usr/local/bin"
  sbin directory: ............ "/usr/local/sbin"
  lib directory: ............. "/usr/local/lib"
  include directory: ......... "/usr/local/include"
  modules directory: ......... "/usr/local/modules"
  state directory: ........... "/usr/local/state"

  pid file: .................. "/usr/local/unit.pid"
  log file: .................. "/usr/local/unit.log"

  control API socket: ........ "127.0.0.1:38080"

  non-privileged user: ....... "uunit"
  non-privileged group: ...... "gunit"

  IPv6 support: .............. NO
  Unix domain sockets support: NO
  TLS support: ............... NO

  debug logging: ............. YES
```
and,
```
./configure python --config=/usr/local/bin/python3.8-config --lib-path=/usr/local/lib
configuring Python module
checking for Python ... found
checking for Python version ... 3.8.0
 + Python module: python3.8.unit.so
```

**Comment by VBart** [comment]
Could you elaborate more on what do you mean by "_keep applications and listeners_" and "_rebuilding related downtime_"?

As long as you run Unit pointing to the same `state` directory, it will use the previous configuration. But you need to make sure that the configuration is still valid for the new build (i.e. all the modules and features are available).

**Comment by samthesuperhero** [comment]
Sure,
"_keep applications and listeners_" - keep the configuration of applications and listeners after re-building, so that not needed to reconfigure; but to be honest this is minor one
"_rebuilding related downtime_" - this is more important, I mean that after I stop the Unit, then rebuild, and then launch again - is there something I have to pay attention to, during the building it again after new ./config, to have no troubles _after_ ?

> As long as you run Unit pointing to the same state directory

you mean that I can keep `bin`, `sbin`, `lib`, `include`, `modules` directories the same, (build the new configuration with same directories) but I will need to point different `state` directory?

> But you need to make sure that the configuration is still valid for the new build

can you please clarify this ? Haven't got it.

**+ question: should I somehow remove or uninstall the current installation before building new configuration ?**

**Comment by VBart** [comment]
> "rebuilding related downtime" - this is more important, I mean that after I stop the Unit, then rebuild, and then launch again - is there something I have to pay attention to, during the building it again after new ./config, to have no troubles after ?

First of all, you don't need to stop Unit before rebuilding. You can rebuild it first, and when the building process is finished, just stop the old one and run a new one.

> you mean that I can keep bin, sbin, lib, include, modules directories the same, (build the new configuration with same directories) but I will need to point different state directory?

The only directory that keeps Unit state is the `state` directory. Everything else is irrelevant. As long as you start Unit with the same `state` directory it will load the same configuration stored in that directory. If you start Unit with a new `state` directory, then its configuration will be cleared (like when you've started Unit the first time). You can copy or move `state` directory, it just holds Unit runtime state. In other words it holds everything you've changed while Unit is running.

>> But you need to make sure that the configuration is still valid for the new build
>
> can you please clarify this ? Haven't got it.

If your previous configuration uses IPv6 addresses, but you've build a new Unit without IPv6 support, then the configuration won't be applied. The same will happen if the relevant application modules won't be found.

> should I somehow remove or uninstall the current installation before building new configuration ?

No, you shouldn't.
