### ISSUE TITLE
Expose TLS version and ciphers configuration

### ISSUE THREAD

**Issue by josephapg** [nginx/unit#359]
Hi,
It looks like Unit doesn't have this capability yet.
This would be useful in the following cases:
1. Limiting TLS version to 1.2 and 1.3
2. Prioritizing 128-bit ciphers over 256-bit
3. Limiting available ciphers

**Comment by artemkonev** [comment]
@josephapg hi, take a look at the recent updates, the TLS config was extended: https://unit.nginx.org/configuration/#ssl-tls-configuration
