### ISSUE TITLE
IMAP/SMTP proxy : allow different authorization and authentication identities 

### ISSUE THREAD

**Issue by a4i** [nginx/unit#362]
IMAP servers (dovecot, cyrus...) rely on SASL authentication.

The SASL specs let the client requests a different identity than the one
used for authentication.

RFC 3501 says : The authorization identity passed from the client to the
server during the authentication exchange is interpreted by the server as
the user name whose privileges the client is requesting.

Dovecot proxy and Cyrus frontends in murder architecture use this to
authenticate with an admin account and request a user identity. It's very
useful to authenticate via proxies without to know the user's password.

Can we have a way to let NGINX use different identification and authentication
ids to authenticate to the remote imap server ?

Thanks

**Comment by VBart** [comment]
This is issue tracker for **Unit** web-server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
