### ISSUE TITLE
Fixed missing ipv6 checking in `route addr`.

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#363]
Hi.

```
diff -r 96e6ac1926f8 src/nxt_http_route_addr.c
--- a/src/nxt_http_route_addr.c	Thu Dec 26 17:04:37 2019 +0300
+++ b/src/nxt_http_route_addr.c	Mon Dec 23 15:19:45 2019 +0800
@@ -179,7 +179,10 @@
             return NXT_ADDR_PATTERN_FORMAT_ERROR;
         }

-        nxt_inet6_addr(&inet6->start, addr.start, addr.length);
+        ret = nxt_inet6_addr(&inet6->start, addr.start, addr.length);
+        if (nxt_slow_path(ret != NXT_OK)) {
+            return NXT_ADDR_PATTERN_FORMAT_ERROR;
+        }

         goto parse_port;
 #endif
```

**Comment by Izorkin** [comment]
Not builded with this patch:
```
-o build/src/nxt_http_route_addr.o \
-MMD -MF build/src/nxt_http_route_addr.dep -MT build/src/nxt_http_route_addr.o \
src/nxt_http_route_addr.c
src/nxt_http_route_addr.c: In function 'nxt_http_route_addr_pattern_parse':
src/nxt_http_route_addr.c:21:43: error: unused variable 'end' [-Werror=unused-variable]
     u_char                       *delim, *end;
                                           ^~~
cc1: all warnings being treated as errors
make: *** [build/Makefile:1124: build/src/nxt_http_route_addr.o] Error 1
```

**Comment by hongzhidao** [comment]
@Izorkin 
It seems you found another issue, this happens if ipv6 in your system is not supported.

**Comment by astlock** [comment]
same, when I added --no-ipv6 to `./configure`
build via Dockerfile from debian:stable-slim

-o build/src/nxt_http_route_addr.o \
-MMD -MF build/src/nxt_http_route_addr.dep -MT build/src/nxt_http_route_addr.o \
src/nxt_http_route_addr.c
src/nxt_http_route_addr.c: In function 'nxt_http_route_addr_pattern_parse':
src/nxt_http_route_addr.c:21:43: error: unused variable 'end' [-Werror=unused-variable]
     u_char                       *delim, *end;
                                           ^~~
cc1: all warnings being treated as errors
make: *** [build/Makefile:1122: build/src/nxt_http_route_addr.o] Error 1

**Comment by axelduch** [comment]
There is a patch that should be coming this way soon.
