### ISSUE TITLE
nginx logs api keys on querystring when request to upstream fails

### ISSUE THREAD

**Issue by marty2bell** [nginx/unit#372]
When there is an error in connecting to an upstream due to a transient error, nginx writes out the requestline which can include an apikey.

We were able to mask the apikey for successful requests using a custom formatter and regex, but we need to be able to do the same for error logs.  Error details below:

[error] 27#0: *74091557 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XX.XX, server: kong, request: “GET /{{my-route}}?apikey=XXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1”

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
