### ISSUE TITLE
Problem with package sources in Debian repository

### ISSUE THREAD

**Issue by Articus** [nginx/unit#374]
It seems that there is some issue with publishing Nginx Unit package sources for Debian repository `https://packages.nginx.org/unit/debian`. [Sources file](https://packages.nginx.org/unit/debian/dists/buster/unit/source/Sources) is empty and for example trying to get build dependencies for `unit-php` package ends up with `E: You must put some 'source' URIs in your sources.list`. Simple Dockerfile to reproduce:
```Dockerfile
FROM debian:buster
#Add Nginx Unit repository
RUN apt update \
    && apt -y install apt-transport-https ca-certificates gnupg \
    && echo "deb https://packages.nginx.org/unit/debian/ buster unit" >> /etc/apt/sources.list.d/unit.list \
    && echo "deb-src https://packages.nginx.org/unit/debian/ buster unit" >> /etc/apt/sources.list.d/unit.list \
    && apt-key adv --fetch-keys https://nginx.org/keys/nginx_signing.key \
    && apt update
#Try to install build dependencies for Nginx Unit PHP language module - throws error
RUN apt -y build-dep unit-php
```
It should be working though - according [Dockerfile](https://github.com/nginx/unit/blob/master/pkg/docker/Dockerfile.php7.3#L47) for official Nginx Unit image.

Could you please help to investigate this issue?

**Comment by thresheek** [comment]
Hi @Articus, indeed we don't provide package sources files in the repositories, and that might be inconvenient.  The Dockerfiles were wrong to utilize that code path.

The actual sources to build and package the binaries are available in `pkg/` directory in the development tree (they're not copied over to tarballs): https://github.com/nginx/unit/tree/master/pkg
