### ISSUE TITLE
Nginx is mixing cache between my two domains

### ISSUE THREAD

**Issue by adrianTNT** [nginx/unit#376]
I don't know if this is a bug or I am defining cache incorrectly, I have a nginx cache (reverse proxy) server that is used by 2 **different** domains (`mydomain1.com` and `mydomain2.com`), different content, not an alias domain. 

I defined a single cache, then defined the two domains/vhosts in nginx and set it to use that cache, both domains take their data from same source server, but they pass the different vhost to the source server so they take the right content.

Problem is that nginx seems to mix the cache on the two servers, accessing one home page shows cached homepage of the other.

Do I need a separate cache defined for each vhost ?

Shouldn't NGINX cached data also associate a vhost with each request ? It seems to just associate a source server, port, etc.

This is the head of cached home page, showing that there is nothing to differentiate between the two vhosts:

```
KEY: http://source.example.com:81/
HTTP/1.1 200 OK
Date: Sun, 02 Feb 2020 00:54:33 GMT
Server: Apache/2.4.6 (CentOS) mpm-itk/2.4.7-04 OpenSSL/1.0.2k-fips PHP/5.4.16
X-Powered-By: PHP/5.4.16
Expires: Sun, 02 Feb 2020 02:54:33 GMT
Cache-Control: public, max-age=7200
X-Mod-Pagespeed: 1.13.35.2-0
Vary: Accept-Encoding
```

My NGINX cache settings:
```
proxy_cache_path /ramdisk/nginx_cache levels=1:2 keys_zone=nginx_ramdisk_cache:512m max_size=3g
                     inactive=30d use_temp_path=off;



# defining domain 1
server {
    [...]
    server_name  mydomain1.com;
  
    location / {

            proxy_pass       http://source.example.com:81;

            proxy_set_header Host      mydomain1.com;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;

            proxy_cache             nginx_ramdisk_cache;
    }
}

# defining domain 2
server {
    [...]
    server_name  mydomain2.com;
  
    location / {

            proxy_pass       http://source.example.com:81;

            proxy_set_header Host      mydomain2.com;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;

            proxy_cache             nginx_ramdisk_cache;
    }
}
```
and on the source server (apache) I have my 2 vhosts defined like this:

```

<VirtualHost *:81>
     ServerName mydomain1.com
     DocumentRoot /var/www/html/mydomain1.com
</VirtualHost>


<VirtualHost *:81>
     ServerName mydomain2.com
     DocumentRoot /var/www/html/mydomain2.com
</VirtualHost>
```

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html

**Comment by adrianTNT** [comment]
Maybe someone else stumbles upon same issue...
By [default](https://nginx.org/en/docs/http/ngx_http_proxy_module.html?&_ga=2.55268011.129501190.1580606348-1160844069.1578342746#proxy_cache_key) nginx uses a proxy_cache_key that includes the proxy source server, not the actual host:
```
proxy_cache_key $scheme:$proxy_host$request_uri;
```
Solution to differentiate keys for two different domains:
```
proxy_cache_key $scheme://$host$request_uri;
```
