### ISSUE TITLE
Joomla config example

### ISSUE THREAD

**Issue by bvm84** [nginx/unit#377]
Hello.
Can somebody provide working Joomla config example.
I'm truing to adopt WP config but got Error on domain/installation/index.php.
Nginx, unit, php logs do not show any valuable information.
Maybe somebody have working example for reference.

**Comment by bvm84** [comment]
Working Joomla config for reference:
{
    "listeners": {
        "*:8092": {
            "pass": "routes/domain"
        }
    },
    "routes": {
    "domain": [
            {
                "match": {
                     "uri": [
                        "*.php",
                        "*.php/*"
                    ]
                },
                "action": {
                    "pass": "applications/domain_direct" 
                }
            },
            {
                "match": {
                  "uri": [
                    "*.manifest",
                    "*.appcache",
                    "*.html",
                    "*.json",
                    "*.rss",
                    "*.atom",
                    "*.jpg",
                    "*.jpeg",
                    "*.gif",
                    "*.png",
                    "*.ico",
                    "*.cur",
                    "*.gz",
                    "*.svg",
                    "*.svgz",
                    "*.mp4",
                    "*.ogg",
                    "*.ogv",
                    "*.webm",
                    "*.htc",
                    "*.css",
                    "*.js",
                    "*.ttf",
                    "*.ttc",
                    "*.otf",
                    "*.eot",
                    "*.woff",
                    "*.woff2",
                    "/robot.txt"
                  ]
                },
                "action": {
                  "share": "/var/www/domain"
                }
            },
            {
                "action": {
                    "pass": "applications/domain_index"
                }
            }
        ]
    },
    "applications": {
        "domain_index": {
            "type": "php",
            "processes": 1,
            "user": "root",
            "group": "root",
            "root": "/var/www/domain/",
            "index": "index.php"
        },
        "domain_direct": {
            "type": "php",
            "processes": 1,
            "user": "root",
            "group": "root",
            "root": "/var/www/domain/"
        }
    }
} 

N.B. If you get such error: "call to undefined function simplexml_load_file()" install php-xml ext. 
sudo apt install php-xml in Ubuntu.
"try_files" directive must have feature for Unit. Ugly file extension list maybe avoided by using Nginx proxy to serve static files.
Separate config files also must have feature (like sites-enabled in Nginx). My Unit config files for 4 aps just so long, it's hard to read and manage (json format good for APIs, but not so human-readable).

**Comment by bvm84** [comment]
The issue is solved.

**Comment by artemkonev** [comment]
Thank you for the suggestion, I'm on it.

**Comment by bvm84** [comment]
This conf is incompatible with Joomla SEF rewrite policy. I stucked deleting index.php from url for a couple of days.
It seems such kind of routing rule "match":  "*.php", "*.php/*" is bad idea for joomla. When index.php is in route the rule is mathed and everything goes smooth. Then Joomla SEF module exclude index.php from URL Unit falls into redirect loop. I tried to modify match rule in different ways - no luck.

**Comment by VBart** [comment]
@bvm84 It seems you need to use "script" option instead of "index" option. Note that there's no difference between "domain_index" and "domain_direct" application targets in the configuration above, since "index: index.php" is the default setting.

**Comment by bvm84** [comment]
VBart thanks a lot. "script" options fixed everything. To sum up, working config;
{
    "listeners": {
        "*:8092": {
            "pass": "routes/domain"
        }
    },
    "routes": {
    "domain": [
            {
                "match": {
                     "uri": [
                        "*.php",
                        "*.php/*",
                       "/administrator/"
                    ]
                },
                "action": {
                    "pass": "applications/domain_direct" 
                }
            },
            {
                "action": {
                    "pass": "applications/domain_index"
                }
            }
        ]
    },
    "applications": {
        "domain_index": {
            "type": "php",
            "processes": 1,
            "user": "www-data",
            "group": "www-data",
            "root": "/var/www/domain/",
            "script": "index.php"
        },
        "domain_direct": {
            "type": "php",
            "processes": 1,
            "user": "www-data",
            "group": "www-data",
            "root": "/var/www/domain/"
        }
    }
}

**Comment by artemkonev** [comment]
Wrapped up here: https://unit.nginx.org/howto/joomla/
