### ISSUE TITLE
Supporting many language versions on the same machine

### ISSUE THREAD

**Issue by ajmyyra** [nginx/unit#38]
Many languages (PHP, Python, etc) have numerous versions in active use that can be installed on the same machine. Could there be an option named version to support this? Or just a binpath setting where you could define the interpreter used?

Example for config with version included:

```
"blogs": {
    "type": "php",
    "version": "7.1",
    "workers": 20,
    "root": "/www/blogs/scripts",
    "index": "index.php",
    "user": "www-blogs",
    "group": "www-blogs"
},
"legacy": {
    "type": "php",
    "version": "5.6",
    "workers": 5,
    "root": "/www/legacy/public_html",
    "index": "index.php",
    "user": "www-legacy",
    "group": "www-legacy"
}
```

**Comment by igorsysoev** [comment]
You just need add version after application type:

```
"blogs": {
    "type": "php 7.1",
    ...
},
"legacy": {
    "type": "php 5.6",
    ...
}
```

**Comment by ajmyyra** [comment]
Nice, thanks! Will check if it was just me being dumb or could the documentation be improved on this.

**Comment by igorsysoev** [comment]
We will certainly document this.
BTW you can specify just "php7" and unit will find the most highest available php7 version module. Version can be specified with one space or without it: "php7.1" or "php 7.1".
