### ISSUE TITLE
Brew tap for macOS

### ISSUE THREAD

**Issue by artemkonev** [nginx/unit#399]
Unit tap for Homebrew will simplify installation on Macs.

**Comment by mar0x** [comment]
:beer: The tap is available at https://github.com/nginx/homebrew-unit .
Help yourself!

**Comment by misaon** [comment]
PHP module missing for in formulas?

**Comment by mar0x** [comment]
Yes, PHP module is missing because of absence of embedded libphp library in Brew's PHP installation.
@misaon, if you really need one, let me know. I'll try to create formula to build the library and Unit module.

**Comment by mar0x** [comment]
@misaon, @bondie in case you are still interesting, `unit-php` formula has been added to nginx tap. Be aware it depends on `php-embed` which will be build from sources and it takes time and CPU.
🍺 Cheers!
