### ISSUE TITLE
How to use the REST API for configuration

### ISSUE THREAD

**Issue by skillslasher** [nginx/unit#401]
I understand that this is most likely a very silly question, but I do not fully understand how to use the REST API for configuration.

For example I have this configuration:
```
{
  "listeners": {
    "*:8302": {
      "pass": "applications/my_app"
    }
  },
  "applications": {
    "my_app": {
      "type": "php 7.2",
      "processes": {
         "max": 10,
         "spare": 3,
         "idle_timeout": 20},
      "user": "nginx",
      "group": "nginx",
      "root": "/var/site/web/public_html/test.ru/www",
      "script": "index.php",
      "options": {
        "file": "/etc/unit-php72.ini"
      }
    }
  }
}
```
Why add to the configuration is:

> sudo curl -X PUT -d '{"limits": {"timeout":15, "requests":1000}}' --unix-socket /run/control.unit.sock http://localhost/config/applications/my_app

I get an error:

> {
>         "error": "Invalid configuration.",
>         "detail": "Application must have the \"type\" property set."
> }
If I load the complete configuration:
> sudo curl -X PUT -d '{_Here, all of the fields from the block my_app_}' --unix-socket /run/control.unit.sock http://localhost/config/applications/my_app

I get an error:

> {
>         "error": "Failed to apply new configuration."
> }

Please explain why and how to properly use the configuration settings?

**Comment by mar0x** [comment]
Hello,

As stated in [Configuration Management](http://unit.nginx.org/configuration/#configuration-management): "PUT  Replaces the entity at the request URI ..". Try this way:

> sudo curl -X PUT -d '{"timeout":15, "requests":1000}' --unix-socket /run/control.unit.sock
> http://localhost/config/applications/my_app/limits

**Comment by skillslasher** [comment]
> 
> 
> Hello,
> 
> As stated in [Configuration Management](http://unit.nginx.org/configuration/#configuration-management): "PUT Replaces the entity at the request URI ..". Try this way:
> 
> > sudo curl -X PUT -d '{"timeout":15, "requests":1000}' --unix-socket /run/control.unit.sock
> > http://localhost/config/applications/my_app/limits

Thank you. It works. I didn't think of it ((
