### ISSUE TITLE
Need help with running simple java app

### ISSUE THREAD

**Issue by BorisChistov** [nginx/unit#403]
Hello guys, maybe someone can help me. I installed Nginx unit on Ubuntu 18.04 with module unit-jsc11.

Trying to run the application from @mar0x  [repository](https://github.com/mar0x/gs-spring-boot)

Unit logs [here](https://gist.github.com/BorisChistov/02e5772db36759cb0fc883c57893579c)

Instead of "Greetings from Spring Boot!" I'm getting an unarchived war file. with META-INF, WEB-INF

Configuration for app is:
``` json
{
	"listeners": {
		"*:8080": {
			"pass": "applications/uapi"
		}
	},

	"applications": {
		"uapi": {
			"working_directory": "/tmp",
			"processes": 1,
			"type": "java",
			"webapp": "/www/app/uapi/gs-spring-boot-0.1.0.war",
			"options": [
			],
			"classpath": []
		}
	}
}
```

**Comment by mar0x** [comment]
Hello,
I confirm there is an issue with unit java module.  I will investigate this and let you know the results.

**Comment by mar0x** [comment]
There is an issue introduced with WebSocket implementation patch.  Please try this patch:
```patch
diff --git a/src/java/nginx/unit/Context.java b/src/java/nginx/unit/Context.java
--- a/src/java/nginx/unit/Context.java
+++ b/src/java/nginx/unit/Context.java
@@ -1517,7 +1517,7 @@ public class Context implements ServletC
                     || ci.isAnnotation()
                     || ci.isAbstract())
                 {
-                    return;
+                    continue;
                 }
 
                 trace("loadInitializer: handles class: " + ci.getName());
```

**Comment by BorisChistov** [comment]
Tested, this patch fixes the issue. Thanks.
