### ISSUE TITLE
Ability to load multiple certificates

### ISSUE THREAD

**Issue by smtalk** [nginx/unit#406]
Hello,

It'd be nice to have an ability to use multiple certificates on the same listener. This way standalone Nginx Unit would make sense, as multiple different sites would still be covered on port :443.

Currently we have:
`"tls": {
                "certificate": "<bundle>"
            }`

Something like this would be perfect:
`"tls": {
                "certificate": [ "domain_name1.com": "<bundle1>",  "domain_name2.com,domain_name3.com": "<bundle2>" ]
            }`

Where 2nd one is multi-domain cert. On SNI-matching time Nginx Unit would just send a correct cert to the client.

Thank you!

**Comment by artemkonev** [comment]
Released with Unit 1.23.0: https://unit.nginx.org/configuration/#listeners
