### ISSUE TITLE
Ability to pass hostname to 'routes'

### ISSUE THREAD

**Issue by smtalk** [nginx/unit#407]
Hello,

We're planning to include Nginx Unit into DirectAdmin control panel.

At this time we're planning to use just 2 listeners for all the applications (HTTP and HTTPs). We can store application-per-domain, however we need to update whole routes array, because we cannot simply manipulate with routes just as with applications.

Currently every host update needs update of whole routes object.

Current situation:
```
 "routes": {
       "default": [
        {
            "match": {
                "host": "domain1,com",
                "uri": [ "/goapp1/*", "/goapp1" ]
            },
            "action": {
                "pass": "applications/admin_goapp1"
            }
    },
    {
        "match": {
            "host": "domain1.com",
            "uri": [ "/my_first_php_page/*", "/my_first_php_page" ]
        },
        "action": {
            "pass": "applications/admin_myphp"
        }
},
        {
            "match": {
                "host": "domain1.com"
            },
            "action": {
                "share": "/home/admin/domains/domain1.com/my_first_php_page"
            }
        },
       { "action": {
                "share": "/var/www/html/"
            }
	}
    ]
    },
	"listeners": {
		"*:8372": {
			"pass": "routes/default"
		},
		"*:8085": {
			"pass": "routes/default"
		}
	}
```

Proposal:
```
	"listeners": {
		"*:8372": {
			"pass": "routes/$host"
		},
		"*:8085": {
			"pass": "routes/$host"
		}
	}
```

This way it could pass to $host array element, and only URI matching would be done there. It'd really help with the management on shared webhosting environment.

That way we could simply override just the $host element in array for particular host, and it'd be somewhat similar to 'virutal hosts' in apache or 'server blocks' in nginx :)

**Comment by VBart** [comment]
You can optimize your config by using multiple `routes` objects (one per domain):
```json
"routes": {
    "default": [
        {
            "match": {
                "host": "domain1.com",
            },
            "action": {
                "pass": "routes/domain1.com"
            }
        },
        {
            "match": {
                "host": "domain2.com",
            },
            "action": {
                "pass": "routes/domain2.com"
            }
        },
        {
            "action": {
                "share": "/var/www/html/"
            }
        }
    ],
    "domain1.com": [
        {
            "match": {
                "uri": [ "/goapp1/*", "/goapp1" ]
            },
            "action": {
                "pass": "applications/admin_goapp1"
            }
        },
        {
            "match": {
                "uri": [ "/my_first_php_page/*", "/my_first_php_page" ]
            },
            "action": {
                "pass": "applications/admin_myphp"
            }
        },
        {
            "action": {
                "share": "/home/admin/domains/domain1.com/my_first_php_page"
            }
        }
    ],
    "domain2.com": [ .. ],
},

"listeners": {
    "*:8372": {
        "pass": "routes/default"
    },
    "*:8085": {
        "pass": "routes/default"
    }
}
```

**Comment by smtalk** [comment]
@VBart nice idea! Still requires updating "routes/default" object after every new domain addition/removal though. Your suggestion already improves readability/implementation - thanks you :)

**Comment by smtalk** [comment]
@VBart any suggestions for different static paths for different URIs? (at this time there is only 1 static file path per-route array object). If not, I'll likely need to change "domain.com" route to "domain.com_$app_name" and then change some logics again..

Thank you!

**Comment by tiago4orion** [comment]
> @VBart nice idea! Still requires updating "routes/default" object after every new domain addition/removal though. Your suggestion already improves readability/implementation - thanks you :)

Just in case you didn't know:

```
$ curl $sock -XGET http://127.0/config
{
	"routes": {
		"default": []
	}
}
```
Using POST in array you can append elements:

```
$ curl $sock -XPOST http://127.0/config/routes/default --data-binary '{
    "action": {
        "share": "/tmp"
    }
}'

$ curl $sock -XPOST http://127.0/config/routes/default --data-binary '{
    "action": {
        "share": "/usr"
    }
}'

$ curl $sock -XGET http://127.0/config
{
	"routes": {
		"default": [
			{
				"action": {
					"share": "/tmp"
				}
			},
			{
				"action": {
					"share": "/usr"
				}
			}
		]
	}
}
```

You can reference specific array elements using `/config/routes/default/<index>` for GET, DELETE and PUT.

```
$ curl $sock -XDELETE http://127.0/config/routes/default/1
{
	"success": "Reconfiguration done."
}
$ curl $sock -XGET http://127.0/config
{
	"routes": {
		"default": [
			{
				"action": {
					"share": "/tmp"
				}
			}
		]
	}
}
```

**Comment by smtalk** [comment]
@tiago4orion I know this, thanks for a reminder though. The problem is:
domain.com array object cannot be removed, as routes/default is pointing to it. routes/default needs to be updated after every domain change, or.. looping through every element of it and double-checking the state is consistent would be needed otherwise :)

Passing to "routes/$host" (+ ability to specify aliases) would be awesome. At this time it can be workarounded, of course.

**Comment by smtalk** [comment]
@VBart https://github.com/nginx/unit/issues/434 would solve this issue if we had 'host' as a variable available there.

**Comment by VBart** [comment]
@smtalk I assume that you mean #410. We will add $host in the next release.

**Comment by smtalk** [comment]
Yes, definitely :) Thank you!

**Comment by smtalk** [comment]
Just a thought... maybe we could also have $hostw, or something else to save duplicate code and auto-truncate www. beginning? Duplicate code isn’t a huge problem though (same code for www.domain.com and domain.com)

Thanks!

**Comment by VBart** [comment]
> Just a thought... maybe we could also have $hostw, or something else to save duplicate code and auto-truncate [www](http://www). beginning? Duplicate code isn’t a huge problem though (same code for [www.domain.com](http://www.domain.com) and domain.com)

This case is better covered by the planned regular expressions support in the matching rules. Using regexp captures you'll be able to save specific part of the host into custom variable with the capture name.
