### ISSUE TITLE
Send POST request with no response

### ISSUE THREAD

**Issue by ghostarc** [nginx/unit#41]
I am using Ubuntu server 16.04 with unit, with simple php application. and it's works.
and trying to run phpmyadmin it's works too, but with some issue.

index.php is appears, if I trying to login, nothing happened.
without error message. just like reload the pages.

![screenshot 16](https://user-images.githubusercontent.com/26864484/30727604-686d4198-9f7c-11e7-935c-fbff01191ee3.png)

**Comment by mar0x** [comment]
Most likely you are experiencing issue #10. Please try to build unit yourself using latest sources.

If you already using latest sources, please reconfigure unit with --debug, rebuild and provide configuration and log files for further analysis.

**Comment by ghostarc** [comment]
#fixed

it's using PUT method not POST
