### ISSUE TITLE
App help, logging not working when run in unit

### ISSUE THREAD

**Issue by elijahsgh** [nginx/unit#419]
Sorry, I know you all cannot provide specific app help but I got stuck.

I have an app that is using Bunyan for logging but not through an express middleware function or similar. Any logging operations in the unit `executable` configuration (ie: index.js) work fine. Any logging operations outside of `index.js` do not regardless of if the configuration is for `stdout` or files. Is there a hint on why it works like this within unit?

Some relevant links to source.
Messages that should be logged at startup: https://github.com/TryGhost/Ghost/blob/master/core/server/ghost-server.js#L192

Logging for the app: https://github.com/TryGhost/Ignition/tree/master/lib/logging

**Comment by tiago4orion** [comment]
@elijahsgh Try running Unit with --no-daemon parameter and see if the logging shows in the console or if you're using systemd, maybe `sudo journalctl -u unit`.

**Comment by elijahsgh** [comment]
Thanks, @tiago4orion but neither of those work. I can see the normal unit logs just fine but the applications logs never get written. It doesn't matter if the application is configured to log to stdout or files. It seems like the writes just don't fire and I'm not sure why it would be like that under unit.

If I try logging from the `executable` (ie: index.js) it works fine but no other logging works anywhere else. It's very strange.

**Comment by elijahsgh** [comment]
I'm going to close this since it's sort of a 3rd party support request.
Thanks!
