### ISSUE TITLE
Matcher: /foo/* to match /foo

### ISSUE THREAD

**Issue by smtalk** [nginx/unit#420]
Wouldn't it make sense to make` /foo/*` match `/foo` as well by default?

`/foo*` also matches /foobar etc., so, it's not a solution, and.. multiple uri's always need to be defined for this very common case.

Thank you!

**Comment by VBart** [comment]
I see a few problems with this approach:
1. Anyone who doesn't need this behaviour will have to explicitly turn it off by adding "!/foo".
2. Extending quite simple rules for "*" with some implicit magic here, that will need to be explicitly documented and remembered by users.
3. Differentiating of behaviour of "*" for the "uri" matching property from other properties, where "/" doesn't have any special meaning.

So, in overall it complicates matching rules and may confuse users if they wouldn't remember this subtle nuance of "*" in "uri". As a worst case scenario it even can lead to security breach.

Note that the location directive in nginx works similar way... "location /foo/" matches only "/foo/", but not "/foo".

We are going to introduce ability to use regular expressions in the "match" objects. Having them you will be able to write more complicated patterns.

**Comment by smtalk** [comment]
Oh, regex there would do the trick! (and be the "right" way to solve it). I'll be waiting for the implementation. Thanks!
