### ISSUE TITLE
"Error 400" in Cloud Foundry?

### ISSUE THREAD

**Issue by dannmartens** [nginx/unit#422]
I've been trying to deploy a custom Docker container with Nginx Unit in a Cloud Foundry instance, but the only response I get is "Error 400" across the line.

Can someone tell me if this is generated by Nginx Unit?
```
<!DOCTYPE html><title>Error 400</title><p>Error 400.
```
I turned on the Unit access logs, but I only see this:
```
10.244.112.49 - - [02/Apr/2020:13:26:06 +0000] "GET / HTTP/1.1" 400 54 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
```
The Cloud Foundry router reports something similar:
```
[2020-04-02T13:26:05.921827769Z] "GET / HTTP/1.1" 400 0 54 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" "10.164.95.242:33022" "158.176.87.28:61022" x_forwarded_for:"77.56.208.204, 10.164.95.242" x_forwarded_proto:"http" vcap_request_id:"f0b4325d-7dac-487f-42d5-f2c1f1ead485" response_time:0.120993 gorouter_time:0.000282 app_id:"02b6df87-2617-4b4f-8b1e-67abd17984b6" app_index:"0" x_global_transaction_id:"f28b14df5e85e7edc32d031d" true_client_ip:"-" x_b3_traceid:"3ff4a457fc085864" x_b3_spanid:"3ff4a457fc085864" x_b3_parentspanid:"-" b3:"3ff4a457fc085864-3ff4a457fc085864"
``` 

In order to compare, I have deployed the official Unit Docker image in the same way, and configured it live over SSH, only to get the same "Error 400" again.

The configuration which I used with the official image is very simple:
```javascript
cat << EOF > config.json
{
    "listeners": {
        "*:8080": {
            "pass": "routes"
        }
     },
    "routes": [
        {
            "action": {
                "share": "/var/www/static"
             }
        }
    ],
    "access_log": "/var/log/access.log"
}
EOF
```
As soon as I curl the configuration into Unit, I get confirmation:
```javascript
{
        "success": "Reconfiguration done."
}
```
Before the configuration is live, I get a "502 Bad Gateway"—which is to be expected—in Cloud Foundry's typical response format, then afterwards "Error 400" is back. This response does not appear as if it was generated by Cloud Foundry.

I can still curl from inside the live container to get a proper application response, as there seems to be a working service listening on 0.0.0.0:8080. And just running the container bare on the OS also works. 

I wonder what happens when the request traverses through the system [HTTP Client] -> [Cloud Foundry Router] -> [Nginx Unit]. Is there any way to get a dump of this request from Unit?

Your help would be appreciated!

**Comment by VBart** [comment]
Could you check what's in the [`unit.log`](https://unit.nginx.org/troubleshooting/#logging)?

**Comment by dannmartens** [comment]
Actually, there is nothing in unit.log—at all.

I have used the same link in my custom Docker container, as the official image does.
```
ln -sf /dev/stdout /var/log/unit.log
```
This is the reason I activated the access log: I didn't get any other logging out of the system.

**Comment by VBart** [comment]
@dannmartens Is it completely empty, or there are some lines? If it's empty, this is weird, because Unit daemon always logs some lines during startup.

**Comment by dannmartens** [comment]
No,

At start-up, this is piped to stdout/stderr:
```
   2020-04-03T16:38:31.65+0200 [APP/PROC/WEB/0] OUT /usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is empty, skipping initial configuration...
   2020-04-03T16:38:31.70+0200 [APP/PROC/WEB/0] ERR 2020/04/03 14:38:31 [info] 13#13 unit started
   2020-04-03T16:38:31.70+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [info] 55#55 discovery started
   2020-04-03T16:38:31.71+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 55#55 module: perl 5.28.1 "/usr/lib/unit/modules/perl.unit.so"
   2020-04-03T16:38:31.75+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 55#55 module: php 7.3.11-1~deb10u1 "/usr/lib/unit/modules/php.unit.so"
   2020-04-03T16:38:31.76+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 55#55 module: python 2.7.16 "/usr/lib/unit/modules/python2.7.unit.so"
   2020-04-03T16:38:31.77+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 55#55 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
   2020-04-03T16:38:31.77+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 55#55 module: ruby 2.5.5 "/usr/lib/unit/modules/ruby.unit.so"
   2020-04-03T16:38:31.77+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [notice] 13#13 process 55 exited with code 0
   2020-04-03T16:38:31.77+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [info] 56#56 controller started
   2020-04-03T16:38:31.78+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [info] 57#57 router started
   2020-04-03T16:38:31.78+0200 [APP/PROC/WEB/0] OUT 2020/04/03 14:38:31 [info] 57#57 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
```

Nothing shows up here when when reconfiguring with curl.
Nothing shows up here when accessing over the external URL.

**Comment by VBart** [comment]
@dannmartens Could you enable [debug logging](https://unit.nginx.org/troubleshooting/#debug-log) to see what happens in details?

**Comment by dannmartens** [comment]
I haven't managed to enable debug logging yet. It would mean rebuilding the Docker image, as it does not appear to be doable by changing the configuration. Is there another image available which starts this "unitd-debug" binary?

For now, I injected a socat instance in front of Unit, inside a live container:
```
root@eac3c01c-2116-4f0a-69cd-1da1:~# ./socat -v TCP-LISTEN:8080,reuseaddr TCP-CONNECT:127.0.0.1:9090
> 2020/04/09 09:47:33.460427  length=1027 from=0 to=1026
GET / HTTP/1.1\r
Host: www.example.com\r
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36\r
$wsis: false\r
$wsra: 77.56.208.204\r
$wssc: http\r
$wssn: www.example.com\r
$wssp: 80\r
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r
Accept-Encoding: gzip, deflate\r
Accept-Language: en-US,en;q=0.9\r
B3: ab3114a0f3d1da92-ab3114a0f3d1da92\r
Cache-Control: no-transform\r
Dnt: 1\r
Upgrade-Insecure-Requests: 1\r
Via: 1.1 DQAAADtvDEQ-\r
X-B3-Spanid: ab3114a0f3d1da92\r
X-B3-Traceid: ab3114a0f3d1da92\r
X-Cf-Applicationid: 02b6df87-2617-4b4f-8b1e-67abd17984b6\r
X-Cf-Instanceid: eac3c01c-2116-4f0a-69cd-1da1\r
X-Cf-Instanceindex: 0\r
X-Client-Ip: 77.56.208.204\r
X-Forwarded-For: 77.56.208.204, 10.164.95.242\r
X-Forwarded-Proto: http\r
X-Global-Transaction-Id: f28b14df5e8eef35e3be829f\r
X-Request-Start: 1586425653430\r
X-Vcap-Request-Id: 44eb6f3a-bd59-4786-7480-6bce6bfd3ec5\r
\r
< 2020/04/09 09:47:33.497045  length=204 from=0 to=203
HTTP/1.1 400 Bad Request\r
Content-Type: text/html\r
Server: Unit/1.16.0\r
Date: Thu, 09 Apr 2020 09:47:33 GMT\r
Content-Length: 54\r
Connection: close\r
\r
<!DOCTYPE html><title>Error 400</title><p>Error 400.\r
```
Unit is running on port 9090 with a simple "Hello World" static page, socat on 8080 to intercept the requests.

As you can see from the output, Unit is generating the "Error 400" on account of—I presume—one or more headers in the request.

The ones with the '$' characters seemed to be the most likely candidates, and bingo:
```
root@eac3c01c-2116-4f0a-69cd-1da1:~# curl localhost:9090
Hello World
root@eac3c01c-2116-4f0a-69cd-1da1:~# curl -H "$wssn: 80" localhost:9090
<!DOCTYPE html><title>Error 400</title><p>Error 400.
```

**Comment by dannmartens** [comment]
I tested again with the latest image 1.17.10 and the issue doesn't appear to be patched yet.

Can you corroborate my finding that this is caused by the header(s)?

According to RFC 7230, "$wssn: 80" should be considered a valid header, see the sections:
*3.2.  Header Fields*:
```
     header-field   = field-name ":" OWS field-value OWS
     field-name     = token
```
and
*3.2.6.  Field Value Components*:
```
   Most HTTP header field values are defined using common syntax
   components (token, quoted-string, and comment) separated by
   whitespace or specific delimiting characters.  Delimiters are chosen
   from the set of US-ASCII visual characters not allowed in a token
   (DQUOTE and "(),/:;<=>?@[\]{}").

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters
```

**Comment by dannmartens** [comment]
Unit is still not RFC 7230 compliant: checked with v1.20.0.

**Comment by VBart** [comment]
We need functionality similar to the "[ignore_invalid_headers](https://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers)" directive in nginx. Currently Unit rejects requests with such headers.

While "$" is allowed in header names by RFC, such headers are considered unsafe to use, that's why they have special processing.

**Comment by dannmartens** [comment]
I am not sure how these characters would make a header name "unsafe."

These characters are not invalid; they are not even in the range of ASCII control characters. 

These are simple printable ASCII characters, they don't have superpowers:

![image](https://user-images.githubusercontent.com/263133/97327907-bd3c0680-1875-11eb-8b51-2be5b3956474.png)

The Nginx setting you are referring to would actually ignore those headers (default) and the application would not even know that some headers were stripped away. Now Unit is returning a 400 BAD REQUEST, which is technically not correct. In my opinion, there is no client error in this case.

**Comment by VBart** [comment]
I know that the setting in nginx works different way, I've just pointed out that we need similar setting and similar behaviour, while current Unit behaviour is too restrictive.

The "$" is known to be used as a variable marker in a number of languages (notably PHP). There were vulnerabilities in different web-applications found in the past that related to processing unusual characters in header field names. Unit, as well as nginx is also responsible for protecting the services behind, that's why we prefer to be more strict, unless it's violates interoperability. And I agree with you, that this particular case violates it and need to be fixed. But honestly, this is the first time I see using a non-alphabetic character in the header field name.

**Comment by VBart** [comment]
I'm going to fix this before 1.21 release, which is expected in the next month.

**Comment by dannmartens** [comment]
I avoid this type of header naming myself, as I tend to use the 'X-Namespace-Header-Name' convention for proprietary headers.

In this case, the $ naming scheme seems IBM-specific, with $ws__ referring to WebSphere.

![image](https://user-images.githubusercontent.com/263133/97434262-098f5100-191f-11eb-91b5-08633f530600.png)
 
I can imagine that it is tempting to use more exotic header namespacing in cloud-based application layer HTTP routing, in order to avoid naming conflicts.

Here's an [Nginx configuration to load balance WebSphere](https://cdn.wp.nginx.com/wp-content/uploads/2015/06/NGINX_IBM_WebSphere_Deployment-Guide.pdf):

![image](https://user-images.githubusercontent.com/263133/97434826-def1c800-191f-11eb-92fc-9f82a22fc901.png)

The IBM Cloud Foundry gorouter is probably configured to include those headers, as WebSphere Liberty is an important product in their Paas offering. Or perhaps load balancers (e.g. DataPower) inject those even earlier in the call chain.

**Comment by dannmartens** [comment]
I saw there was a v1.21 release, recently, so I was keen to test it. Unfortunately, I still get a 400 BAD REQUEST, with e.g.

curl -H "$wssn: 80" localhost:9090

I tested this on an Ubuntu 20.04 system:
ii  unit                                 1.21.0-1~focal                    amd64        NGINX Unit

Is this patch slated for a next release? Still looking forward to be able to use this in the cloud!

**Comment by VBart** [comment]
@dannmartens you have to escape `$` in your curl command:
`curl -H "\$wssn: 80" localhost:9090`
 
Оtherwise curl sends a header field with empty name:
```
% curl -v -H "$wssn: 80" 127.0.0.1:8080/env.php
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /env.php HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> : 80
> 
```

**Comment by dannmartens** [comment]
@VBart Thank you for pointing out my mistake!

I did not take Bash shell parameter expansions into account, when I tested this locally... 

I deployed the container directly to the IBM cloud and I can confirm it works perfectly!
