### ISSUE TITLE
Q: Static files point to 1 file

### ISSUE THREAD

**Issue by BorisChistov** [nginx/unit#423]
Is there any way to config route to serve 1 static file for match?

We have a react application, and we configured it as static resource. Config below.
Routing is done with react router, so the entry point for all requests should be index.html and then path is handled by react. 

``` json
{
  "listeners": {
    "*:9000": {
      "pass": "routes"
    }
  },

  "routes": [
    {
      "match": {
        "uri": [
          "/api/*",
          "/v3/*"
        ]
      },
      "action": {
        "pass": "applications/backend"
      }
    },
    {
      "action": {
        "share": "/home/unit/webapp/front/"
      }
    }
  ],

  "applications": {
    "backend": {
      "type": "java",
      "webapp": "/home/unit/webapp/uapi.war",
      "environment": {
        "SPRING_CONFIG_LOCATION": "file:/home/unit/bin/backend/application.yml"
      }
    }
  }
}
```

**Comment by JLLLinn** [comment]
This is something that's blocking us too, any news on this?
Basically any client side routing would require this

**Comment by VBart** [comment]
@hongzhidao is going to work on it soon. No ETA yet, but it has good chances to appear in a couple of months.

**Comment by artemkonev** [comment]
@BorisChistov hi, take a look at the latest release, the file share mechanism was updated, so now it can point to individual files as well

**Comment by tippexs** [comment]
That is a thing now. :) Will close this issue due to its complete implementation. Lmk if you have any more questions about it.
Timo
