### ISSUE TITLE
How to extract metrics

### ISSUE THREAD

**Issue by daniel-blake** [nginx/unit#427]
A customer needs me to retrieve metrics (for prometheus) from a number of nginx-unit docker images.
Is there currently a way to retrieve those, and if so, what are the necessary steps?

The metrics are a requirement of the setup, so if they're not available I need to start work on another solution.

**Comment by artemkonev** [comment]
Hi, @daniel-blake,

What kind of metrics are we talking about here? Currently, Unit forwards its access log to Docker container log, if it's any help to your cause.

**Comment by daniel-blake** [comment]
We're looking for metrics like those exposed in the nginx stub_status:
- The current number of active client connections including Waiting connections. 
- The total number of accepted client connections. 
- The total number of handled connections.
- The total number of client requests. 
- The current number of connections where nginx is reading the request header. 
- The current number of connections where nginx is writing the response back to the client. 
- The current number of idle client connections waiting for a request.

Not all are needed. We're also looking for metrics from the php subsystem, like:
- Memory usage
- Number of active processes

The precise metrics aren't set in stone, but the above is the ballpark estimate of what we need.

**Comment by artemkonev** [comment]
Thanks for the elaboration, Daniel. Unfortunately, this goes beyond Unit's capabilities at the moment. However, you can suggest specific metrics to be implemented in the future, as we're making mental notes of user concerns like this one.

**Comment by rowerok-it** [comment]
Good day! Any news on getting metrics from the app? The project is actively developing, but it is impossible to introduce it into the product without metrics.

**Comment by livelace** [comment]
Just a reminder from 2022.

**Comment by hongzhidao** [comment]
Hi

Here's the patch of metrics exported from Unit.
https://gist.github.com/hongzhidao/79ace78851667e50474623f9d191aeab

Welcome to suggest.

For example:
1. start
```
> ./build/unitd --control 127.0.0.1:8000
```
2. get status
```
> curl http://127.1:8000/status
{
	"connections": {
		"accepted": 0,
		"active": 0,
		"idle": 0,
		"closed": 0
	},

	"requests": {},
	"applications": {}
}
```
Or
```
> curl http://127.1:8000/status/connections
{
	"accepted": 0,
	"active": 0,
	"idle": 0,
	"closed": 0
}
```

Currently, we only support very basic statistics, welcome to suggest more metrics.

**Comment by hongzhidao** [comment]
Hi,
We just committed the statistics patch, and it'll be in the 1.28 version.
Welcome more suggestions on statistics, thanks.
