### ISSUE TITLE
Typo in "HOWTO: Symfony" symfony_direct root path ?

### ISSUE THREAD

**Issue by misaon** [nginx/unit#430]
I probably found a typo in the "root" path definition for "symfony_direct". The documentation says ":/path/to/my_project/public/", but I think there should be "/path/to/my_project/public/" (there is an extra colon).

https://unit.nginx.org/howto/symfony/

It is so?

**Comment by artemkonev** [comment]
Hi, @misaon ,

Yes, you're right. Will fix ASAP.
