### ISSUE TITLE
What is the correct way to POST request with json body via ngx_http_subrequest ?

### ISSUE THREAD

**Issue by sdouek** [nginx/unit#433]
I tried :
location /internal/event {
            set $event_type unknown;
            proxy_method POST;
            proxy_set_header content-type "application/json";
            proxy_set_body '{"event": "$event_type"}';
		    proxy_pass http://HOST:PORT/event

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
