### ISSUE TITLE
No packages for Fedora 32

### ISSUE THREAD

**Issue by chocolatkey** [nginx/unit#436]
Hello,

Fedora 32 was released in late April. I would like to use Nginx Unit on the latest version of Fedora, however no packages exist for 32: https://packages.nginx.org/unit/fedora/ . Could I know when they will be added?

Thanks

**Comment by defanator** [comment]
@chocolatkey thanks for the notice. We've added Fedora 32 into the building infra. Packages for the latest release (1.18.0) are now available in the repo. Documentation is about to be adjusted as well.
