### ISSUE TITLE
how to load certificates files,   not upload

### ISSUE THREAD

**Issue by find456789** [nginx/unit#437]
like nginx:

```
 ssl_certificate     www.example.com.crt;
 ssl_certificate_key www.example.com.key;
```

i used nginx-unit in docker, how to load my ssl_certificate files ?

thank you very much

**Comment by VBart** [comment]
It's not clear what do you mean by "load ..., not upload"? You can load certificate files via Unit API:
https://unit.nginx.org/configuration/#ssl-tls-and-certificates

Here's some tutorials, how to use it inside Docker containers: 
https://unit.nginx.org/howto/docker/

If you're using our official images, then you can use the initialization script, that is looking for certificate bundles in the `/docker-entrypoint.d/` directory at the first start. See here for details: https://unit.nginx.org/installation/#initial-configuration

**Comment by stfenjobs** [comment]
上传的方式好麻烦， 不得不更换了caddy
