### ISSUE TITLE
Support for custom python command 

### ISSUE THREAD

**Issue by gxpd-francisco** [nginx/unit#447]
Hello. We've been using Nginx Unit to run our python apps and are very happy with it. 
But we want to implement Datadog APM and I see no way in the docs to customize the python command in order to wrap it with their `ddtrace-run` script.

Could you please add this functionality?

Thank you.

**Comment by VBart** [comment]
Could you elaborate more about what do you mean by "customize the python command"? What command? Could you give an example?

**Comment by gxpd-francisco** [comment]
Yes, in order to start the application with datadog tracing you must wrap the python command like this:
`ddtrace-run python app.py`
or
`ddtrace-run gunicorn app.wsgi:application`

**Comment by VBart** [comment]
@gxpd-francisco But unlike gunicorn, the Python module for Unit is written in C for performance. Unit doesn't call "python command" to start applications. It embeds interpretor and uses [Python/C API](https://docs.python.org/3/c-api/index.html) instead. I'm sure there are should be other ways how to use datadog tracing, but I'm not familiar with it. I recommend to review its documentation for other possible usage examples.

**Comment by gxpd-francisco** [comment]
Thank you for the clarification @VBart. I think it would be useful to mention this in the docs so that other user don't get confused like me. 
And you're right there are more ways to add the datadog tracer, but I have to modify the code a little bit. Any way, a big thank your for explaining this.

**Comment by i4ki** [comment]
Hi @gxpd-francisco 

I did a look in the ddtrace-run python script and it seems the only thing he does is modify the PYTHONPATH environment variable. Maybe you can make it work that way.

https://github.com/nginx/unit/issues/447#issuecomment-667158231

**Comment by artemkonev** [comment]
@gxpd-francisco 
I'll see whether the docs should be updated to clarify this in more detail.
