### ISSUE TITLE
Upload problem if file size > 15 kB

### ISSUE THREAD

**Issue by userVF** [nginx/unit#448]
Hi guys!
There is problem with file upload to PHP Unit application(using Nginx as web server) when file size is more than ~15 kB. 
For example, attempt to upload ~39 kB causes an error:
```
...
2020/07/29 21:43:06.573 [debug] 231#238 *41 h1p request body read 39063 te:0
2020/07/29 21:43:06.573 [debug] 231#238 posix_memalign(16, 16592): 7F42800154D0
2020/07/29 21:43:06.573 [error] 231#238 *41 mkstemp() failed (2: No such file or directory)
2020/07/29 21:43:06.573 [debug] 231#238 *41 http request error: 500
...
```
While uploading less than ~15kB works properly.

### Relevant info:
OS version: CentOS 8.1.1911 x86_64
Nginx version: 1.18.0 (compiled from source)
Unit version: 1.18.0 (compiled from source)
PHP version: 7.4.5

##### HTTP request
```
Request URL: http://site.loc/api/upload
Request method: POST
Status code: 500
Version: HTTP/1.1
...
Content-Type: multipart/form-data; boundary=---------------------------88544995712297368021178556863
Content-Length: 39067
...
```
##### http.conf
```
server {
    listen 80;
    server_name site.loc;    
    location / {        
        proxy_pass http://127.0.0.1:8302;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```
#### unit.conf.json
```
{  
    "listeners": {
        "127.0.0.1:8302": {
            "pass": "applications/site"
        }
    },
    "applications": {
        "site": {
            "type":"php",
            "root":"/home/www/site.loc/public",
            "script": "index.php"
        }
    }
}
```
##### php.ini
```
memory_limit = 128M
post_max_size = 8M
upload_max_filesize = 2M
```

Could you advise what to do?

**Comment by VBart** [comment]
How did you install Unit? It seems the temp files path hasn't been set. As a result, Unit attempts to create temporary files inside its working directory.

You should use [`--tmp=/tmp`](https://unit.nginx.org/installation/#configuring-sources) ./configure option to specify path for temporary files.
Or you can overwrite it in runtime via [`unitd --tmp /tmp`](https://unit.nginx.org/installation/#startup)

**Comment by userVF** [comment]
Hi Valentin.
Yes, I didn't set this parameter during compiling, due the default value is provided.
However run Unit with `--tmp /tmp` solved the problem.
Thank for help!
