### ISSUE TITLE
need help: server_protocol

### ISSUE THREAD

**Issue by panda-lab** [nginx/unit#454]
I found my nginx log more http 400 and the `$server_protocol` is space in the access.log

use command can reproduce
 
```
echo 'GET / HTTP2.0' | nc 127.0.0.1 80
```

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
