### ISSUE TITLE
Complete implementation of "try_files"-style fallback

### ISSUE THREAD

**Issue by kohenkatz** [nginx/unit#465]
v1.16.0 included the ability to include a `fallback` parameter for static files which would be used if the file did not exist. As of now, it can fall back to another directory and/or to another application in the unit configuration.

This is described in #392 (and #400) as being equivalent to the nginx `try_files` directive.

However, there is one very important case that is missing from `fallback` but can be handled by `try_files`: fallback to a static page.

Here are two examples that illustrate the use of this feature, and what I would expect the config to look like:

- A simple static website that includes a 404 error page.

   ```
   "action": {
   	"share": "/www/",
   		"fallback": {
   			"share": "/www/404.html"
   		}
   	}
   }
   ```

- A Vue.js, React.js, or similar "Single-Page Application" that uses HTML5 History routing.

   ```
   "action": {
   	"share": "/www/",
   		"fallback": {
   			"share": "/www/index.html"
   		}
   	}
   }
   ```

---

As I see it, there are two ways this could be implemented:

1. As in the configuration examples above, the same `share` configuration that points to a file name instead of a directory.
2. Adding a new route action type, maybe `file` that explicitly tells Unit that it is using a single static file to respond to all requests.

   ```
   "action": {
   	"share": "/www/",
   		"fallback": {
   			"file": "/www/index.html"
   		}
   	}
   }
   ```

**Comment by sycured** [comment]
Any ETA on this issue.
It's essential for serving SPA using Nginx Unit
@kohenkatz have you an alternative without using vercel/serve or nginx (full) ?

**Comment by kohenkatz** [comment]
@sycured I do not have an alternative within Unit, so I'm not using it.

**Comment by tobiasge** [comment]
For a python app I'm using this work around:
```
    "routes": [
        ...
        {
            "action": {
                "share": "/opt/app/web",
                "fallback": {
                  "pass": "applications/fallback"
                }
            }
        }
    ],

    "applications": {
        ...
        "fallback": {
          "type": "python 3",
          "path": "/opt/app/fb/",
          "module": "fallback.wsgi"
        }
    },
```

Python file (/opt/app/fb/fallback/wsgi.py):
```
def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    with open("/opt/app/web/index.html", "rb") as index:
        return index.read()
```

**Comment by VBart** [comment]
The relevant patches currently on review. This can be included in the next version (expected to be released in October-November).

**Comment by artemkonev** [comment]
@kohenkatz hi, take a look at the latest release: https://unit.nginx.org/configuration/#static-files
it accommodates for individual files

**Comment by kohenkatz** [comment]
@artemkonev That looks great, I'll have to test it out.
