### ISSUE TITLE
Build error on upcoming Fedora 33

### ISSUE THREAD

**Issue by remicollet** [nginx/unit#467]
```
src/nxt_http_route.c:854:28: error: 'name.start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  854 |             c = name->start[i];
      |                            ^
src/nxt_http_route.c:853:9: error: 'name.length' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  853 |         for (i = 0; i < name->length; i++) {
      |         ^

```

**Comment by remicollet** [comment]
FYI, this is related to https://fedoraproject.org/wiki/LTOByDefault

So, workaround:
`%define _lto_cflags %{nil}`

**Comment by VBart** [comment]
Could you tell please all the build flags and compiler version? I can't reproduce this issue on my Gentoo system with clang 9.0.1 and gcc 10.1.0 with just -flto flag set.

**Comment by VBart** [comment]
Ok.. it reproduced it with `gcc 10.1.0` and `-O2 -flto` flags set.

**Comment by VBart** [comment]
This warning is definitely false. You can just disable it with `-Wno-maybe-uninitialized`.
