### ISSUE TITLE
analog of nginx alias directive

### ISSUE THREAD

**Issue by temoto** [nginx/unit#468]
First, thanks for Unit, looks very promising.

Looking for something like `location /static/ { alias /app/static_root/; }`
Is it possible?

```
% ls /app/static_root
img.png

    {"routes": 
	{"match": {"uri": "/static/*"}, "action": {"share": "/app/static_root/"}},

[debug] 452#658 *14 open("/app/static_root//static/img.png", 0x800, 0x0): -1 err:2
```

**Comment by VBart** [comment]
It's not possible yet, but currently we're planning to introduce some kind of rewriting rules, that will solve this.

**Comment by lcrilly** [comment]
This will be addressed by https://github.com/nginx/unit/issues/732
