### ISSUE TITLE
Unit deployment options and benchmarking

### ISSUE THREAD

**Issue by dakshinai** [nginx/unit#475]
Hi,

Unit is launched baremetal per node or VM or container. Specifically with containers, all of its services can run from a single container hosting apps that Unit needs to support as well, but we do not have support for Unit to proxy multiple containers or pods. Can we reconfirm this?

Also, is there a way to benchmark the Unit router process for connection rate, throughput or latency. Has this been attempted before?

Thanks,
Dakshina

**Comment by dakshinai** [comment]
@mar0x  Could you help us with any inputs here?

**Comment by mar0x** [comment]
@dakshinai Could you please describe the 1st paragraph with more details?

There are a lots of benchmarking tools and infinite number of possible configurations. It is hard to provide an absolute numbers for connection rate, throughput, latency.

**Comment by dakshinai** [comment]
On benchmarking we would like to know if Unit has some proven benchmark numbers or tools that have been used. We are interested in learning how applications perform standalone vs behind Unit.

If we have to support applications running from containers, should Unit be deployed in the same container as the application?

If so, if I have N container instances running thier own Unit instance + apps, can we control how traffic is redirected (proxied) to the containers. Do we rely on NGINX?

**Comment by mar0x** [comment]
> If we have to support applications running from containers, should Unit be deployed in the same container as the application?
Yes.

> If so, if I have N container instances running thier own Unit instance + apps, can we control how traffic is redirected (proxied) to the containers. Do we rely on NGINX?
Yes. NGINX is a good choice for balancing.

**Comment by dakshinai** [comment]
Thanks Max, any inputs on benchmarking, if the team/community has done before?

**Comment by VBart** [comment]
> Thanks Max, any inputs on benchmarking, if the team/community has done before?

You can look this one:
https://itnext.io/performance-comparison-between-nginx-unit-and-uwsgi-python3-4511fc172a4c

**Comment by dakshinai** [comment]
Thank you.

**Comment by tippexs** [comment]
@dakshinai great questions! I will close this issue for now but please reach out if you have any more questions in the future. More than happy to answer them.
