### ISSUE TITLE
Enhancements to variables, and PHP $_SERVER 

### ISSUE THREAD

**Issue by natesymer** [nginx/unit#480]
# Problem

Something I often use with Nginx is the ability to set custom response headers to either hardcoded or dynamic values (i.e. variables and variable maps). I also need to set the $_SERVER variables for a PHP application, which I haven't seen how to accomplish with nginx unit alone. I see these concepts translating well to Unit.

For example, in Nginx I do do something like this in order to have my WordPress app run correctly behind a load balancer:

	# Since we might be behind a proxy, determine
	# the IP sending the current request.
	map $http_x_forwarded_for $wp_remote_addr {
		default $http_x_forwarded_for;
		"" $remote_addr;
	}

I take this value and then use it in a location block (to set $_SERVER["REMOTE_ADDR"]):

     fastcgi_param REMOTE_ADDR	$wp_remote_addr;

Another thing I do is manipulate headers (including Server):

     more_set_headers 'Server: ScriptKiddieKiller/2.0';

I also need to ignore some headers generated by the web app (in a location block):

    fastcgi_hide_header X-Generator;

# Solutions

I think some of these things could be accomplished in a route:

    {
        "response_headers": {
             "Server": "ScriptKiddieKiller/2.0",
             "X-Generator": null
         }
    }

Where setting a header to "null" hides it (as opposed to setting it to "", which would set the header to the empty string). These values would be applied AFTER application code ran, so as to override the application.

Variables could be defined on a per-app basis, but it would also make sense to have variables on many different levels of the config (with precedence rules):

    {
        "type": "php",
        "variables": {
            "foo": "bar",
            "asdf": ["variable_name", {
                 "one_value_of_variable_name": "value_of_asdf",
                 "another_value_of_variable_name": "another_value_of_asdf",
             }, "optional_default_value"]
         }
    }

The variable "asdf" is assigned conditionally using pattern matching - much like maps in nginx.

Finally, $_SERVER vars could be provided inside PHP apps:

    {
        "type": "php",
        "variables": {
            "wp_remote_addr": ["http_x_forwarded_for", {
                 "": "{remote_addr}",
             }, "{http_x_forwarded_for}"]
         },
        "fastcgi": {
            "parameters": {
                "REMOTE_ADDR": "{wp_remote_addr}"
            }
        }
    }

**Comment by VBart** [comment]
Why do you prefer to override fastcgi_param with a custom "map" directive instead of using [ngx_http_realip_module](http://nginx.org/en/docs/http/ngx_http_realip_module.html)?

**Comment by JanMikes** [comment]
Hi, i am not sure if it is exactly the same situation or should i open new issue, so i try to start here.

Our use case is that we want to hide some headers in response completely. 

Something we could accomplish with this module https://www.nginx.com/resources/wiki/modules/headers_more/:
```
more_clear_headers 'MyHeader';
```

**Comment by lcrilly** [comment]
Controlling response headers is being tracked in https://github.com/nginx/unit/issues/313

**Comment by tippexs** [comment]
This can be closed as support for managing response headers has been released.
