### ISSUE TITLE
Debian 11 ""Bullseye" base image support in Docker

### ISSUE THREAD

**Issue by DJviolin** [nginx/unit#485]
Because all of the Docker images based on Debian 10 "Buster", PHP 7.4 is unlikely to be supported in the near future:
https://github.com/nginx/unit/issues/402

There is a custom maintained repository regarding this case:
https://hub.docker.com/r/piotrpazola/nginx-unit

Please provide official binaries built for Debian 11 "Bullseye" and also create a Docker image targeting "debian:bullseye-slim".

Thank You!

**Comment by piotrpazola** [comment]
@DJviolin I've just delivered sources of the build: https://github.com/piotrpazola/nginx-unit-1.20.0-php7.4-pdo-mysql - It can be also useful, especially for other custom builds.

**Comment by DJviolin** [comment]
@piotrpazola Thank You! It really useful!

**Comment by thresheek** [comment]
I think a better approach would be not to rely on Debian 11, but to base our dockers off official images ones, which will help getting latest versions faster.  We're working on something like that.

**Comment by thresheek** [comment]
Hi @DJviolin @piotrpazola,

We've decided to indeed not to chase Bullseye release but provide a way to use newer language runtimes without being tied to Debian releases.  Now, we don't build and publish PHP 7.4 images, but 8.0 instead;  you can, however easily build those with the following commands:
```
$ git clone https://github.com/nginx/unit
$ cd unit
$ git checkout 1.22.0
$ cd pkg/docker/
$ make build-php7.4 VERSION_php=7.4
```
As a result you will have a local docker image under the name of `unit:1.22.0-php7.4` which you can use for your deployments and/or push to your local registries.

As the images are based on official Docker images for the runtimes, you can use the same tricks installing the extensions.

**Comment by wardance-ferret** [comment]
@thresheek Just to note, for others who may be following this thread historically, I've followed the steps you shared in 2021 to get the PHP 7.4 language runtime.  However, the following have no installation candidates via `apt install`:
'php{7.4}-cli'
'php{7.4}-mbstring'
'php{7.4}-gd'
'php{7.4}-xml'
'php{7.4}-zip'
'php{7.4}-curl'
Presumably this is where I would need to use tricks to install extensions.  Or bite the bullet and update a legacy app for PHP 8.0.

**Comment by thresheek** [comment]
Hello @wardance-ferret I think that happens because Debian `bookworm` on which current images are based does not have PHP 7.4, as opposed to `bullseye` used previously.
