### ISSUE TITLE
run c/c++ libraries in Unit module

### ISSUE THREAD

**Issue by RimeOCRLIB** [nginx/unit#491]
Добрый день.

Для потокового сервиса OCR нам нужно связать около 100 ARM компьютеров и мобильных устройств по TCP.
Каким образом можно запустить динамические библиотеки C ++ OCR, DJVU и ZIP на NGINX Unit ?
Можно ли для этого использовать уже написанные модули NGINX?
например
nginx-c-function Это модуль NGINX, который позволяет связать ваше приложение .so (c / c ++)

https://github.com/Taymindis/nginx-c-function
https://www.nginx.com/resources/wiki/modules/

Мы запустили пробное выполнение с++ библиотек под сокет-сервером Питона подключенного к Unit. 
Однако поскольку Unit ориентирован на оптимизацию загрузки ресурсов и уже написан на С, 
то оптимальным выглядит решение которое позволит подключать библиотеки С к Unit.

Будем очень признательны за любую помощь.

Александр Строганов
Открытая Библиотека Буддийских Текстов
www.buddism.ru/ocrlib

Good day.

For huge OCR service we need link about 100 arm single board computer by TCP.
How does it possible to run OCR, DJVU and ZIP dynamic c++ libraries on NGINX Unit??
Does it possible to use NGINX module  for that?
for example
nginx-c-function 	It is a NGINX module that allow you to link your .so(c/c++) application

https://github.com/Taymindis/nginx-c-function
https://www.nginx.com/resources/wiki/modules/

Will be  really appreciated for any help.

Alexander Stroganov
Open Source Buddhism Library
www.buddism.ru/ocrlib

**Comment by VBart** [comment]
Если хочется именно на Си, то на нем тоже можно писать приложения под Unit с помощью libunit.
Пример такого приложения есть в исходниках: https://hg.nginx.org/unit/file/tip/src/test/nxt_unit_app_test.c

Интерфейс кратко описан в nxt_unit.h: https://hg.nginx.org/unit/file/tip/src/nxt_unit.h

Других способов пока не предусмотрено. Модули от nginx не подходят, т.к. Unit написан практически с нуля, имеет иную архитектуру и соответственно другой API, нежели nginx.

**Comment by RimeOCRLIB** [comment]
Добрый день. 
Благодарю за обстоятельный ответ и пример использования с++ кода в Unit.

Каким образом можно получить из С доступ к параметрам и заголовкам HTTP запроса?
Например как получить в С модуле данные HTTP формы пересылки файла?

Насколько можно понять эти сведения есть в структуре nxt_unit_request_info_t ? 
Часть ответов удалось извлечь из обработчика модуля для Phython
http://hg.nginx.org/unit/rev/29efab062b4e
Есть ли какие либо примеры извлечения параметров запроса?

Мы планируем использовать NGINX Unit в пользовательских приложениях для минимальных систем, поэтому необходимо работать с HTTP запросом на С

С уважением 
Александр

**Comment by mar0x** [comment]
Александр,

Библиотека находится в разработке и активно меняется. Валентин привёл ссылку на [самый обстоятельный пример](https://github.com/nginx/unit/blob/master/src/test/nxt_unit_app_test.c), существующий в данный момент. В нём есть обращение ко всем данным запроса, заголовкам и телу запроса, пример многопоточной обработки сообщений.

Вот обстоятельная инструкция по сборке и запуску примера:
```
$ ./configure --tests --debug --modules=build --state=build
$ make all tests
$ ./build/unitd
$ cat <<EOF > unit_app_test.conf
{
  "applications": {
    "unit_app_test": {
      "type": "external",
      "executable": "./build/unit_app_test",
      "arguments": [ "-t", "2" ]
    },
  },

  "listeners": {
    "*:8400": {
      "pass": "applications/unit_app_test"
    }
  }
}
EOF
$ curl -d @unit_app_test.conf -X PUT --unix-socket control.unit.sock http://localhost/config
$ curl 'http://127.0.0.1:8400/the_test?a=1&b=test'
```

Интерфейс библиотеки предоставляет доступ к заголовкам, как к массиву структур, индексирование или поиск по имени несложно написать самому в том объёме, в котором он нужен для решения Вашей задачи.

[Доступ к заголовкам](https://github.com/nginx/unit/blob/3837d28f9b7c5d0840d2e4b26f4867b66838d31b/src/test/nxt_unit_app_test.c#L249) осуществляется через массив `fields` из структуры `nxt_unit_request_t`, которая содержится в  как поле `request` в структуре `nxt_unit_request_info_t`, указатель на которую передаётся в обработчик запроса.

Параметры `GET` запроса можно получить из строки [`query`](https://github.com/nginx/unit/blob/3837d28f9b7c5d0840d2e4b26f4867b66838d31b/src/test/nxt_unit_app_test.c#L241), параметры `POST` запроса из [тела запроса](https://github.com/nginx/unit/blob/3837d28f9b7c5d0840d2e4b26f4867b66838d31b/src/test/nxt_unit_app_test.c#L262). В обоих случаях, строку надо будет [раскодировать](https://stackoverflow.com/questions/154536/encode-decode-urls-in-c). Готовых примеров извлечения параметров запроса на C у нас нет, т.к. они реализованы для разных языков по-разному и не нами.

Да, интерфейс библиотеки достаточно низкоуровневый и C++'ный сахар там отсутствует. Дело в том, что структура запроса расположена в разделяемой памяти и такое "неудобное" обращение к разным данным продиктовано именно требованием к "перемещаемости" структуры. Для конкретной прикладной задачи, обычно, нужно фиксированное и ограниченное кол-во заголовков и параметров запроса.

Попробуйте начать использовать тестовое приложение, просто выбрасывая ненужные фрагменты. Появятся вопросы - задавайте.

--
Max

**Comment by RimeOCRLIB** [comment]
Добрый день.
Очень благодарен Вам за объяснения и пример. 
С параметрами запроса разбираюсь.

При тестировании примера  https://hg.nginx.org/unit/file/tip/src/test/nxt_unit_app_test.c
возник следующий вопрос:
В каком именно месте отработчика запроса необходимо выполнять «тяжелые» пользовательские функции?
По смыслу кода ответ модуля формируется в функции
`static void greeting_app_request_handler(nxt_unit_request_info_t *req) `
и отправляется как ответ модуля вызовом функции
`nxt_unit_buf_send(buf);`
однако при каждом запросе браузера функция greeting_app_request_handler выполняется два раза. 
Это можно проверить поставив вывод в лог файл из функции greeting_app_request_handler
```
    static int dll_data=1;
    dll_data++;
    rc = nxt_unit_buf_send(buf);
    nxt_unit_debug(NULL, "C worker send buffer. dll_data %d ", dll_data);

```
В логе на каждый вызов браузера появляется два ответа, и счетчик показывает два приращения.
Первый ответ функции greeting_app_request_handler отправляется браузеру, второй виден только в логе.
От типа браузера этот двойной ответ не зависит.

Функция greeting_app_request_handler установлена как 
`
init.callbacks.request_handler = greeting_app_request_handler;
`
и согласно описанию в заголовке  https://hg.nginx.org/unit/file/tip/src/nxt_unit.h является 
callback функцией ответа модуля.
```
/*
     * Process request. Unlike all other callback, this callback
     * need to be defined by application.
     */
    void     (*request_handler)(nxt_unit_request_info_t *req);
```
Каким образом можно обеспечить однократный вызов функции - отработчика запроса?



Еще раз выражаю Вам глубокую благодарность за помощь и замечательный open source сервер.
Александр

**Comment by VBart** [comment]
@RimeOCRLIB Для каждого запроса функция вызывается единожды. Вероятно вы просто наблюдате два запроса от браузера: запрос страницы и запрос пиктограммы (`/favicon.ico`) для отображения во вкладке.

В этом не сложно убедиться, если добавить вывод также URI запроса:
```c
nxt_unit_req_debug(req, "request uri: %*s", r->target_length, (char *) nxt_unit_sptr_get(&r->target));
```

**Comment by RimeOCRLIB** [comment]
@VBart  Чудесно. Благодарю за разъяснение.
Добавил в конфигурацию отработку статических файлов. 
```
{
  "applications": {
    "unit_app_test": {
      "type": "external",
      "executable": "./build/unit_app_test",
      "arguments": [ "-t", "3" ]
    },
  },

  "listeners": {
    "127.0.0.1:8080": {
      "pass": "routes"
    }
  },
  "routes": [
    {
      "match": {
        "uri": [
          "*.esp",
           "/"
        ]
      },
        "action": {
	    "pass": "applications/unit_app_test"
      }
    },
    {
      "action": {
        "share": "/www"
      }
    }
  ]
}
```
Для разработки практических приложений планируем добавить возможность компиляции
шаблонов в этом модуле. Такие шаблоны могут содержать HTML и С код и компилироваться в динамически подключаемые библиотеки.  
Такой подход реализован в сервере Appweb и ESP
Компиляция кода приложений позволяет исключить интерпретатор и использовать байт-код  С на основе динамической компиляции.
HTML шаблоны позволяют включать код С в таком же виде как например Python/bottle
```
<@ header @>
<h1>Hello world</h1>
<% 
 char cur_time[128]; 
  time_t      t;
  struct tm*  ptm; 
  t = time(NULL);
  ptm = localtime(&t);
  strftime(cur_time, 128, "%d-%b-%Y %H:%M:%S", ptm);
  printf("Current date and time: %s\n", cur_time);
 %>
<@ footer @>
```
