### ISSUE TITLE
Is Nginx OSS required/recommended in front of Unit when facing the internet?

### ISSUE THREAD

**Issue by sureshjoshi** [nginx/unit#492]
Hello, sorry if this question has been answered already. I've read through the docs and some of the existing Github issues, but I haven't found a "crisp" answer to this question - especially as some of the blog posts and examples I've read through are from 1-2 years ago.

I just recently discovered Unit, and it looks like a fantastic solution for some of my internal polyglot microservices to make maintainability a bit easier. 

However, I wasn't clear if it was recommended to be used in-place of Nginx OSS in new deployments. It has reverse proxying, SSL, static file serving - so it seems to cover my use cases, but am I missing something here? Are there any concerns I should have about making Unit directly face the internet?

**Comment by VBart** [comment]
The only concern here is that you may lack some functionality in Unit, that you may want to have. Lots of things are still in our TODO list, like SNI, sessions, tickets, ciphers configuration in TLS, custom error pages, rewrite rules, extended load-balancing, health checks... etc.

If you are fine with the current feature set, then I see no reasons why you should add another proxy layer.

**Comment by sureshjoshi** [comment]
Fantastic, thanks for the quick response!

In some of my simpler configurations (e.g. in the internal VPN), it works great in testing so far - once it's up and running, it's really seamless to operate.

I still need to get a better handle on some of the process management and application restarts - but I think that's more about experimenting with static vs dynamic workers/processes.
