### ISSUE TITLE
Java module broken after update

### ISSUE THREAD

**Issue by smtalk** [nginx/unit#493]
Simple yum update broke java module in unit. Is there a reason libjvm isn't statically compiled in to prevent issues like this?

Situation before:
[root@server ~]# ldd /usr/lib/unit/modules_backup/java1.8.0.unit.so 
	linux-vdso.so.1 (0x00007fffc1b55000)
	**libjvm.so => not found**
	libc.so.6 => /lib64/libc.so.6 (0x00007facb7b6b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facb8142000)

Situation after:
[root@server ~]# ldd /usr/lib/unit/modules/java1.8.0.unit.so 
	linux-vdso.so.1 (0x00007ffe6ccfe000)
	**libjvm.so => /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el8_2.x86_64/jre/lib/amd64/server/libjvm.so (0x00007f7616338000)**
	libc.so.6 => /lib64/libc.so.6 (0x00007f7615f76000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7615be1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f761585f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f761565b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f761543b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f76175ba000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7615223000)

Thank you!

**Comment by mar0x** [comment]
Hello, @smtalk 

Could you please provide more information about your installation: at least distributive used and how Unit was installed.
libjvm is linked dynamically, because it is dynamic library.

Thank you!

**Comment by smtalk** [comment]
@mar0x - it nginx unit compiled from the source. openjdk-java was installed from yum repos (CentOS8). Customer simply ran "yum update", and reported to us that nginx unit doesn't work there.

We could change the way we auto-install nginx-unit to DirectAdmin boxes (it's still in "alpha" stage), but.. I don't think it should work this way?

The issue - /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el8_2.x86_64/jre/lib/amd64/server is not in /etc/ld.co.conf, so, ldconfig has no effect (it doesn't re-assign that new lib there).

If we add /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el8_2.x86_64/jre/lib/amd64/server to ld.co.conf - it would have worked, but it sounds too hacky to me.

Please let me know if you need more information there.

**Comment by mar0x** [comment]
@smtalk I completely agree, minor jre updates should not require Unit re-build. To achieve this, please configure Java module same way, as Unit [packaging script](https://github.com/nginx/unit/blob/3837d28f9b7c5d0840d2e4b26f4867b66838d31b/pkg/rpm/Makefile.jsc8#L11):
```
./configure java --module=java8 --home=/usr/lib/jvm/java-1.8.0 --lib-path=/usr/lib/jvm/jre-1.8.0/lib/amd64
```

Please let me know whether it works or not for you.

**Comment by smtalk** [comment]
@mar0x that solution only works because of a /usr/lib/jvm/java-1.8.0 ->  /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el8_2.x86_64 symlink. We build java version dynamically, extracting home using:
echo $(dirname $(dirname $(readlink -f $(which javac))))

I don't think anything can print /usr/lib/jvm/java-1.8.0 ? Because even "alternatives --config java" prints full directory name.

I'll be waiting for any suggestions from your side. Worst case scenario - we'd need to simply check /usr/lib/jvm for every symlink possible and just to use them if javac endpoint matches the symlink-followed route.

Thank you!

**Comment by mar0x** [comment]
@smtalk I've already suggested you solution we use to package Unit.

I have no idea what can print `/usr/lib/jvm/java-1.8.0`. This is the question to RedHat/CentOS java package maintainers.

As far as I can see from our packaging scrips, there are 2 java versions supported and both configured with proper lib-path. Please explain, why you cannot specify `--lib-path` manually?

**Comment by smtalk** [comment]
@mar0x we specify it automatically, because it's a system with hundreds of thousands of servers (and automatic installation of unit is coming). We don't know what java versions they have installed (and where) without checking their "javac" bin. Your packaging has it hardcoded just for CentOS8 (entered manually). Anyway, we can simply limit "unit" to support hardcoded versions of java (1.8.0 + 11 on CentOS8), as it seems there are no other 'nice' solutions at this time. Thanks!

**Comment by mar0x** [comment]
@smtalk Yes, there is a limited number of java versions and it is even more limited of them are packaged for CentOS8, so it worth to hardcode the paths for known versions to avoid minor upgrade issue.

Let us know it you find more elegant solution.
