### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by doctryhc** [nginx/unit#494]

**Comment by mar0x** [comment]
@doctryhc This is very interesting!
Could you please describe how you currently use Webassembly, brief application sample would be a good start. This information will help us design and properly implement Webassembly support in Unit.

**Comment by doctryhc** [comment]
Hi mates! I use wasm modules experimentally with AWS Lambda faas. Nothing really special there. It runs on NodeJS enviroment and executes my wasm code compiled from Rust.
 
Another approach what actually I was asking you about is integration NGINX Unit with WebAssembly System Interface (WASI) and possibility to write standalone Rust(C, C++,Go and etc.) applications, compile them into WebAssembly, and then execute the application from WASI VM like Wasmtime or Lucet. In my opinion it could be a "killer feature" for NGINX Unit.

**Comment by moonming** [comment]
https://github.com/api7/wasm-nginx-module is a great try for Nginx and WASM

**Comment by ac000** [comment]
You can checkout an early preview of this work [here](https://github.com/ac000/unit/commits/wasm).

**Comment by ac000** [comment]
This has been merged https://github.com/nginx/unit/commit/52b334acd1a5678ee111d6db73dc02675c21a277, https://github.com/nginx/unit/commit/0c444397366aa07e23573a03e733a0552187eac4, https://github.com/nginx/unit/commit/6a211e2b7468a2524715b7f00a24aa460481bea7, https://github.com/nginx/unit/commit/2b4a7eedd0804f49ebbe53cfb046015fff6053e3, https://github.com/nginx/unit/commit/e99854afdf555678df5af149e53659c5b30a2f6d & https://github.com/nginx/unit/commit/47ff51009fa05d83bb67cd5db16829ab4c0081d7.
