### ISSUE TITLE
unit-python3.9 rpm/deb packages

### ISSUE THREAD

**Issue by akamoroz** [nginx/unit#500]
Since Unit 1.21.0 is compatible with Python 3.9 could you also add `unit-python3.9` rpm/deb packages to the repos?
Thanks!

**Comment by defanator** [comment]
@akamoroz long time no see! For the regular unit package repositories, we use language versions provided by the corresponding OS vendor. Is there any platform supported by unit with python 3.9 out of the box?

**Comment by akamoroz** [comment]
@defanator Yeah, a lot's happened since those days! 😄 

It seems Ubuntu 20.04 and 20.10 are already supported python3.9 and python3.9-dev packages through universe updates repo:
https://packages.ubuntu.com/search?suite=focal-updates&arch=any&searchon=names&keywords=python3.9

**Comment by thresheek** [comment]
python 3.9 packages are available in Unit repos for Debian 11, Ubuntu 21.04, Ubuntu 21.10, Fedora 33+;  upcoming Ubuntu 22.04 will also have 3.9 and 3.10.

That being said, I'm not sure it's worth making those avaliable for 20.04.

**Comment by akamoroz** [comment]
I've just moved to the Docker image with python3.9, so you can close the issue if you think deb package for Ubuntu 20.04 is not actual.
Thank you!

**Comment by VBart** [comment]
@thresheek there're still users who prefer to stay with LTS release. I don't see reasons why we should discriminate them and don't build a module for all available python versions on that release. EOL for 20.04 is far far away.

**Comment by jkugler** [comment]
As noted here, there are python38 and python39 packages on RHEL 8.x, vendor supported, out of the box: https://github.com/nginx/unit/issues/778

**Comment by tippexs** [comment]
This issue can be closed but it will lead to an internal discussion on what packages we are about to build or better documentation and scripting about how to build a language module for a given OS and language.

**Comment by jkugler** [comment]
Thank you. What is the best way to track when the Python 3.9 module is released?
