### ISSUE TITLE
Change Access Log Format

### ISSUE THREAD

**Issue by robjr** [nginx/unit#501]
Hi guys, 

I didn't find in the documentation a way to change the format of the access logs. I would like to change the order and add other fields (e.g. X-Forwarded-For, Host). How can I accomplish that? 

Thank you!

**Comment by VBart** [comment]
It's not possible yet. To add such feature we first need to implement more configuration variables.

**Comment by hongzhidao** [comment]
@robjr 
1. Could you show your full format expected?
2. With X-Forwarded-For, which usage do you prefer to? $http_x_forwared_for or $headers['X-Forwarded-For'].

**Comment by robjr** [comment]
Hi @hongzhidao, 

1. It would be great to have the output formatted as JSON or at least we could have it as an option. I'm looking for timestamp, remote address, host, request method, URI, status, user agent, referer, response size, request time,  xforwarded.
2. I prefer $headers['X-Forwarded-For'] as it looks more legible to me and it explicitly states that the value comes from the headers. 

Thank you for looking into this @hongzhidao , @VBart

**Comment by hongzhidao** [comment]
@robjr 
Just add that there is another format. ${headers.X-Forwarded-For}
Syntax: ${headers.arbitray-head-name}

**Comment by hongzhidao** [comment]
@robjr 
Here's a patch to support the custom log format.
https://gist.github.com/hongzhidao/adecca91feb7179fedadf339ea751894

Please note it's just my personal try, not unit official.

Unit configuration.
access_log: {
    "path": "access log file",
    "format": "$remote_addr - - [$local_time] \"$request_uri\" $status $bytes_sent \"$http_referer\" \"$http_user_agent\""
}

Now, these variables are avaiable.
$host, $uri, $method, $remote_addr, $local_time, $request_uri, 
$status, $bytes_sent, $http_referer, $http_user_agent,
${headers.header name}, ${args.arg name}, ${cookies.cookie name}

Feedbacks are welcome :)

**Comment by hongzhidao** [comment]
@robjr 
Here's a patch to support the custom log format.
https://gist.github.com/hongzhidao/adecca91feb7179fedadf339ea751894

Please note it's just my personal try, not unit official.

Unit configuration.
access_log: {
    "path": "access log file",
    "format": "$remote_addr - - [$local_time] \"$request_uri\" $status $bytes_sent \"$http_referer\" \"$http_user_agent\""
}

Now, these variables are avaiable.
$host, $uri, $method, $remote_addr, $local_time, $request_uri, 
$status, $bytes_sent, $http_referer, $http_user_agent,
${headers.header name}, ${args.arg name}, ${cookies.cookie name}

Feedbacks are welcome :)

**Comment by robjr** [comment]
Hi @hongzhidao ,

Awesome, I like this format ${headers.X-Forwarded-For}. 
I just tested the patch locally and it is working like a charm. If we can add two other variables to include the HTTP version and another for the request time it would be perfect. After enough testing, I'm wondering if we can include this in one of the next releases. Thank you very much!

**Comment by hongzhidao** [comment]
>  If we can add two other variables to include the HTTP version and another for the request time it would be perfect. 

1. The HTTP version can be implemented together with the above variables.
2. It seems the request time information is related to Unit `metric` information, it's a big feature.
https://github.com/nginx/unit/issues/384

> I'm wondering if we can include this in one of the next releases.

Actually, from my personal impression, all these NGINX open source projects are quite stable, even if development versions.
And they are active with feedback. I'll keep updating the patch in this ticket, you are welcome to merge it in the latest version.

**Comment by hongzhidao** [comment]
@robjr 

Updated.
https://gist.github.com/hongzhidao/adecca91feb7179fedadf339ea751894

Added two variables. $http_version and $request_time. Welcome to test.

**Comment by martin-hoger** [comment]
Thank you for including the $request_time variable. This is exactly what I was so much missing! Hope it is a part of the stable version soon.

**Comment by travisbell** [comment]
Oh man! This is great. I came here looking to see if Unit could support logging custom formats (ie. outputting JSON like how Nginx does with `escape=json`).

Any chance more options like this can find its way into stable?

**Comment by maastiff** [comment]
Hi!
When can we expect this to be merged in a stable version? 
Thanks for this great work!

**Comment by VBart** [comment]
A reworked version on this patch is currently on review.

**Comment by travisbell** [comment]
Hi @VBart, has there been any progress on these features making their way into stable?

**Comment by hongzhidao** [comment]
@travisbell 
This patch is on review, most likely be released in the next version 1.27.0.

**Comment by travisbell** [comment]
Very good news! Can't wait.

**Comment by buldezir** [comment]
hi, any updates?

@hongzhidao do u have mergable pull request? or branch that can be built manually?

**Comment by hongzhidao** [comment]
Hi, @buldezir 

Here's the patch.
https://gist.github.com/hongzhidao/29d60b95cbaf401b012de842a2ddda01

And we plan to release it in version 1.28, it might be months away.

**Comment by buldezir** [comment]
> Hi, @buldezir
> 
> Here's the patch. https://gist.github.com/hongzhidao/29d60b95cbaf401b012de842a2ddda01
> 
> And we plan to release it in version 1.28, it might be months away.

@hongzhidao sorry for stupid question, but how to apply it? 
i tried `git apply unit-log-format.patch` and `patch < unit-log-format.patch` in master branch

**Comment by buldezir** [comment]
i also tried to `hg clone https://hg.nginx.org/unit` and `hg import unit-log-format.patch`, its failing too.
... 
im confused, u posted diff from commit that is not public yet? so patch cannot be applied?

**Comment by hongzhidao** [comment]
I checked it. Since it's not a very new patch, and recently my mates published a few patches.
I have to say we usually maintain them without always rebasing the latest public commit.
I usually update it when it's ready to review and publish.

If you'd like to have a try with the feature, I will update it again with the latest commit tomorrow.

**Comment by buldezir** [comment]
yep it cant merge with latest version.

for now it works with that:
`hg update -C -r 8a068eaba1e7fdc51fda2feb4f13ad5ad1eaf5f3`
and then `hg import`

**Comment by buldezir** [comment]
@hongzhidao btw feature request - log format for unit log (nxt_log.c ?), need only 3 placeholder there - $time, $level, $message

---
also checked build with modified Dockerfile, everything works, just your "documentation" about variables is a little incorrect, but its easy to see what vars names are available in `nxt_http_variables.c`, example (to match with symfony monolog.formatter.json):

```
"access_log": {
    "path": "/dev/stdout",
    "format": "{\"message\":\"$request_line\",\"level\":200,\"level_name\":\"INFO\",\"channel\":\"access_log\",\"datetime\":\"$time_local\",\"extra\":{\"url\":\"$uri\",\"ip\":\"$remote_addr\",\"http_method\":\"$method\",\"server\":\"$host\",\"referrer\":\"$header_referer\",\"user_agent\":\"$header_user_agent\",\"status\":\"$status\"}}"
  }
```

**Comment by hongzhidao** [comment]
> yep it cant merge with latest version.
> 
> for now it works with that: `hg update -C -r 8a068eaba1e7fdc51fda2feb4f13ad5ad1eaf5f3` and then `hg import`

Updated, now the patch can be merged with the version of master.
https://gist.github.com/hongzhidao/50b7932e9d0c03aa807b610afaaf2fda

**Comment by hongzhidao** [comment]
>  just your "documentation" about variables is a little incorrect

Which "document" do you mean?

>  feature request - log format for unit log (nxt_log.c ?), need only 3 placeholder there - $time, $level, $message

Sorry that I can't get it. Could you tell me more about it?

**Comment by buldezir** [comment]
> > just your "documentation" about variables is a little incorrect
> 
> Which "document" do you mean?

https://github.com/nginx/unit/issues/501#issuecomment-737718850

> > feature request - log format for unit log (nxt_log.c ?), need only 3 placeholder there - $time, $level, $message
> 
> Sorry that I can't get it. Could you tell me more about it?

There is unit log in format `2022/06/01 17:27:33 [info] 12#12 unit 1.27.0 started`, there is no control over it. in docker it outputs to same stdout as everything else, so, for example, if i want to format logs as json (kibana ready) - i need to have formatting settings for it.
Maybe it is impossible to have in config, but maybe at least some control through `unitd` arguments?

**Comment by buldezir** [comment]
@hongzhidao your git patch file is corrupt (missing some data in the end), i fixed it with info from hg patch, and created diff as pull request: https://github.com/nginx/unit/pull/712
pull request as patch file: https://patch-diff.githubusercontent.com/raw/nginx/unit/pull/712.patch

**Comment by hongzhidao** [comment]
> Which "document" do you mean?

Yes, it's not updated, we have an official document. If the descriptions for the variables are reviewed, they will be released on the website. https://unit.nginx.org/

**Comment by hongzhidao** [comment]
Hi,

The feature of custom log format has been released. It will be in version 1.28.
In the future, we will consider supporting more rich features in the access log, such as multiple log format, JSON-type format, etc. 

Welcome to suggest, And I'll close this issue.

**Comment by malsatin** [comment]
Hi,

I have looked through the patch and wondered if it is possible to add all http variables from the standard Nginx (i.e. like described [in Grafana tutorial](https://grafana.com/docs/grafana-cloud/data-configuration/integrations/integration-reference/integration-nginx/)) to achieve the feature parity for monitoring?

Right now I see there are these variables
- dollar
- method
- request_uri
- uri
- host
- remote_addr
- time_local
- request_line
- status
- body_bytes_sent
- header_referer
- header_user_agent
- arg
- header
- cookie

For me lack of the `$request_time` is the biggest problem.

**Comment by hongzhidao** [comment]
Hi malsatin,

> For me lack of the $request_time is the biggest problem.

I'll share with your a separate patch next week if possible, thanks for your feedback.
Since we'll release version 1.28 soon, maybe in the next month, the feature will be 1.29 if possible.

**Comment by hongzhidao** [comment]
> I have looked through the patch and wondered if it is possible to add all http variables from the standard Nginx 

Not sure about all HTTP variables like nginx. Unit is a different OSS with nginx, but we'll discuss it internally.

**Comment by malsatin** [comment]
Thanks!
Presence of the `$request_time` would help a lot (just like an ability to write in JSON format, but this is a topic for another issue as I understand 😅).

**Comment by hongzhidao** [comment]
@malsatin 
We have opened a new issue #749  to track `$request_time`.
And I've uploaded a patch mentioned in #749, welcome to test. Thanks!

**Comment by hongzhidao** [comment]
Hi,
The patch of the $request_time variables is committed.
https://github.com/nginx/unit/commit/7aa6b0629897235684961dfb9aa16e226efa27e6

Thanks again.
