### ISSUE TITLE
Internal redirect from application

### ISSUE THREAD

**Issue by do11** [nginx/unit#503]
Is it possible in Unit to do internal redirect (which will be handled by Unit and not by a browser) to other location inside of Unit caused by application. For example, application could prepare missing files and redirect to them leaving file serving work (which is hard) to the Unit.

**Comment by VBart** [comment]
It's not possible yet. But it's in our plans to add such feature.

**Comment by lcrilly** [comment]
Duplicate of https://github.com/nginx/unit/issues/764
