### ISSUE TITLE
HTTP 424 Failed Dependency

### ISSUE THREAD

**Issue by robjr** [nginx/unit#507]
Hi guys,

I found a few requests failing for one particular client when the HTTP response is 424 Failed Dependency. After investigation, I found that the library that makes the requests is expecting the response message in this format:
`HTTPVersion StatusCode Reason
`
which seems to be in accordance with the RFC (https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html). 

It works fine if the application is served through Nginx instead of Nginx unit. Then I checked the network packets and I found that Nginx unit doesn't send the Reason.

Nginx message:
Hypertext Transfer Protocol
    HTTP/1.1 424 Failed Dependency\r\n

Nginx Unit message:
Hypertext Transfer Protocol
    HTTP/1.1 424\r\n

For HTTP 200, both send HTTP/1.1 200 _OK_. 

Can anyone help me take a look at this issue?

Thank you, guys!

**Comment by VBart** [comment]
Could you test if the patch below fixes the problem?

```diff
diff --git a/src/nxt_h1proto.c b/src/nxt_h1proto.c
--- a/src/nxt_h1proto.c
+++ b/src/nxt_h1proto.c
@@ -1252,7 +1252,7 @@ nxt_h1p_request_header_send(nxt_task_t *
 
     } else {
         p = nxt_sprintf(buf, buf + UNKNOWN_STATUS_LENGTH,
-                        "HTTP/1.1 %03d\r\n", n);
+                        "HTTP/1.1 %03d \r\n", n);
 
         unknown_status.length = p - buf;
         unknown_status.start = buf;
```

**Comment by robjr** [comment]
Hi @VBart,

Unfortunately, it didn't work. I noticed that it doesn't reach that line. 

However, I made the change here
https://github.com/nginx/unit/blob/fb80502513bf0140c5e595714967f75ea3e1e5d3/src/nxt_h1proto.c#L1160

From 
`nxt_string("HTTP/1.1 424\r\n"),` 
to
`nxt_string("HTTP/1.1 424 \r\n"),` or `nxt_string("HTTP/1.1 424 Failed Dependency\r\n"),`

and it works fine. Maybe we can add the space as an empty reason for all of those codes? 

Thank you!

**Comment by VBart** [comment]
> Maybe we can add the space as an empty reason for all of those codes?

Yeap, the space is needed on those lines also. Thanks for spotting that!

**Comment by robjr** [comment]
Hi @VBart, was that fix released?

**Comment by VBart** [comment]
> Hi @VBart, was that fix released?

Not yet. The upcoming release will be in a week or two.

**Comment by robjr** [comment]
> > Hi @VBart, was that fix released?
> 
> Not yet. The upcoming release will be in a week or two.

Perfect! Thank you, @VBart
