### ISSUE TITLE
Is there a roadmap or project board planned?

### ISSUE THREAD

**Issue by centminmod** [nginx/unit#51]
For Nginx Unit is their a planned development roadmap or project board planned ?

* https://help.github.com/articles/about-project-boards/
* https://medium.com/@dawsonbotsford/how-to-use-github-projects-aa15a8411b72

Would love to follow Nginx Unit's development while testing etc :)

**Comment by binnnliu** [comment]
![wechat image_20170926183838](https://user-images.githubusercontent.com/12108174/30856149-1078ec3c-a2ea-11e7-8cb2-77b69f086225.jpg)

**Comment by centminmod** [comment]
Cheers i know of general road map just looking for more specifics for features or improvements I'd look forward to.

i.e. @VBart mentioned 

* support for MERGE/PATCH is planned https://github.com/nginx/unit/issues/48#issuecomment-331681067
* improved module directory discovery without restarts https://github.com/nginx/unit/issues/46#issuecomment-331673851

**Comment by VBart** [comment]
Sorry, the detailed roadmap isn't publicly available.
