### ISSUE TITLE
Import error when using pypy-django-psycopg2

### ISSUE THREAD

**Issue by spranav97** [nginx/unit#518]
Using
Ubuntu 18.04LTS Server - ARM64
unit (1.21.0-1~bionic).
Python3.6 Language pack
Virtual environment of Pypy3.6 (7.3.2) - python version 3.6.9
Django 3.1
psycopg2 2.8.6
PostgreSQL 12

Unit is able to launch and run Django project perfectly when using pypy virtual environment and using sqlite3 as db. When using psycopg2 connector to use PostgreSQL with Django it is unable to launch. when reconfiguring it says

{
        "error": "Failed to apply new configuration."
}

error log shows

```
2021/01/01 19:01:57 [alert] 4339#4339 Python failed to import module "new.wsgi"
Traceback (most recent call last):
  File "/home/ubuntu/django-env/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 25, in <mo$
    import psycopg2 as Database
  File "/home/ubuntu/django-env/lib/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

the file '_psycopg.pypy36-pp73-linux-gnu.so' exists in the library and works since running 'python manage.py runserver' works without any issues.

**Comment by mar0x** [comment]
Hello,
Could you please share complete example of your app and config.

**Comment by spranav97** [comment]
> Hello,
> Could you please share complete example of your app and config.

unit_config.json
{
    "listeners": {
        "127.0.0.1:8000": {
            "pass": "applications/project"
        }
    },
    "applications": {
        "project": {
            "processes": {
                "max":2,
                "spare":1
            },
            "threads": 3,
            "type": "python 3.6",
            "path": "/home/ubuntu/websites/example.com/",
            "home": "/home/ubuntu/django-env/",
            "module": "se.asgi",
            "protocol": "asgi",
            "environment": {
                "DJANGO_SETTINGS_MODULE": "se.settings"
            }
        }
    }
}

i have tried with wsgi, python 3.7 language pack with pypy3.7 as well, it gives the same error. "home" points to pypy3.6 virtual-env named django-env. it has Django, pyscopg2 installed using pip. i also tried with pyscopg2-binary, it didn't work as well.

project settings.py - database section

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', 
        'NAME': 'project-db',
        'USER': 'project-user',
        'PASSWORD': 'some-password',
        'HOST': '/var/run/postgresql/',
        'PORT': '5432',
        'client_encoding': 'UTF8',
    }
}

i hope these configs suffice to alleviate the problem

**Comment by mar0x** [comment]
Does the `psycopg2` connector installed in same virtual environment (`/home/ubuntu/django-env/`)?

**Comment by spranav97** [comment]
> Does the `psycopg2` connector installed in same virtual environment (`/home/ubuntu/django-env/`)?

yes, all libraries were installed in the 'django-env' virtual-env. The django test server was able to run everything perfectly when the django-env was activated(being used).

**Comment by mar0x** [comment]
The thing is django test server and application runs in different environment. To double check, please issue following command and share the output: `find /home/ubuntu/django-env psycopg2`.

**Comment by spranav97** [comment]
> The thing is django test server and application runs in different environments. To double check, please issue following command and share the output: `find /home/ubuntu/django-env -name psycopg2`.

output is
/home/ubunut/django-env/site-packages/psycopg2

i also created symbolic link of folder 'site-packages' from /home/ubuntu/django-env to /home/ubuntu/django-env/lib/python3.6/. This was done because UNIT tries to search for libraries installed in env using pip in lib/python3.x/site-packages/ and lib64/python3.x/site-packages/.

**Comment by mar0x** [comment]
I would suggest you to create virtual environment with standard python3.6 tools (`python3.6 -m venv django-venv) because Unit module is linked against libpython and will use python interpreter, not pypy.

**Comment by spranav97** [comment]
> I would suggest you to create virtual environment with standard python3.6 tools (`python3.6 -m venv django-venv`) because Unit python module is linked against libpython and will use python interpreter, not pypy.

UNIT's python module works fine with pypy, I tried running it with sqlite3 instead of postgres and it worked just fine, I think it's just one file in psycopg2 lib that's creating problems it's a .so file.

**Comment by mar0x** [comment]
PyPy is binary incompatible with Python. I've created venv for both Python and PyPy and compared the _psycopg*.so files import - it is completely different.
Again, instead of creating symlinks you need to properly initialise virtual environment for Python:
```
python3.6 -m venv /home/ubuntu/django-env
source /home/ubuntu/django-env/bin/activate
pip3.6 install django psycopg2
```
Otherwise you may face any issue. To check your venv run django server using python3.6 `python3.6 manage.py runserver`.

**Comment by spranav97** [comment]
> PyPy is binary incompatible with Python. I've created venv for both Python and PyPy and compared the _psycopg*.so files import - it is completely different.
> Again, instead of creating symlinks you need to properly initialise virtual environment for Python:
> ```
> python3.6 -m venv /home/ubuntu/django-env
> source /home/ubuntu/django-env/bin/activate
> pip3.6 install django psycopg2
> ```
> Otherwise you may face any issue. To check your venv run django server using python3.6 `python3.6 manage.py runserver`.

Thanks for the clarification.
