### ISSUE TITLE
python3.9

### ISSUE THREAD

**Issue by stfenjobs** [nginx/unit#519]
I don't see Unit docker image for python 3.9 in Docker Hub. Is there a plan to release python 3.9 docker image?

**Comment by sureshjoshi** [comment]
For what it's worth, this is particularly painful for those of us who heavily leverage python 3.8/3.9's typing system upgrades. I would have to downgrade a lot of code for 3.7, so I'll be making my own docker container - but the official one would be fantastic!

**Comment by artemkonev** [comment]
Hello,
There's some good news coming your way soon, I hope: https://github.com/nginx/unit/issues/485#issuecomment-759436615

**Comment by thresheek** [comment]
Hi @stfenjobs @sureshjoshi.

Python 3.9 images are now available on Docker Hub and AWS ECR: http://unit.nginx.org/installation/#docker-images

**Comment by sureshjoshi** [comment]
@thresheek Of note: The nginx-unit python 3.7 installation was 37MB, the python 3.9 installation is 328MB!

It looks like all of the build/compilation code was pulled in as well, whereas it should just be the binaries/libs

![Screen Shot 2021-03-16 at 14 19 19](https://user-images.githubusercontent.com/3823045/111359997-9a629100-8662-11eb-873c-9a9164eccf75.png)

![Screen Shot 2021-03-16 at 14 19 36](https://user-images.githubusercontent.com/3823045/111360038-a51d2600-8662-11eb-8b83-d82bfc1981ab.png)

**Comment by VBart** [comment]
@sureshjoshi it's the size of original official Python 3.9 image: `docker pull python:3.9`

**Comment by sureshjoshi** [comment]
@VBart Yep, I noticed that, but, it looks like it's using 3.9, instead of 3.9-slim?

**Comment by VBart** [comment]
@sureshjoshi "slim" isn't recommended for general purpose:
> Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
