### ISSUE TITLE
Debug message logging

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#523]
Where could I see standart output prodused by server app.js throw **console.log('some message');**? Because I do not see piont 0 string in **/var/log/unit.log**
My app.js started whis
```javascript
#!/usr/bin/env /home/web/.nvm/versions/node/v14.15.4/bin/node
"use strict";

console.log('point 0');

Object.defineProperty(exports, "__esModule", { value: true });
exports.jwt = exports.config = exports.Router = void 0;
const { createServer, IncomingMessage, ServerResponse, } = require('unit-http');
require('http').ServerResponse = ServerResponse;
require('http').IncomingMessage = IncomingMessage;
...
```
Or should I use some other debug logging method?

**Comment by pilot87** [comment]
**upd:** I found that nodejs app could write to user's log file, but I feel thar it is not good way

**Comment by mar0x** [comment]
Unit redirects `stdout` to `/dev/null`, `stderr` to `unit.log` before starting an application. So, `console.warn()` and `console.errors()` should go to `unit.log`.

If you need original `console` stdout, you may create startup (shell) script which redirects stdout to desired file and starts your application:
```bash
#!/bin/bash
exec ./app.js >>stdout.log
```

If you don't care about `console` output, you may [create your own Console](https://nodejs.org/api/console.html#console_new_console_stdout_stderr_ignoreerrors) object and use it for logging:
```javascript
const fs = require('fs');

// Custom simple logger
const logger = new Console(fs.createWriteStream('./stdout.log'));
// use it like console
const count = 5;
logger.log('count: %d', count);
```

**Comment by pilot87** [comment]
Thank you for interesting details!
