### ISSUE TITLE
Is there a plan to make php 7.4 package available soon?

### ISSUE THREAD

**Issue by denishpatel** [nginx/unit#524]
Missing.  nginx/unit:1.21.0-php7.4 package on docker hub

**Comment by thresheek** [comment]
Hi @denishpatel,

We currently ship PHP 8.0 in the docker images for the latest release.

If you need an image based on PHP 7.4, you can build it yourself:

```
$ git clone https://github.com/nginx/unit
$ cd unit
$ git checkout 1.22.0
$ cd pkg/docker/
$ make build-php7.4 VERSION_php=7.4
```
As a result you will have a local docker image under the name of `unit:1.22.0-php7.4` which you can use for your deployments and/or push to your local registries.

**Comment by denishpatel** [comment]
thanks!

**Comment by denishpatel** [comment]
@thresheek  I need to build/install other php packages too.. how can i do that?

  php7.4-gd \
        php7.4-xml \
        php7.4-pgsql \

**Comment by thresheek** [comment]
Hi @denishpatel, check out https://hub.docker.com/_/php/ the section "PHP Core Extensions".  Instead of php:7.4-fpm as stated there you'd just use the unit image to start FROM.
