### ISSUE TITLE
Conditional UNIT spesefic structure (Node.js)

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#526]
For maintaining & testing process I want to use one codebase for UNIT and non-UNIT cases. But for many good reasons I do not wish to use separate projects/branches becouse only main **app.js** have a problems to be conditionaly UNIT compatible.
Rebase bouth react and express by product environment & current url is not a real problem, but nodejs do not let me to use **require('unit-http')** and **require('http')** conditionally.
Add ts changing abilitie to install.sh script is most real option in my case, but may be thear are some more eleganse and stable way community use?

**Comment by mar0x** [comment]
Hello,
You can detect environment and use `unit-http` only when your app is started by Unit.

```javascript
const http = function() {
  if (process.env.NXT_UNIT_INIT) {
    return require('unit-http');
  } else {
    return require('http');
  }
}();
```

**Comment by VBart** [comment]
After https://github.com/nginx/unit/commit/a0c083af208cd9f676bb56762b4e27a3174a773d Node.js apps can be run without modifying sources.
