### ISSUE TITLE
PHP 8.0 Install

### ISSUE THREAD

**Issue by yannickgranger** [nginx/unit#527]
Hi,

I launched ubuntu 20.04 LTS and after install of unit unit-dev and unit-php I found in log that the php module could not be found.
Also it is php 7.4

<pre>2021/02/13 13:05:47 [info] 9111#9111 discovery started
2021/02/13 13:05:47 [alert] 9111#9111 dlopen(&quot;/usr/lib/unit/modules/php.unit.so&quot;), failed: &quot;libphp7.so: cannot open shared object file: No such file or directory&quot;
2021/02/13 13:05:47 [info] 9110#9110 controller started
2021/02/13 13:05:47 [info] 9113#9113 router started
2021/02/13 13:05:47 [info] 9113#9113 OpenSSL 1.1.1f  31 Mar 2020, 1010106f
2021/02/13 13:05:47 [notice] 9110#9110 process 9111 exited with code 0
</pre>

How do you install php 8.0 ?

**Comment by VBart** [comment]
Our packages are built with the language versions available in the official distribution. For a custom version installed you have to build your own module. Here's some guide: https://unit.nginx.org/howto/modules/#packages-deb

**Comment by yannickgranger** [comment]
All right, i followed this procedure with success. Though, after I used apt to upgrade unit, Unit server did stop and I had a message "module php8.0 not found". (The one I built). And after I tried to uninstall all with apt. Everything seemed to be uninstalled (with --purge option), but the new installation did ask for the missing php8.0 module. Could you explain me which settings I should delete further ? Currently I'm not able to reproduce because It was a new server and I gave up by re-installing OS.

**Comment by VBart** [comment]
In order to upgrade the Unit with manually installed module you have to:
1. Uninstall the manually installed module with `dpkg -P` command
2. Upgrade the Unit to a newer version
3. Build a new module with the new version of Unit (using the same procedure)
4. Install the newly built module with `dpkg`

Of course, it's easier to write a script that will automate these steps on your system.
