### ISSUE TITLE
URL Rewrite

### ISSUE THREAD

**Issue by barmalej1** [nginx/unit#530]
Does Unit support URL rewrite? For example I have a Python application sitting at `https://www.website.com/aaa/bbb/ccc`. I would like to also be able to call it just by `https://www.website.com/ccc`. If I install Nginx in front of the application, I can use `proxy_pass` directive to achieve this functionality.

**Comment by lcrilly** [comment]
Planned as #732

**Comment by lcrilly** [comment]
Shipped with unit-1.30.0 (see https://github.com/nginx/unit/issues/732 )
