### ISSUE TITLE
Unit not respecting system encoding (US-ASCII vs. UTF-8) in Ruby

### ISSUE THREAD

**Issue by travisbell** [nginx/unit#531]
Hey guys,

I've come a cross a strange problem... even though my environment encodings are all set to `UTF-8`:

```
LC_ALL=C.UTF-8
LANG=en_US.UTF-8
```

It looks like however Ruby is compiled and/or started within Nginx Unit, it's ignoring those settings. As you can see below,  the `Encoding.default_external` is returning `US-ASCII` within a Unit environment. If I load my app up (in the same environment) with Puma, you can see it's obeying my system settings, and reporting `UTF-8`.

**Inside of Nginx Unit:**

```
$ Encoding.default_external
=> US-ASCII

$ file = File.read('test.yml')
$ file.encoding
=> #<Encoding:US-ASCII>
```

**Inside of Puma:**

```
$ Encoding.default_external
=> UTF-8

$ file = File.read('test.yml')
$ file.encoding
=> #<Encoding:UTF-8>
```

Any ideas as to why the compiled Ruby module for Nginx Unit is reading these files as `US-ASCII`?

Nginx Unit Version: 1.22.0
Ruby: 2.7.2

**Comment by VBart** [comment]
Please try the following patch:
```diff
diff --git a/src/ruby/nxt_ruby.c b/src/ruby/nxt_ruby.c
--- a/src/ruby/nxt_ruby.c
+++ b/src/ruby/nxt_ruby.c
@@ -12,6 +12,8 @@
 
 #include NXT_RUBY_MOUNTS_H
 
+#include <locale.h>
+
 
 #define NXT_RUBY_RACK_API_VERSION_MAJOR  1
 #define NXT_RUBY_RACK_API_VERSION_MINOR  3
@@ -200,6 +202,8 @@ nxt_ruby_start(nxt_task_t *task, nxt_pro
 
     nxt_ruby_threads = c->threads;
 
+    setlocale(LC_CTYPE, "");
+
     RUBY_INIT_STACK
     ruby_init();
     ruby_options(2, argv);
```

**Comment by travisbell** [comment]
Looks good @VBart! I don't see the encoding errors on my files anymore, and the `Encoding.default_external` is reporting UTF-8 like I expect.

Thanks!
