### ISSUE TITLE
can't seem to match uris for static files

### ISSUE THREAD

**Issue by TinyAtoms** [nginx/unit#533]
So I'm trying to set up a docker container, mount a folder to it and serve it (and a django app, but that's not the problem), but none of the rules match.
this is the dockerfile
```

## pull official base image
FROM nginx/unit:1.22.0-python3.9
EXPOSE 80
## set work directory
WORKDIR /app
# perms
RUN chown -R unit:unit /app 
COPY ./deployment/entrypoints/* /docker-entrypoint.d/ 
RUN chmod +x /docker-entrypoint.d/start.sh
```
(the ./deployment/entrypoints folder only has the config.json and a script that does an `ls -l /app`)
I'm running the container with this
```
 docker run --publish 80:80 \
# -v '/<some dir that has a statictest.txt in it>:/app/data' \
# -v '/<some dir that has a statictest.txt in it>/:/app/calibredir' \
# --name cw calibreweb:1.0
```
I can serve it just fine when the route is just an action without matching
```json
        {
            "action": {"share": "/app/data/"}
        },
```
or if i use only a wildcard
```json
        {
            "match": {"uri": "*"},
            "action": {"share": "/app/data/"}
        },
```
but those aren't ideal, because I also want to route traffic to a django app in the same container.
https://unit.nginx.org/howto/django/#django-wsgi is what i'm trying to do

this is the unit file (with just my attempts to serve static content, django stuff removed)
```json
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
    },
    "routes": [
        {
            "match": {"uri": "/download/*"},
            "action": {"share": "/app/data/"}
        },
        {
            "match": {"uri": "/download/"},
            "action": {"share": "/app/data/"}
        },
        {
            "match": {"uri": "/download"},
            "action": {"share": "/app/data/"}
        },
        {
            "match": {"uri": "download/*"},
            "action": {"share": "/app/data/"}
        },
        {
            "match": {"uri": "download/"},
            "action": {"share": "/app/data/"}
        },
        {
            "match": {"uri": "download"},
            "action": {"share": "/app/data/"}
        }
    ]
}
```
I've also tried this (this is only a snippet of a full config)
```json
        {
            "match" : {"uri" : ["!/download/*", "!/static/*"]},
            "action": {"pass": "applications/django"
            }
        },
        {
            "match": {"uri": "!/static/*"},
            "action": {"share": "/app/calibredir/"}
        },
        {
            "action": {"share": "/app/CalibreWebCompanion/static/"}
        },
```
I expect to be able to go to localhost/download/statictest.txt and to get it, but I only get 404s.
What am I doing wrong? 
EDIT: fixed typo

**Comment by VBart** [comment]
> I expect to be able to go to localhost/downloads/statictest.txt and to get it, but I only get 404s.

Note that `download` in your matching rules doesn't match `downloadS` in your request.

**Comment by TinyAtoms** [comment]
> > I expect to be able to go to localhost/downloads/statictest.txt and to get it, but I only get 404s.
> 
> Note that `download` in your matching rules doesn't match `downloadS` in your request.

Yeah, sorry, that was a typo in the post.
It (also) doesn't work for `/download/statictest.txt`

I'm using a script to check error codes when i'm trying out configs, and the typo isn't there.
```
curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/download/statictest.txt
curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/statictest.txt
```
.

**Comment by VBart** [comment]
@TinyAtoms Do you actually have `download` directory in your `/app/data/`?  Note that matching rules don't alter the request, they just filter requests, but the request URI and other parameters stay unmodified. In your case, Unit will try to open `/app/data/download/statictest.txt`.

**Comment by TinyAtoms** [comment]
OH. That was the issue. I thought it worked like `location <uri> { alias <folder> }` in nginx, that tried to look for * from /download/*  (so `/app/data/statictest.txt`), but instead it works like `location <uri> {root <folder>}`.
Thank you, the issue is resolved.

**Comment by VBart** [comment]
You're welcome.
