### ISSUE TITLE
PHP app with no native php-embed lib

### ISSUE THREAD

**Issue by defme** [nginx/unit#534]
Hi,

I built and run Unit on Openbsd which has no php-embed library in the packages base, and as far as I understand even its PHP port cannot be build with '--enable-embed' option (not sure).
So, my SAPIs list which Unit found during build is
php-config --php-sapis
apache2handler cli fpm phpdbg cgi
And i also set --lib-path=/usr/local/lib/php-7.3/ where dynamic lib for mod_php is
ls /usr/local/lib/php-7.3/
libphp7.so modules

Since Unit is working successfully, do I understand correctly that he uses one of the SAPIs he found? How to know which one exactly from the SAPIs list?

**Comment by VBart** [comment]
There's no way to use other SAPIs. Actually, `libphp7.so` is embed SAPI (without embed SAPI compiled you won't have this lib at all). It seems that `php-config --php-sapis` script provides incorrect information about presence of embed SAPI in your system.

**Comment by defme** [comment]
I got it, thanks much!

**Comment by defme** [comment]
closed

**Comment by VBart** [comment]
@defme Sorry, actually I was wrong with my first assumption. I looked carefully at the OpenBSD port and realized, that in fact it's not embed SAPI library, but the Apache module library. The fun thing here is that it seems provide the same interfaces as when PHP is compiled with embed SAPI.

Unit uses his own SAPI, that is written from scratch and compiled as the Unit language module, but it needs PHP library and building this library is forced by enabling embed SAPI. I didn't know that building Apache module also works fine.

**Comment by VBart** [comment]
Looks like the only drawback here is that to build PHP you need Apache as the dependency.

**Comment by defme** [comment]
I think so, because i cannot figure out how to build PHP with "--enable-embed" on Openbsd (it seems there is no such a support, but i didnt look deep at php port source tree). Its not an issue for me, because im using apache in system, but i will keep in mind that in future, as i moved php apps to Unit completely.
Thank you, for investigation.

**Comment by defme** [comment]
@VBart  "I didn't know that building Apache module also works fine."
Im not sure how fine it works globaly, but for my apps it works with no issues (at least for now).
Why i asked initial question about which lib exaclty Unit uses in its module, because of i have some warnings in Unit's log relative to PHP, and so i thought that its may be due to my libphp is third-party like, and may be it has lack of native lib parts or so.

Logs are
unitd:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'apr_pool_cleanup_null'
unitd:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_loaded_modules'
unitd:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_server_root'
unitd:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_unixd_config'

So just for you information.

**Comment by defme** [comment]
To be complete myself, this is how Unit's module was build

./configure php --lib-path=/usr/local/lib/php-7.3/
configuring PHP module
checking for PHP ... found
 + PHP SAPI: [apache2handler cli fpm phpdbg cgi]
checking for PHP version ...autotest:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'apr_pool_cleanup_null'
autotest:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_loaded_modules'
autotest:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_server_root'
autotest:/usr/local/lib/php-7.3/libphp7.so: undefined symbol 'ap_unixd_config'
 7.3.10
checking for PHP embed SAPI ... found
checking for PHP Zend Thread Safety ... not found
checking for PHP zend_signal_startup() ... found
 + PHP module: php.unit.so

**Comment by VBart** [comment]
@defme These warnings are produced by system linker and mention functions from Apache. This is because this library contains also Apache SAPI that Unit doesn't use. Unit has its own SAPI module, that is distributed with Unit sources and compiled into Unit language module.

**Comment by defme** [comment]
So, it looks OK :)
Thank you again.
