### ISSUE TITLE
Remove the need for unit-http in Node applications

### ISSUE THREAD

**Issue by ocanty** [nginx/unit#538]
Currently users of Node need to require a unit-http library in their applications, and replace the standard http and websocket modules with Unit's drop in replacement

      var http = require('unit-http');

We need to find a way of realistically avoiding this.

Only requiring `require('unit-http')` rather than assigning it to a var like `http` is good.

Completely removing the need to modify the source code is even better

This may not be possible, it needs to be investigated

**Comment by smtalk** [comment]
It's been reported https://github.com/nginx/unit/issues/413. As it's almost Q2 of 2021, and it's a big feature (if this would still be planned for 2021), I guess it really needs attention now :)

**Comment by VBart** [comment]
> Hi,
> 
> is there any progress re this feature? Army of directadmin resellers waiting to deploy nodejs )

It's ready and will be committed next day or two (then released with 1.24.0 till the end of the month).

**Comment by VBart** [comment]
Committed as https://github.com/nginx/unit/commit/a0c083af208cd9f676bb56762b4e27a3174a773d.

**Comment by smtalk** [comment]
@ocanty 
[root@development ~]# find /usr/lib/node_modules/ -name 'require_shim' -type d
[root@development ~]# 

# node --loader unit-http/require_shim.mjs --require unit-http/require_shim app.js
```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'unit-http/require_shim'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1225:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:467:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:70:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

# ls /usr/lib/node_modules/unit-http/require_shim.*
```
/usr/lib/node_modules/unit-http/require_shim.js
/usr/lib/node_modules/unit-http/require_shim.mjs
```

**Comment by smtalk** [comment]
@ocanty I'm testing it out, but it doesn't seem to spin a new process after reconfiguration?

```
# curl -X PUT -d '{ "type": "external", "processes": { "spare": 0 }, "working_directory": "/home/admin/domains/aaba.com/nodetest", "executable": "/usr/bin/node", "arguments": [ "--loader", "unit-http/require_shim.mjs", "--require", "unit-http/require_shim.js", "app.js" ] }' --unix-socket /var/run/unit/control.sock http://localhost/config/applications/aaba.com_NodeTest
{
	"success": "Reconfiguration done."
}

```

After this - process is not running. app.js is simply test/node/require_shim/unit_http/app.js. I've tried other numbers for processes - it failed with them.

**Comment by ocanty** [comment]
Hi @smtalk

This is expected behaviour part of the process scaling feature, see:

https://unit.nginx.org/configuration/#configuration-proc-mgmt-prcs

In the case of "spare": 0, you can launch a request at Unit and it will automatically start the application if a match is made
