### ISSUE TITLE
Testing demo app results in "error": "Failed to apply new configuration."

### ISSUE THREAD

**Issue by iolbr** [nginx/unit#542]
Log states: 
```
2021/04/14 17:06:30 [warn] 30793#30793 failed to start application "fastapi"
2021/04/14 17:06:30 [alert] 30793#30793 failed to apply new conf
2021/04/14 17:09:04 [info] 31342#31342 "fastapi" application started
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f188bf5ea80 (most recent call first):
2021/04/14 17:09:04 [alert] 30790#30790 process 31342 exited on signal 6
2021/04/14 17:09:04 [warn] 30793#30793 failed to start application "fastapi"
2021/04/14 17:09:04 [alert] 30793#30793 failed to apply new conf
```
Demo app in filename asgi.py:
```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello, World!"}
```
config.json:
```
{

    "listeners": {
        "*:80": {
            "pass": "applications/fastapi"
        } 
    },
    "applications": {
        "fastapi": {
            "type": "python 3.7",
            "path": "/home/ec2-user/montyhall_api/",
            "home": "/home/ec2-user/montyhall_api/.venv/",
            "module": "asgi",
            "callable": "app"
        }
    }
}

```
Python env:
```
(.venv) [ec2-user]$python --version
Python 3.7.9
```

**Comment by artemkonev** [comment]
Hi, 

Have you tried checking the file permissions on the app directory?

Unit's router process needs to access it, so either specify a `user` that has permissions in the app config or assign ownership of the directory to Unit's own `unit:unit` (assuming you're using the latest Unit version).

**Comment by artemkonev** [comment]
Usually this 'encodings' error emerges when Unit can't access the venv for some reason.

**Comment by mar0x** [comment]
@iolbr Your application is configured to use python 3.**7** (`"type": "python 3.7",`), whereas venv is created for python 3.**9**.

**Comment by iolbr** [comment]
Hi, thanks for the help! I was able to get it working. I've created a separate directory for unit account and installed venv and app there (server is running as unit). Changed port to 8080 and now it works with python 3.7. @mar0x: could you explain, why you said that my venv in the first setup was created for 3.9?

**Comment by mar0x** [comment]
@iobr sorry I misread python version. Please ignore my comment.
