### ISSUE TITLE
Fix for some variables($_SERVER['HTTPS'], $_SERVER['SERVER_PORT'], $_SERVER['REQUEST_URI']) for Wordpress based site, which prevents 'Too many redirects' error.

### ISSUE THREAD

**Issue by glowingsword** [nginx/unit#545]
Hi. Yesterday I moved my WP-based blog from Nginx + FastCGI to Nginx + Nginx Unit with PHP module, and I and i faced two problems(with SERVER_PORT and REQUEST_URI), which provoked the "too many redirects" error on the moved site.

I have this settings in my wp_options:

```mysql
# mysql blogdb -e 'select option_name,option_value from wp_options where option_name="siteurl" or option_name="home";'
+-------------+-------------------------+
| option_name | option_value            |
+-------------+-------------------------+
| home        | https://glowingsword.ru |
| siteurl     | https://glowingsword.ru |
+-------------+-------------------------+
```

## Absent the $_SERVER['HTTPS'] and posibility to redefine the $_SERVER['SERVER_PORT'])

How you can see, my site use the HTTPS protocol. And if the protocol differs from https, site make redirect to canonical URl, when I make the request to main page of my site.

The WP use $_SERVER['HTTPS'] and $_SERVER['SERVER_PORT'] to detect protocol. If $_SERVER['HTTPS']  is On, or  $_SERVER['SERVER_PORT'] == '443' — WP detect the HTTPS protocol. If we can't see this variables, they think that site used the plain HTTP protocol.

If I add to the end of the wp-config.php this code:

```bash
if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false){
        $_SERVER['HTTPS'] = 'on';
        $_SERVER['SERVER_PORT'] = '443';
}
```

the problem with the HTTPS detection of the WP ceases to appear.

See the difference between PHP FastCGI and UNIT PHP:

```bash
# curl -s https://glowingsword.ru/ 2>&1|grep -P 'Server API|SERVER_PORT|$_SERVER\[.HTTPS'|grep -v 'Abstraction Layer'|html2text
Server API | unit  
$_SERVER['SERVER_PORT']| 80  
$_SERVER['HTTP_X_FORWARDED_SERVER_PORT']| 443
```

```bash
# curl -s https://glowingsword.ru/ 2>&1|grep -P 'Server API|SERVER_PORT|$_SERVER\[.HTTPS'|grep -v 'Abstraction Layer'|html2text
Server API | FPM/FastCGI  
$_SERVER['SERVER_PORT']| 443
```

Proposal to enachement: you can make the $_SERVER['HTTPS'] = 'on' in unit php, if the HTTP_X_FORWARDED_SERVER_PORT is equal the 443 port, or $_SERVER['HTTP_X_FORWARDED_PROTO'] is equal the 'https'. Or can you add an option for the unit config, that enable the $_SERVER['HTTPS'] if this option is enabled in config?

## Problem with the bad value in the REQUEST_URI the we make request the URL with the / on the end

When we make the probmem to the URL with the '/' on the end, like https://some.domain/ we see the 

```bash
$_SERVER['REQUEST_URI'] = '/index.php'
```

instead the  

```bash
$_SERVER['REQUEST_URI'] = '/'
```

when we use the 

```yaml
"index": {
  "root": "/var/www/glowingsword.ru/",
  "script": "index.php"
}
```
in the targets.

When I use FastCGI, WP receive this values in the variables:

```php
# curl -s https://glowingsword.ru/ 2>&1|grep -P 'Server API|SCRIPT_NAME|REQUEST_URI|DOCUMENT_URI'|grep -v 'Abstraction Layer'|html2text
Server API | FPM/FastCGI  
$_SERVER['DOCUMENT_URI']| /index.php  
$_SERVER['REQUEST_URI']| /  
$_SERVER['SCRIPT_NAME']| /index.php
```

and site work well.

When I use php UNIT I see

```php
# curl -s https://glowingsword.ru/ 2>&1|grep -P 'Server API|SCRIPT_NAME|REQUEST_URI|DOCUMENT_URI'|grep -v 'Abstraction Layer'|html2text
Server API | unit  
$_SERVER['SCRIPT_NAME']| /index.php  
$_SERVER['REQUEST_URI']| /index.php
```
and site makes too many redirects, because the CMS use **home** or **siteurl@** value from wp_options, compares it with REQUEST_URI and if the canonical URL differs, CMS make the redirect to canonical URL.

See the from ./wp-includes/canonical.php:

```php

        if ( ! $requested_url && isset( $_SERVER['HTTP_HOST'] ) ) {
                // Build the URL in the address bar.
                $requested_url  = is_ssl() ? 'https://' : 'http://';
                $requested_url .= $_SERVER['HTTP_HOST'];
                $requested_url .= $_SERVER['REQUEST_URI'];
        }
```

How we see, Wordress make the $requested_url from the protocol from is_ssl() function, hostname from ```$_SERVER['HTTP_HOST']```, and the REQUEST_URI from ```$_SERVER['REQUEST_URI']``` to the **$requested_url** and compare it with the URL from home_url() function.

But, when in DB we have URL like this https://site.name/ without the /index.php, but in the REQUEST_URI we have '/index.php' — we have the too many redirects.

When I add the

```php
if ($_SERVER['REQUEST_URI'] == '/index.php') {
  $_SERVER['REQUEST_URI']='/';
}
```

to the wp-config.php — the site works good, the main page becomes available and site works good without redirects.

Proposal: you can fix problem for the URL '/' if fix the value of the $_SERVER['REQUEST_URI'] and set the $_SERVER['DOCUMENT_URI'] value, like we see in the FastCGI output. Of you can add the option for php application, which switch the behavior of the $_SERVER['REQUEST_URI']  and $_SERVER['DOCUMENT_URI'] of the unit php module between the current and the new proposed behavior.

**Comment by mar0x** [comment]
Hello @glowingsword .

The issue with `SERVER_PORT` is clear. Yes, Unit always has `80` there and it is not always true. When the Unit runs behind the proxy, it is hard to guess correct server port and it is up to the server maintainer to determine the correct port and protocol.

The second issue with `REQUEST_URI` is not so obvious. According to the source code, Unit obtains the value of `REQUEST_URI` from request and it is expected to be '/' for the root of your site. Could you please check the Nginx proxy settings and make sure it does not change the URL when proxying request ended with '/' ?

**Comment by glowingsword** [comment]
My Unit conf

```yaml
# sudo curl --unix-socket /run/nginx-unit.control.sock http://localhost/                                                                                                                        
{                                                                                                                                                                                                                    
        "certificates": {},                                                                                                                                                                                          
        "config": {                                                                                                                                                                                                  
                "listeners": {                                                                                                                                                                                       
                        "127.0.0.1:8090": {                                                                                                                                                                          
                                "pass": "routes/wordpress_blog"
                        }
                },

                "routes": {
                        "wordpress_blog": [
                                {
                                        "match": {
                                                "uri": [
                                                        "*.php",
                                                        "*.php/*",
                                                        "/wp-admin/"
                                                ]
                                        },

                                        "action": {
                                                "pass": "applications/wordpress_blog/direct"
                                        }
                                },
                                {
                                        "action": {
                                                "pass": "applications/wordpress_blog/index"
                                        }
                                }
                        ]
                },
```

**Comment by glowingsword** [comment]
Hello, @mar0x .

Hooray! You are right! The issue of the bad REQUEST_URI value was because I had this

```nginx
    index index.php;

    # set up logging
    access_log /var/log/nginx/glowingsword.ru.access.log;
    error_log /var/log/nginx/glowingsword.ru.error.log;

    location / {
        try_files $uri $uri/ @index_php;
    }

    location @index_php {
        proxy_pass       http://wordpress_blog;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Server-Port $server_port;
    }
```

in the Nginx conf for my blog.

When I comment the

```nginx
#index index.php;
```

and in the   location /  change the

```nginx
        try_files $uri $uri/ @index_php;
```
to the 

```nginx
        try_files $uri $uri/ @index_php;
```
I receive the good value

```bash
curl -s https://glowingsword.ru/ 2>&1|grep -P 'Server API|SCRIPT_NAME|REQUEST_URI|DOCUMENT_URI'|grep -v 'Abstraction Layer'|html2text
Server API | unit  
$_SERVER['SCRIPT_NAME']| /index.php  
$_SERVER['REQUEST_URI']| /
```
and as we see, script received the good REQUEST_URI value.

**Comment by glowingsword** [comment]
> The issue with SERVER_PORT is clear. Yes, Unit always has 80 there and it is not always true. When the Unit runs behind the proxy, it is hard to guess correct server port and it is up to the server maintainer to determine the correct port and protocol.

Yes. And I think that if Unit can proxy the value from `$_SERVER['HTTP_X_FORWARDED_SERVER_PORT']` to the `$_SERVER['SERVER_PORT']` if the special option is defined in the conf, or if the developers of the Unit can add possibility  in the application section to define the value of the `$_SERVER['SERVER_PORT']` - will be great!

But, for WP the main variable that detects the protocol is the `$_SERVER['HTTPS']`.

If you can add the option to the unit php that read the `$_SERVER['HTTP_X_FORWARDED_PROTO']` and if it has value 'https', Unit PHP switch the `$_SERVER['HTTPS']` to  'on' – this will resolve the problem for protocol detection for Wordpress, because it use the `$_SERVER['HTTPS']` first and if it is absent, check the port in the `$_SERVER['SERVER_PORT']`  as fallback.

**Comment by iron-udjin** [comment]
Similar issue: #231

I had the same issue with wordpress and laravel.
Workaround: change SERVER_PORT and HTTPS variables in the source code of unit:

```
--- nxt_php_sapi.c.orig	2021-11-30 00:50:22.311219512 +0200
+++ nxt_php_sapi.c	2021-11-30 00:50:57.412117591 +0200
@@ -1367,11 +1367,9 @@
 
     nxt_php_set_sptr(req, "SERVER_NAME", &r->server_name, r->server_name_length,
                      track_vars_array TSRMLS_CC);
-    nxt_php_set_cstr(req, "SERVER_PORT", "80", 2, track_vars_array TSRMLS_CC);
+    nxt_php_set_cstr(req, "SERVER_PORT", "443", 3, track_vars_array TSRMLS_CC);
 
-    if (r->tls) {
-        nxt_php_set_cstr(req, "HTTPS", "on", 2, track_vars_array TSRMLS_CC);
-    }
+    nxt_php_set_cstr(req, "HTTPS", "on", 2, track_vars_array TSRMLS_CC);
 
     f_end = r->fields + r->fields_count;
     for (f = r->fields; f < f_end; f++) {
```

I'm waiting possibility to override env variables in config a few years.

**Comment by lacosteque** [comment]
I had a similar problem, but it was solved when I carefully studied the sample configuration for wordpress [https://unit.nginx.org/howto/wordpress/](https://unit.nginx.org/howto/wordpress/).

There are configuration examples on the Nginx blog [https://www.nginx.com/blog/installing-wordpress-with-nginx-unit/ ](https://www.nginx.com/blog/installing-wordpress-with-nginx-unit/) and [https://www.nginx.com/blog/automating-installation-wordpress-with-nginx-unit-on-ubuntu/](https://www.nginx.com/blog/automating-installation-wordpress-with-nginx-unit-on-ubuntu/)

But they also cause redirection error and are fixed via wp-config.php.

But as I understood, the problem lies in Unit configuration, namely in the route 

    "action": {
    "share":"/path/to/app$uri",
    "fallback": {
     { "pass": { "applications/wordpress/index"
     }

If you don't specify **$uri**, then just a redirection error occurs and you need to edit wp-config.php, if you don't forget it, then everything works.

**Comment by hongzhidao** [comment]
Hi,

**Comment by lacosteque** [comment]
> Hi,
> 
> We are supporting the feature of client protocol replacement. #592

That's great, I wish I had seen it before. And spent a few hours solving it :)))
