### ISSUE TITLE
Large payload (when body_length > body_buffer_size ) produce a mkstemp failed (2: No such file or directory)

### ISSUE THREAD

**Issue by datatravelgit** [nginx/unit#546]
This error is happening on Ngx unit version unit.1.22.0

While I am calling an API with a payload larger than 16k, Ngx unit is producing this error:
```
mkstemp(tmp/req-XX0ukfBw) failed (2: No such file or directory)
```
The code where this error is produced is here :
https://github.com/nginx/unit/blob/5b332cae832c9f8245280fa60a6edc2ce48202c6/src/nxt_h1proto.c#L925

I am not sure if this a corner case that has not been tested when body_length > body_buffer_size

**Comment by VBart** [comment]
How was Unit installed in your system? It seems that it was built without specifying a proper path to the temporary files directory via the `--tmp` ./configure option.

You can fix that by overriding the path via `--tmp /tmp` command line option of `unitd`.

**Comment by datatravelgit** [comment]
Hi, thanks for the answer. It seems that --tmp /tmp did the trick. 
Should I close the item or reface it to add a validation if the temporary files directory was set before trying to save a temporary file?

Thanks

**Comment by VBart** [comment]
@datatravelgit It doesn't make sense because if the directory doesn't exist then Unit can't continue operate anyway.  It must be set properly during the compilation time as well as other system specific parameters.  The package maintainers are responsible for setting them right, so you'd better to report the issue to them.

**Comment by datatravelgit** [comment]
Understood. Closing the issue. Thanks
