### ISSUE TITLE
Best practice about certificate rotation

### ISSUE THREAD

**Issue by sycured** [nginx/unit#547]
Hi, I'm doing Mutual TLS between services and I would like your idea about doing the best way about certificate rotation.

In my setup, some certificates are rotating frequently (near each month), unit with `curl -X PUT`, I can update dynamically the certificate without restarting/respawning a new container so it's very interesting for my use case.

I plan to have inside my container:
- 1 process: unit
- 1 daemon/cron: pulling the new certificate with private key + intermediate CA + root CA, bundling everything, and doing the `curl`

Do you have a best practice or return of experience?
Because in my plan, I'll need an init system or process manager to do the job.

Do you plan/see a way to use Consul Custom Proxy Integration (https://www.consul.io/docs/connect/proxies/integrate)?

Thanks

**Comment by tippexs** [comment]
Thanks for explaining your use case. I have a couple of more questions.

1. Is it not possible to restart the container (rebuild is not needed) to renew the certs? 
2. If this is not possible you can add a crontab to your container image

For option number one we can use the `docker-entrypoint.d` logic in our official Unit Docker Images.

Finde more information about it here: http://unit.nginx.org/installation/#initial-configuration

DR; TL
You can  have your initial unit configuration json file somewhere in your container. In the docker-entrypoint.d upload any shell-script e.g. `init.sh`. In this init-script you will be able to get the newest certs from anywhere you want and upload it to the certstore of NGINX Unit. After that, apply the unit configuration. This will update your certificates anytime your container will be restarted. To me that sounds like the most "docker-friendly" approach.

**Comment by sycured** [comment]
Thank you but the use case is more complex:

- HashiCorp Vault is my internal root and intermediate CA
- all containers are using TLS and mutual TLS (something missing in Unit… hoping to see it soon)

So, when the certificate is rotated, I need to pull it and apply it.

In that case, I'll look to use consul-template (integrate with consul and vault) maybe with s6-overlay. I'll try with my Nomad cluster.

It'll be good to have Unit with Hashicorp Consul and Vault integration

**Comment by tippexs** [comment]
s6-overlay sounds good to me. So you are looking forward to pull certs from Hashicorps vault?

Another idea. Having a go-application hosted on unit using Hashicorps Vault Lib (https://www.vaultproject.io/api/libraries) pulling the certs and sending it to the unit-cert store. The secrets to open the vault can be then part of your NGINX Unit Container Image. 

The renew process can then be kicked off by calling an HTTP Endpoint from inside the container or even from outside. What kind of Vault support you are looking for? Something like Unit will be able to get certs directly form Hashicorp vault?

**Comment by sycured** [comment]
I've tried some solutions and finally I'll use:
- the orchestrator pulls:
  -  certificates from vault and write it to files
  - load environment variables from vault and certificates
- mount files (certificates) into the container (volumes)
- `docker-entrypoint.d` with the right script, we'll put certificate to Unit

When value changes inside Consul or Vault, the orchestrator restarts automatically the container.

Do you plan to support Mutual TLS in Unit? It's the only missing part at this time about certificate/SSL/TLS.

**Comment by VBart** [comment]
> Do you plan to support Mutual TLS in Unit?

Yes. Something similar to the `ssl_verify_client` and `ssl_client_certificate` directives in nginx is planned. No ETA yet, but likely will be implemented this year.

**Comment by sycured** [comment]
> > Do you plan to support Mutual TLS in Unit?
> 
> Yes. Something similar to the `ssl_verify_client` and `ssl_client_certificate` directives in nginx is planned. No ETA yet, but likely will be implemented this year.

Perfect, thank you
