### ISSUE TITLE
Issue in proxy pass from nginx to angular application

### ISSUE THREAD

**Issue by sanikadjango** [nginx/unit#548]
I have created an angular application that displays a page with “Hello World” on ‘/hello’ route.
url for angular: http://localhost:4200/hello
When I make request from browser to nginx on ‘/greet’:  http://localhost/greet
that should be redirected to /hello route of angular application so that the page with “Hello World” is displayed.
But if the request is http://localhost/hello , an err should appear 

The nginx conf:
server {
	listen 80;
	server_name _;
location /greet {
		proxy_pass  http://localhost:4200/hello;
}
location /hello {
	return 404;
}
}

The issue is that while redirecting, the route is not getting modified as ‘/hello’ 
And since there is no ‘/greet’ route in angular, we get a not found.

**Comment by VBart** [comment]
Could you show your Unit configuration as well?

**Comment by sanikadjango** [comment]
What is unit configuration? In which file do I find it? The configuration that I have mentioned is the only configuration I have done.

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
