### ISSUE TITLE
Out-of-bounds access - false positive

### ISSUE THREAD

**Issue by geyslan** [nginx/unit#549]
Coverity caught these `Out-of-bounds accesses (CWE-119)`

```
369674 nxt_openssl.c
353388 nxt_runtime.c
353384 nxt_application.c
353383 nxt_application.c
353375 nxt_cert.c
```

`nxt_str_t` structure holds the size of the string ignoring the `nul` string terminator.

Coverity is catching these probably because the `nxt_strlen()` relies on `string.h` `strlen()` which let the `nul` terminator out in the counting. Is the current `nxt_strlen()` an alias for the `string.h` for performance purposes? What about an **own** `nxt_strlen()`?

P.S. I tried to put that info in the coverity issues triage but I have no access.

**Comment by ac000** [comment]
Our `nxt_str_t`'s hold both unterminated and nul-terminated strings depending on their source.

```c
#define nxt_strlen(s)                                                         \ 
    strlen((char *) s) 
```

Like many of our string wrappers, it is there simply to cast from `u_char` to `char`... although that doesn't really make sense.

For whatever reason, Unit chose to use `u_char` (unsigned char) for strings, of course the C library uses `char`. So we need to cast when  using an nxt_str_t.start as a parameter to a C library function.

We do seem to be using nxt_strlen() on `char` strings. e.g `src/nxt_cert.c:857:`.

This is an area that has been attempted to be cleaned up but proposed patches have never been accepted...
