### ISSUE TITLE
Err: Request "pass" points to invalid location "routes"

### ISSUE THREAD

**Issue by ibot3** [nginx/unit#557]
As shown in the [documentation](https://unit.nginx.org/configuration/#routes), it should be possible to use `routes` as a value for the `pass` field. However, this does not seem to work. This simple configuration example will fail:

````
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
    },

    "routes": {
        "test": [
            {
                "action": {
                    "share": "/tmp/test"
                }
            }
        ]
    }
}
````

Error:

````
{
	"error": "Invalid configuration.",
	"detail": "Request \"pass\" points to invalid location \"routes\"."
}
````

This was observed with version 1.24.0

**Comment by VBart** [comment]
> As shown in the documentation, it should be possible to use routes as a value for the pass field.

And in this case the `routes` field must be an array, not an object like in your configuration.
