### ISSUE TITLE
Python: asgi app stucks on asyncio loop

### ISSUE THREAD

**Issue by ingria** [nginx/unit#560]
I'm trying to use unit for my application, which is currently running on uvicorn (asgi3). 

```python
service = MyBackgroundService()

async def application(scope, receive, send):
    if scope['type'] == 'lifespan':
        message = await receive()
        if message['type'] == 'lifespan.startup':
            await send({"type": "lifespan.startup.complete"})
            await service.bootUp()
            logger.info('This line is never displayed')
        return

    # handle http request
```

Under the hood of `MyBackgroundService.bootUp()` is an [infinite loop](https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/network/mtprotosender.py#L500-L507), which is constanly running and receiving new data. The idea is that this service is running asynchronously "in background" while asgi `application` is interacting with it.

The problem is that the app stucks on that `recv()` loop and becomes unresponsive (doesn't process any requests and cannot be stopped with anything except `kill -9`).

I'm not sure whether the problem is in my code or in unit, but it works just fine with uvicorn. My guess is that there's something wrong with event loops (maybe app and unit are using different loops?).

App config:

```json
"01_01": {
    "type": "python 3",
    "module": "worker",
    "callable": "application",
    "protocol": "asgi",
    "working_directory": "/home/user/dir",
    "path": "/home/user/dir",
    "user": "user",
    "environment": {
        "SOME_VARS": "some_value"
    }
}
```

**Comment by mar0x** [comment]
Hello,

`telethon.network.MTProtoSender.connect()->_connect()` [creates tasks](https://github.com/LonamiWebs/Telethon/blob/4b16183d2bbe80cbf4dabdb266a8015c5bf975cc/telethon/network/mtprotosender.py#L259-L264) to run send and receive loops. So, it is not 100% correct saying _it is an infinite loop_ unless you have your own loop inside `bootUp()` method. According to [ASGI Lifespan specification](https://asgi.readthedocs.io/en/latest/specs/lifespan.html) your application needs to await further `shutdown` message in `lifespan` scope.

The fact your application running on uvicorn, but blocks on Unit points on possible problem in Unit ASGI implementation and requires deeper investigation. Please share as much information about your application as possible. Sources or tiny mockup which replicates the issue would be perfect.

Thanks for your attention to Unit. I’m looking forward to your reply.

**Comment by ingria** [comment]
I've created a mockup project:

https://github.com/ingria/nginx-unit-example

To test it, you'll need to get a credentials for Telegram API. If you don't use Telegram, please leave your e-mail and I will send some test credentials to you.

**Comment by mar0x** [comment]
Thank you for the effort. With your mockup it was easy to reproduce and find the issue.

Telethon creates `asyncio` objects (`asyncio.Event`) when it initialises the client. `Event` object is bound to the current `loop`. Unit creates new `loop` and run the application in this `loop`. So, the `Event` object cannot work properly. Maybe there are another issues, not only one `Event`.

The reason of creating new loop for application is multithreading support in Unit - each thread uses its own loop.

In order to make your app work with both uvicorn and Unit, consider to move telethon client initialisation into `lifespan.startup` handler:

```
diff --git a/index.py b/index.py
index 28bafa5..ffbff3d 100755
--- a/index.py
+++ b/index.py
@@ -13,7 +13,7 @@ logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(leve
 logger = logging.getLogger('worker')
 
 
-telethon = TelegramClient(api_id=API_ID, api_hash=API_HASH, session='bot.session')
+telethon = None
 
 
 async def application(scope, receive, send):
@@ -32,6 +32,7 @@ async def handle_lifespan(message: dict) -> dict:
     message_type = message['type']
 
     if message_type == 'lifespan.startup':
+        telethon = TelegramClient(api_id=API_ID, api_hash=API_HASH, session='bot.session')
         promise = telethon.start(bot_token=BOT_TOKEN)
     elif message_type == 'lifespan.shutdown':
         promise = telethon.disconnect()
```

**Comment by ingria** [comment]
@mar0x, thank you very much for your time and explanation 🙏

Everything works fine if I create the client instance inside the lifespan handler. Seems like my assumption about different loops was right, I just didn't know where to dig.

I'm closing this issue now, since there's nothing wrong with Unit.
