### ISSUE TITLE
latest python container is not starting in ECS 

### ISSUE THREAD

**Issue by SureshDamera** [nginx/unit#566]
Hi Team 

We are using the `nginx/unit:1.24.0-python3.9` container to deploy our application but when we run the container in ECS unit socket connections are not getting closed(which runs as part of docker-entrypoint.sh).
![image](https://user-images.githubusercontent.com/47925861/125505103-781eb25b-4d4a-4468-9913-4cc2c97411a1.png)

Interestingly it is working as expected when we run it on my personal machine.

**Comment by thresheek** [comment]
This should be fixed starting with 1.29.0: https://github.com/nginx/unit/commit/63cc4a31bdea2601c8adc08194759657f1476b16.  We've added a timeout for control socket removal/creation so it won't hang again.
