### ISSUE TITLE
How to see what open source Nginx purging from cache?

### ISSUE THREAD

**Issue by yamarane** [nginx/unit#568]
How to see what open source Nginx purging from cache? Is there any log for it?

How much data it will purge after reaching max_size?

`proxy_cache_path /docker_mirror_cache levels=1:2 max_size=3000G inactive=60d keys_zone=cache:500m use_temp_path=off;
`

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
