### ISSUE TITLE
ASGI streaming responses fail

### ISSUE THREAD

**Issue by dannmartens** [nginx/unit#569]
Under certain conditions, Nginx Unit interrupts streaming responses.

I investigated two separate cases:
1. A reverse proxying service written in Starlette,
2. The "Slow Numbers" StreamingResponse example in the [Starlette documentation](https://www.starlette.io/responses/).

The reverse proxy fails, when the octet stream surpasses a certain length. Smaller files are delivered complete, but larger files are truncated.

"Slow Numbers" just stops after a single yield: only a small amount of data is sent in this case, but the delay between sends is much larger than in the reverse proxy case.

These are the reverse proxy debug logs, for a request to stream a large file:
[unitd-reverse-proxy.log](https://github.com/nginx/unit/files/6860838/unitd-reverse-proxy.log)

When the truncation occurs, the server is told to abandon the connection; as a result, the proxy client gets cancelled. I initially assumed the proxy client was failing, but it is just responding to a framework event.
```
2021-07-21 10:22:28,327 [ERROR] proxy - Streaming failed!
Traceback (most recent call last):
  File "/vagrant/infraportal/server/proxy.py", line 87, in content_streamer
    chunk = await client_response.content.read(config.CHUNK_SIZE)
  File "/home/vagrant/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 380, in read
    await self._wait("read")
  File "/home/vagrant/.local/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
asyncio.exceptions.CancelledError
```
These are the "slow numbers" debug logs:
[unit-slow-numbers.log](https://github.com/nginx/unit/files/6860906/unit-slow-numbers.log)

With Nginx Unit, the updates stop after the first bullet.
![85A0C829-88E0-470C-BB14-536863BFFD17](https://user-images.githubusercontent.com/263133/126610420-57208431-d81c-444c-8806-22a30b907f1f.GIF)

A similar cancellation occurs:
```
2021-07-22 08:26:00,583 [ERROR] proxy - Streaming failed!
Traceback (most recent call last):
  File "/vagrant/infraportal/server/proxy.py", line 122, in slow_numbers
    await asyncio.sleep(0.5)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 648, in sleep
    return await future
asyncio.exceptions.CancelledError
```

Both cases work with Uvicorn.

Could this be a single timeout issue? On account of longer octet streams taking more time?

**Comment by mar0x** [comment]
Hello,

Please check the latest Unit from GitHub. We've just made a couple ASGI fixes and "Slow Numbers" sample works for me.

**Comment by dannmartens** [comment]
Hi, 

I've rekindled my passion to run Starlette with Nginx Unit, but I am still experiencing issues. So far, I've been using Uvicorn, instead.

I propose to close this issue and continue on https://github.com/nginx/unit/issues/564, only. I'll describe my recent findings over there.
