### ISSUE TITLE
SIGSEGV in unit controller process on CentOS 6.9

### ISSUE THREAD

**Issue by zarianu** [nginx/unit#57]
Hello dear sirs, I'm getting SIGSEGV when trying to configure unit via TCP socket. Here's my env:

> [root@dev unit]# uname -a
> Linux 4.9.50-x86_64-linode86 #1 SMP Thu Sep 14 19:28:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 

> [root@dev unit]# ./sbin/unitd -V
> unit version: 0.2
> configured as ./configure --prefix=/usr/local/unit --debug

Here's config file:

> [root@dev unit]# cat /root/wiki.json
> {
>     "type": "php",
>     "workers": 10,
>     "root": "/home/kost"
> }

> [root@dev unit]# curl http://127.0.0.1:8400/
> {
> 	"listeners": {},
> 	"applications": {}
> }
> 

> [root@dev ~]# curl -X PUT -d @wiki.json http://127.0.0.1:8400/applications/test
> curl: (52) Empty reply from server
> 

> [root@dev ~]# strace -p 21835
> Process 21835 attached
> write(2, "2017/10/24 19:58:27.562 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:27.562 [info] 2"..., 93) = 93
> write(2, "2017/10/24 19:58:27.562 [debug] "..., 86) = 86
> write(2, "2017/10/24 19:58:27.562 [debug] "..., 69) = 69
> epoll_wait(3, {{EPOLLIN, {u32=22244816, u64=22244816}}}, 32, -1) = 1
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 84) = 84
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 86) = 86
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 63) = 63
> accept4(6, {sa_family=AF_INET, sin_port=htons(40230), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_NONBLOCK) = 11
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 59) = 59
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 63) = 63
> accept4(6, 0x1541748, [16], SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 94) = 94
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 74) = 74
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 78) = 78
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 74) = 74
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 70) = 70
> recvfrom(11, "GET / HTTP/1.1\r\nUser-Agent: curl"..., 1024, 0, NULL, NULL) = 167
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 81) = 81
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 68) = 68
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 118) = 118
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 79) = 79
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 74) = 74
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 64) = 64
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 64) = 64
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 72) = 72
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 71) = 71
> writev(11, [{"HTTP/1.1 200 OK\r\nServer: unit/0."..., 145}, {"{\r\n\t\"listeners\": {},\r\n\t\"applicat"..., 46}], 2) = 191
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 66) = 66
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 72) = 72
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 66) = 66
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 69) = 69
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 78) = 78
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 69) = 69
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 70) = 70
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 75) = 75
> shutdown(11, SHUT_RDWR)                 = 0
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 63) = 63
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 72) = 72
> close(11)                               = 0
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 64) = 64
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 68) = 68
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:58:38.736 [debug] "..., 69) = 69
> epoll_wait(3, {{EPOLLIN, {u32=22244816, u64=22244816}}}, 32, -1) = 1
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 84) = 84
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 86) = 86
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 63) = 63
> accept4(6, {sa_family=AF_INET, sin_port=htons(40232), sin_addr=inet_addr("127.0.0.1")}, [16], SOCK_NONBLOCK) = 11
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 59) = 59
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 62) = 62
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 63) = 63
> accept4(6, 0x1541708, [16], SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 94) = 94
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 74) = 74
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 77) = 77
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 78) = 78
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 74) = 74
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 70) = 70
> recvfrom(11, "PUT /applications/test HTTP/1.1\r"..., 1024, 0, NULL, NULL) = 315
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 81) = 81
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 61) = 61
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 68) = 68
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 120) = 120
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 79) = 79
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 79) = 79
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 65) = 65
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 79) = 79
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 75) = 75
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 78) = 78
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 64) = 64
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 67) = 67
> ftruncate(0, 10489856)                  = -1 EINVAL (Invalid argument)
> write(2, "2017/10/24 19:59:16.646 [warn] 2"..., 88) = 88
> write(2, "2017/10/24 19:59:16.646 [debug] "..., 58) = 58
> write(2, "2017/10/24 19:59:16.649 [debug] "..., 79) = 79
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x30} ---
> +++ killed by SIGSEGV +++

Pls find unit.log attached.
[unit.log](https://github.com/nginx/unit/files/1410869/unit.log)

I'm ready to provide more info as needed.

**Comment by VBart** [comment]
Could you show your `./configure` output and `build/autoconf.err`? It looks like you don't have any working shared memory facility in your system.

**Comment by zarianu** [comment]
Thank you for your prompt answer!

> [kost@dev]% ./configure
> configuring for Linux 4.9.50-x86_64-linode86 x86_64
> checking for C compiler: cc
>  + using GNU C compiler
>  + gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
> building an "echo" program
> checking for int size ... 4
> checking for long size ... 8
> checking for long long size ... 8
> checking for void * size ... 8
> checking for size_t size ... 8
> checking for off_t size ... 8
> checking for time_t size ... 8
> checking for C99 variadic macro ... found
> checking for GCC __builtin_expect() ... found
> checking for GCC __builtin_unreachable() ... found
> checking for GCC __builtin_prefetch() ... not found
> checking for GCC __builtin_clz() ... found
> checking for GCC __attribute__ visibility ... found
> checking for GCC __attribute__ aligned ... found
> checking for GCC __attribute__ malloc ... found
> checking for GCC __attribute__ packed ... found
> checking for GCC builtin atomic operations ... found
> checking for posix_memalign() ... found
> checking for Linux malloc_usable_size() ... found
> checking for alloca() ... found
> checking for Linux mallopt() ... found
> checking for MAP_ANON ... found
> checking for MAP_POPULATE ... found
> checking for MAP_PREFAULT_READ ... not found
> checking for shm_open() ... not found
> checking for shm_open() in librt ... found but is not working
> checking for memfd_create() ... not found
> checking for Linux clock_gettime(CLOCK_REALTIME_COARSE) ... found
> checking for FreeBSD clock_gettime(CLOCK_REALTIME_FAST) ... not found
> checking for clock_gettime(CLOCK_REALTIME) ... not found
> checking for clock_gettime(CLOCK_REALTIME) in librt ... found
> checking for Linux clock_gettime(CLOCK_MONOTONIC_COARSE) ... found
> checking for FreeBSD clock_gettime(CLOCK_MONOTONIC_FAST) ... not found
> checking for clock_gettime(CLOCK_MONOTONIC) ... not found
> checking for clock_gettime(CLOCK_MONOTONIC) in librt ... found
> checking for HP-UX hg_gethrtime() ... not found
> checking for struct tm.tm_gmtoff ... found
> checking for altzone ... not found
> checking for localtime_r() ... found
> checking for pthread_yield() ... found
> checking for pthread spinlock ... found
> checking for pthread spinlock zero initial value ... found but is not working
> checking for MacOSX spinlock ... not found
> checking for sem_timedwait() ... not found
> checking for sem_timedwait() in libpthread ... found
> checking for __thread ... found
> checking for Linux epoll ... found
> checking for Linux signalfd() ... found
> checking for Linux eventfd() ... found
> checking for kqueue ... not found
> checking for Solaris event port ... not found
> checking for /dev/poll ... not found
> checking for AIX pollset ... not found
> checking for AF_INET6 ... found
> checking for sockaddr.sa_len ... not found
> checking for struct sockaddr size ... 16
> checking for struct sockaddr_in size ... 16
> checking for struct sockaddr_in6 size ... 28
> checking for struct sockaddr_un size ... 110
> checking for struct sockaddr_storage size ... 128
> checking for socketpair(AF_UNIX, SOCK_SEQPACKET) ... found
> checking for struct msghdr.msg_control ... found
> checking for sys/filio.h ... not found
> checking for ioctl(FIONBIO) ... found
> checking for socket(SOCK_NONBLOCK) ... found
> checking for accept4() ... found
> checking for Linux sendfile() ... found
> checking for posix_fadvise() ... found
> checking for fcntl(F_READAHEAD) ... not found
> checking for fcntl(F_RDAHEAD) ... not found
> checking for getrandom() ... not found
> checking for ucontext ... found
> checking for dlopen() ... not found
> checking for dlopen() in libdl ... found
> checking for posix_spawn() ... found
> checking for setproctitle() ... not found
> creating build/Makefile
> 
> Configuration summary:
> 
>   unit bin directory:           "bin"
>   unit sbin directory:          "sbin"
>   unit modules directory:       "build"
>   unit state directory:         "build"
> 
>   unit pid file:                "unit.pid"
>   unit log file:                "unit.log"
> 
>   unit control API socket:      "unix:control.unit.sock"
> 
>   non-privileged user:          "nobody"
>   non-privileged group:         ""
> 
>   IPv6 support:                 YES
>   Unix domain sockets support:  YES
>   debug logging:                NO
> 

[autoconf.err.txt](https://github.com/nginx/unit/files/1411141/autoconf.err.txt)

**Comment by VBart** [comment]
Right.
```
checking for shm_open() ... not found
checking for shm_open() in librt ... found but is not working
checking for memfd_create() ... not found
```
Are you building Unit in some very restricted environment? Do you have `/dev/shm` mounted? Could you provide more information about your system?

Also, it seems you don't have kernel header files:
```
checking for memfd_create()
build/autotest.c:1:25: error: linux/memfd.h: No such file or directory
```

**Comment by zarianu** [comment]
I'm using CentOS on Linode, KVM virtualization.

Thanks for idea about shared memory - /dev/shm permissions was 755 instead of 777, everything works like a charm after fixing that.

**Comment by VBart** [comment]
After https://github.com/nginx/unit/commit/5ed4d7b9dcd11bf2f37130812dbc34d951a73484 Unit won't be compiled on systems with no working shared memory. The build is dysfunctional in this case.
