### ISSUE TITLE
Django channels websocket: Python failed to call 'future.result()'

### ISSUE THREAD

**Issue by Hybridlo** [nginx/unit#572]
Hello.
I have been having a problem with nginx unit for a while now, but i've recently started digging in the right direction, and want to probive the info i've found, so that someone can fix a bug, or tell me what i was doing wrong

Platform: Ubuntu 20.04 LTS
NGINX Unit: 1.24.0
Python: 3.8.10
Django: 3.2.3
channels: 3.0.3

So i have deployed an asgi application with django and django-channels, and was able to make it work successfully with daphne, but wanted a bit more complete solution out-of-the-box, and tried nginx unit. It was working fine until i tried to open the page that connects to websocket. In logs this is what i saw:

````
[error] 236207#236207 [unit] #7185: Python failed to call 'future.result()'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/usr/local/lib/python3.8/dist-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/usr/local/lib/python3.8/dist-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/usr/local/lib/python3.8/dist-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/usr/local/lib/python3.8/dist-packages/channels/utils.py", line 39, in await_many_dispatch
    tasks = [
  File "/usr/local/lib/python3.8/dist-packages/channels/utils.py", line 40, in <listcomp>
    loop.create_task(consumer_callable())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got <Future pending>
````

Now, here's my speculation on the problem

I'm not exactly good at debugging this kind of stuff, so the only thing that came to mind is to play around with last function in the traceback - create_task. After checking the "coro" object more closely, it turns out the "coro" (which is a Future, with a pending state) isn't ready to return result yet, which causes the "Python failed to call 'future.result()'" error. The workaround it i've come up with was to modify "create_task" function, so that it wraps the future in a async function that awaits it:

````
try:
    task = tasks.Task(coro, loop=self, name=name)
except TypeError as e:
    if isinstance(coro, futures.Future) and not coro.done():
        async def corout(future):
            return await future
        task = tasks.Task(corout(coro), loop=self, name=name)
    else:
        raise e
````
Not the most elegant solution but it works. Looking through the source code of unit, i've found the function that reports about the [error](https://github.com/nginx/unit/blob/60cf1399611ae1b2728492c94ff57a4a044774b4/src/python/nxt_python_asgi_http.c#L646) and possibly the [reason](https://github.com/nginx/unit/blob/60cf1399611ae1b2728492c94ff57a4a044774b4/src/python/nxt_python_asgi_http.c#L150) for this situation. Since it uses set result on next async loop iteration, the result isn't ready at the time it's required, although i'm not sure about the whole flow of the code there.

And this is it. I hope my explanation wasn't too messy and someone can figure this out, or tell me where i went wrong.

**Comment by mar0x** [comment]
Hello.
There is a PR https://github.com/django/channels/pull/1577 to fix this. Please try to apply it and check if it helps.

**Comment by Hybridlo** [comment]
Yeah, this PR fixes this as well, so it was django-channels issue after all.

Thank you for the help!
