### ISSUE TITLE
only the first "tls" in config works

### ISSUE THREAD

**Issue by daustin391** [nginx/unit#573]
Hi there,

Thanks for taking the time to take a look at this. It's maybe a problem with my VPS, but if someone can point me in the right direction it would be greatly appreciated.

I have two domains which I am using Unit as an application server for, my listeners look like this:

```
{
    "listeners": {
        "127.0.0.1:8080": {
            "application": "app_1",
            "tls": {
                "certificate": "cert_1"
            }
        },
       "127.0.0.1:8081": {
            "application": "app_2",
            "tls": {
                "certificate": "cert_2"
            }
        }
    }
}
```
In this setup, the application on port 8080 works, and the app on port 8081 returns a 502. The error log reads like:
```
2021/08/15 22:15:00 [error] 2369572#2369572: *24451 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: xxx.xxx.xx.xx, server: myseconddomain.com, request: "GET / HTTP/1.1", upstream: "https://127.0.0.1:8081/", host: "myseconddomain.com"
```

If I -X DELETE 'localhost/config/127.0.0.1:8080', and then add it back in so that now port 8081 appears first in the configuration, then 8080 returns the 502 and the domain at port 8081 works.

Many thanks!

**Comment by mar0x** [comment]
Hello,
Your issue looks similar to #561. Please check the recently released 1.25.0 version.
