### ISSUE TITLE
Unit does not honor HTTP response statuses

### ISSUE THREAD

**Issue by Tylerian** [nginx/unit#579]
# Context
I'm testing Unit with a PHP (Laravel) Application which acts as a REST API.

# Problem
When I return a Response  other than 200OK, Unit overrides the response and sends back a 500 error.

Is this expected? Is there any way of disabling this behavior? Also, is there any way of debugging those kind of errors? So far Unit did not print any info to stdout whenever the error occours.

**Comment by VBart** [comment]
> When I return a Response other than 200OK, Unit overrides the response and sends back a 500 error.

Unit doesn't override any responses from the app.  Could you please provide a minimal example of the application that doesn't work right?

> Also, is there any way of debugging those kind of errors? So far Unit did not print any info to stdout whenever the error occours.

See troubleshooting section of the documentation: https://unit.nginx.org/troubleshooting/#logging

**Comment by Tylerian** [comment]
Hello VBart, nice timing!

After battling a bit I've just figured out it was a permissions problem. Once I gave write permissions on the target folder to the `unit` user & group everything is working as expected.

Sorry for bothering!
