### ISSUE TITLE
Pyramid: loading the configuration .ini file

### ISSUE THREAD

**Issue by sxpert** [nginx/unit#582]
a pyramid app usually requires the use of a .ini file for app configuration (including database urls), such as used by the pserve call:

<code>
$ pserve development.ini
</code>

\
I can't seem to find a way to do so, and the documentation appears to skip over that point.

I would have expected there would be a "configuration_file" entry in the "pyramid" section of the .json configuration file.

**Comment by sxpert** [comment]
something like this seems to do the job:

```python
import os
import sys

from pyramid.paster import bootstrap, get_app, setup_logging

def start_docker_dev(wsgi_vars, request):
    ini_file = os.environ.get("PYRAMID_INI_FILE", None)
    if not ini_file:
        print("ERROR: no PYRAMID_INI_FILE passed in environment variables", file=sys.stderr, flush=True)
        sys.exit(1)

    app = get_app(ini_file)
    setup_logging(ini_file)
    return app(wsgi_vars, request)
```

**Comment by artemkonev** [comment]
Please take a look at the updated howto: https://unit.nginx.org/howto/pyramid/
