### ISSUE TITLE
Please add unit-python38 for RHEL7

### ISSUE THREAD

**Issue by tkloda** [nginx/unit#588]
Hello,

would it be possible to add unit-python38 for RHEL7? Currently only unit-python36 is supported: https://packages.nginx.org/unit/rhel/7Server/x86_64/RPMS/

**Comment by tkloda** [comment]
It should be available as rh-python38 package.
RHEL7 container images are also offered with python38: https://catalog.redhat.com/software/containers/rhscl/python-38-rhel7/5e838896dd19c7789613d625

**Comment by thresheek** [comment]
RHEL 7 is EOL, so this is moot.
