### ISSUE TITLE
Unit对Python包的搜索路径有哪些？

### ISSUE THREAD

**Issue by xinlingqudongX** [nginx/unit#589]
![微信截图_20211014190633](https://user-images.githubusercontent.com/26372348/137306553-0a44fb64-ca95-4863-91df-78444ff23886.png)
![微信图片_20211014190836](https://user-images.githubusercontent.com/26372348/137306562-042a97be-9d1c-44d1-9d60-931c5e44daba.png)
1.Unit搜索Python解释器的路径是从哪里搜索的？
1. Where does Unit search the Python interpreter path?
2.我使用了Home目录设置了Python的执行路径，但是Python的版本并不对，为什么没有使用Home目录中的Python版本呢？
2. I used the Home directory to set the execution path of Python, but the Python version is wrong. Why didn't I use the Python version in the Home directory?

这是我的配置
This is my configuration
{
    "listeners": {
        "*:5000": { "pass": "routes" },
        "*:8000": {
            "pass": "applications/test"
        }
    },

    "routes": [
        {
            "action": { "share": "/home/project/ams" }
        }
    ],
    "applications": {
        "test": {
            "working_directory": "/home/project/ams",
            "type": "python 3",
            "path": "./",
            "home": "/home/vdir",
            "module": "main",
            "callable": "application",
            "user": "root",
            "group": "root",
            "threads": 4
        }
    }
}

**Comment by mar0x** [comment]
Hello,

Unit use Python interpreter from libpython library, not as standalone interpreter. Check exact version from unit.log:
```
2021/10/14 14:16:12.274 [notice] 11455#182089 module: python 3.7.6 ...
```

`home` is a _Path to the app’s virtual environment. Absolute or relative to working_directory._ (see https://unit.nginx.org/configuration/#python). Virtual environment usually created with `venv` or `python -m venv` command. Python version in virtual environment should match Python version used by Unit. Use `type` attribute to specify exact Python version.

**Comment by xinlingqudongX** [comment]
> Hello,
> 
> Unit use Python interpreter from libpython library, not as standalone interpreter. Check exact version from unit.log:
> 
> ```
> 2021/10/14 14:16:12.274 [notice] 11455#182089 module: python 3.7.6 ...
> ```
> 
> `home` is a _Path to the app’s virtual environment. Absolute or relative to working_directory._ (see https://unit.nginx.org/configuration/#python). Virtual environment usually created with `venv` or `python -m venv` command. Python version in virtual environment should match Python version used by Unit. Use `type` attribute to specify exact Python version.

谢谢回复，还有些问题
Thank you for your reply, there are still some questions
1.我的问题是因为Python找不到库，所以是我只需要将path指向site-packages路径，那么就可以搜索到了吗？
1. My question is because Python can't find the library, so I only need to point the path to the site-packages path, then can it be searched?
2.我在Unit的日志中看到了支持Python3.9，你给出的是Python3.7，是版本差异吗？
2. I saw support for Python 3.9 in the log of Unit. What you gave is Python 3.7. Is it a version difference?

**Comment by mar0x** [comment]
According to your configuration file, Python will try to find module `main` (and other imported modules) in the following paths:
1. `/home/project/ams` because of `"working_directory": "/home/project/ams"` and `"path": "./"` settings;
2. `/home/vdir/lib/python3.x/site-packages` (where `3.x` is replaced to the latest version available to Unit, see unit.log) because of `"home": "/home/vdir"`;

More information about your setup required before I can give you some particular recommendations:
- OS distribution and version;
- Unit version and installation method (pre-build, build from sources and exact commands etc.)
- `unit.log` content

Unit does support Python 3.9, but we build packages only for Python version(s) which is supported by particular OS distributive. If Python 3.9 is not yet supported by your distro, you may install Python 3.9 manually and build Unit module from source files.

**Comment by xinlingqudongX** [comment]
> According to your configuration file, Python will try to find module `main` (and other imported modules) in the following paths:
> 
> 1. `/home/project/ams` because of `"working_directory": "/home/project/ams"` and `"path": "./"` settings;
> 2. `/home/vdir/lib/python3.x/site-packages` (where `3.x` is replaced to the latest version available to Unit, see unit.log) because of `"home": "/home/vdir"`;
> 
> More information about your setup required before I can give you some particular recommendations:
> 
> * OS distribution and version;
> * Unit version and installation method (pre-build, build from sources and exact commands etc.)
> * `unit.log` content
> 
> Unit does support Python 3.9, but we build packages only for Python version(s) which is supported by particular OS distributive. If Python 3.9 is not yet supported by your distro, you may install Python 3.9 manually and build Unit module from source files.

你好，我遇到了新的编译问题
环境：Centos8
已安装Python：Python3.6.8、Python3.9.7
1.使用编译配置但是提示未找到文件或者目录
Compile configuration is used but the file or directory is not found
- 错误日志 error log
 build/autoconf.err

checking for Python
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
/bin/sh: line 1: -I/usr/include/python3.6m: No such file or directory
/bin/sh: line 2: -I/usr/include/python3.6m: No such file or directory
/bin/sh: line 3: -I/usr/include/python3.6m: No such file or directory
/bin/sh: line 4: -L/usr/lib64: No such file or directory
----------

        #include <Python.h>

        int main() {
            Py_Initialize();
            return 0;
        }
----------
- 编译命令 compile command
configure --prefix=/usr/local/unit --log=/var/log/unit.log && ./configure python --config="python3.6-config --libs --cflags"
- 目录存在的截图 Screenshot of directory existence
![微信截图_20211016143400](https://user-images.githubusercontent.com/26372348/137576641-e9755ea2-dfc2-449d-a887-dac62e4989a7.png)
![image](https://user-images.githubusercontent.com/26372348/137576700-38428cce-e6c6-4ddf-b7eb-ae7798dda7fb.png)

**Comment by mar0x** [comment]
@synodriver, this issue is not related to conda as well as your original report.

**Comment by synodriver** [comment]
Sorry for the misunderstood. My fault. So it seems related to the compile command？

**Comment by xinlingqudongX** [comment]
> Sorry for the misunderstood. My fault. So it seems related to the compile command？

多谢提醒，我看了下和我的问题不一样
Thanks for reminding, I looked at it and the question is different from mine

**Comment by xinlingqudongX** [comment]
> > compile command
> > ./configure python --config="python3.6-config --libs --cflags"
> 
> Why do you specify `--config="python3.6-config --libs --cflags"`? Have you read it somewhere? Where?
> 
> ```
> $ ./configure python --help
> 
>     --config=FILE         set python-config filename
> ...
> ```
> 
> Note the _filename_ word.
> 
> Please try `./configure python --config=python3.6-config`.

说明：我是用python3.6成功编译了，多谢，但是我想再编译python3.9的
Note: I successfully compiled with python3.6, thank you, but I want to compile python3.9 again
成功配置
Successful configuration
![unit_configure](https://user-images.githubusercontent.com/26372348/137612953-aaa21f50-2e15-43c6-85d8-fedab3b09d00.png)

因为下图这个错误，添加--embed选项是我查看了其他issues之后加上的
Because of the error in the following figure, the -- Embed option was added after I looked at other issues
![unit_make](https://user-images.githubusercontent.com/26372348/137612839-46180351-54a2-4765-a3d2-3aaf56fd23b1.png)
configure配置
configure command output
![image](https://user-images.githubusercontent.com/26372348/137612996-e4114a50-4541-417a-8cfa-e2720a772fae.png)
make配置
make command output
![unit_configure2](https://user-images.githubusercontent.com/26372348/137612877-458adb92-b554-4555-9ab9-224175fec612.png)

如何解决这个问题提示？How to solve this problem tip?
can not be used when making a shared object; recompile with -fPIC

我用过这个命令，但是提示：no such file or directory
I've used this command before, but it says: No such file or directory
./configure python --config="python-config --cflags"

**Comment by mar0x** [comment]
Please provide complete set of commands issued (starting from `hg clone` or `curl`), console output (in text format, not the screenshots) and `build/autoconf.err` file. (Note to put console output in file you may use `./configure 2>&1 | tee output.txt`)

**Comment by mar0x** [comment]
It is still not clear for me why do you specify --config="python3.6-config --libs --cflags" earlier? Have you read it somewhere? Where?

**Comment by xinlingqudongX** [comment]
> > Please provide complete set of commands issued (starting from `hg clone` or `curl`), console output (in text format, not the screenshots) and `build/autoconf.err` file. (Note to put console output in file you may use `./configure 2>&1 | tee output.txt`)
> 
> command：(./configure --prefix=/usr/local/unit --log=/var/log/unit.log && ./configure python --config=python-config)>output.txt [configure_output.txt](https://github.com/nginx/unit/files/7359983/configure_output.txt)
> 
> command：make > make.txt 2>&1 [make_output.txt](https://github.com/nginx/unit/files/7359986/make_output.txt)
> 
> 还需要其他提供的东西吗？谢谢你的帮助了 Do you need anything else provided? Thanks for your help
[autoerr_output.txt](https://github.com/nginx/unit/files/7359997/autoerr_output.txt)

**Comment by mar0x** [comment]
I've installed CentOS 8.4.2105 and python 3.9 (using `yum install python39-devel`) command. I have Python-3.9.2 installed and your issue is not reproduced.
How do you install `python-3.9.6`?

**Comment by mar0x** [comment]
It makes sense to use `make clean` or just `rm -rf build` before next configure attempt.

**Comment by mar0x** [comment]
> Try to add --cc-opt=-fPIC option to main Unit configure command (just as linker suggests).
> Also try to add --ld-opt=-fPIC too.

It seems to be the wrong way. Please ignore suggestions above.

It looks linker does not like the static library compilation option. It means the Python should be re-compiled with `-fPIC` option.
