### ISSUE TITLE
Conditional access logging

### ISSUE THREAD

**Issue by joachimBurket** [nginx/unit#594]
Hi there,

It would be great to be able to filter access logs by its content. I'm running my apps in a Kubernetes cluster, and have some healthchecks configured on '/readyz' and '/livez'. 
These checks are generating a lot of access logs, which make hard to see the important ones.

**Comment by VBart** [comment]
Any ideas on how such configuration may look like? Or maybe we just need to allow configuring access log in the router objects somehow?

**Comment by akalineskou** [comment]
in nginx we do it like this
```
# ignore health checks from logs
    map $request_uri $loggable {
        /health 0;

        default 1;
    }

    access_log /proc/self/fd/1 main if=$loggable;
```

This feature is a must since it does flood the access logs

**Comment by lcrilly** [comment]
Current thoughts for this are to provide an `if` object within the `access_log` configuration that provides very simple matching with variables or more complex matching with JavaScript expressions.

1. Only log requests that sent a session cookie (a non-empty string is considered true)
```json
{
  "access_log": {
    "if": "$cookie_session",
    "path": "…"
}
```

2. Do not log health check requests
```json
{
  "access_log": {
    "if": "`uri == '/health' ? false : true`",
    "path": "…"
}
```
