### ISSUE TITLE
Lua should be supported

### ISSUE THREAD

**Issue by gtfcugb** [nginx/unit#60]
Lua is borned to be a glue language，and it is very powerful。also multithead mode should be supported。

**Comment by VBart** [comment]
It seems, Lua doesn't have any standard interface for web-applications, like WSGI (Python), SAPI (PHP), Rack (Ruby), PSGI (Perl).

How it should be supported?

Please note, that Unit supports various language modules not for scripting, but to run web applications written on them.

**Comment by netroby** [comment]
If you want to programing with lua, you can try openresty. it may fill your need
