### ISSUE TITLE
Native Windows build

### ISSUE THREAD

**Issue by hifron** [nginx/unit#604]
Would be there native Windows build? Currently there is also problem with building on Windows, maybe using cmake or another tool would help...

**Comment by VBart** [comment]
You can use WSL2, there's should be any problem.

**Comment by hifron** [comment]
According [WSL FAQ](https://docs.microsoft.com/en-us/windows/wsl/faq) _is primarily a tool for developers, or deploying to Linux server environments_ and Windows developers, environment or solutions may vary...

**Comment by VBart** [comment]
@hifron Unit doesn't support native Windows interfaces and never will. It has architecture based on POSIX principles and highly tuned for *nix kernels. There's just no way to run it on Windows without WSL2.

**Comment by hifron** [comment]
Cygwin do a lot of amazing things without WSL2, but that's community project not much responding to evolving world...

**Comment by VBart** [comment]
Cygwin wouldn't help. It's just limited and slow emulation of POSIX, while Unit utilizes much more than that. Even Microsoft gave up trying to emulate *nix interfaces over winapi in WSL1 and come up with full virtualisation of Linux kernel in WSL2.

**Comment by hifron** [comment]
MS had unix services in historic versions of Windows, but abandon that. HW could help where there is soft problem(but that's problem), but differences between platform for graphics (even between graphics of same vendor on same platform) were benchmarked with various tests and journalist like Phoronix even create own benchmark tests for that (some time with Windows test for this graphic adventures).

In this(game) industry, there are various solutions for proper use of their techs and in UNIX industry could take some advantage from this.

**Comment by Pen-y-Fan** [comment]
I had problems getting Unit installed using WSL2, I did manage to get it working and documented it:

- [How to Install NGINX Unit on WSL 2 (Ubuntu)](https://pen-y-fan.github.io/2022/07/26/how-to-install-nginx-unit-on-wsl-2-ubuntu/)

I hope this will help others.

**Comment by lcrilly** [comment]
Thanks for sharing, @Pen-y-Fan - this is a great resource!
