### ISSUE TITLE
Provide images for alternative architectures (ARM/aarch64, ppc64le)

### ISSUE THREAD

**Issue by mgiessing** [nginx/unit#606]
Hi, would it be possible to provide container images for alternative CPU architectures such as aarch64, or ppc64le?

I'm able to build these with minimal changes on Power Systems (and would potentially create a PR to support that) but would like  to understand what kind of CI toolchain you use in order to understand if that setup supports these architectures.

Thanks!

**Comment by thresheek** [comment]
The code we use as a part of release process to build the images is at https://github.com/nginx/unit/blob/master/pkg/docker/Makefile

I think it can be adapted to use qemu/binfmt_misc to build for aarch64/ppc64le too, and create manifests for the resulting images.

Ref: https://github.com/multiarch/qemu-user-static/blob/master/docs/examples.md or even maybe https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408 these days.

**Comment by thresheek** [comment]
And then I'm not sure about the feasibility of `ppc64le` images from effort to usefulness ratio. `aarch64` is another story though, being widely available.

**Comment by robd003** [comment]
I'd like to use unit on AWS Graviton2 instances. Could you please make an ARM64 image available?

This would also let people with new M1 Mac's use unit in docker.

**Comment by thresheek** [comment]
Thanks for the comment @robd003 !

We are currently in a process of moving Unit docker images to become official (as in https://github.com/docker-library/official-images/#what-are-official-images) - and we aim to get at least arm64 and ppc64le images published when it's done.

I'll post a link here to track the PR once we have it ready to be submitted.

**Comment by aehlke** [comment]
Pardon for the ping, but is there somewhere better to track progress on this, or any update on workarounds? Trying to build on my M1 for local dev. Hard to use for app stack otherwise. Thanks

**Comment by robjr** [comment]
Facing the same issue here. It'd be great to have the images released for M1.

**Comment by JanMikes** [comment]
Hi, what i am using on my M1 is:
```
# clone the repo, just do once, otherwise fetch/pull if you need newer changes
git clone https://github.com/nginx/unit.git

cd pkg/docker

# this builds and tags image as unit:1.26.1-php for example
make build-php

# tag, so it is same as official image
docker tag unit:1.26.1-php docker.io/nginx/unit:1.26.1-php8.1
```

**Comment by tippexs** [comment]
Hi Folks! Thanks for reaching out. Currently the build of official packages is ongoing.

The build for dev on Mac is valid concern. I will put a detailed and scripted documentation till the packages are ready.
Timo

**Comment by tippexs** [comment]
> Hi, what i am using on my M1 is:
> 
> ```
> 
> # clone the repo, just do once, otherwise fetch/pull if you need newer changes
> 
> git clone https://github.com/nginx/unit.git
> 
> 
> 
> cd pkg/docker
> 
> 
> 
> # this builds and tags image as unit:1.26.1-php for example
> 
> make build-php
> 
> 
> 
> # tag, so it is same as official image
> 
> docker tag unit:1.26.1-php docker.io/nginx/unit:1.26.1-php8.1
> 
> ```
> 
> 
> 
> For more info, explore the [makefile](https://github.com/nginx/unit/blob/master/pkg/docker/Makefile).

Thanks for this!!

**Comment by maffinca69** [comment]
@JanMikes Hi, thanks for your solution! On her based i created commit which added support Mac M1 chip and updated php image to 8.2 version
For full work you need build changed image on your mac
P.S. I getting problems with use alpine version image, so use cli version
https://github.com/maffinca69/unit/commit/fbfc67ff6fb775eca3697ceb744443bfcd4bdfb2

**Comment by 0x6f677548** [comment]
Hi, sorry to ping, but any progress on this? It would be great to have arm published images…

**Comment by brunohenriquy** [comment]
Hello, need it here as well for M1! How is the progress on it?

**Comment by thresheek** [comment]
Hi,

This will be implemented once Unit is accepted to the Docker Official Images program: https://github.com/docker-library/official-images/pull/11542

**Comment by 0x6f677548** [comment]
For those that missed the news (like me), it seems arm64v8/amd64 images are now available in the official docker images: https://hub.docker.com/_/unit 

Since I was looking for a slim version of Python targeting arm64, I had to make the image myself.  The command is straightforward using buildx (qemu), but I've written a small makefile to allow some automation. 
If you need to target other platforms, or variants, it might help: https://github.com/0x6f677548/nginx-unit/blob/branches/packaging/pkg/docker/buildx.Makefile

You'll need to set up your docker hub repo, and [buildx ](https://docs.docker.com/build/building/multi-platform/) on your docker desktop.

**Comment by thresheek** [comment]
Thanks @0x6f677548!

Indeed, we've published the official images with arm64 some time ago, but waited for 1.30.0 to officially notify about it.
Note that you'd need to adapt your Makefile for 1.30.0, since I've changed the build process a bit (you'd need to redefine VERSIONS_*).

All in all, arm64 support is now there and ready.   I'm actively looking for a feedback if we'd really need ppc64le support for our images.

**Comment by 0x6f677548** [comment]
> For those that missed the news (like me), it seems arm64v8/amd64 images are now available in the official docker images: https://hub.docker.com/_/unit
> 
> Since I was looking for a slim version of Python targeting arm64, I had to make the image myself. The command is straightforward using buildx (qemu), but I've written a small makefile to allow some automation. If you need to target other platforms, or variants, it might help: https://github.com/0x6f677548/nginx-unit/blob/branches/packaging/pkg/docker/buildx.Makefile
> 
> You'll need to set up your docker hub repo, and [buildx ](https://docs.docker.com/build/building/multi-platform/) on your docker desktop.

I dropped the forked repo that contained this script and publish the new makefiles on a dedicated repo, in case anyone needs to create multi-arch/slim versions: 
https://github.com/0x6f677548/nginx-unit-buildx
Hope it helps other folks.

**Comment by callahad** [comment]
As mentioned, aarch64 is now part of our official release. We don't have hands-on experience with the POWER architecture, so I'm going to close this as wontfix. However, patches are welcome if someone wants to step up and take responsibility for ensuring that we build and run properly on that architecture.

**Comment by 0x6f677548** [comment]
and python-slim are also published as part of latest release, which is great. many thanks!
