### ISSUE TITLE
Ssl Mixed Content Works only during restart

### ISSUE THREAD

**Issue by dedfft** [nginx/unit#608]
Hello dear community. Please advise, maybe you can assume what is wrong here. People from linux comminute assumed that it is nginx bug.

Initially, I noticed on the seatables application when trying to open the table in the browser (network track), requests were shown as mixed content warning and nothing was opened over https protocol. 
But if you disable https redirection in the panel, then everything worked. So via http.

A similar problem is now with the n8n application
Here is the test deployed n8n app If you click execute workflow, it will be executed without errors via http. 
But over https any actions hang and do not give the result. (I am 99% sure that content warning is similar to the previous application)

Take a look : (Maybe this behavior nginx will tell you something)
I accidentally noticed this anomaly:  recorded a video.
https://www.loom.com/share/40c02ed969324c5bb65e4fabfc02adea

I comment: in the application, as a standard, I press execute a cube (get request, for example) while the https protocol is enabled - it hangs up as always.

But!! , if at this moment you update the nginx settings (if you press save & update in the console, then the caprover reloads this instance and nginx settings), then the REQUEST WILL BE FULFILLED!)
 Then, of course, 10-15 seconds error 502, the container is loaded. And again you can refresh the page and it won’t work when you push it.

Maybe you have any suggestions what this might be related to?

**Comment by VBart** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
