### ISSUE TITLE
feature request: nginx's http_access_module (allow / deny) functional

### ISSUE THREAD

**Issue by TheFatal** [nginx/unit#612]
Thanks again for Unit.

Please add something similar to nginx's http_access_module (allow / deny) functional, it would be wery cool too !

**Comment by shmux8** [comment]
Indeed. Due to Unit architecture, dynamic allow/deny lists will be extremely useful for real applications.

**Comment by VBart** [comment]
How do you see this functionality? Because currently it seems easy to configure using [route matching conditions](https://unit.nginx.org/configuration/#matching-conditions) in combination with [the `return` option](https://unit.nginx.org/configuration/#instant-responses-redirects).

**Comment by shmux8** [comment]
@VBart Thank you for pointing to this! Is there a chance to include allow/deny lists in documentation as a particular example?

**Comment by tippexs** [comment]
@artemkonev this could be a great example for a new how to section about routing / advanced routing. I know the documents road map is more than full 😬

**Comment by artemkonev** [comment]
https://unit.nginx.org/configuration/#instant-responses-redirects
