### ISSUE TITLE
unable to load python 3.10 module 

### ISSUE THREAD

**Issue by sandeep-gh** [nginx/unit#614]
I have compile unit with python 3.10 support. The unit is not able to load the python module. The log file reports error: 
```
dlopen("/home/shared/Builds/unit-1.26.0//modules/python3.10.unit.so"), failed: "Cannot load specified object"
```
Although I have turned on debug, there is no other info on why the load is failing. 
The ldd information is as follows:
```
ldd python3.10.unit.so
python3.10.unit.so:
        Start            End              Type  Open Ref GrpRef Name
        0000000ae9c18000 0000000ae9c68000 dlib  2    0   0      /home/shared/Builds/unit-1.26.0/modules/python3.10.unit.so
        0000000b28ed1000 0000000b29222000 rlib  0    1   0      /home/shared/Builds/Python-3.10.0/lib/libpython3.10.so.1.0
        0000000ab1380000 0000000ab13b8000 rlib  0    4   0      /usr/lib/libpthread.so.26.1
        0000000aeda0c000 0000000aeda4c000 rlib  0    2   0      /usr/lib/libutil.so.15.1
        0000000b26ba0000 0000000b26c05000 rlib  0    2   0      /usr/lib/libm.so.10.1
        0000000b3bf54000 0000000b3c015000 rlib  0    1   0      /usr/local/lib/eopenssl11/libssl.so.11.6
        0000000bad813000 0000000bada89000 rlib  0    2   0      /usr/local/lib/eopenssl11/libcrypto.so.11.6

bsdim1% ldd unitd
unitd:  
        Start            End              Type  Open Ref GrpRef Name
        0000001283220000 00000012832c9000 exe   2    0   0      unitd
        0000001713ef4000 0000001713fb5000 rlib  0    1   0      /usr/local/lib/eopenssl11/libssl.so.11.6
        00000016e7747000 00000016e79bd000 rlib  0    2   0      /usr/local/lib/eopenssl11/libcrypto.so.11.6
        000000175a583000 000000175a5e8000 rlib  0    1   0      /usr/lib/libm.so.10.1
        00000016b9923000 00000016b995b000 rlib  0    3   0      /usr/lib/libpthread.so.26.1
        000000170e767000 000000170e7ea000 rlib  0    1   0      /usr/local/lib/libpcre2-8.so.0.6
        00000016ae103000 00000016ae207000 rlib  0    1   0      /usr/lib/libc.so.96.1
        0000001757950000 0000001757950000 ld.so 0    1   0      /usr/libexec/ld.so
```
It took quite a bit of effort to reach this far only to see it fail  with now good error messages.

**Comment by mar0x** [comment]
Hello.
Please share
- the OS distribution you are using;
- the way you installed Python 3.10 into `/home/shared`;
- exact configure command(s) and Python module configure and make output;

Note: it makes sense to use Unit-1.26.1. This issue most likely is still there, but some other critical bugs are fixed.

**Comment by sandeep-gh** [comment]
Hello, 

   These are the details:
- OS: OpenBSD 7.0
- Python install command: `./configure --prefix=/home/shared/Builds/Python-3.10.0 --enable-optimizations --with-lto --with-computed-gotos --with-system-ffi --with-openssl-rpath=auto --with-openssl=/usr/local --enable-shared`
- unit configure: `./configure --prefix=/home/shared/Builds/unit --debug  --openssl  --user=www --group=www --ld-opt="-L/usr/local/lib/eopenssl11/ -Wl,-rpath /usr/local/lib/eopenssl11/ -lssl -lcrypto"  --cc-opt="-fPIC -I/usr/local/include/eopenssl11" --debug`
- unit python module configure: 
   `./configure  python --config=/home/shared/Builds/Python-3.10.0/bin/python3.10-config`
 
Have added make output for unit and python modules.  Thanks for taking a look. 

[make_pymod.txt](https://github.com/nginx/unit/files/7687003/make_pymod.txt)

[make.txt](https://github.com/nginx/unit/files/7686985/make.txt)

**Comment by mar0x** [comment]
Thanks for information.

It looks the reason is the absence of `rpath` for libpython. Maybe your have `LD_LIBRARY_PATH` when running `ldd` (please confirm).

Try to re-configure Python module with `--libpath=/home/shared/Builds/Python-3.10.0/lib` option and then `make`.

**Comment by sandeep-gh** [comment]
That was the issue. LD_LIBRARY_PATH was set when using ldd but not when running unitd. "--lib-path" setting also worked. Thanks so much for fixing this promptly.
