### ISSUE TITLE
php extension path  in options not load extension

### ISSUE THREAD

**Issue by Alexufo** [nginx/unit#619]
I can override php.ini settings, for example "upload_max_filesize": "16M"

	"applications": {
		"php": {
			"type": "php7.2",
			"user": "root",
			"group": "root",
			"root": "/home/alex/r/",
			"options": {
				"file": "/etc/php/7.2/embed/php.ini",
				"admin": {
					"memory_limit": "256M",
					"enable_dl": "true",
					"expose_php": "0",
					"error_log": "/home/alex/php_error.log",
					"display_errors": "1",
					"zlib.output_compression": "1",
					"post_max_size": "8M",
					"upload_max_filesize": "16M"
				}
			}
		}
	}
But I cant load extension `"extension" :  "/home/alex/samples/phpS.so"`

Directly in php.ini my extension loaded successfully  `extension=/home/alex/samples/phpS.so` but not in unit config :-(

**Comment by VBart** [comment]
That is the PHP interpreter limitation.  See the official manual here: https://www.php.net/manual/en/ini.list.php
The `extension` option can be changed in "php.ini only".

**Comment by VBart** [comment]
But I think we can try to workaround this limitation and provide ability to specify `extension` in the configuration as well.

**Comment by Alexufo** [comment]
Yes it is interesting! Because unit config will become as full portable config for any php environment
