### ISSUE TITLE
mkstemp - No such file or directory

### ISSUE THREAD

**Issue by doolijb** [nginx/unit#620]
Running a Django application with Unit on Ubuntu/DirectAdmin with Apache.

Client can't upload files through the web application. Worked fine on cPanel before migrating to DirectAdmin/NGINX Unit so I'm fairly sure it's not a configuration issue with the application.

unit.log reads:
```
2021/12/11 21:37:01 [alert] 817#882 *21 mkstemp(/usr/tmp/req-XXP6jxDX) failed (2: No such file or directory)
```

**Comment by mar0x** [comment]
Hello.
Please check the directory `/usr/tmp` exists and your application has permissions to read and write there.

**Comment by doolijb** [comment]
I created /usr/tmp and chmodded it with public permissions for troubleshooting as well. No dice.

**Comment by mar0x** [comment]
Please share more information about your setup:
- OS distribution;
- Unit version and source (packages, build from sources, etc)
- Exact app versions;
- configuration file(s).

Since you've _created_ the directory, I assume it does not exists before. Am I right?

**Comment by doolijb** [comment]
Sorry I knew better.

- Ubuntu 20.04 x64, DirectAdmin
- Unit v. 1.26.1 - Distributed through DirectAdmin
- Django 3.1.8, Django Filer 2.0.2 (For file uploading, management)
- Unfortunately, I've scoured the directories and I'm now sure where DirectAdmin places the Unit conf.

**Comment by mar0x** [comment]
Thanks for the update.
Am I right thinking the directory is not created yet (since you not get the response from DA)?
If yes, please test again after directory creation.

**Comment by doolijb** [comment]
```
If yes, please test again after directory creation.
```
Already tried, even with public chmod.

DA has responded, but I'm troubleshooting getting them connected via SSH right now.

Env variables while I have them in front of me.

```
root@host:~# printenv
SHELL=/bin/bash
PWD=/root
LOGNAME=root
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/root
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=73.169.234.201 40918 45.32.228.31 50900
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=root
SHLVL=1
XDG_SESSION_ID=8
XDG_RUNTIME_DIR=/run/user/0
SSH_CLIENT=73.169.234.201 40918 50900
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
SSH_TTY=/dev/pts/0
_=/usr/bin/printenv
```

**Comment by doolijb** [comment]
Weird, I used 777 to chmod this time for /usr/tmp and the issue resolved. Not sure what caused it to use /usr/tmp in the first place.

**Comment by mar0x** [comment]
It makes sense to rise the ticket to DA asking to re-configure Unit with something like `--tmp=/tmp`. `/tmp` always exists and usually mounts as `tmpfs` instead of persistent data storage.

**Comment by VBart** [comment]
In our packages we use `/var/tmp`. It doesn't make much sense to put it on `tmpfs`, as the main reason why big request bodies are dumped to a file is to avoid occupying memory (and swap space) by those bodies. Otherwise, you can just have bigger body buffers and avoid additional syscalls related to file operations.

**Comment by doolijb** [comment]
@mar0x DA has pushed an update with your suggested changes.
