### ISSUE TITLE
PHP 8.1 official images

### ISSUE THREAD

**Issue by zlodes** [nginx/unit#621]
Some time ago official docker images for PHP 8.1 released: https://hub.docker.com/_/php?tab=tags&page=1&name=8.1

Is it possible to release nginx unit images with PHP 8.1?

**Comment by kopotp** [comment]
also can't w8 for it to be released 😊

**Comment by Elnadrion** [comment]
Same 😅

**Comment by mrdurb** [comment]
Me too

**Comment by thresheek** [comment]
It will probably land in the next release.

Meanwhile you can build one yourself, see http://unit.nginx.org/installation/#docker-images "Customizing Language Versions In Docker Images":
```
git clone https://github.com/nginx/unit
cd unit
git checkout 1.26.1
cd pkg/docker/
make build-php8.1 VERSION_php=8.1
```

When this succeeds, you will have a local image tagged `unit:1.26.1-php8.1`.

**Comment by lokkivan** [comment]
Me too

**Comment by thresheek** [comment]
Well Christmas came early, please enjoy `nginx/unit:1.26.1-php8.1`: https://hub.docker.com/layers/nginx/unit/1.26.1-php8.1/images/sha256-d66b375b3e900a63b0908c7fe6b82a62c492c8282f3174cdd5e76cfbaff6cd28?context=explore

We'll update the documentation shorty to reflect its availability.

**Comment by Elnadrion** [comment]
@thresheek thanks a lot :)
