### ISSUE TITLE
[SUGGESTION] Smaller python3 docker image

### ISSUE THREAD

**Issue by rsaleev** [nginx/unit#622]
I see that you use official bullseye image, but even without any static files or uploads your image is too large ~900MB. Is it possible to migrate to slim version? Time for microservices.

**Comment by thresheek** [comment]
While I agree that making the image smaller is a good cause, the documentation on the "slim" image states:

"Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository."

I'm not too sure that changing the current "fat" image to a "slim" variant is justified just by the size (although 1G is quite big), especially considering current users would need to fix their pipelines.  Providing an additional slim variant could be an option, though.

**Comment by robd003** [comment]
Please make sure that whichever python image you use it still uses glibc. **Lots** of C based modules will break if you aren't using glibc.

**Comment by thresheek** [comment]
Definitely, alpine-based images are out of question for this effort.

**Comment by TBK** [comment]
Python has implemented musl support https://www.python.org/dev/peps/pep-0656/ so Alpine will be a viable option in the "near" future.

An example of a pkg that already supports musl - https://pypi.org/project/gevent/#files
