### ISSUE TITLE
ReactJS App deployed on kubernetes being served by Nginx is not working

### ISSUE THREAD

**Issue by shahid-mushtaq** [nginx/unit#623]
i have deployed my react app on kubernetes - Master - Slave i am successfully able to brose my deployed application when i use following nginx settings on my website domain.

location / {

    proxy_cookie_domain $host ****.com;       
    proxy_pass_header Set-Cookie;
     
    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
    
    proxy_ssl_name ****.com;
    
    proxy_redirect off;
    proxy_ssl_session_reuse on;
    proxy_ssl_certificate /etc/letsencrypt/live/****/fullchain.pem;
    proxy_ssl_certificate_key /etc/letsencrypt/live/****/privkey.pem;

    
    
    proxy_pass https://****:32494; 
} 
then it works fine it load relative deployed app

but when i changes location / as following

location /service_authentication {

    proxy_cookie_domain $host ****.com;       
    proxy_pass_header Set-Cookie;
     
    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
    
    proxy_ssl_name ****.com;
    
    proxy_redirect off;
    proxy_ssl_session_reuse on;
    proxy_ssl_certificate /etc/letsencrypt/live/****/fullchain.pem;
    proxy_ssl_certificate_key /etc/letsencrypt/live/****/privkey.pem;

    
    
    proxy_pass https://****:32494; 
}
it does not related application.

**Comment by mar0x** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html
