### ISSUE TITLE
Issue: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by MuhammadMunir12** [nginx/unit#624]
I am trying to run the nginx on Openshift 4.6, but facing this error message. The image is pulled but container is not starting because of this error message. 
I have following permissions set for the file used in configmaps. 
```
drwxr-xr-x 3 root root 4096 Jul 26 07:33 /etc/nginx
drwxr-xr-x 2 root root 4096 Jul 26 07:33 /etc/nginx/conf.d
-rw-r--r-- 1 root root 3957 Jul 11 13:06 /etc/nginx/mime.types
drwxr-xr-x 2 root root 4096 Jul 11 13:06 /var/cache/nginx
drwxr-xr-x 1 root root 4096 Jul 26 07:34 /var/log/nginx
drwxr-xr-x 4 root root 4096 Jul 23 00:00 /var/run
```

Any help would be appreciated.

**Comment by mar0x** [comment]
This is issue tracker for **Unit** web and application server. See: https://unit.nginx.org/ for details.

Please use nginx support options for everything related to nginx server: http://nginx.org/en/support.html

I would suggest to adjust the permissions for `/var/cache/nginx`, but I'm not an expert :)
