### ISSUE TITLE
How to change the install php 8.1 application in the configuration file?

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit#625]
The documentation does not indicate about changing the php version. Containers support different images, how can I do this in the config file? For example
<img width="756" alt="Screenshot 2021-12-23 at 3 31 10 PM" src="https://user-images.githubusercontent.com/49598333/147240931-2360a7ce-4270-46b6-9ccb-c7cd5d3390d5.png">
This configuration only applies php 8.0, not php 8.1
<img width="767" alt="Screenshot 2021-12-23 at 3 32 20 PM" src="https://user-images.githubusercontent.com/49598333/147241049-1737f930-1cc3-455f-815a-a30c3cdebfdb.png">

**Comment by mar0x** [comment]
Hello.
You need a Unit module for PHP 8.1. Most likely it needs to be built from sources. Please read the [Building from Source](https://unit.nginx.org/howto/source/#) article.

**Comment by Pavlusha311245** [comment]
> Hello. You need a Unit module for PHP 8.1. Most likely it needs to be built from sources. Please read the [Building from Source](https://unit.nginx.org/howto/source/#) article.

How can this problem be solved? Python has a choice of version. I think that you can make a feature out of this, so that every time you do not need to compile from source for each versio
<img width="520" alt="Screenshot 2021-12-23 at 4 24 48 PM" src="https://user-images.githubusercontent.com/49598333/147246814-8b78f0d3-259a-4f38-8483-67aac498ce3a.png">
n

**Comment by mar0x** [comment]
Once you have a modules for multiple versions available for Unit, you can choose the version in the configuration.

**Comment by Pavlusha311245** [comment]
> 



> If you need a detailed instructions, please provide more information about your setup:
> 
> * OS distribution, version;
> * Exact Unit version;
> * Method of installation (pre-packaged, build from sources with commands);
> * Method of PHP 8.1 installation;
> * Other information related to your application (requirements etc.);

1. Ubuntu 21.10 x86_64 (Server)
    Kernel 5.13.19-2-pve 
2. v1.26.1
3. 
```bash
sudo apt install unit unit-php
```
4. 
```bash
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
```
5. Laravel application
Install PHP extensions
```bash
sudo apt install php8.1-common php8.1-dom php8.1-bcmath openssl php8.1-mbstring
```
Install composer and build
```bash
sudo apt install composer
composer create-project laravel/laravel
```

**Comment by mar0x** [comment]
1. install required php8.1 headers and libraries
```
sudo apt install php8.1-dev libphp8.1-embed
```
2. download and unpack Unit sources
```
curl -O https://unit.nginx.org/download/unit-1.26.1.tar.gz
tar xzf unit-1.26.1.tar.gz
cd unit-1.26.1
```
3. configure Unit and php8.1 module
```
./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tmp=/var/tmp --user=unit --group=unit --tests --openssl --modules=/usr/lib/unit/modules --libdir=/usr/lib/x86_64-linux-gnu
./configure php --module=php81 --config=php-config8.1
```
4. build php8.1 module
```
make php81
```
5. install php8.1 module
```
sudo make install php81-install
```
6. restart Unit
```
sudo system unit restart
```
7. make sure module is found by Unit
```
sudo grep php81 /var/log/unit.log
```

Now your default (most recent) php is 8.1. To use php 7.4, specify `"type": "php 7"` in config.

**Comment by Pavlusha311245** [comment]
> 1. install required php8.1 headers and libraries
> 
> ```
> sudo apt install php8.1-dev libphp8.1-embed
> ```
> 
> 2. download and unpack Unit sources
> 
> ```
> curl -O https://unit.nginx.org/download/unit-1.26.1.tar.gz
> tar xzf unit-1.26.1.tar.gz
> cd unit-1.26.1
> ```
> 
> 3. configure Unit and php8.1 module
> 
> ```
> ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tmp=/var/tmp --user=unit --group=unit --tests --openssl --modules=/usr/lib/unit/modules --libdir=/usr/lib/x86_64-linux-gnu
> ./configure php --module=php81 --config=php-config8.1
> ```
> 
> 4. build php8.1 module
> 
> ```
> make php81
> ```
> 
> 5. install php8.1 module
> 
> ```
> sudo make install php81-install
> ```
> 
> 6. restart Unit
> 
> ```
> sudo system unit restart
> ```
> 
> 7. make sure module is found by Unit
> 
> ```
> sudo grep php81 /var/log/unit.log
> ```
> 
> Now your default (most recent) php is 8.1. To use php 7.4, specify `"type": "php 7"` in config.

### Thanks for the detailed instructions. She helped.
My wishes for the next releases:

- Add php version selection (at least 8 and 8.1)
- Add the database extension image (pdo, pdo_ppgsgl) to the docker. Not enough to fully launch Laravel according to the instructions -> https://unit.nginx.org/howto/laravel

**Comment by mar0x** [comment]
If your wishes are no longer related to this issue, it makes sense to close the issue.

Pre-build Unit PHP modules is restricted by PHP version(s) for particular distributive, so you'd better write the letter to Santa at Ubuntu.

Consider to use [unit-php8.1 image](https://github.com/nginx/unit/issues/621#issuecomment-999490063), add your layer for required extensions and wishes come true almost instantly!

**Comment by Pavlusha311245** [comment]
Thank you for your reply, Merry Christmas.

> If your wishes are no longer related to this issue, it makes sense to close the issue.
> 
> Pre-build Unit PHP modules is restricted by PHP version(s) for particular distributive, so you'd better write the letter to Santa at Ubuntu.
> 
> Consider to use [unit-php8.1 image](https://github.com/nginx/unit/issues/621#issuecomment-999490063), add your layer for required extensions and wishes come true almost instantly!

Thank you for your reply, Merry Christmas.

**Comment by VBart** [comment]
@Pavlusha311245 Your PHP interpreter is installed from a 3rd-party repository, then you should either build Unit module yourself (as you did using @mar0x instruction) or ask owner of this repository to start doing it.

There are endless number of 3rd-party repositories, it's impossible to provide modules for each of them. Our modules are provided only for the official repositories.
