### ISSUE TITLE
web acess ip view "HTTP ERROR 502" ,nginx  :9589#9589: signal 15 (SIGTERM) received from 11124, exiting

### ISSUE THREAD

**Issue by awmbtc** [nginx/unit#626]
<details> 
  <summary>nginx error log</summary>

```
[root@awmbtc ~]# tail /var/log/nginx/error.log 
2021/12/24 10:48:00 [notice] 9589#9589: signal 29 (SIGIO) received
2021/12/24 10:53:01 [notice] 9589#9589: signal 15 (SIGTERM) received from 11124, exiting
2021/12/24 10:53:01 [notice] 10252#10252: exiting
2021/12/24 10:53:01 [notice] 10252#10252: exit
2021/12/24 10:53:01 [notice] 10251#10251: exiting
2021/12/24 10:53:01 [notice] 10251#10251: exit
2021/12/24 10:53:01 [notice] 9589#9589: signal 17 (SIGCHLD) received from 10252
2021/12/24 10:53:01 [notice] 9589#9589: worker process 10252 exited with code 0
2021/12/24 10:53:01 [notice] 9589#9589: worker process 10251 exited with code 0
2021/12/24 10:53:01 [notice] 9589#9589: exit
```
</details>

<details> 
  <summary>unit log</summary>

```
[root@awmbtc ~]# tail /var/log/unit/unit.log
2021/12/24 10:54:41 [info] 1545#1545 "script_index_php" prototype started
2021/12/24 10:54:41 [info] 1546#1546 "script_index_php" application started
2021/12/24 10:54:41 [info] 1547#1547 "script_index_php" application started
2021/12/24 10:54:41 [info] 1548#1548 "script_index_php" application started
2021/12/24 10:54:41 [info] 1549#1549 "script_index_php" application started
2021/12/24 10:54:41 [info] 1550#1550 "script_index_php" application started
2021/12/24 10:54:41 [alert] 1229#1229 sendmsg(19, -1, -1, 1) failed (32: Broken pipe)
2021/12/24 10:54:41 [notice] 1229#1229 app process (isolated 1231) exited with code 0
2021/12/24 10:54:41 [notice] 1229#1229 app process (isolated 1230) exited with code 0
2021/12/24 10:54:41 [notice] 1192#1192 process 1229 exited with code 0
```
</details>

unit status
```
unit.service - NGINX Unit
   Loaded: loaded (/usr/lib/systemd/system/unit.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-12-24 10:53:25 CST; 18min ago
 Main PID: 1192 (unitd)
    Tasks: 11 (limit: 23697)
   Memory: 31.5M
   CGroup: /system.slice/unit.service
           ├─1192 unit: main v1.26.1 [/usr/sbin/unitd --log /var/log/unit/unit.log --pid /run/unit/unit.pid --no-daemon]
           ├─1225 unit: controller
           ├─1226 unit: router
           ├─1545 unit: "script_index_php" prototype
           ├─1546 unit: "script_index_php" application
           ├─1547 unit: "script_index_php" application
           ├─1548 unit: "script_index_php" application
           ├─1549 unit: "script_index_php" application
           └─1550 unit: "script_index_php" application

Dec 24 10:53:25 awmbtc systemd[1]: Started NGINX Unit.
Dec 24 10:53:25 awmbtc unitd[1192]: 2021/12/24 10:53:25 [info] 1192#1192 unit 1.26.1 started
```

<details>
  <summary>wordpress conf</summary>

```json
{
    "listeners": {
        "127.0.0.1:8090": {
            "application": "script_index_php"
        },
        "127.0.0.1:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "index": "index.php"
        }
    }
}
```
</details>

<details>
  <summary>/etc/nginx/niginx.conf</summary>

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```
</details>

<details>
  <summary>/etc/nginx/conf.d/default.conf</summary>

```
upstream index_php_upstream {
    server 127.0.0.1:8090; # NGINX Unit backend address for index.php with
                           # 'script' parameter
}

upstream direct_php_upstream {
    server 127.0.0.1:8091; # NGINX Unit backend address for generic PHP file handling
}

server {
    listen      80;
    server_name localhost;
    root        /var/www/wordpress/;

    location / {
        try_files $uri @index_php;
    }

    location @index_php {
        proxy_pass       http://index_php_upstream;
        proxy_set_header Host $host;
    }

    location /wp-admin {
        index index.php;
    }

    location ~* .php$ {
        try_files        $uri =404;
        proxy_pass       http://direct_php_upstream;
        proxy_set_header Host $host;
    }
}
```
</details>

open page view 502
![image](https://user-images.githubusercontent.com/96400309/147311896-ff7fa88e-4d61-424a-a509-4131ee0e993f.png)

How do I fix this?

I've tried this several times, following the official nginx tutorials.

This is the second time I've done this, and after the first failure I reinstalled the host OS and redeployed all the applications, but the error is always there. Please help me out, thank you very much!

**Comment by awmbtc** [comment]
add：/var/www/wordpress/wordpress.config
`{
    "listeners": {
        "127.0.0.1:8090": {
            "application": "script_index_php"
        },
        "127.0.0.1:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "index": "index.php"
        }
    }
}
~      `

info:/var/www/wordpress/
`[root@awmbtc wordpress]# pwd 
/var/www/wordpress
[root@awmbtc wordpress]# ls -sl 
total 216
 4 -rw-r--r--  1 nginx nginx   405 Feb  6  2020 index.php
20 -rw-r--r--  1 nginx nginx 19915 Jan  1  2021 license.txt
 8 -rw-r--r--  1 nginx nginx  7346 Jul  6 20:23 readme.html
 4 -rw-r--r--  1 root  nginx   811 Dec 24 10:43 wordpress.config
 8 -rw-r--r--  1 nginx nginx  7165 Jan 21  2021 wp-activate.php
 4 drwxr-sr-x  9 nginx nginx  4096 Nov 11 01:24 wp-admin
 4 -rw-r--r--  1 nginx nginx   351 Feb  6  2020 wp-blog-header.php
 4 -rw-r--r--  1 nginx nginx  2328 Feb 17  2021 wp-comments-post.php
 4 -rw-r--r--  1 nginx nginx  3276 Dec 24 10:23 wp-config.php
 4 -rw-r--r--  1 nginx nginx  3004 May 21  2021 wp-config-sample.php
 0 drwxrwsr-x  4 nginx nginx    52 Nov 11 01:24 wp-content
 4 -rw-r--r--  1 nginx nginx  3939 Jul 31  2020 wp-cron.php
12 drwxr-sr-x 25 nginx nginx  8192 Nov 11 01:24 wp-includes
 4 -rw-r--r--  1 nginx nginx  2496 Feb  6  2020 wp-links-opml.php
 4 -rw-r--r--  1 nginx nginx  3900 May 16  2021 wp-load.php
48 -rw-r--r--  1 nginx nginx 45463 Apr  7  2021 wp-login.php
12 -rw-r--r--  1 nginx nginx  8509 Apr 14  2020 wp-mail.php
24 -rw-r--r--  1 nginx nginx 22297 Jun  2  2021 wp-settings.php
32 -rw-r--r--  1 nginx nginx 31693 May  8  2021 wp-signup.php
 8 -rw-r--r--  1 nginx nginx  4747 Oct  9  2020 wp-trackback.php
 4 -rw-r--r--  1 nginx nginx  3236 Jun  9  2020 xmlrpc.php`

**Comment by awmbtc** [comment]
add:/var/www/wordpress/wordpress.config

{
    "listeners": {
        "127.0.0.1:8090": {
            "application": "script_index_php"
        },
        "127.0.0.1:8091": {
            "application": "direct_php"
        }
    },

    "applications": {
        "script_index_php": {
            "type": "php",
            "processes": {
                "max": 20,
                "spare": 5
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "script": "index.php"
        },
        "direct_php": {
            "type": "php",
            "processes": {
                "max": 5,
                "spare": 0
            },
            "user": "nginx",
            "group": "nginx",
            "root": "/var/www/wordpress",
            "index": "index.php"
        }
    }
}

**Comment by awmbtc** [comment]
<img width="617" alt="WX20211224-113731@2x" src="https://user-images.githubusercontent.com/96400309/147313267-c56933eb-8de9-48b4-817e-ffa75621d4a9.png">
<img width="720" alt="WX20211224-113831@2x" src="https://user-images.githubusercontent.com/96400309/147313324-fb7389df-3a97-4374-bffd-fc47f91f3895.png">

/etc/nginx/niginx.conf
<img width="685" alt="WX20211224-113951@2x" src="https://user-images.githubusercontent.com/96400309/147313404-61474a4c-ff14-4844-b8db-cb1dadb810ed.png">

/etc/nginx/conf.d/default.conf
<img width="684" alt="WX20211224-114058@2x" src="https://user-images.githubusercontent.com/96400309/147313475-7d6e757c-f552-4b94-a111-221c352a8062.png">

**Comment by mar0x** [comment]
<img width="825" alt="Screenshot 2021-12-24 at 15 15 54" src="https://user-images.githubusercontent.com/17641893/147352108-8e129b45-49d0-46bf-b9a6-9777002e9f42.png">

Please try to follow updated [Wordpress HowTo](https://unit.nginx.org/howto/wordpress/).

**Comment by VBart** [comment]
@awmbtc Hi. First of all, this error looks like neither from nginx, nor from Unit and I doubt that it can come from WordPress.

I suggest these steps:
1. Verify that your request actually reaching your webserver at least by checking nginx access log
2. Enable and provide debug log in Unit: https://unit.nginx.org/troubleshooting/#debug-log

**Comment by VBart** [comment]
@awmbtc Also please provide the full logs, not just `tail` of them. Currently in your nginx logs only lines related to its shutdown are visible. Are you sure that your nginx is running?

**Comment by alejandro-colomar** [comment]
Closing due to no response.
