### ISSUE TITLE
Open files limit

### ISSUE THREAD

**Issue by swood** [nginx/unit#628]
Hello, does Unit have an analog for Nginx option `worker_rlimit_nofile` ?

I came across a situation like below:
```
2021/12/26 19:29:51 [info] 23661#23748 no available connections, close idle connection
2021/12/26 19:29:51 [alert] 23661#23753 accept4(29) failed (24: Too many open files)
```

**Comment by mar0x** [comment]
Hello. No, it does not have such option. You need to prepare the environment before start `unitd`.

**Comment by tippexs** [comment]
Depending on the OS you are using you can make changes to `/etc/security/limits.conf` or modify the `systemd` service definition and add `LimitNOFILE=16000 LimitNOFILESoft=16000` for example in the Service section. We will add a section about tuning and configure the server environment on our website.

**Comment by artemkonev** [comment]
The process is more or less similar to this: https://unit.nginx.org/troubleshooting/#core-dumps-linuxsystemd
