### ISSUE TITLE
Setup SSL in docker

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit#630]
## I want to ask a question about connecting ssl certificates for my container.
I transfer the config file and the certificate inside the container to the docker-entrypoint.d directory, the result can be seen below. I am interested in further steps, since I cannot follow the steps as in the documentation. How do I customize the config file? It is also shown below. The file does not contain an indication of tls certificates, because I do not know what to specify for the certificates key in order for it to work.
<img width="852" alt="Screenshot 2022-01-11 at 6 24 13 PM" src="https://user-images.githubusercontent.com/49598333/148970926-550c06f4-ca13-4441-bf94-a1c31e9d51a5.png">
<img width="426" alt="Screenshot 2022-01-11 at 6 24 41 PM" src="https://user-images.githubusercontent.com/49598333/148971002-e7636add-6e15-4baf-b80b-20399ae09605.png">

**Comment by Pavlusha311245** [comment]
@thresheek Can you reset the example config.json file? I will be grateful

**Comment by thresheek** [comment]
So here we go:
```
$ ls -l
-rw-r--r--  1 thresh 2953 Jan 12 12:47 cert.pem
-rw-r--r--  1 thresh  515 Jan 12 12:47 config.json
```
```
$ cat config.json
{
        "applications": {
                "example_php": {
                        "type": "php",
                        "processes": 2,
                        "root": "/usr/share/doc",
                        "index": "index.php"
                }
        },

        "listeners": {
                "*:8300": {
                        "pass": "applications/example_php",
                        "tls": {
                            "certificate": "cert"
                        }
                }
        }
}
```

I've added a tls section to a configuration json with a reference to the same bundle name that stores the certificate and the key.

**Comment by Pavlusha311245** [comment]
@thresheek I will definitely try and report the result. You can mark the issue with a question label
