### ISSUE TITLE
Get real ip Nginx & Unit

### ISSUE THREAD

**Issue by lacosteque** [nginx/unit#632]
**Versions:**
- Oracle Linux Server release 8.5 (core Linux 5.4.17-2136.302.7.2.el8uek.x86_64)
- podman version 3.3.1
- podman-composer version 1.0.3
- unit version: 1.26.1 - php8.0
- nginx version: nginx/1.21.5
- Official images on Docker Hub 

I can not get the real ip of the user.

The addresses inside the containers are as follows: 

- nginx - 10.88.2.3
- unit - 10.88.2.2

The only thing I see in nginx and PHP logs is - 10.88.2.3. 

If I configure services without containers according to manual [https://unit.nginx.org/howto/integration/](https://unit.nginx.org/howto/integration/) everything works thanks to _client_ip_.

**nginx unit.conf**

    {
    "listeners": {
    "*:8081": {
    "pass": "routes/unit",
    "client_ip": {
    "header": "X-Forwarded-For",
    "recursive": true,
    "source": ["0.0.0.0/0"]
    }
    }
    },
    "routes": {
    "unit": [
    {
    "match": {
    "uri": ["*.php", "*.php/*", "/wp-admin/"]
    },
    "action": {
    "pass": "applications/unit/direct"
    }
    },
    {
    "action": {
    "share": "/var/www/unit$uri",
    "fallback": {
    "pass": "applications/unit/index"
    }
    }
    }
    ]
    },
    "applications": {
    "unit": {
    "type": "php",
    "user": "unit",
    "group": "unit",
    "processes": {
    "max": 30,
    "spare": 1
    },
    "targets": {
    "direct": {
    "root": "/var/www/unit/"
    },
    "index": {
    "root": "/var/www/unit/",
    "script": "index.php"
    }
    }
    }
    }
    }

**nginx host.conf**

    upstream php_unit {

    server unit:8081;
    keepalive 32;

    }

    server {

    listen              	80;
    listen              	[::]:80;
    server_name	localhost;
    set                 	$base /var/www/;
    root                	$base/unit;

    location / {
        try_files 		$uri @index_php;
    }

    location @index_php {
      proxy_pass 	http://php_unit;
      include		proxy_params;
    }

    location ~* \.php$ {
      try_files		$uri =404;
      proxy_pass	http://php_unit;
      include		proxy_params;
    }

    }

**proxy_params**

	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_socket_keepalive on;
	proxy_http_version 1.1;
	proxy_set_header Connection "";
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	set_real_ip_from unit;
	real_ip_header X-Forwarded-For;
	real_ip_recursive on;

Ideally should help _set_real_ip_from_, but alas. Also, there is a version that RHLE 8 and its FirewallD is to blame when working with containers, but disabling it also did not help.

That said, without containers, all it takes is 

- proxy_set_header Host $host;
- proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 

for Nginx and 

- client_ip 

for Unit.

**Comment by VBart** [comment]
Hi.

Could you clarify this nginx setting in your config:
```
set_real_ip_from unit;
```
?

According to [the documentation](https://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from) it similar to "source" option of Unit and should contain addressed of proxy servers that set X-Forwarded-For header and redirect traffic to nginx.

What server in your config is responsible for passing proper client IP to nginx?

**Comment by lacosteque** [comment]
> 

Yes, I'm sorry. I didn't specify. The Unit in the Nginx configuration is the DNS name of the container where the Unit is deployed. 
**UNIT == ip 10.88.2.2** and in Nginx configuration you can specify direct IP (10.88.2.2) and it will be the same.  

**set_real_ip_from unit;**
or
**set_real_ip_from 10.88.2.2;**
doesn't matter, I don't get real ip anyway.

**Comment by VBart** [comment]
@lacosteque 
The Real IP module in nginx is used to receive the client IP address from the proxy in front of nginx. What proxy do you use in front of nginx?  You need to specify IP address of that proxy, not Unit.

**Comment by lacosteque** [comment]
> @lacosteque The Real IP module in nginx is used to receive the client IP address from the proxy in front of nginx. What proxy do you use in front of nginx? You need to specify IP address of that proxy, not Unit.

Maybe this modul is not needed, it was an attempt to solve the problem with the help of google tips ))

Again, we have a container with Nginx and a container with Nginx Unit.

Nginx in its logs writes ip address of its container, not the real client ip.

At the front $_SERVER['REMOTE_ADDR'] also gives the IP of the Nginx container.

If you configure the bundle according to the manual - https://unit.nginx.org/howto/integration/ 
and place Nginx and Nginx Unit outside of containers, everything works, thanks to the client_ip directive.

I have a question, when working in containers should there be some other configuration of configs to solve the problem or not?

Or is it all the fault of containers and already need to do something with them?

Thank you!

**Comment by lacosteque** [comment]
Now I understand that this problem is not related to Unit.

Nginx when working in a container in general does not give the real ip of the client, but gives the ip of its own container.

Hence it can be solved either by some Nginx configuration or by container configuration.
Or it is not solvable in general because of the peculiarities of Docker internal network.
