### ISSUE TITLE
mkstemp -  No such file or directory

### ISSUE THREAD

**Issue by w-** [nginx/unit#637]
similar to #620  except i'm not using DirectAdmin

Using Unit to host a django application. When attempting to upload a file, I get a 500 error from Unit (not from django). in the logs it looks like

```
[alert] 2041#2075 *1567 mkstemp(/usr/local/unitd/tmp/req-XXuHYl0p) failed (2: No such file or directory)
```

The unitd config below shows the  `tmp` config is correctly set to `/var/tmp`
I have explicitly set django setting `FILE_UPLOAD_TEMP_DIR = "/var/tmp"` and still get the error. the only thing that worked was actually creating the dir `/usr/local/unitd/tmp/`, and adjusting ownership and permissions so that it was writable by the process resolved the error. 

I'm sure this is a config issue somewhere, but can't find it. any help?

```
$ unitd --version
unit version: 1.26.1
configured as ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/unit/control.sock --pid=/var/run/unit/unit.pid --log=/var/log/unit/unit.log --tmp=/var/tmp --user=unit --group=unit --tests --openssl --modules=/usr/lib64/unit/modules --libdir=/usr/lib64 --cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
```

```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

running with python 3.8

**Comment by VBart** [comment]
> I'm sure this is a config issue somewhere, but can't find it. any help?

Could you show arguments list used to run `unitd`?

**Comment by w-** [comment]
is this what you mean? I'm on a server where i didn't configure this myself.

```
$ ps ax | grep unitd
 2038 ?        Ss     0:00 unit: main v1.26.1 [/usr/local/unitd/sbin/unitd --log /var/log/unit/unit2.log --pid /var/run/unit/unit2.pid --no-daemon]
```

**Comment by mar0x** [comment]
@w- Is it possible there are more than one `unitd` binary available in your environment?

Please share the output of `which unitd` and `/usr/local/unitd/sbin/unitd --version` commands.

**Comment by w-** [comment]
sorry for the delay in my reply. great catch. i hadn't even considered this possibility. from the terminal output it certainly looks like there are two versions ?


$ which unitd
/usr/sbin/unitd

$ /usr/local/unitd/sbin/unitd --version
unit version: 1.26.1
configured as ./configure --prefix=/usr/local/unitd/

$ ls -alh /usr/sbin/unitd
-rwxr-xr-x 1 root root 471K Dec  2 11:27 /usr/sbin/unitd

$ /usr/sbin/unitd --version
unit version: 1.26.1
configured as ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/unit/control.sock --pid=/var/run/unit/unit.pid --log=/var/log/unit/unit.log --tmp=/var/tmp --user=unit --group=unit --tests --openssl --modules=/usr/lib64/unit/modules --libdir=/usr/lib64 --cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -pie'

**Comment by mar0x** [comment]
Yes, it seems `/usr/local/unitd/sbin/unitd` is running and `/usr/sbin/unitd` have the configuration you need.

As MacLeod says "There can be only one" :)

**Comment by w-** [comment]
_Here we are..... Born to be kings and the princes of the universe..........!_ 

thanks....
