### ISSUE TITLE
Python WSGI shutdown

### ISSUE THREAD

**Issue by ambrussimon** [nginx/unit#65]
Hi,

I cannot get python functions registered via `atexit` to run when running the sample WSGI application below. Trying to migrate from uWSGI, where `cleanup` was always executed whenever the uWSGI service was terminated.

I've tried sending TERM|QUIT|INT to unit, all of which resulted in the workers exiting with 0 in the logs, yet `cleanup` was never triggered.

Could you please give some pointers, what am I missing here? Thanks!

```python
import atexit, webapp2

def cleanup():
    print('Cleanup done.')
atexit.register(cleanup)

class Handler(webapp2.RequestHandler):
    def get(self):
        self.response.write('hello\n')

application = webapp2.WSGIApplication([
    (r'/', Handler)
])
```

**Comment by VBart** [comment]
Graceful shutdown of python applications isn't implemented yet.

**Comment by TokuiNico** [comment]
I am experiencing the same issue. When I stop or kill Docker, nginx unit immediately shuts down the application without waiting for Django to complete all connections.
