### ISSUE TITLE
[Ruby] Lack of `SCRIPT_NAME` Rack environment parameter causes crash

### ISSUE THREAD

**Issue by winduptoy** [nginx/unit#651]
The `Rack::URLMap` class in (used by `Rack::Builder`, a commonly used utility) expects a `SCRIPT_NAME` parameter. When `env['SCRIPT_NAME']` is `nil`, the following line causes a crash.

https://github.com/rack/rack/blob/98dbe17dd1e552783e056af15f4632ae4d462cc6/lib/rack/urlmap.rb#L73

```
undefined method `+' for nil:NilClass (NoMethodError)
```

I used the following middleware hack to temporarily fix it.

```
require 'rack'

class NginxPatcher
	def initialize(app)
		@app = app
	end

	def call(env)
		env[Rack::SCRIPT_NAME] ||= ''
		@app.call(env)
	end
end
```

In config.ru:

```
use NginxPatcher
```

I don't really care about the value of `SCRIPT_NAME` and I don't use it for anything. However, it would be nice if Unit would set this to an empty string at least so that the internals of Rack don't crash under normal use. `SCRIPT_NAME` is mentioned in the [Rack spec](https://github.com/rack/rack/blob/main/SPEC.rdoc), so it would be nice to have some kind of guarantees that the the spec is implemented at least to a point where it doesn't crash.

**Comment by travisbell** [comment]
Thanks for sharing @winduptoy, I've had this on my backlog to report for the past few months and just never got to it. 🙏🏼 Happy that someone wasn't as lazy as me! 😉

**Comment by hongzhidao** [comment]
Hi, @winduptoy @travisbell 

Thanks for your reporting. Here's the patch of adding "SCRIPT_NAME" parameter.
https://gist.github.com/hongzhidao/1bbe0479a57377682a51dd3fabf7061e

Welcome to test.

**Comment by hongzhidao** [comment]
@winduptoy 
It has been fixed with the commit: https://github.com/nginx/unit/commit/0032543fa65f454c471c968998190b027c1ff270
