### ISSUE TITLE
flush php opcache or restart via control socket

### ISSUE THREAD

**Issue by jamesRUS52** [nginx/unit#665]
Hi, Is it possible to restart unit via control socket?
or any other method to flush php opcache without systemctl restart unit

**Comment by tippexs** [comment]
Hi @jamesRUS52 . Thanks for reaching out.  From the context of your question I assume you are looking for a way to clear the PHP opcache. Am I correct? The opcache lifes in the shared memory zone restarting the unit application should fee the cache. You can use this `sudo curl -X GET --unix-socket /path/to/control.unit.sock http://localhost/control/applications/app_name/restart` to restart the application.

**Comment by jamesRUS52** [comment]
Yes, you are correct.
It works, thank you.
But Is the way to do the same without sudo (run by app user)
