### ISSUE TITLE
add header Access-Control-Allow-Headers via nginx

### ISSUE THREAD

**Issue by MarkSinD** [nginx/unit#668]
How to insert header into request response via nginx?
The fact is that a CORS error occurs during a cross-domain request, which is solved simply by adding the Access-Control-Allow-Headers header through the nginx proxy server (as I read on the Internet).
Here is cors error code:
![2022-04-01_14-05-51](https://user-images.githubusercontent.com/33195675/161262625-b679f34a-9f78-47fe-9398-291da7001096.png)
add header via nginx
I cannot change the backend and disable cors check.
1) No headers are connected, although the application starts and works correctly. nginx config:
```
server {
  listen 80;

  add_header Access-Control-Allow-Headers "*" always;
  add_header Access-Control-Allow-Methods "*" always;
  add_header Access-Control-Allow-Origin "*" always;
  add_header Custom Header Value;
  
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
```
2) How the request works. Let's create a simple fetch on the back, which contains one controller. Simple fetch request with React:
```
function MyPoster() {
  const [recommended, setRecommended] = useState(null);
 
  const getPeers = () =>
    fetch('http://localhost:9002/c', {method: "GET"})
      .then(response => response.text());
 
  useEffect(() => {
    getPeers()
      .then(result => {
        setRecommended(result);
      });
  }, [])
 
  return(
    <div>
      {recommended}
    </div>
  );
}
```
3) The controller on the back is also simple, which returns a string.

``````
@GetMapping("/c")
    public String simpleTemplate2(){
        return "i'm the programmer";
    }
``````
4) Docker configuration
``````
FROM node:12.2.0-alpine as react_build
WORKDIR /app
COPY. /app/

#prepare contiainer for building react
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
RUN npm run build

#preparing nginx
FROM nginx:1.16.0-alpine

COPY --from=react_build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

#start nginx
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
``````
https://github.com/MarkSinD/docker-nginx-react
Where are my added headers?
![image](https://user-images.githubusercontent.com/33195675/161262959-18b92b56-b005-44e6-a890-e4f13987c19c.png)

Why are the headers not substituted? What can be added?

**Comment by artemkonev** [comment]
Hi @MarkSinD ,

this is the NGINX Unit repo, you may want to ask your question here: https://github.com/nginx/nginx

**Comment by MarkSinD** [comment]
@artemkonev thanks
