### ISSUE TITLE
Problem when restarting unix socket as listener

### ISSUE THREAD

**Issue by echolimazulu** [nginx/unit#669]
**Hello Nginx Team and Contributors,**

This is a separation of the unix socket restart problem from the socket cleanup problem (https://github.com/nginx/unit/issues/643) when the program is closed, as these are technically and conceptually different problems.

**Issue:**
`bind(\"unix:/var/run/unit.sock\") failed (98: Address already in use)`

**Comment by echolimazulu** [comment]
In the next hour there will be a PR for this request.

**Comment by echolimazulu** [comment]
The solution to the problem is proposed in the **PR**:
https://github.com/nginx/unit/pull/670

**Comment by echolimazulu** [comment]
**Repository to reproduce the issue:**
https://github.com/echolimazulu/unit-bind-aaiu

**Comment by hongzhidao** [comment]
Hi, @echolimazulu 

Thanks for your patch.
Actually, it's much more complicated. It also happens during reconfiguration.
Just take a look at the case:
```
{
    "listeners": {
        "unix:/tmp/test.sock": {
            "pass": "routes"
        }
    },
    "routes": [
        {
            "action": {
                "return": 205
            }
        }
    ]
}
```
Then
```
# conf.json
{
    "pass": "routes"
}

> curl -X DELETE http://127.1:8000/config/listeners/unix:%2Ftmp%2Ftest.sock
> curl -X PUT -d@conf.json http://127.1:8000/config/listeners/unix:%2Ftmp%2Ftest.sock
It failed
```

**Comment by echolimazulu** [comment]
Good morning @hongzhidao,

Thanks for the option you suggested.

Reproducing the specified list of commands with the patch (**PR:** https://github.com/nginx/unit/pull/670) applied, I get an error:
```
# cat conf.json
{
    "listeners": {
        "unix:/tmp/test.sock": {
            "pass": "routes"
        }
    },
    "routes": [
        {
            "action": {
                "return": 205
            }
        }
    ]
}

# curl -X PUT --data-binary @conf.json --unix-socket /var/run/control.unit.sock http://localhost/config/
{
	"success": "Reconfiguration done."
}

# curl -X DELETE --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock

# cat /var/lib/unit/conf.json
{"listeners":{},"routes":[{"action":{"return":205}}]}

# curl -X PUT -d@conf.json --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock
{
	"error": "Invalid configuration.",
	"detail": "Unknown parameter \"listeners\"."
}
```
It seems to me that these are slightly different problems. Since the configuration you described above causes a problem related to the router, configuration, parameters, validation. And the problem that I tried to catch and solve was connected precisely with the reuse of a unix socket using bind.

https://github.com/nginx/unit/blob/aee908bcbd6ae160ab8e470ea6a373148649968b/src/nxt_conf_validation.c#L2429

I may be wrong in my research, please correct me if I somehow incorrectly reproduced the sequence you indicated or for some reason I do not see the relationship between these two components. Grateful to you!

**Comment by hongzhidao** [comment]
> Since the configuration you described above causes a problem related to the router, configuration, parameters, validation

```
# curl -X PUT -d@conf.json --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock
{
	"error": "Invalid configuration.",
	"detail": "Unknown parameter \"listeners\"."
}
```

Try the new conf.json, it's just an object for `unix:/tmp/test.sock`.
```
# conf.json
{
    "pass": "routes"
}
```

**Comment by echolimazulu** [comment]
> > Since the configuration you described above causes a problem related to the router, configuration, parameters, validation
> 
> ```
> # curl -X PUT -d@conf.json --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock
> {
> 	"error": "Invalid configuration.",
> 	"detail": "Unknown parameter \"listeners\"."
> }
> ```
> 
> Try the new conf.json, it's just an object for `unix:/tmp/test.sock`.
> 
> ```
> # conf.json
> {
>     "pass": "routes"
> }
> ```

Thanks for the correction.

**Execution log:**
```
# cat /var/lib/unit/conf.json
{"listeners":{"unix:/tmp/test.sock":{"pass":"routes"}},"routes":[{"action":{"return":205}}]}

# curl -X DELETE --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock
{
	"success": "Reconfiguration done."
}

# cat /var/lib/unit/conf.json
{"listeners":{},"routes":[{"action":{"return":205}}]}

# cat hongzhidao.json
{
    "pass": "routes"
}

# curl -X PUT -d@hongzhidao.json --unix-socket /var/run/control.unit.sock http://localhost/config/listeners/unix:%2Ftmp%2Ftest.sock
{
	"success": "Reconfiguration done."
}

# cat /var/lib/unit/conf.json
{"listeners":{"unix:/tmp/test.sock":{"pass":"routes"}},"routes":[{"action":{"return":205}}]}
```
It seems to work.

**Comment by hongzhidao** [comment]
> It seems to work.

Is it based on your patch?

**Comment by echolimazulu** [comment]
> > It seems to work.
> 
> Is it based on your patch?

```
# git log
commit f5671830575d8b9c9fe63c05e393935f8de31fbe (HEAD -> master, origin/master, origin/HEAD)
Author: Make it real <26638058+echolimazulu@users.noreply.github.com>
Date:   Fri Apr 1 20:04:56 2022 +0400

    Socket: fix unix socket reuse problem
    
    Issue solution: https://github.com/nginx/unit/issues/669.
    
    Earlier, @VBart suggested to implement a check in case of ECONNREFUSED.
    
    The problem happened a little earlier for bind() and threw an EADDRINUSE error.
    
    It was also suggested by @mar0x to check if the file type matches the socket before deleting it.
    
    Discussion:
    https://github.com/nginx/unit/pull/649

commit 34184729886a40182f044d6a92744bbfa095c90c
Author: Make it real <26638058+echolimazulu@users.noreply.github.com>
Date:   Fri Apr 1 18:35:35 2022 +0400

    Socket: setting permissions for unix socket
    
    Access for unix sockets should be equal to 0666 and controlled by the rights set on the directory.
    
    Discussion:
    https://github.com/nginx/unit/pull/647

commit ef4e7afa80bb0063e314c38bd8f7efaacc590eb9
Author: Make it real <26638058+echolimazulu@users.noreply.github.com>
Date:   Fri Apr 1 17:57:53 2022 +0400

    Socket: replacing the function call that creates the socket
    
    Previously, @VBart suggested replacing the socket creation function to avoid code duplication.
    
    https://github.com/nginx/unit/pull/649#issuecomment-1043707026
    https://github.com/nginx/unit/pull/649#issuecomment-1044298169

commit aeed86c6829c62359e79f239b849766efb8857a7
Author: Zhidao HONG <z.hong@f5.com>
Date:   Tue Feb 22 19:18:18 2022 +0800

    Workaround for the warning in nxt_realloc() on GCC 12.
    
    This closes #639 issue on Github.
```
Yes, I even specifically recompiled the Unit build to double check this.

Checked twice.

**Comment by hongzhidao** [comment]
Ok, mine is based on the official release.
Just remind it that there is a problem during re-config.

**Comment by tippexs** [comment]
Hi @echolimazulu - Thanks for the contribution, again 🚀
We have looked into the issue with the Unix Sockets and we should split the problem into two different chunks.
1. Being able to restart Unit while using previously created Unix Domain Sockets as `listeners`
2. Clean-Up old Socket files

As the 1st issue is the most important one to release this feature in one of the next releases, your idea shared in #670 is highly appreciated. @hongzhidao will review the PR.

See you in the PR 🤟🏼

**Comment by echolimazulu** [comment]
> Hi @echolimazulu - Thanks for the contribution, again 🚀 We have looked into the issue with the Unix Sockets and we should split the problem into two different chunks.
> 
> 1. Being able to restart Unit while using previously created Unix Domain Sockets as `listeners`
> 2. Clean-Up old Socket files
> 
> As the 1st issue is the most important one to release this feature in one of the next releases, your idea shared in #670 is highly appreciated. @hongzhidao will review the PR.
> 
> See you in the PR 🤟🏼

Hello @tippexs!

Sorry for the long answer on my part.

Thank you for your attention to this issue!

I'm happy to help resolve this issue. @hongzhidao and I are trying to actively work on this issue. I am sincerely glad to work together with the professionals from your team and I endlessly appreciate the experience that you can get in the process of solving this problem!
