### ISSUE TITLE
Support `$` as a URI sub-delimiter

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit#675]
`$` is a reserved character for URIs, for use as a subdelimiter.  However, we already use that character for Unit variables.  To be able to Represent a literal `$`, we need some variable or character sequence that evaluates to the `$` itself.

For more details, including RFC references, see the PR where this issue was first raised:
https://github.com/nginx/unit/pull/660

@VBart proposed adding a variable called something like `$sign`.  That's easy, as it only requires adding a new variable with a static content.

I suggest an alternative, `$$` (as in [_make_(1)](https://man7.org/linux/man-pages/man1/make.1.html) for example: <https://www.gnu.org/software/make/manual/make.html#Basics-of-Variable-References>).  Implementing it will probably be more complex, probably needing to change the parsing code, but the result might be nicer for the user.

**Comment by alejandro-colomar** [comment]
I should note that while discussing some completely unrelated thing, I just met a URI in the wild that had a `$` subdelimiter, so they are actually in use in some places.

**Comment by ac000** [comment]
So, yes, using ${sign} to represent a literal _$_ is straightforward and the patch looks like

```diff
diff --git a/src/nxt_http_variables.c b/src/nxt_http_variables.c
index 1c0b561..0adcb8c 100644
--- a/src/nxt_http_variables.c
+++ b/src/nxt_http_variables.c
@@ -13,6 +13,8 @@ static nxt_int_t nxt_http_var_uri(nxt_task_t *task, nxt_var_query_t *query,
     nxt_str_t *str, void *ctx);
 static nxt_int_t nxt_http_var_host(nxt_task_t *task, nxt_var_query_t *query,
     nxt_str_t *str, void *ctx);
+static nxt_int_t nxt_http_var_dollar(nxt_task_t *task, nxt_var_query_t *query,
+    nxt_str_t *str, void *ctx);
 
 
 static nxt_var_decl_t  nxt_http_vars[] = {
@@ -27,6 +29,10 @@ static nxt_var_decl_t  nxt_http_vars[] = {
     { nxt_string("host"),
       &nxt_http_var_host,
       0 },
+
+    { nxt_string("sign"),
+      &nxt_http_var_dollar,
+      0 },
 };
 
 
@@ -77,3 +83,13 @@ nxt_http_var_host(nxt_task_t *task, nxt_var_query_t *query, nxt_str_t *str,
 
     return NXT_OK;
 }
+
+
+static nxt_int_t
+nxt_http_var_dollar(nxt_task_t *task, nxt_var_query_t *query, nxt_str_t *str,
+    void *ctx)
+{
+    *str = (nxt_str_t) nxt_string("$");
+
+    return NXT_OK;
+}
```
and seems to work

From unit config
```json
"location": "https://$host/path/${sign}something"
```
```
$ curl -I http://localhost:8080/
HTTP/1.1 301 Moved Permanently
Location: https://localhost/path/$something
```

However, I also prefer the _$$_ idea and it also somewhat mirrors the likes of printf(3) with _%%_, so that's what I'm going to look into next.

@alejandro-colomar Do you have an example of such a URL? I can't say it's something I remember ever seeing and I'm not entirely sure exactly how it's used.

**Comment by alejandro-colomar** [comment]
@ac000  Sure, here the URL: <https://wd5.myworkday.com/ffive/d/task/1422$1469.htmld>

However, I have no idea what meaning that dollar has.

**Comment by ac000** [comment]
@alejandro-colomar Thanks for that.

**Comment by ac000** [comment]
So with this patch on top of the above

```diff
diff --git a/src/nxt_http_variables.c b/src/nxt_http_variables.c
index 0adcb8c..a47cdab 100644
--- a/src/nxt_http_variables.c
+++ b/src/nxt_http_variables.c
@@ -30,7 +30,7 @@ static nxt_var_decl_t  nxt_http_vars[] = {
       &nxt_http_var_host,
       0 },
 
-    { nxt_string("sign"),
+    { nxt_string("$$"),
       &nxt_http_var_dollar,
       0 },
 };
diff --git a/src/nxt_var.c b/src/nxt_var.c
index 0a722d1..d8781ae 100644
--- a/src/nxt_var.c
+++ b/src/nxt_var.c
@@ -362,6 +362,14 @@ nxt_var_next_part(u_char *start, size_t length, nxt_str_t *part,
             return NULL;
         }
 
+        /* Allow $$ in URIs to represent $ sub-delimiters. */
+        if (*p == '$') {
+            part->start = p - 1;
+            part->length = 2;
+
+            return p + 1;
+        }
+
         if (*p == '{') {
             bracket = 1;

```

Using $$ to represent a single $ for sub-delimiters (or anything else I guess)
now works.

E.g In unit config

```json
"location": "https://$host/path/$$sub1$$sub2"
```
```
curl -I http://localhost:8080/
HTTP/1.1 301 Moved Permanently
Location: https://localhost/path/$sub1$sub2
```

A pull request will be forthcoming.

**Comment by alejandro-colomar** [comment]
> So with this patch on top of the above
> 
> ```diff
> diff --git a/src/nxt_http_variables.c b/src/nxt_http_variables.c
> index 0adcb8c..a47cdab 100644
> --- a/src/nxt_http_variables.c
> +++ b/src/nxt_http_variables.c
> @@ -30,7 +30,7 @@ static nxt_var_decl_t  nxt_http_vars[] = {
>        &nxt_http_var_host,
>        0 },
>  
> -    { nxt_string("sign"),
> +    { nxt_string("$$"),
>        &nxt_http_var_dollar,
>        0 },
>  };
> diff --git a/src/nxt_var.c b/src/nxt_var.c
> index 0a722d1..d8781ae 100644
> --- a/src/nxt_var.c
> +++ b/src/nxt_var.c
> @@ -362,6 +362,14 @@ nxt_var_next_part(u_char *start, size_t length, nxt_str_t *part,
>              return NULL;
>          }
>  
> +        /* Allow $$ in URIs to represent $ sub-delimiters. */
> +        if (*p == '$') {
> +            part->start = p - 1;
> +            part->length = 2;
> +
> +            return p + 1;
> +        }
> +
>          if (*p == '{') {
>              bracket = 1;
> ```
> 
> Using $$ to represent a single $ for sub-delimiters (or anything else I guess) now works.
> 
> E.g In unit config
> 
> ```json
> "location": "https://$host/path/$$sub1$$sub2"
> ```
> 
> ```
> curl -I http://localhost:8080/
> HTTP/1.1 301 Moved Permanently
> Location: https://localhost/path/$sub1$sub2
> ```
> 
> A pull request will be forthcoming.

Great!

I guess it handles `$$$host` correctly, and rejects things like `$$$notavar`, and handles `$$host` as meaning literally `$host`.  Right?

**Comment by ac000** [comment]
@alejandro-colomar 

```json
"location": "$$$host"
```
```
$ curl -I http://localhost:8080/
Location: $localhost
```

```json
"location": "$$$notavar"
```
```
{
        "error": "Invalid configuration.",
        "detail": "Unknown variable \"notavar\" in the \"location\" value."
}
```

```json
"location": "$$host"
```
```
$ curl -I http://localhost:8080/
Location: $host
```

```json
"location": "${$}"
```
```
{
        "error": "Invalid configuration.",
        "detail": "Invalid variable at position 0 in the \"location\" value."
}
```
