### ISSUE TITLE
Support UDP load-balancing for TFTP 

### ISSUE THREAD

**Issue by damalhot** [nginx/unit#678]
nginx can load-balance TCP and UDP traffic. But things do not work when backend is a TFTP server. Certain protocols like TFTP use fixed port for control traffic (port 69) and a random port  for data traffic. In such cases, data traffic is not received by the client.

**Comment by tippexs** [comment]
Hi @damalhot 

this is the NGINX Unit repo, you may want to ask your question here: http://nginx.org/en/support.html
