### ISSUE TITLE
NXT_TEST_CFLAGS being set in auto/os/test?

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit#679]
`$ grep -rnI NXT_TEST_CFLAGS`
```
configure:19:NXT_TEST_CFLAGS=${NXT_TEST_CFLAGS=}
build/autoconf.data:13:NXT_TEST_CFLAGS=''
auto/feature:38:nxt_test="$CC $CFLAGS $NXT_CFLAGS $NXT_CC_OPT $NXT_TEST_CFLAGS \
auto/save:19:NXT_TEST_CFLAGS='$NXT_TEST_CFLAGS'
auto/os/test:35:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE"
auto/os/test:36:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE_EXTENDED=1"
auto/os/test:37:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D__EXTENSIONS__"
auto/os/test:64:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE"
auto/os/test:65:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE_EXTENDED"
auto/os/test:66:        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_HPUX_ALT_XOPEN_SOCKET_API"
```

`$ cat auto/os/test`
```sh
NXT_SYSTEM=`uname -s 2>/dev/null`


case "$NXT_SYSTEM" in
#...
    SunOS)
        NXT_SYSTEM_VERSION=`uname -r 2>/dev/null`
        NXT_SYSTEM_PLATFORM=`uname -p 2>/dev/null`
        echo=echo
        CC=${CC:-gcc}
        AR=${AR:-ar}

        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE"
        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D_XOPEN_SOURCE_EXTENDED=1"
        NXT_TEST_CFLAGS="$NXT_TEST_CFLAGS -D__EXTENSIONS__"
        NXT_TEST_LIBS="-lsocket"
        ;;
#...
esac

$echo "configuring Unit $NXT_VERSION"                                         \
      "for $NXT_SYSTEM $NXT_SYSTEM_VERSION $NXT_SYSTEM_PLATFORM"
```

I'm not sure why those are being set.  It looks like those are not being tested at all (we're not running `auto/feature` which is the only place `NXT_TEST_CFLAGS` seems being read for something useful, nor the content of the variable seems being later assigned to the actual `NXT_CFLAGS` after some test).

---

As something related, I question the usefulness of this flag at all, because `nxt_feature_incs` is being overused for cflags too:

`$ grep -rn 'nxt_feature_incs=.'`
```
auto/pcre:18:        nxt_feature_incs="-DPCRE2_CODE_UNIT_WIDTH=8 $NXT_PCRE_CFLAGS"
auto/pcre:49:        nxt_feature_incs=$NXT_PCRE_CFLAGS
auto/modules/perl:73:    nxt_feature_incs="${NXT_PERL_INCLUDE}"
auto/modules/perl:120:nxt_feature_incs="${NXT_PERL_INCLUDE}"
auto/modules/ruby:78:    nxt_feature_incs="${NXT_RUBY_INCPATH}"
auto/modules/ruby:102:        nxt_feature_incs="${NXT_RUBY_INCPATH}"
auto/modules/ruby:130:nxt_feature_incs="${NXT_RUBY_INCPATH}"
auto/modules/python:84:    nxt_feature_incs="${NXT_PYTHON_INCLUDE}"
auto/modules/python:111:nxt_feature_incs="${NXT_PYTHON_INCLUDE}"
auto/modules/java:189:nxt_feature_incs="${NXT_JAVA_INCLUDE}"
auto/modules/php:129:nxt_feature_incs="${NXT_PHP_INCLUDE}"
auto/modules/php:145:nxt_feature_incs="${NXT_PHP_INCLUDE}"
auto/modules/php:169:nxt_feature_incs="${NXT_PHP_INCLUDE}"
auto/modules/php:190:nxt_feature_incs="${NXT_PHP_INCLUDE}"
auto/ssltls:99:        nxt_feature_incs=$NXT_GNUTLS_CFLAGS
auto/ssltls:120:            nxt_feature_incs=$NXT_GNUTLS_CFLAGS
auto/ssltls:134:            nxt_feature_incs=$NXT_GNUTLS_CFLAGS
```

This is thanks to the fact that the `-I ` that `auto/feature` is adding is adding an empty path that doesn't really affect (not exactly sure how that is interpreted by GCC, but I guess it's not problematic, and don't care enough to test it for now), and then the cflags are correctly being added.  Maybe it would have been better to separate cflags and incs... but as long as it works, we can live with it for now.  But I'd like to clarify `NXT_TEST_CFLAGS` for now.

Thanks,

Alex

Cc: @hongzhidao 
Cc: @VBart

**Comment by VBart** [comment]
> This is thanks to the fact that the -I that auto/feature is adding is adding an empty path that doesn't really affect (not exactly sure how that is interpreted by GCC, but I guess it's not problematic, and don't care enough to test it for now), and then the cflags are correctly being added

Hm... Could you clarify what do you mean here? Because `auto/feature` actually checks for `-` in the beginning of `$nxt_feature_incs` and doesn't add `-I` in this case.

**Comment by VBart** [comment]
> It looks like those are not being tested at all (we're not running auto/feature which is the only place NXT_TEST_CFLAGS seems being read for something useful, nor the content of the variable seems being later assigned to the actual NXT_CFLAGS after some test).

Hm... the `auto/feature` is run for each feature test.

**Comment by alejandro-colomar** [comment]
> > This is thanks to the fact that the -I that auto/feature is adding is adding an empty path that doesn't really affect (not exactly sure how that is interpreted by GCC, but I guess it's not problematic, and don't care enough to test it for now), and then the cflags are correctly being added
> 
> Hm... Could you clarify what do you mean here? Because `auto/feature` actually checks for `-` in the beginning of `$nxt_feature_incs` and doesn't add `-I` in this case.

Nah, you're right there.  I forgot about that obvious detail.  Probably effects of COVID :)

So `nxt_feature_incs` is effectively an extra CFLAGS that we set for each test.  That's what I think I'll use for testing the Clang flag.

**Comment by alejandro-colomar** [comment]
> > It looks like those are not being tested at all (we're not running auto/feature which is the only place NXT_TEST_CFLAGS seems being read for something useful, nor the content of the variable seems being later assigned to the actual NXT_CFLAGS after some test).
> 
> Hm... the `auto/feature` is run for each feature test.

Yes, what I meant here is that we're not setting `NXT_TEST_CFLAGS` for a specific case.
The only thing that would make some sense to me right now is:
maybe we need those extra CFLAGS for all (or many) of the `auto/feature` tests but don't need them for Unit code itself?
I guess we don't need them in Unit, because otherwise they would already be in `NXT_CFLAGS`.

**Comment by VBart** [comment]
> maybe we need those extra CFLAGS for all (or many) of the auto/feature tests but don't need them for Unit code itself?

That's what the code tells.

> And why would (all/many of) the tests need those flags?

To answer this question we need access to those platforms where they are set. I don't have, unfortunately, but Igor added them for purpose. Maybe `NXT_TEST_CFLAGS` can be removed, but only if we decide to not support those platforms or if we check and confirm that it's no more needed there (or can merged into `NXT_CFLAGS`).

**Comment by alejandro-colomar** [comment]
> > maybe we need those extra CFLAGS for all (or many) of the auto/feature tests but don't need them for Unit code itself?
> 
> That's what the code tells.
> 
> > And why would (all/many of) the tests need those flags?
> 
> To answer this question we need access to those platforms where they are set. I don't have, unfortunately, but Igor added them for purpose. Maybe `NXT_TEST_CFLAGS` can be removed, but only if we decide to not support those platforms or if we check and confirm that it's no more needed there (or can merged into `NXT_CFLAGS`).

Thanks.

**Comment by VBart** [comment]
Well, a bit more investigation shows that my previous explanation is not accurate. Actually these options are defined and documented here as well: https://github.com/nginx/unit/blob/master/src/nxt_unix.h#L131

So, it seems these options are needed not only for tests, but for most of Unit code (at least that depends on `nxt_unix.h`).

Why didn't Igor add them to CFLAGS? I guess, there can be at least one possible good reason: to clearly indicate for other devs (and their IDEs) these defines in the code (by explicitly having them in `nxt_unix.h`).
