### ISSUE TITLE
SSL certificate invalid

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit#700]
I have issue with attaching certificates

My steps by documentation

`certbot certonly --standalone`

<img width="902" alt="Screenshot 2022-05-17 at 7 22 56 PM" src="https://user-images.githubusercontent.com/49598333/168860782-c1051abd-41e1-4742-b57e-76b67d6a3e65.png">

`cat fullchain.pem privkey.pem > bundle.pem `

<img width="762" alt="Screenshot 2022-05-17 at 7 24 08 PM" src="https://user-images.githubusercontent.com/49598333/168861010-71ae5f8b-6acb-4e6f-b47c-7dd93

`curl -X PUT -d @bundle.pem --unix-sock /var/run/control.unit.sock http://localhost/certificates/bundle`

<img width="1178" alt="Screenshot 2022-05-17 at 7 25 02 PM" src="https://user-images.githubusercontent.com/49598333/168861179-47972f3e-029b-454c-b97b-4b103b106efd.png">
bddfb43.png">

Screenshot below show logs

<img width="892" alt="Screenshot 2022-05-17 at 7 25 27 PM" src="https://user-images.githubusercontent.com/49598333/168861263-e9e7112c-b922-478d-bdd7-d32a573239ed.png">

**Comment by tippexs** [comment]
I have tested it just yesterday with certs from letsencrypt and it was working as expected. What's the Unit version you are using? 

I will share my commands once I am back on my laptop but in general your request / config looks good.

**Comment by Pavlusha311245** [comment]
Nginx unit 1.26.1

**Comment by Pavlusha311245** [comment]
> I have tested it just yesterday with certs from letsencrypt and it was working as expected. What's the Unit version you are using?
> 
> I will share my commands once I am back on my laptop but in general your request / config looks good.

Nginx unit 1.26.1

**Comment by tippexs** [comment]
Sorry just updated my comment. See above 👆🏼

**Comment by Pavlusha311245** [comment]
> You have to use `--data-binary` instead of `-d`
Wow. It works!
<img width="1007" alt="Screenshot 2022-05-19 at 10 29 12 AM" src="https://user-images.githubusercontent.com/49598333/169236922-a384c74a-1932-48bc-a73e-d3cc9c6b7b80.png">

But why arg `-d` not work? I can update the config with `-d`
<img width="827" alt="Screenshot 2022-05-19 at 10 30 16 AM" src="https://user-images.githubusercontent.com/49598333/169237117-e477ad5c-d756-408d-b90d-dd5e0d41baf1.png">

**Comment by tippexs** [comment]
`-d` will send data in text mode whereas `--data-binary` will send data in binary mode. As the main config is just json (text) text mode will be fine. But remember to use binary upload for certificates.

```
 -d, --data DATA     HTTP POST data (H)
     --data-ascii DATA  HTTP POST ASCII data (H)
     --data-binary DATA  HTTP POST binary data (H)
     --data-urlencode DATA  HTTP POST data url encoded (H)
```

**Comment by Pavlusha311245** [comment]
@tippexs Thank you!
