### ISSUE TITLE
How unit/php works?

### ISSUE THREAD

**Issue by icy** [nginx/unit#707]
Hi team,

My team comes up with the question how `unit/php` works compared to `nginx/php-fpm`. I have a quick look and both seem to use `php sapi`, that means the PHP version of our application won't be a problem. But I may be wrong.

To be specific, our team worries if there is any gap between the latest php development and our php support.

Thanks for for your reading.

**Comment by tippexs** [comment]
Hi @icy,

yes you are correct. NGINX Unit implements its PHP functional against the SAPI from PHP.

No, the PHP Version of your application would not be a problem. As long as you can install / build the correct Language Module (Like a specific version of a PHP-FPM).

> To be specific, our team worries if there is any gap between the latest php development and our php support.

I did not get this? What do you mean by gap? Do you  have a specific PHP Version in mind?

**Comment by icy** [comment]
Hi @tippexs,

> [...]
> > To be specific, our team worries if there is any gap between the latest php development and our php support.
> 
> I did not get this? What do you mean by gap? Do you have a specific PHP Version in mind?

Thanks a lot for your feedback.  I'm sorry if my last sentence confused you. It's about if the latest version of PHP (i.e php-8.1 or some latest versions) could be used with our `unit` product. I believe that it's positive thanks to your answer for my first question.

Thanks again and happy weekend.

PS: Let me explain the context. We have a product that's been running well with `nginx/php-fpm` and I found the whole setup spends a lot of time on TCP connective. I give `unit` a try and for a simple endpoint, the performance is 3x better. I'm still far behind the target to get a productive attempt, and though I'm very convinced it's important for me to understand how `unit` works and to convince my team to focus on `unit` in their future development.
