### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#71]
Hi!

src/nxt_http_request.c
```
158     ar->request = r;
159     ar->mem_pool = r->mem_pool;
160     nxt_mp_retain(r->mem_pool);  // Now the retain number is 2, but where to be released before close?
```
```
378     r->proto.any = NULL;
379     nxt_mp_release(r->mem_pool);
```

It seems the mem pool of the request has not any chance to be destroyed.
Since the number of 'retain' is not 1 when the request is closed.

Please take a look. Thanks. @igorsysoev

**Comment by VBart** [comment]
I believe the second release is done by `nxt_app_http_release()`.

**Comment by igorsysoev** [comment]
Yes, the second call to release memory pool is made in nxt_app_http_release().
