### ISSUE TITLE
Variables: add request_id

### ISSUE THREAD

**Issue by icy** [nginx/unit#714]
Hi team,

In our nginx setup, we are using `request_id` for tracing purpose . This is an embedded variable as documented here https://nginx.org/en/docs/http/ngx_http_core_module.html#variables. The setting is done thanks to `fastcgi` setting as below

```
# nginx.conf
fastcgi_param       HTTP_X_REQUEST_ID   $request_id;
```

My question is how we can get a similar thing with `unit` configuration?

Thanks for your reading and support.

**Comment by lcrilly** [comment]
Hello!

How do you use this variable end-to-end? Presumably you also log this variable in the access log for correlation purposes? Or does it end up somewhere else?

**Comment by icy** [comment]
> Hello!
> 
> How do you use this variable end-to-end? Presumably you also log this variable in the access log for correlation purposes? Or does it end up somewhere else?

We are using Symfony + Newrelic integration. Though I don't really get all details how it's exactly working, I think our developers are using `HTTP_X_REQUEST_ID` header value (which is `$request_id`) as Newrelic tracing ID.

Fyi, the Symfony project seems not to get a final resolution (discussed in https://github.com/symfony/symfony/issues/11573 ). There are some patches, but I think it's great if `unit` can support `$request_id` out of the box.

**Comment by icy** [comment]
Thanks the team for looking into this and getting it done.

**Comment by phpclub** [comment]
@andrey-zelenkov @tippexs @icy @lcrilly @sshaw  Can you tell me why this is added only to logs? You need to set an additional header for forwarding to the backend

**Comment by andrey-zelenkov** [comment]
Hi @phpclub,

The plan was to implement header modification using NJS (and/or within the `action` block) which was a separate task. However, as far as I remember, it was never implemented and the project is no longer under active development: https://unit.nginx.org/community/#maintenance-and-support-guidelines
