### ISSUE TITLE
Ruby/Rails: config.ru in request.path

### ISSUE THREAD

**Issue by lluuaapp** [nginx/unit#715]
Hi!

Since the lates release (1.27) all my rails/rack app gets an extra `config.ru` prefix added to the `request.path`. The relatively simple config is relatively simple:

```
  "applications": {
    "app_name": {
      "type": "ruby",
      "processes": 2,
      "working_directory": "/usr/local/app_name",
      "user": "www-data",
      "group": "www-data",
      "script": "/usr/local/app_name/config.ru",
      "environment": {
        "RAILS_ENV": "production",
        "SECRET_KEY_BASE": "blah"
      }
    }
```

Seems the new index name feature has broken something there?

Please tell me if you need any further information. Reverted back to 1.26.1 and it works again.

**Comment by ac000** [comment]
Hi

My ruby is almost non-existent but I don't think I'm seeing what you're seeing.

Here's my config

```JSON
{
    "listeners": {
        "*:8080": {
            "pass": "applications/test"
        }
    },
    "applications": {
        "test": {
            "type": "ruby",
            "script": "/var/tmp/config.ru"
        }
    }
}
```

Here's my config.ru

```ruby
app = Proc.new do |env|                                                         
    p env                                                                       
    ["200", {                                                                   
        "Content-Type" => "text/plain",                                         
    }, ["Hello World"]]                                                         
end                                                                             
                                                                                
run app
```

Here's my request

```
$ curl http://localhost:8080/test
Hello World
```

Here's 'env'
```
{"SERVER_SOFTWARE"=>"Unit/1.27.0", "SCRIPT_NAME"=>"config.ru", "rack.version"=>[1, 3],
"rack.input"=>#<NGINX_Unit_Stream_IO_Read:0x00007ff183ed1120>, 
"rack.errors"=>#<NGINX_Unit_Stream_IO_Error:0x00007ff183ed0ec8>, "rack.multithread"=>false,
"rack.multiprocess"=>true, "rack.run_once"=>false, "rack.hijack?"=>false, "rack.hijack"=>nil, 
"rack.hijack_io"=>nil, "REQUEST_METHOD"=>"GET", "REQUEST_URI"=>"/test", 
"PATH_INFO"=>"/test", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1",
"REMOTE_ADDR"=>"127.0.0.1", "SERVER_ADDR"=>"127.0.0.1", "SERVER_NAME"=>"localhost",
"SERVER_PORT"=>"80", "rack.url_scheme"=>"http", "HTTP_HOST"=>"localhost:8080",
"HTTP_USER_AGENT"=>"curl/7.82.0", "HTTP_ACCEPT"=>"*/*"}
```

I'm not sure how to get _request.path_. Perhaps you could provide a minimal test case that shows the issue?

**Comment by xeron** [comment]
I see exactly the same issue with a Rails app.

May be try a simple `rails new` and check the UI?

The problem is not in request/response, the problem is URLs generated by e.g. rails' `root_path` have `config.ru` suffix, for example `/` becomes `/config.ru` when view is rendered.

**Comment by tippexs** [comment]
Thank. We will try to reproduce and let you know. Thanks for reaching out!

**Comment by ac000** [comment]
While I'm figuring out how to reproduce this, I'm looking for potential suspect commits. This so far is the only real stand out contender

    0032543 Ruby: added the Rack environment parameter "SCRIPT_NAME".

and while I can't immediately see how it would be causing your issue. It is specifically ruby related (is this only happening with ruby?) and it's dealing with SCRIPT_NAME which would be your 'config.ru'.

You could try reverting that commit and see if it makes a difference.

**Comment by tippexs** [comment]
We were just talking about the exact same thing. We are going to test it tomorrow and see if this will fix the issue. If so we will investigate why and how we can combine the new feature of the `SCRIPT_NAME` as well as not breaking the current Ruby implementation. But yes - you are right.

**Comment by lluuaapp** [comment]
Thanks for looking into this!

Yes, all my ruby/rack apps in unit are indeed Rails apps. And I can confirm that reverting this commit:

`0032543 Ruby: added the Rack environment parameter "SCRIPT_NAME".`

does fix the issue. Will this be fixed in code or should I try setting an (empty) `SCRIPT_NAME` env variable in the `environment` setting? Don't know when the line

`rb_hash_aset(hash_env, rb_str_new2("SCRIPT_NAME"), rctx->script);`

Is executed (after or before setting the environment from the JSON), but maybe just removing this (src/ruby/nxt_ruby.c, line 601) would fix the issue, too? I can try this and create a PR if you like...

**Comment by alejandro-colomar** [comment]
We would also need `PATH_INFO` maybe?

**Comment by lluuaapp** [comment]
Don't quite understand, should I test anything right now? The patch above? Or changing anything in my configuration?

If I am not wrong, the "script" parameter in Ruby/Rails/Rack configurations will always contains something that is rarely a part of the URL (e.g. config.ru which contains something like `run Rails.application`).

Als, my app runs behind NGINX as a reverse proxy (if that matters). The `SCRIPT_NAME` aka location is empty in this case, but as far as I know this is handled either by NGINX and/or by the Rails router??!

**Comment by alejandro-colomar** [comment]
No, don't try that.  That was just a guess, but a wrong guess.  I'll open a PR right now, and please check that one if you can.

**Comment by tippexs** [comment]
@lluuaapp All good - no changes required on your end. The `script` param in our UNIT configuration tells UNIT what's the entrypoint of your application. The `SCRIPT_NAME` env variable for Ruby / Rails is telling Rails if there is a location / path it should attach as a prefix to each URL it creates by functions like `link_to` and friends. As @alejandro-colomar said - we are going to set the `SCRIPT_NAME` to an empty string will be (according to the spec) the correct thing if the Rails application is hosted under the documents root `/`. If you want to host a Rails app under a specific path like `/app1/` you can always set the `SCRIPT_NAME` to that path using the apps `environment` section in the UNIT configuration.

**Comment by lluuaapp** [comment]
OK, can confirm that the PR above fixes the issue for me. Thanks!

Also thanks for the tip with the SCRIPT_NAME, this may simplify some configurations of my Rails apps that have the specific path.

Thanks again!
