### ISSUE TITLE
PHP: Routes uri match and trailing slash

### ISSUE THREAD

**Issue by lucatacconi** [nginx/unit#717]
I'm configuring a route as follow for a php application:
`
{
        "app2" : [
                {
                        "match":{
                                "uri": ["/test/*"],
                                "method": "GET"
                        },
                        "action":{
                                "pass": "applications/app2"
                        }
                }
        ]
}`

with a basic listener:
`	
"listeners": {
		"*:8080": {
			"pass": "routes/app2"
		}
	},
`

Accessing route by browser i can test correctly the application by the following address http://SERVER_IP:8080/test/
Is it possible to avoid trailing slash in the address (ex http://SERVER_IP:8080/test)?
I tried changing the uri match from "uri": ["/test*"], to "uri": ["/test*"] but the result is the same: Error 503.

Thanks in advance.

**Comment by tippexs** [comment]
Can you please share the unit.log as well as the whole unit configuration? That will help to trace down the issue. Thanks

**Comment by hongzhidao** [comment]
Hi @lucatacconi 

I suggest testing pure matching first. For example:
```
{
    "listeners": {
        "*:8080": {
            "pass": "routes"
        }
    },
    "routes": [
        {
            "match": {
                "uri": "/test*"
            },
            "action": {
                "return": 206
            }
        }
    ]
}
```
If it doesn't match, it will return 404. I just tested and it works.
If it returns 503, it shows that the route is matched, but the application doesn't work, you need to check its service.

**Comment by ac000** [comment]
The fix for has been merged. [a032744](https://github.com/nginx/unit/commit/a03274456b54cbc39e220b9dd73c3fc3fb935e46)
