### ISSUE TITLE
heavy python docker image since 1.22

### ISSUE THREAD

**Issue by raphaelauv** [nginx/unit#725]
https://hub.docker.com/r/nginx/unit/tags?page=1&name=python

1.27.0-python3.10 is `338.31 MB`

where 1.21.0-python3.7 is `36.85 MB`

would be great to have a slim image

Thanks

**Comment by thresheek** [comment]
The size change is due to us moving to Official Python docker images.

slim has the following clause in the description:
>  Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository.

**Comment by thresheek** [comment]
See https://github.com/nginx/unit/issues/519 and https://github.com/nginx/unit/issues/622 too.

**Comment by raphaelauv** [comment]
okay , I see

a `1.27.0-python3.10-slim` based on `python3.10-slim`  would be great

**Comment by tippexs** [comment]
@raphaelauv currently, we are working on becoming an official docker package. Once that process has been finished, it will be a lot more easier to create those images. We will keep this issue open till that day and let you know as soon as we have any updates on this.

Thanks for reaching out! Appreciate it!

Cheers Timo

**Comment by thresheek** [comment]
Starting with 1.30.0, you can try something along the lines of:
```
git clone --branch branches/packaging https://github.com/nginx/unit
cd unit/pkg/docker
make build-python3.11 VERSIONS_python=3.11 CONTAINER_python3.11=python:3.11-slim
```

**Comment by 0x6f677548** [comment]
It seems the next release will include a slim version according to #1352 . That's great - thanks!
Since I needed multi-arch and slim images, I wrote a small utility to build it and push to my docker hub. Feel free to use it and adapt to your needs: https://github.com/0x6f677548/nginx-unit-buildx

**Comment by callahad** [comment]
1.33 is out and has `-slim` variants for the Python images, which weigh in at around 50 MB. Please let us know if you encounter any issues with these :)
