### ISSUE TITLE
Parallel work with supervisor inside docker

### ISSUE THREAD

**Issue by Pavlusha311245** [nginx/unit#727]
Maybe a stupid question, but I'm having trouble starting a container on Nginx Unit with Supervisor. Only one of these technologies starts. Is there any way to start the Supervisor at container startup without breaking the Unit ?
<img width="346" alt="Screenshot 2022-06-22 at 10 07 12 PM" src="https://user-images.githubusercontent.com/49598333/175116926-1abccc0b-4755-4d21-9348-36c202eb2ca4.png">
My docker-compose file with nginx unit
<img width="562" alt="Screenshot 2022-06-22 at 10 07 38 PM" src="https://user-images.githubusercontent.com/49598333/175116982-2b3f252e-d37d-48bc-9f5b-d6906a960d82.png">

**Comment by tippexs** [comment]
This looks like you are trying to send `unit` to supervisord. Which will not work. What are you trying to do? What is the use case for using supervisord in your container?

**Comment by Pavlusha311245** [comment]
@tippexs I'm trying to start supervisord after container startup.

**Comment by tippexs** [comment]
as you can see in the error message you have provided your are trying to use `unitd --no-daemon` as a supervisord command which will not work.

If you want to start unit with supervisord you should create a supervisor configuration
http://supervisord.org/configuration.html

**Comment by PaulZavadski** [comment]
@tippexs I will try
