### ISSUE TITLE
config case sensitive error missed by 'nginx -t', failed during 'systemctl restart nginx' ('SSL'=bad, 'ssl'=good)

### ISSUE THREAD

**Issue by aspiringguru** [nginx/unit#729]
as per the title

I had this line in a '/etc/nginx/sites-available/domain-name' file

```
listen 443 SSL;
```
this passed nginx error-checking /testing
```
sudo nginx -t
```

then nginx failed during
```
sudo systemctl restart nginx
```

thankfully checking 
```
journalctl -xeu nginx.service
```
identified the error including a line number reference which made the fix easy,
```
listen 443 ssl;
```

Not a huge issue, would be 'nicer' for this to be caught during 'nginx -t'

my environment
Ubuntu 22.04 LTS
nginx version: nginx/1.18.0 (Ubuntu)

(otherwise props to the team for building and maintaining a great tool)

**Comment by tippexs** [comment]
Hi @aspiringguru 

this is a bug tracker and repository for NGINX Unit. If you want to ask questions about NIGNX you can use the mailing list or the NGINX github repository. More information can be found here https://nginx.org/en/support.html

Let me know if you need anything else.
