### ISSUE TITLE
URI rewrite

### ISSUE THREAD

**Issue by lcrilly** [nginx/unit#732]
The generic requirement is for Unit to accept requests for one URI, and process it as if it were for a different URI. This need often arises as web sites/apps evolve, and resources get reorganised. Clients may continue to make requests against URIs that no longer exist. Unit can preserve the original behaviour and optimize for end user experience by transparently rewriting the URI to one that exists in the new scheme.

|Use case|Request URI|Rewrite URI|
|---|---|---|
|Application accepts requests at root level but shares a hostname with other apps (disambiguation)|```/calc/subtract```|```/subtract```|
|API endpoint got renamed|```/api/calc/v1/add```|```/api/calc/v1/sum```|
|Introduced 2-level nav structure for blog posts (now with topic)|```/blog/20220628/how-to-swim.html```|```/blog/swimming/20220628/how-to-swim.html```|
|Someone put upper case in an email newsletter|```/news/Summer-SALE.html```|```/news/summer-sale.html```|
|A function of one application is now implemented in its own application with a different input style|```/calc/trigonometry/tan/60```|```/trig/tangent?degrees=60```|

It is anticipated that the `"routes"` object will be extended to support this capability.

**Comment by lcrilly** [comment]
Initial release of `rewrite` shipped with unit-1.30.0

**Comment by MagnusOxlund** [comment]
> The generic requirement is for Unit to accept requests for one URI, and process it as if it were for a different URI.

From [StackOverflow](https://stackoverflow.com/a/74054793/1662230), on a question inquiring about dynamic URI rewriting:

> This is not possible today. In the future you will be able to specify [URI rewrites](https://github.com/nginx/unit/issues/732) to reconstruct the URI to match the new layout.

Is the `rewrite` feature expected to eventually support dynamic cases without the use of njs?

For reference, NGINX's `rewrite` achieves this with regex substitution:
`rewrite ^user/([0-9]+)/?$ user.php?id=$1 break;`

**Comment by hongzhidao** [comment]
> Is the rewrite feature expected to eventually support dynamic cases without the use of njs?
Yes.

> rewrite ^static/my-module/(.*) /app/myapp/modules/my-module/static/$1 break;

Compared to NGINX, Unit's configuration format is different, which is json. In Unit, it might look like this if we support it in the future.
```
{
  "match": {
    "uri": "~^static/my-module/(?<sub>.*)"
  },
  "action": {
    "rewrite": "/app/myapp/modules/my-module/static/$sub"
  }
}
```
Btw, `rewrite` has supported variables, the unsupported feature here is the custom variables setting through regexp.
After the next version 1.31, we'll start this feature that has been added to our plan. And we assume we only support named captured to set custom variables, but not the format like `$1, $2, $n` in nginx.

Feel free to add any ideas on this feature.

**Comment by MagnusOxlund** [comment]
> Yes.

Thank you 🙏

> [...] unsupported feature here is the custom variables setting through regexp.
After the next version 1.31, we'll start this feature that has been added to our plan. 

Issue #544 deals with this, for anyone who wants to track development.

**Comment by hongzhidao** [comment]
Good reference, thanks!

**Comment by l2dy** [comment]
> A function of one application is now implemented in its own application with a different input style

Has the last use case (rewrite path into arguments) in the table been implemented in unit-1.30.0? If not, do we have a workaround or another issue to track that?

**Comment by lcrilly** [comment]
@l2dy [the query part cannot be rewritten](https://unit.nginx.org/configuration/#uri-rewrite)

> All route step [actions](https://unit.nginx.org/configuration/#configuration-routes-action) support the rewrite option that updates the URI of the incoming request before the action is applied. **It does not affect the [query](https://datatracker.ietf.org/doc/html/rfc3986#section-3.4)** but changes the uri and $request_uri [variables](https://unit.nginx.org/configuration/#configuration-variables).

The best we can do today is to use a redirect:

```json
{
  "match": {
    "uri": "/calc/trigonometry/tan/*"
  },
  "action": {
    "return": 301,
    "location": "`${'/trig/tangent?degrees=' + uri.substring(23)}`"
  }
}
```

Do you have a real-world use case for this? Feel free to create a new issue to track it.

**Comment by mqudsi** [comment]
What's the correct approach for rewriting `$uri` but not `$request_uri`? Real-world case is WordPress multi-site installation, you have `/wp1/` and `/wp2/` being "instances" of the same `/wordpress/` installation. You need to redirect all `/wp1/` and `/wp2/` requests to `/wordpress/` (so static resources can be found in that directory, named php files can be executed as-is) and then a separate rule to fallback any unserved static resources (via the `types` restriction) to `/wordpress/index.php` to handle virtual urls.

If you use the current url rewriting facilities in nginx-unit, `$request_uri` gets rewritten as well meaning `/wordpress/index.php` never sees a request with the virtual path `/wp1/` or `/wp2/` in it, only with the actual path `/wordpress/` in it (which doesn't match an actual virtual installation and so will issue infinite redirects).
