### ISSUE TITLE
Cant proxy to a path

### ISSUE THREAD

**Issue by ArtruneTranspara** [nginx/unit#744]
Can only proxy to a host, are there plans to proxy to a host and a path?

Docker image: nginx/unit:1.26.1-python3.9

```

{
        "listeners": {
            "*:80": {
                "pass": "routes"
            }
        },
        "routes": [
            {
                "match": {
                    "uri": "/*"
                },
                "action": {
                    "proxy": "http://192.168.1.137:80/test"
                }
            }
        ]
    }

```
Error:
```

{
        "error": "Invalid configuration.",
        "detail": "The \"proxy\" address is invalid \"192.168.1.137:80/test\""
}
```

**Comment by lcrilly** [comment]
Hi Arturo, this use case is designed to be solved with https://github.com/nginx/unit/issues/732

**Comment by ArtruneTranspara** [comment]
Is there an ETA for this or should I be using regular nginx in the meantime instead? @lcrilly

**Comment by tippexs** [comment]
Hi @ArtruneTranspara sorry for the late response on this.

It is not scheduled for the next release, so I would advice you to use NGINX OSS for the rewrite in the mean time and will come back to you in this thread as soon as the feature is out for review.

**Comment by ArtruneTranspara** [comment]
Hi @tippexs  thanks!
