### ISSUE TITLE
Clarify http error

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#75]
Hi.

The r->resp.fields has been created in nxt_http_request_create.
```
78 nxt_http_request_t *
 79 nxt_http_request_create(nxt_task_t *task)
 80 {
...
 93
 94     r->resp.fields = nxt_list_create(mp, 8, sizeof(nxt_http_field_t));
 95     if (nxt_slow_path(r->resp.fields == NULL)) {
 96         goto fail;
 97     }
```

So we can clarify codes shown below.

```
diff -r 8e31d63208f2 src/nxt_http_error.c
--- a/src/nxt_http_error.c	Fri Jan 12 18:15:58 2018 +0300
+++ b/src/nxt_http_error.c	Sat Jan 13 09:47:28 2018 -0500
@@ -34,11 +34,6 @@

     r->status = status;

-    r->resp.fields = nxt_list_create(r->mem_pool, 8, sizeof(nxt_http_field_t));
-    if (nxt_slow_path(r == NULL)) {
-        goto fail;
-    }
-
     content_type = nxt_list_zero_add(r->resp.fields);
```

**Comment by igorsysoev** [comment]
We should clear all existing headers during error generating.

**Comment by hongzhidao** [comment]
That'll be better.

Another question about engine's fast_work_queue.
Is the queue intentionally designed to pop first?
```
474     if (wq->head == NULL) {
475         wq = &engine->fast_work_queue;
476
477         if (wq->head == NULL) {
```

For example in error generating. Suppose we have not clear existing headers as you mentioned.
```
    r->resp.content_length = NULL;
    r->resp.content_length_n = sizeof(error) - 1;

    r->state = &nxt_http_request_send_state;

    nxt_http_request_header_send(task, r);
```
nxt_http_request_send_state->ready_handler will be called before io->write (nxt_conn_write).

The questions are:
1. Dose fast_work_queue mean execute first anyway?
2. The other queues like read/write_work_queue should be executed in order? I think it is.
    The design is particularly fine that we needn't block read while write is processing.
    The opposite is the same, we needn't block write while read is processing.
    These (block) things we should do in NGINX, is it right?

**Comment by VBart** [comment]
1. Yes.
2. Reads and writes are non blocking. Separate work queues are used for optimization to accumulate these operations and run them in batches.
