### ISSUE TITLE
ip based server_name doesnt filter

### ISSUE THREAD

**Issue by jonnytest1** [nginx/unit#750]
having an nginx conf like
```
server{
    ...
    server_name some_dns:443;
}

server{
    ...
    server_name 192.168.178.54:443;
}
```

will when 192.168.178.54:433 is used in the browser (local net obviously) still route to the some_dns page 
🤔

**Comment by jonnytest1** [comment]
my bad i thought i did it the same as all the other servers but i accidentally put the port in the server_name 😅

**Comment by tippexs** [comment]
Hi @jonnytest1 thanks for reaching out but this is a bug tracker for NGINX Unit not for NIGNX the Webserver / Proxyserver. Glad it is working now for you.
