### ISSUE TITLE
OCSP might optionally dont check signature

### ISSUE THREAD

**Issue by MartinKosicky** [nginx/unit#757]
We have a setting where nginx is in our internal network, but we want some further validation of a client certificate via OCSP. W have many persistent connections (around 700K) and made a custom ocsp server implementation for additional ocsp validation of client certificates. The thing is that because the responses have to be signed, it's eating quite a lot of CPU, and we trust our internal infrastructure. So is there a possibility to add disabling of ocsp signature verification?

Possibly are there any other ways how to do custom "cert revocation checks" besides OCSP?

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for [NGINX Unit](https://unit.nginx.org/) but your question seems related to [`ssl_ocsp`](http://nginx.org/r/ssl_ocsp) in NGINX. Please direct this to the other channels https://nginx.org/en/support.html or nginxcommunity Slack.
