### ISSUE TITLE
Missing wsgi.errors as mandated by PEP 3333

### ISSUE THREAD

**Issue by kgriffs** [nginx/unit#76]
Hi, we just had a Falcon user report an error when attempting to run their WSGI app on NGINX Unit. It seems that the WSGI environ is missing the mandatory ``wsgi.errors`` variable.

See also: https://github.com/falconry/falcon/issues/1209

**Comment by VBart** [comment]
Funny, that the same typo in the issue subject. =)

**Comment by kgriffs** [comment]
LOL, to typo is human I guess.

**Comment by totaki** [comment]
If you interesting i test django and tornado projects to, all works fine. Because tornado use sys.stderr (PEP allow this) and in django source code i dont find wsgi.errors or wsgi.error.
