### ISSUE TITLE
Oss-fuzz remander

### ISSUE THREAD

**Issue by 0x34d** [nginx/unit#762]
Hello everyone. 
This is a reminder for oss-fuzz unit integration. 
I'd like to hear your thoughts on [oss-fuzz PR](https://github.com/google/oss-fuzz/pull/8511). 
I would say that the Nginx/Unit tests are the hardest test suite I have seen in unit tests. 
Will you check both harness validations? 
so they don't produce false positives.

**Comment by andrey-zelenkov** [comment]
Hi @0x34d! I will take a look at this PR next week if you don't mind. Thank you!
