### ISSUE TITLE
How to install the rtmp on mac os monterey

### ISSUE THREAD

**Issue by harishinka** [nginx/unit#765]
Hi team,
I wanted to install nginx with rtmp and run on mac os monterey M1. Can you please guide with the command. The old commands:
brew tap homebrew/nginx
brew install nginx-full --with-rtmp-module

does not work

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for NGINX Unit but your question seems related to rtmp in NGINX. Please direct this issue to the channels listed at https://nginx.org/en/support.html or to the [nginxcommunity Slack](https://community.nginx.org/joinslack).

Also note that "does not work" combined with detailed error information is more likely to produce helpful responses.
