### ISSUE TITLE
Add response header variables

### ISSUE THREAD

**Issue by sevdog** [nginx/unit#773]
As of now Unit uses only **request**'s headers for variables. However it could be useful to be able use **response**'s headers.

Example: I want to log the user which performed a request using an `X-Username` header which is set by my application.

Using nginx this is easy using the `$sent_http_x_username`, it would be nice to have something similar also in unit. Since some information could only be trusted when coming from the server and not from the client (just like in my example, the client could fake the user).

**Comment by hongzhidao** [comment]
Hi @sevdog,

It makes sense to add variables related to response headers. But currently, we are busy with the 1.29 version. 
If the feature isn't ready for 1.29, we'll add it to the 1.30 version.
BTW, I think I can send your a patch if it's ready. Thanks for your suggestion.

**Comment by hongzhidao** [comment]
Hi @sevdog 
Here's the patch of response header variables support, we'll merge it into the next version 1.31.
https://gist.github.com/hongzhidao/162b005920e905503b2b3c1752ca7cbd
Welcome to tests, thanks.

**Comment by sevdog** [comment]
Thank you @hongzhidao, I will try this as soon as I get a free slot to experiment with unit again.

**Comment by hongzhidao** [comment]
@sevdog 
Btw, here's another feature related to response headers. https://github.com/nginx/unit/issues/313
We are on it at the same time and plan to support it in the next version.

**Comment by hongzhidao** [comment]
Hi,
This has been merged by https://github.com/nginx/unit/commit/458722df55bb9727680b7734e7fff8fb5639db28
Thanks.
