### ISSUE TITLE
Deployment on Heroku: add options to handle SIGTERM

### ISSUE THREAD

**Issue by PetrDlouhy** [nginx/unit#774]
I am using Nginx on Heroku in Docker container along with Gunicorn/Supervisor.

When Heroku scales down it first sends SIGTERM to all processes in the container and after 30 seconds it sends SIGKILL. I don't think, that I can change this behavior.

After receiving SIGTERM Nginx terminates ungracefully not waiting for running requests.

I wonder if the possibility to terminate gracefully on SIGTERM signal could be added.

**Comment by PetrDlouhy** [comment]
I found temporary workaround by compiling Nginx from sources and patching them:
```bash
curl -L http://nginx.org/download/nginx-1.22.0.tar.gz -o nginx.tar.gz
tar -xvzf nginx.tar.gz
cd nginx-1.22.0
sed -i "s/ QUIT$/TIUQ/g" src/core/ngx_config.h
sed -i "s/ TERM$/QUIT/g" src/core/ngx_config.h
sed -i "s/ TIUQ$/TERM/g" src/core/ngx_config.h
./configure
make
make install
```

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for [NGINX Unit](https://unit.nginx.org/) but your question seems related to [nginx](http://nginx.org/en/). Please direct this issue to the channels listed at https://nginx.org/en/support.html or to the [nginxcommunity Slack](https://community.nginx.org/joinslack).
