### ISSUE TITLE
NOT support PHP5.2.*

### ISSUE THREAD

**Issue by xxyyboy** [nginx/unit#776]
lots  of errors：

src/nxt_php_sapi.c:174:5: error: initialization discards ‘const’ qualifier from pointer target type [-Werror]
     nxt_php_ext_functions,       /* function table */
     ^
src/nxt_php_sapi.c: In function ‘zif_fastcgi_finish_request’:
src/nxt_php_sapi.c:222:5: error: implicit declaration of function ‘zend_parse_parameters_none’ [-Werror=implicit-function-declaration]
     if (nxt_slow_path(zend_parse_parameters_none() == FAILURE)) {
     ^
src/nxt_php_sapi.c: At top level:
src/nxt_php_sapi.c:314:5: error: initialization makes integer from pointer without a cast [-Werror]
     NULL,                        /* executable_location */
     ^
src/nxt_php_sapi.c:314:5: error: (near initialization for ‘nxt_php_sapi_module.php_ini_ignore’) [-Werror]
src/nxt_php_sapi.c:329:5: error: initialization makes integer from pointer without a cast [-Werror]
     NULL,                        /* ini_defaults */
     ^
src/nxt_php_sapi.c:329:5: error: (near initialization for ‘nxt_php_sapi_module.phpinfo_as_text’) [-Werror]
src/nxt_php_sapi.c:332:5: error: excess elements in struct initializer [-Werror]
     NULL,                        /* ini_entries */
     ^
src/nxt_php_sapi.c:332:5: error: (near initialization for ‘nxt_php_sapi_module’) [-Werror]
src/nxt_php_sapi.c:333:5: error: excess elements in struct initializer [-Werror]
     NULL,                        /* additional_functions */
     ^
src/nxt_php_sapi.c:333:5: error: (near initialization for ‘nxt_php_sapi_module’) [-Werror]
src/nxt_php_sapi.c:335:1: error: excess elements in struct initializer [-Werror]
 };
 ^
src/nxt_php_sapi.c:335:1: error: (near initialization for ‘nxt_php_sapi_module’) [-Werror]
src/nxt_php_sapi.c: In function ‘nxt_php_setup’:
src/nxt_php_sapi.c:424:42: error: ‘ZEND_INI_SYSTEM’ undeclared (first use in this function)
         nxt_php_set_options(task, value, ZEND_INI_SYSTEM);
                                          ^
src/nxt_php_sapi.c:424:42: note: each undeclared identifier is reported only once for each function it appears in
src/nxt_php_sapi.c:427:42: error: ‘ZEND_INI_USER’ undeclared (first use in this function)
         nxt_php_set_options(task, value, ZEND_INI_USER);

**Comment by alejandro-colomar** [comment]
Hi!

PHP 5.2 has been unsupported since 2011.  Why is it that you need that version?  Could you please share some info about the platform/OS?

Is upgrading to a newer 5.x version or to 7.0 a possibility?

Thanks!

@remicollet  you might be interested in this.  I don't even see 5.6, which was EOL in 2018. being supported anymore by distros (for example, Debian oldoldstable has PHP 7.0).  I understand that some users might need 5.x versions even after the EOL for legacy reasons, but is it still widespread for supporting it?

**Comment by remicollet** [comment]
> @remicollet you might be interested in this. I don't even see 5.6, which was EOL in 2018, being supported anymore by distros (for example, Debian oldoldstable has PHP 7.0). I understand that some users might need 5.x versions even after the EOL for legacy reasons, but is it still widespread for supporting it?

* RHEL 7 have 5.4 (supported until June 2024)
* RHEL 8 have 7.4
* RHEL 9 have 8.0

**Comment by ac000** [comment]
CentOS 7 (and I assume RHEL 7) has 5.4 which Unit builds OK against.

**Comment by alejandro-colomar** [comment]
Thanks!  So we need to support PHP 5.4.  5.2 seems to be out of luck, unless there's some supported system out there that has it.

**Comment by tippexs** [comment]
@xxyyboy as mentioned above. 5.4 should work for you but 5.2 is out of support. Are you able to move your application to 5.4? That would work. Will close this issue.

**Comment by xxyyboy** [comment]
@tippexs Thank you guys，Cause our company still has many old PHP projects running online for our customers. maybe over 2000 projects.
I successfully compiled version 5.3.29，still trying to test all function

**Comment by xxyyboy** [comment]
There also are many new PHP projects.  we use 7.1.3.
