### ISSUE TITLE
No Python 3.8/3.9 packages for RHEL/CentOS 8

### ISSUE THREAD

**Issue by jkugler** [nginx/unit#778]
RHEL 8.x allows you to install python36, python38, and python39 packages, out of the box, vendor supported. However, there is only Python 3.6 here https://packages.nginx.org/unit/centos/8/x86_64/RPMS/ and here: https://packages.nginx.org/unit/rhel/8Server/x86_64/RPMS/

Could we get Python 3.8 and Python 3.9 RPMs for RHEL/CentOS as well?

On a RockyLinux docker container:
```
[root@4d22824d9f1f /]# cat /etc/redhat-release 
Rocky Linux release 8.6 (Green Obsidian)
[root@4d22824d9f1f /]# yum install python36 python38 python39
Last metadata expiration check: 0:02:46 ago on Mon Oct 31 23:30:08 2022.
Dependencies resolved.
================================================================================================================================
 Package                             Architecture     Version                                         Repository           Size
================================================================================================================================
Installing:
 python36                            x86_64           3.6.8-38.module+el8.5.0+671+195e4563            appstream            18 k
 python38                            x86_64           3.8.12-1.module+el8.6.0+794+eba84017            appstream            78 k
 python39                            x86_64           3.9.7-1.module+el8.6.0+795+de4edbcc             appstream            32 k
Installing dependencies:
 python3-pip                         noarch           9.0.3-22.el8.rocky.0                            appstream            19 k
 python3-setuptools                  noarch           39.2.0-6.el8                                    baseos              162 k
 python38-libs                       x86_64           3.8.12-1.module+el8.6.0+794+eba84017            appstream           8.3 M
 python38-pip-wheel                  noarch           19.3.1-5.module+el8.6.0+794+eba84017            appstream           1.0 M
 python38-setuptools-wheel           noarch           41.6.0-5.module+el8.5.0+672+ab6eb015            appstream           303 k
 python39-libs                       x86_64           3.9.7-1.module+el8.6.0+795+de4edbcc             appstream           8.2 M
 python39-pip-wheel                  noarch           20.2.4-7.module+el8.6.0+795+de4edbcc            appstream           1.1 M
 python39-setuptools-wheel           noarch           50.3.2-4.module+el8.5.0+673+10283621            appstream           496 k
Installing weak dependencies:
 python38-pip                        noarch           19.3.1-5.module+el8.6.0+794+eba84017            appstream           1.8 M
 python38-setuptools                 noarch           41.6.0-5.module+el8.5.0+672+ab6eb015            appstream           667 k
 python39-pip                        noarch           20.2.4-7.module+el8.6.0+795+de4edbcc            appstream           1.9 M
 python39-setuptools                 noarch           50.3.2-4.module+el8.5.0+673+10283621            appstream           870 k
Enabling module streams:
 python36                                             3.6                                                                      
 python38                                             3.8                                                                      
 python39                                             3.9                                                                      

Transaction Summary
================================================================================================================================
Install  15 Packages

Total download size: 25 M
Installed size: 90 M
```

Instructions for RHEL 8.x here: https://blog.hqcodeshop.fi/archives/510-Python-3.9-in-RedHat-Enterprise-Linux-8.4.html

**Comment by thresheek** [comment]
Hi @jkugler ! Thank you for opening this issue.

RockyLinux is a bit different repo-wise to RHEL, I'm going to check if it's possible to install multiple versions of Python (and its development libraries, which we need to build packages against) on it.

**Comment by thresheek** [comment]
Indeed it seems possible. I've posted a patch addressing this for an internal review.

**Comment by jkugler** [comment]
Thanks! Yeah, I first became aware of the ability at the blog post https://blog.hqcodeshop.fi/archives/510-Python-3.9-in-RedHat-Enterprise-Linux-8.4.html which details the steps for RHEL 8.x. I tried it on RockyLinux because that is all I have access to. Thanks for addressing this so quickly! I look forward to seeing the package as our application is ready to go for Python 3.9.

**Comment by thresheek** [comment]
Support added in https://github.com/nginx/unit/commit/11f416878a9f5f7ec13d548b85982c5de5b55a11.

This will be available packaged & built on the next Unit release.

**Comment by jkugler** [comment]
Just checking in. Is `Makefile.python39` going to be added too? As well as `unit.example-python39-config`?

Thanks!

**Comment by thresheek** [comment]
Hi @jkugler!

Makefile and examples were already present, you can check e.g. https://github.com/nginx/unit/tree/11f416878a9f5f7ec13d548b85982c5de5b55a11/pkg/rpm - they were added on through Fedora 33 support quite a while ago: https://github.com/nginx/unit/commit/e4f7d1a29c59985f291876e2e76852007c2a390a

There is no hard ETA on the next release though, some time in December most probably.

**Comment by jkugler** [comment]
Ah, gotcha! I didn't see anything that would cause a Python 3.9 build for RHEL8, so I was confused.

Thanks much!

**Comment by jkugler** [comment]
Howdy! Any chance you've got a 1.29 beta to which I could get access in order to start some testing on our end?

**Comment by thresheek** [comment]
Hi @jkugler, no betas are available but the plan is to release 1.29 tomorrow - stay tuned :-)

**Comment by jkugler** [comment]
@thresheek Man, I should have been just a little more patient. :) Thanks for the update!

**Comment by thresheek** [comment]
Hi @jkugler, the packages are published now - please test :-)

**Comment by jkugler** [comment]
I saw that! Thank you so much! I'm doing my final changes and will be testing later today. Since the package is published, I'm closing this issue, and I'll open a new one if I hit any problems.
