### ISSUE TITLE
Problem with starting Nextcloud

### ISSUE THREAD

**Issue by SubZero77** [nginx/unit#783]
Hello! I'm trying to run NextCloud on Nginx and Unit on Ubuntu 22.04 but I get error 502 Bad Gateway.  The site config uses a redirect to port 443:
upstream php-handler {
    server 127.0.0.1:9000;
}
server {
        listen 80;
	listen [::]:80;
        server_name nc.site.ru;
	server_tokens off;
        return 301 https://$server_name$request_uri;
}
fastcgi_pass php-handler;

The Unit json config uses the following construction:
{
    "listeners": {
        "127.0.0.1:9000": {
            "pass": "routes"
        }
    },

There are no errors in Unit logs, but there are such errors in Nginx logs:
2022/11/08 08:56:51 [crit] 1806#1806: *24 SSL_do_handshake() failed (SSL: error:0A0004E7:SSL routines::reason(1255):SSL alert number 255) while SSL handshaking, client: 10.20.30.5, server: 0.0.0.0:443
2022/11/08 08:56:51 [error] 1806#1806: *18 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 10.20.30.5, server: nc.site.ru, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.20.30.8"

If necessary, I will post all the configs. Help me please.

**Comment by SubZero77** [comment]
> Unit is not a fcgi backend. You can configure next cloud on unit standalone.
Hello! i.e. you don't need to install Nginx at all? Only Unit?
I saw this tutorial and did it, but I didn't understand that Nginx is not needed.

**Comment by SubZero77** [comment]
I did It!!! tippexs thank You very much for help!!! 
in file config.json (like in manual):
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
    },
and load config file by this command:
curl -X PUT --data-binary @/home/config.json --unix-socket /var/run/control.unit.sock http://localhost/config

**Comment by SubZero77** [comment]
> your whole Unit configuration file? If so this is a not enough to make Next Cloud working.
Of course not. I did as indicated here https://unit.nginx.org/howto/nextcloud/
> What does this mean? What do you expect to change here?
For example configuration file config.php
> Does this mean you unpacked the default next cloud server installation from https://github.com/nextcloud/server/releases?
This file with last version of NextCloud https://download.nextcloud.com/server/releases/latest.zip

**Comment by artemkonev** [comment]
I'll take a look into this, thanks for reporting.

**Comment by tippexs** [comment]
Hi @SubZero77  I was able to complete the NextCloud Tutorial I have mentioned above. I am still confused about the `fcgi` configuration you have shared above. I am simply using Unit to host the whole Next Cloud application so the NGINX OSS part is simply a reveres proxy.

**Comment by tippexs** [comment]
We have tested the latest version of Nextcloud and it works as expected. Please reach out in case you are having any more issues.
