### ISSUE TITLE
Problem with shadow proxying request

### ISSUE THREAD

**Issue by akamoroz** [nginx/unit#784]
Hello,
I've moved some API endpoint to another URL and would like to configure shadow proxying (without 301/302 redirects) for old version clients the same as NGINX proxy_pass directory did. Struggling with the configuration NGINX Unit.

Example:
1. OLD Url: `/api/deprecated_url/`
2. NEW Url: `/api/actual_url/`

NGINX Unit config.json:
```
{
  "listeners": {
    "*:8080": {
      "pass": "routes"
    }
  },
  "routes": [
    {
      "match": {
        "uri": "/api/deprecated_url/"
      },
      "action": {
        "proxy": "http://127.0.0.1:8080/api/actual_url/"
      }
    },
    {
      "action": {
        "pass": "applications/my-super-app"
      }
    }
  ],
  "applications": {
    "my-super-app": {
      "type": "python 3.10",
      ....
    }
  }
}
```

However, it does not work:
```
{
        "error": "Invalid configuration.",
        "detail": "The \"proxy\" address is invalid \"127.0.0.1:8080/api/actual_url/\""
}
```

Could you please check it out and help if it is possible?
Thanks!

**Comment by hongzhidao** [comment]
Hi,
The "proxy" option is only allowed to set IP address. It's different from nginx that it can plus the URI to the "proxy_pass" directive.
BTW, we plan to support url rewrite in the future, I think it can do what you want.

**Comment by lcrilly** [comment]
Indeed. It is intended to solve this issue with https://github.com/nginx/unit/issues/732
