### ISSUE TITLE
Unit is built without the "chroot" option support error on alpine

### ISSUE THREAD

**Issue by jd1378** [nginx/unit#786]
Hi
I was trying to use chroot option with my own alpine nginx image from [here](https://hub.docker.com/r/javadmnjd/nginx-unit-alpine). when it tries to set the unit config it prints out this:
```
...
/usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/.unit.config.json
/usr/local/bin/docker-entrypoint.sh: Error: HTTP response status code is '400'
 }detail": "Unit is built without the \"chroot\" option support."
```
I checked [docs](https://unit.nginx.org/howto/source/) and `configure` help but I could not find an option for it
so how should I build it with chroot option ?

**Comment by jd1378** [comment]
it seems to be happening on `nginx/unit:1.28.0-minimal` as well

**Comment by thresheek** [comment]
`chroot` functionality is enabled automatically if your OS supports `openat2` system call.  As it's a fairly recent addition, it might not be available on every Linux distribution.

You can check if it's found looking at the output of `configure` when you're building unit.  For more details, e.g. why it was not found, you can check `build/autoconf.err` file.

**Comment by jd1378** [comment]
you mean the OS that runs docker engine must support it ?

**Comment by jd1378** [comment]
I'm confused because nginx unit's official docker image also doesn't support chroot

**Comment by thresheek** [comment]
With docker it gets complicated, and indeed both container OS and docker engine host OS must support it.

**Comment by jd1378** [comment]
thanks for explaining

**Comment by thresheek** [comment]
Eh, I've updated the comment. To be clear: I think it's only the container OS that must support it, since we don't check in runtime for that syscall.

**Comment by jd1378** [comment]
so
shouldn't the official image support it by default ?

**Comment by thresheek** [comment]
It looks like Debian 11 (which is the OS used for the minimal image) does not ship support for that syscall too.

**Comment by jd1378** [comment]
hmm
is there any ETA for this feature for minimal image ?

**Comment by thresheek** [comment]
There is no ETA.  When a new Debian version is released (probably some time in 2023), and per-language Docker Images are migrated to it, we will also move Unit docker images to this new version.

To be fair, Alpine 3.16 seems to have openat2, so you might want to check why your Alpine-based image does not have it.

**Comment by jd1378** [comment]
I checked the logs and:
`checking for openat2() ... not found` 

data from autoconf.err:
```
checking for openat2()
build/autotest.c:4:28: fatal error: linux/openat2.h: No such file or directory
    4 |                   #include <linux/openat2.h>
      |                            ^~~~~~~~~~~~~~~~~
compilation terminated.
```

any ideas ?

**Comment by jd1378** [comment]
installing `linux-headers` package should solve the issue I think
it was found after it

**Comment by thresheek** [comment]
Looking at https://pkgs.alpinelinux.org/contents?file=openat2.h&path=&name=&branch=v3.16&repo=main&arch=x86_64, it's indeed in `linux-headers`.

**Comment by jd1378** [comment]
I tested the new build and it seems to be working (no more errors)
thank you

**Comment by jd1378** [comment]
to save time for those who come and see this later, it seems the host OS kernel must also support it
I was getting errors like this on production deploys for the same image that worked locally:
```
2022/12/01 02:37:21 [alert] 41#42 *8594 opening "js/app.ced52ccd.js" at "/var/www/dist/" failed (38: Function not implemented)
```

**Comment by alejandro-colomar** [comment]
> It looks like Debian 11 (which is the OS used for the minimal image) does not ship support for that syscall too.

Debian 11 ships Linux kernel 5.10.
<https://packages.debian.org/bullseye/linux-image-amd64>

The Linux manual page for `openat2(2)` says it was added in Linux kernel 5.6:

```
$ man openat2 | sed -n '/^VERSIONS/,+2p'
VERSIONS
       openat2() first appeared in Linux 5.6.

```

So this seems to not be the issue.  I believe the kernel that needs to have the syscall is the kernel of the machine where it was built, since of course, containers don't have a kernel.  If the host of the builder where the machine was generated was too old, the image will be too old, even if the image is for Debian Sid.
