### ISSUE TITLE
Error 503 FastAPI/Starlette when client_ip forwards an IPv6 address

### ISSUE THREAD

**Issue by mdtomo** [nginx/unit#793]
```
Traceback (most recent call last):   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 750, in call_soon     self._check_closed() ValueError: invalid literal for int() with base 10: '3d08:1d82:de00:bfca:9c47:9232:353d'
```

Please see [this issue](https://github.com/nginx/unit/issues/635) which is directly related. There was a fix done to address unit sockets where this error was caused by an unexpected ':' in the ip address.

After looking at [the fix](https://github.com/nginx/unit/commit/c7543311ca70c0855721a67ac8b0408ba35f5378) I think it's only addressing unix sockets in particular.

Would it be possible to add a fix for IPv6 addresses?

#635

**Comment by ac000** [comment]
Please try the patch from [here](https://github.com/nginx/unit/issues/874#issuecomment-1546712248)

**Comment by ac000** [comment]
The [fix](https://github.com/nginx/unit/commit/47683c4704572bbe0efb3b989b35a3912b65ac83) has been merged.

**Comment by mdtomo** [comment]
Thank you!
