### ISSUE TITLE
Disable access log for specific routes

### ISSUE THREAD

**Issue by aalsmile** [nginx/unit#797]
Could you tell me how can I disable access logging for specific routes like health check or if that option doesn't currently exist, could you add the issue to backlog? Regards for developers.

**Comment by tippexs** [comment]
Hi @aalsmile at the moment this is not possible but we are talking about different configuration options for our access and error logs. I would like to flag this as enhancement and keep the issue open.

**Comment by lcrilly** [comment]
Closing as duplicate of https://github.com/nginx/unit/issues/594
