### ISSUE TITLE
Config option for disabling apps without deleting them

### ISSUE THREAD

**Issue by goc9000** [nginx/unit#798]
Hi, I'd like to suggest a seemingly simple improvement that would be of great help to some of us developing applications served by Nginx Unit.

One scenario that comes up often is that I want to deploy an updated version of an application. Ideally I'd just overwrite the binaries and then restart the app using Unit's control API, but modifying the binaries while the app is still running isn't always possible or safe (e.g. jars etc.). The app might also keep locks on some data files we need to reset. It would be better to have some way of first shutting down the app (as if it was deleted from the config), then safely performing any needed updates, and then starting the app again.

For now there is no convenient way of doing this in the config API. The only way to shut down an application is to completely delete the application config entry (and store it somewhere else), as well as any references in the routes to that particular app. Then we need to add the config entry again, restore the routes etc.

What I'd propose is just adding a 'disabled' field to the application config schema (default false of course). If an application's 'disabled' field is set to true, then Unit should behave exactly as if:

- the application's config entry does not exist, and
- any 'pass: "application/XXX"' action referring to that app is instead read as 'return: 500' or some other safe default

Unless I'm missing something, this could be done with a preprocessing step, I think. Although it does require a separation between "the config as stored by Unit and reported in the API" versus "the config that's actually interpreted for execution". Not sure if this is already the case.

**Comment by tippexs** [comment]
Hi @goc9000 sorry for the late reply. I know what you mean. I am currently handling this kind of situation with a blue / green deployment. 

I am uploading the new JAR file / static files to a new location. In my case the directory `current` is symlinkt to another directory named like a git commit hash.

In my staging Unit-Configuration I am always pointing to the latest git commit directory and test my apps. In case everything is looking good I am changing the symlink and restart the application using Units API endpoint. With this scenario I am able to switch between different app versions pretty fast.

We do not plan to have "inactive" applications in the Unit configuration but we would like to help you to find an implementation that makes your deployment process as seamless as possible.

**Comment by goc9000** [comment]
Indeed the symlink trick can help with many (most?) such situations, although one would still need to be able to shut down the app for other purposes, e.g. manipulating a data file that's normally locked, emergency killswitches etc.

Like others waiting for the official CLI, I've jury-rigged my own, and I've added some commands to do app disabling/reenabling by processing the config (outside of Unit) using the semantics I mentioned in my previous post. This works for me so far, but it's still a kludge.

I don't know how this could be solved cleanly in Unit itself without some sort of disable flag, because the issue is with the very model/paradigm Unit uses for configuration. Every part of the config JSON is utilized and there's no way to deactivate something without deleting it completely, and thus having to back it up somewhere else outside Unit. In traditional file-based config systems, you can often comment out parts you want temporarily deactivated, or unlink/move certain parts of a multi-file config. There's no way to do that with JSON.

I suppose one could also add this sort of processing to the official Unit CLI. It could handle the details of deleting app configs and backing them up to some cache in the Unit directory. There's still the tricky aspect of removing references to the app in e.g. route actions, and especially restoring them if the app is re-enabled.

**Comment by goc9000** [comment]
Interesting, didn't know that. There also seems to be some provision in the parser for multiline `/* */` comments as well.

Unfortunately the comments are only "allowed" in the sense that Unit tolerates them in the input; they are not preserved in the data model, so you can't use them to store commented out parts like you would with a config file. Come to think of it, plain comments (i.e. just used for commenting) would be a useful feature as well too, e.g. to explain/warn about some settings.

Perhaps I misunderstood the intended way to use Unit's config system... It looks more like you're not supposed to store the config permanently in Unit itself, but rather in a file, long-term, while Unit's internal database holds the "active", "effective" config. But then other features of the system no longer make much sense..

**Comment by lcrilly** [comment]
Yes, Unit supports [jsonc](https://changelog.com/news/jsonc-is-a-superset-of-json-which-supports-comments-6LwR) as input but the comments are not preserved in the internal representation.

Regarding the original question, the expected way to rotate in a new version of the application is:
1. Deploy the new version of the app to a new directory (/app/v2)
2. Configure a new `"applications"` object where `"path": "/app/v2"`
3. Change the `"routes"` object (or `"listeners"` if using a direct `"pass"`) to point at the new app
4. `DELETE` **/config/applications/v1**

There's a new command line tool ([unitc](https://github.com/nginx/unit/tree/master/tools#unitc)) that can help with steps 2-4:
```
unitc /config/applications/app | unitc /config/applications/appv2
echo '"/app/v2"' | unitc /config/applications/appv2/path
echo '"applications/appv2"' | unitc /config/routes/0/action
unitc /config/applications/app delete
```

**Comment by lcrilly** [comment]
Closing this as there are multiple alternatives that don't require Unit to carry "null" configuration around.
