### ISSUE TITLE
unit error php

### ISSUE THREAD

**Issue by vorlon001** [nginx/unit#80]
not run php unitd
error: 2018/02/18 08:32:53 [info] 15744#15744 (non ABS_MODE) php root: "/opt/unit"

os: debian 8
PHP 7.0.27-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

unit version: 0.6
configured as ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tests --modules=/usr/lib/unit/modules --cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

{
    "listeners": {
        "*:8300": {
            "application": "echo"
        }
    },
    "applications": {
        "echo": {
            "type": "php",
            "processes": 5,
            "root": "/opt/unit",
            "index": "echo.php"
        }
    }
}

2018/02/18 08:08:58 [info] 8272#8272 discovery started
2018/02/18 08:08:58 [notice] 8272#8272 module: perl 5.20.2 "build/perl.unit.so"
2018/02/18 08:08:58 [notice] 8272#8272 module: php 7.0.27-1~dotdeb+8.1 "build/php.unit.so"
2018/02/18 08:08:58 [notice] 8272#8272 module: python 2.7.9 "build/python.unit.so"
2018/02/18 08:08:58 [info] 8273#8273 controller started
2018/02/18 08:08:58 [notice] 8271#8271 process 8272 exited with code 0
2018/02/18 08:08:58 [info] 8274#8274 router started
2018/02/18 08:09:06 [info] 8345#8345 "echo" application started
2018/02/18 08:09:06 [info] 8345#8345 (non ABS_MODE) php root: "/opt/unit""
2018/02/18 08:09:07 [crit] 8271#8271 process 8345 exited on signal 11
2018/02/18 08:09:07 [warn] 8274#8274 failed to start application "echo"
2018/02/18 08:09:07 [crit] 8274#8274 failed to apply new conf

**Comment by VBart** [comment]
Please, try the debug version of Unit (built with `--debug` configure option or `unitd-debug` from our repositories).

**Comment by vorlon001** [comment]
I can not, i install on vps debian 9. all work.
One question - how to replace unix-socket management with IP?

**Comment by VBart** [comment]
The configuration management socket can be specified either while building Unit with `--control=` configure option, or while starting unitd with `--control` option.

For example:
`./configure --control=127.0.0.1:8443`
`unitd --control 127.0.0.1:8443`

You can use `--help` to get information about other supported options.

**Comment by vorlon001** [comment]
Thanks.
