### ISSUE TITLE
Add ping/pong functionality for websocket

### ISSUE THREAD

**Issue by Vovaman** [nginx/unit#802]
I think it is useful to include ping/pong to nginx.unit like in uvicorn.

**Comment by tippexs** [comment]
hi @Vovaman thanks for reaching out. can you explain what you need? some more details would help

**Comment by lcrilly** [comment]
This, I think
https://uwsgi-docs.readthedocs.io/en/latest/WebSockets.html#ping-pong

**Comment by Vovaman** [comment]
Yes, it is. So, my situation: web app on FastAPI, it uses websocket. By default FastAPI app run with [Uvicorn](https://www.uvicorn.org/). Uvicron has two command line args: --ws-ping-interval and --ws-ping-timeout. So, Uvicorn takes all the job to support ws connection = it sends ping/pong signals and there is no need to program it in my app.
But my app may be scaled and I use Nginx (not Nginx.unit) as proxy in such case. 
...And next idea was to use Nginx.unit instead of Uvicorn. 
But Nginx.unit does not support ws connection alive by itself sending ping/pong. And this is why I've returned to use Uvicorn, because it's not good idea to program this functionality. I still think Nginx + Nginx.unit is more preferrable than Nginx + Uvicorn.

**Comment by Vovaman** [comment]
So, websocket is supported.
