### ISSUE TITLE
snprintf(3) is hard to get right for concatenating strings

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit#804]
https://github.com/nginx/unit/blob/f67a01b88fd7c7057767e18a3dd06c24e94c8aa8/src/nxt_cgroup.c#L44
https://github.com/nginx/unit/blob/f67a01b88fd7c7057767e18a3dd06c24e94c8aa8/src/nxt_cgroup.c#L45

These two lines are very hard to get right.  So much that I found a bug twice (<https://github.com/nginx/unit/pull/734#discussion_r1043963527>), in two different rewrites of that code, before it was finally fixed.  The underlying problem is not in that code per se, but rather on the misdesign of string copying functions in the C library.  There's no function that does the following operation:

"Copy from a (null-terminated) string into a null-terminated string with truncation, report truncation, and allow chaining calls to this function."

Okay, I'm being too picky.  Let's loosen the requirement:

"Copy from a (null-terminated) string into a null-terminated string with truncation."

Nothing, the C standard library still doesn't have such a function.  Only OpenBSD and a few other systems added strlcpy(3) to cover that hole, but it's a misdesigned function _and_ anyway we can't use it.

Two sets of string copying functions that `"copy from a (null-terminated) string into a null-terminated string with truncation"` have been invented:

- The Linux kernel added `strscpy(9)`.  However, it has issues: You can't chain that function easily. And of course, it's not available in user space.

- OpenBSD added `strlcpy(3)` and `strlcat(3)`.  However, they also have issues: Detecting truncation is complex; they have serious performance issues; and you need to detect truncation after every call.  And, we would need to depend on libbsd on GNU/Linux systems; we don't want that.

A better function, which has optimal performance, can be chained, and is difficult to misuse, is the following:

```c
/* This code is in the public domain. */
char *
stpecpy(char *dst, char past_end[0], const char *restrict src)
{
    char *p;

    if (dst == past_end)
        return past_end;

    p = memccpy(dst, src, '\0', past_end - dst);
    if (p != NULL)
        return p - 1;

    /* truncation detected */
    past_end[-1] = '\0';
    return past_end;
}
```

I'll prepare a pull request that simplifies that code in the Isolation code, making it much simpler, faster, and safer.

**Comment by hongzhidao** [comment]
Just wondering if there is an issue with the cgroup isolation?

**Comment by alejandro-colomar** [comment]
> Just wondering if there is an issue with the cgroup isolation?

No, the bug was fixed.  This is just me wanting to remove unsafe code.

**Comment by ac000** [comment]
Can you change the subject line of the issue to remove the _unsafe_ word, unless you can actually point to a problem with them in their current form.

I think you are conflating 'unsafe' with 'hard to get right' which are not really the same thing.

**Comment by hongzhidao** [comment]
Feel free to reopen it if any issue is found.

**Comment by ac000** [comment]
Hmm, not really completed.. where does that come from?, lets see...

**Comment by ac000** [comment]
Hmm, so we only have two options

"Completed"
and
"Not Planned"

That misses quite a wide gamut of possibilities...

Seems it's a relatively new [thing](https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons). Can't immediately see a way of changing, adding new ones (like with issue labels...), oh well...
