### ISSUE TITLE
Match source IP not working as expected with subnet and IP exception

### ISSUE THREAD

**Issue by mattxtaz** [nginx/unit#819]
In the [https://unit.nginx.org/configuration/#instant-responses-redirects](url) page there is an example that shows a simple allow/deny access control list based on source IP. This does not appear to work as expected.

Assuming I'm using 10.0.0.10 as a source IP:

If I use !10.0.0.0/8 then I get 200 OK.
If I use 10.0.0.10 then I get 403 Forbidden.
If I use !10.0.0.0/8 10.0.0.10 then I get 200 OK where I would expect to get 403 Forbidden.

So it looks like the negated entry for the whole subnet is taking precedence over the single IP entry. This may be by design, but the fact the documentation has !192.168.1.0/24 and 192.168.1.1 in it suggests to me that everything in the subnet should be allowed except for that single IP address.

I have tried changing the order and that doesn't appear to make any difference. I'm also using IPv6 but I haven't yet tested it with that, but I assume that is likely to work in a similar way.

**Comment by andrey-zelenkov** [comment]
Hi @mattxtaz, thank you for the report. Could you please share an example of configuration showing your issue?

Please note the matching logic (including `source`) described here: https://unit.nginx.org/configuration/#match-resolution. 

Regarding the allow/deny example from here https://unit.nginx.org/configuration/#instant-responses-redirects there is a mistake in our documentation. It should be `192.168.1.0/24` and `!192.168.1.1` like in https://unit.nginx.org/configuration/#allow-deny which means allow whole subnet `/24` excluding one address from it. (I have already notified @artemkornev about the necessary fix here).

**Comment by mattxtaz** [comment]
So your documentation has it backwards, you are intending to exclude one specific IP from a subnet. Whereas what I want to do is include one specific IP from a subnet.

The exact config I am trying to use is this (although I've changed the IPv6 prefix for the example). I'm trying to deny everything except for localhost, 10.0.0.0/8, 2001:0DB8::/48, but allow 10.0.0.10 and 2001:0DB8:1234::10 as exceptions. This kind of config works on nginx but I guess it doesn't work the same way on unit. With this config 10.0.0.10 and 2001:0DB8:1234::10 are allowed.

```
{
    "match": {
        "source": [
            "!127.0.0.1",
            "!::1",
             "!10.0.0.0/8",
             "10.0.0.10",
             "!2001:0DB8:1234::/48",
             "2001:0DB8:1234::10"
         ]
 },
 
 "action": {
     "return": 403
 }
```

The equivalent nginx config that I'm trying to replicate is this:

```
allow 127.0.0.1;
allow ::1;
deny 10.0.0.10;
allow 10.0.0.0/8;
deny 2001:0DB8:1234::10;
allow 2001:0DB8:1234::/48;
deny all;
```

**Comment by andrey-zelenkov** [comment]
To replicate example from your message above, Unit configuration should looks like:
```
{
    "match": {
        "source": [
            "!10.0.0.10",
            "!2001:0DB8:1234::10",
            "127.0.0.1",
            "::1",
            "10.0.0.0/8",
            "2001:0DB8:1234::/48",
         ]
 },

 "action": {
     "return": 403
 }
 ```
 
Since `!` is used for negation patterns and should be used to replace `deny` directive (see https://unit.nginx.org/configuration/#allow-deny). Please try to use the above config and reconfirm the issue if it still exists.

**Comment by mattxtaz** [comment]
That's the opposite of what I want isn't it? Because the action is 403 (deny). Don't I want it to be more like this? But this doesn't work. If I access from 10.0.0.10 or 2001:0DB8:1234 ::10 I get 200 OK.

```
            "10.0.0.10",
            "2001:0DB8:1234::10",
            "!127.0.0.1",
            "!::1",
            "!10.0.0.0/8",
            "!2001:0DB8:1234::/48"
```

But just to confirm, if I use the config that you came up with the same happens. If I access from 10.0.0.10 or 2001:0DB8:1234 ::10 I still get 200 OK. Which makes sense to me as they are negated against a 403 action.

```
            "!10.0.0.10",
            "!2001:0DB8:1234::10",
            "127.0.0.1",
            "::1",
            "10.0.0.0/8",
            "2001:0DB8:1234::/48"
```

Expectation is that if I access it using 127.0.0.1, ::1, 10.0.0.0/8, 2001:0DB8:1234 ::/48 then I get 200 OK. If I access it using 10.0.0.10 or 2001:0DB8:1234 ::10 then I get 403 Forbidden. And if I access it from any other IP address outside of those ranges then I also get 403 Forbidden.

As another test I just changed the config to use 10.0.0.11 and 2001:0DB8:1234 ::11 instead and this gives 403 Forbidden if I access from .10 or ::10 so the rule is working, just the opposite way around to what I want.

**Comment by andrey-zelenkov** [comment]
Yeah, didn't notice that action is 403. Sorry. 

> Expectation is that if I access it using 127.0.0.1, ::1, 10.0.0.0/8, 2001:0DB8:1234 ::/48 then I get 200 OK. If I access it using 10.0.0.10 or 2001:0DB8:1234 ::10 then I get 403 Forbidden. And if I access it from any other IP address outside of those ranges then I also get 403 Forbidden.

In this case I would suggest to use several steps during routing to be flexible enough to fulfil all requirements (since we need `403` instead of default `404` response): 

```               
 "routes": [
    {
        "match": {
            "source": [
                "2001:0DB8:1234::10",
                "10.0.0.10",
            ],
        },
        "action": {"return": 403},
    },
    {
        "match": {
            "source": [
                "127.0.0.1",
                "::1",
                "10.0.0.0/8",
                "2001:0DB8:1234::/48",
            ],
        },
        "action": {"return": 200},
    },
    {"action": {"return": 403}},
],
```
So, at the first step denying single IPs inside allowed ranges and returning 403 for them. At the second step return 200 for allowed ranges. And the third step is setting the default 403 response for all other addresses.

**Comment by mattxtaz** [comment]
OK. This approach works. So yes I'll use this, thank you very much for your advice.

What confused me is the documentation showing the same thing as what I was trying to do and then finding that it didn't work, but you've confirmed that the documentation was wrong so I'm happy with that now that I know how it is expected to work.

**Comment by andrey-zelenkov** [comment]
@mattxtaz yeah, we will fix documentation.

And actually, I have just realised that it can be simplified using 2 steps only:
```
"routes": [
    {
        "match": {
            "source": [
                "!2001:0DB8:1234::10",
                "!10.0.0.10",
                "127.0.0.1",
                "::1",
                "10.0.0.0/8",
                "2001:0DB8:1234::/48",
            ],
        },
        "action": {"return": 200},
    },
    {"action": {"return": 403}},
],
```

Please try this one, hope this will works for you too.

**Comment by mattxtaz** [comment]
Yes. That also seems to work. So I've used this now. I think we're good! Again, thank you for your help here. Much appreciated. I'm trying to replicate as much of my nginx config that sits in front of unit into unit itself with the eventual goal of not needing to use nginx, so this helps a lot.

**Comment by lcrilly** [comment]
Hi @mattxtaz, I love to hear "not needing to use nginx" because that's the long term goal. Would love to know what else you'd need to get there in your environment.

If you can spare 5-10 minutes to fill out our developer survey it would really help 🙏 https://forms.office.com/r/Ma4WBiaxz8

**Comment by mattxtaz** [comment]
Hi @lcrilly Yes, I wasn't sure if unit was planned as an eventual replacement for nginx or not, but I guess you have just confirmed that. My main reason at the moment for doing this was for disaster recovery purposes. If I can get my applications and websites back up and running quickly on unit only without needing to also install and configure nginx then that helps me out. But of course if I can do that then I no longer actually need nginx.

I will spend some time filling in your survey when I get a spare moment. But as a quick brain dump of missing features I would be looking for eventually, although not all of these are critical at all and I wouldn't necessarily need them:

1) gzip compression
2) proxy_set_header to set some headers in proxied connection requests like Host
3) HTTPS connections in proxied requests
4) Would be useful if you could upload a new TLS certificate/key bundle that overwrites the existing in-use bundle. Currently you have to upload a new second bundle, change the listener config to point to that new bundle, and then delete the old bundle. Which is complicated and needs more scripting than just uploading a new bundle.
5) add_header to set some headers in responses to set things like Strict-Transport-Security etc.
6) auth basic support for username/password access to specific route matches
7) ability to override and switch off access_log for specific route matches to prevent spam of things like API endpoints
8) autoindex support to provide pretty indexes of empty directories
9) Some ability to rewrite content like the nginx ngx_http_sub_module (I guess this will need plugin support etc.)
10) Adding the new unitc wrapper to the main distribution would be useful, any easier way to use curl for changing config is welcomed. Not all platforms are going to have curl installed etc. either. So may be better if unitc was a standalone application that didn't depend on curl.

Hope that helps! But I will put this into your survey as well.

**Comment by lcrilly** [comment]
@mattxtaz thank you for taking the time!

**Comment by mattxtaz** [comment]
@lcrilly I spent some time today replicating all of my nginx configuration into unit including all of my vhosts. The good news is that it mostly works and I could run it standalone without nginx and only sacrifice some minor features of my web applications.

But that said it's given me a much greater understanding of what's missing in unit and what I would need to replace nginx completely. So I've edited my post above with a new list of what's missing, in the order that I think these are important to me. And I've filled in your developer survey for a second time just to update my answers.

**Comment by lcrilly** [comment]
@mattxtaz that's really appreciated. Can I send you some swag? Drop me a note: liam@nginx.com

**Comment by mattxtaz** [comment]
Two weeks later.....

Something else that I've realised is missing is support for the Range, Accept-Ranges, Content-Range headers and 206 Partial Content responses from a share. On NGINX this allows you to fast forward/rewind mp4 media files but you can't do that on Unit.

As it turns out though I have managed to find enough workarounds for all of my list above that I have successfully switched to Unit and I'm only proxying through to NGINX to get some fancy directory indexes from autoindex. There are some compromises, like I've now lost HTTP/2, gzip, password access (have to rely on IP), and the seeking around in mp4 files no longer works, but I can live without these things.

Also because there is no proxy_add_header support I can't pass the real IP address of the client through to the proxied servers so everything behind the proxy thinks I am 127.0.0.1.

And I've had to create a 39 line shell script to automate acme.sh/certbot renewing TLS certificates purely because you can't overwrite the in-use certificate bundles. If you could do that then it would become a 1 line script.

But it is great that I have mostly managed to switch to Unit and if I didn't care about autoindex I could get rid of NGINX now and only use Unit. So thank you very much to the people involved in this. I look forward to seeing new features arriving in future releases!
