### ISSUE TITLE
X-Forwarded-For header

### ISSUE THREAD

**Issue by urba1n** [nginx/unit#82]
With my current application server, my application receives a X-Forwarded-For header with "<client>, <proxy1>" value. With unit, the X-Forwarded-For header has always <proxy1> value; I even tried to force the value of X-Forwarded-For on the proxy to <client>, but in my application it is still <proxy1>.

**Comment by VBart** [comment]
What type of your application, python, perl, php, or go?

**Comment by urba1n** [comment]
Python 2.7, django framework

**Comment by VBart** [comment]
Indeed, Unit currently is unable to concatenate multiple `X-Forwarded-For` headers. But with one header containing commas it works fine. Here is the WSGI test application:
```
def application(environ, start_response):
    start_response('200 OK', [])
    return (environ['HTTP_X_FORWARDED_FOR'])
```
And the result:
```
$ curl -H "X-Forwarded-For: 203.0.113.195, 70.41.3.18, 150.172.238.178" 127.1:8171                                     
203.0.113.195, 70.41.3.18, 150.172.238.178
```

**Comment by VBart** [comment]
Ok, I see. There's a problem if request header ends with space.
