### ISSUE TITLE
Create complex log

### ISSUE THREAD

**Issue by MrSipping** [nginx/unit#827]
Hi, I know that with the new 1.29 version the logs, if I'm not mistaken, can be more complex and I wanted to ask where I can find the entries to create the logs a little more complex and with more information. I mean the access logs

**Comment by lcrilly** [comment]
Hello. Custom access logs arrived with 1.28. There is some information about this in the announcement: https://unit.nginx.org/news/2022/unit-1.28.0-released/#more-variables-and-access-log-customization

It's also covered in the main docs:
https://unit.nginx.org/configuration/#access-log

You'll find a list of all the variables that can be included here:
https://unit.nginx.org/configuration/#variables-scripting

**Comment by MrSipping** [comment]
> Hello. Custom access logs arrived with 1.28. There is some information about this in the announcement: https://unit.nginx.org/news/2022/unit-1.28.0-released/#more-variables-and-access-log-customization
> 
> It's also covered in the main docs: https://unit.nginx.org/configuration/#access-log
> 
> You'll find a list of all the variables that can be included here: https://unit.nginx.org/configuration/#variables-scripting

Thank u so much

**Comment by MrSipping** [comment]
> Hello

I try this: 

```
"path": "/var/log/unit/basic_access.log",
        "format": "`${host + ': ' + uri}`"
```
but give me error to apply new configuration

**Comment by lcrilly** [comment]
You don't need to use the JavaScript template literal format for that example. Try this instead.

```json
{
  "path": "/var/log/unit/basic_access.log",
  "format": "${host}: $uri"
}
```

**Comment by MrSipping** [comment]
> You don't need to use the JavaScript template literal format for that example. Try this instead.
> 
> ```json
> {
>   "path": "/var/log/unit/basic_access.log",
>   "format": "${host}: $uri"
> }
> ```

I try this:

`"access_log":{
        "path": "/var/log/unit/basic.access.log",
        "format": "${host}: $uri"
        },
`

but give me this error: 

Warning: Couldn't read data from file "lab-tools-config.json", this makes an 
Warning: empty POST.
{
	"error": "Invalid JSON.",
	"detail": "An empty JSON payload isn't allowed.  It must be either a literal (null, true, or false), a number, a string (in double quotes \"\"), an array (with brackets []), or an object (with braces {}).",
	"location": {
		"offset": 0,
		"line": 1,
		"column": 1
	}
}

**Comment by hongzhidao** [comment]
Hi MrSipping,
Could you share the full content from lab-tools-config.json" and the command you post to the control API?

**Comment by MrSipping** [comment]
> Hi MrSipping, Could you share the full content from lab-tools-config.json" and the command you post to the control API?

Sure: 

`{
    "settings": {
            "http": {
                    "max_body_size": 1073741824,
                    "discard_unsafe_fields": false
            }
    },

   "access_log":{
        "path": "/var/log/unit/basic.access.log",
        "format": "${host}: $uri"
        },

  "listeners": {
    "*:8008": {
                    "pass": "routes/main"
            }

    },

    "routes": {
            "main": [
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*.php"
                                    ]
                            },

                            "action": {
                                    "pass": "applications/adminer/index"
                            }
                    },
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*"
                                    ]
                            },

                            "action": {
                                    "share": "/test/db/$uri"
                            }
                    },
                    {
                            "action": {
                                    "return": 404
                            }
                    }
            ]
    },
    "applications": {
        "adminer": {
                "type": "php",
                "processes": 12,
                "user": "www-data",
                "group": "www-data",
                "targets": {
                        "direct": {
                                "root": "/test/db/defdb/"
                        },

                        "index": {
                                "root": "/test/db/defdb/",
                                "script": "prova_db.php"
                        }
                },

                "limits": {
                        "timeout": 3600,
                        "requests": 1024
                },

                "environment": {},
                {
    "settings": {
            "http": {
                    "max_body_size": 1073741824,
                    "discard_unsafe_fields": false
            }
    },

   "access_log":{
        "path": "/var/log/unit/basic.access.log",
        "format": "${host}: $uri"
        },

  "listeners": {
    "*:80": {
                    "pass": "routes/main"
            }

    },

    "routes": {
            "main": [
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*.php"
                                    ]
                            },

                            "action": {
                                    "pass": "applications/adminer/index"
                            }
                    },
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*"
                                    ]
                            },

                            "action": {
                                    "share": "/test/db/$uri"
                            }
                    },
                    {
                            "action": {
                                    "return": 404
                            }
                    }
            ]
    },
    "applications": {
        "adminer": {
                "type": "php",
                "processes": 12,
                "user": "www-data",
                "group": "www-data",
                "targets": {
                        "direct": {
                                "root": "/test/db/defdb/"
                        },

                        "index": {
                                "root": "/test/db/defdb/",
                                "script": "prova_db.php"
                        }
                },

                "limits": {
                        "timeout": 3600,
                        "requests": 1024
                },

                "environment": {},
                "options": {
                        "admin": {
                                "memory_limit": "1024M",
                                "variables_order": "EGPCS",
                                "expose_php": "0",
                                "post_max_size": "256M",
                                "upload_max_filesize": "256M",
                                "max_execution_time": "3600",
                                "max_input_time": "1800",
                                "default_socket_timeout" : "3600"
                        },

                        "user": {
                                "display_errors": "1"
                        }
                }
        }
    }
}`

**Comment by MrSipping** [comment]
> Hi MrSipping, Could you share the full content from lab-tools-config.json" and the command you post to the control API?

Sure: 

`
{
    "settings": {
            "http": {
                    "max_body_size": 1073741824,
                    "discard_unsafe_fields": false
            }
    },

   "access_log":{
        "path": "/var/log/unit/basic.access.log",
        "format": "${host}: $uri"
        },

  "listeners": {
    "*:8008": {
                    "pass": "routes/main"
            }

    },

    "routes": {
            "main": [
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*.php"
                                    ]
                            },

                            "action": {
                                    "pass": "applications/adminer/index"
                            }
                    },
                    {
                            "match": {
                                    "uri": [
                                            "/defdb/*"
                                    ]
                            },

                            "action": {
                                    "share": "/test/db/$uri"
                            }
                    },
                    {
                            "action": {
                                    "return": 404
                            }
                    }
            ]
    },
    "applications": {
        "adminer": {
                "type": "php",
                "processes": 12,
                "user": "www-data",
                "group": "www-data",
                "targets": {
                        "direct": {
                                "root": "/test/db/defdb/"
                        },

                        "index": {
                                "root": "/test/db/defdb/",
                                "script": "prova_db.php"
                        }
                },

                "limits": {
                        "timeout": 3600,
                        "requests": 1024
                },

                "environment": {},
                "options": {
                        "admin": {
                                "memory_limit": "1024M",
                                "variables_order": "EGPCS",
                                "expose_php": "0",
                                "post_max_size": "256M",
                                "upload_max_filesize": "256M",
                                "max_execution_time": "3600",
                                "max_input_time": "1800",
                                "default_socket_timeout" : "3600"
                        },

                        "user": {
                                "display_errors": "1"
                        }
                }
        }
    }
}
`

**Comment by hongzhidao** [comment]
It seems the JSON is invalid, you can check it with some tools online first.

**Comment by MrSipping** [comment]
> It seems the JSON is invalid, you can check it with some tools online first.

I try this site: https://jsonformatter.curiousconcept.com/# and this site: https://jsonlint.com/ 

Both give me Valid JSON

**Comment by hongzhidao** [comment]
Yep, it's valid. Sorry that I copied it from yours and more are added...
Will check again.

**Comment by hongzhidao** [comment]
> > You don't need to use the JavaScript template literal format for that example. Try this instead.
> > ```json
> > {
> >   "path": "/var/log/unit/basic_access.log",
> >   "format": "${host}: $uri"
> > }
> > ```
> 
> I try this:
> 
> `"access_log":{ "path": "/var/log/unit/basic.access.log", "format": "${host}: $uri" }, `
> 
> but give me this error:
> 
> Warning: Couldn't read data from file "lab-tools-config.json", this makes an Warning: empty POST. { "error": "Invalid JSON.", "detail": "An empty JSON payload isn't allowed. It must be either a literal (null, true, or false), a number, a string (in double quotes ""), an array (with brackets []), or an object (with braces {}).", "location": { "offset": 0, "line": 1, "column": 1 } }

What's your command to do it?

**Comment by MrSipping** [comment]
> > > You don't need to use the JavaScript template literal format for that example. Try this instead.
> > > ```json
> > > {
> > >   "path": "/var/log/unit/basic_access.log",
> > >   "format": "${host}: $uri"
> > > }
> > > ```
> > 
> > 
> > I try this:
> > `"access_log":{ "path": "/var/log/unit/basic.access.log", "format": "${host}: $uri" }, `
> > but give me this error:
> > Warning: Couldn't read data from file "lab-tools-config.json", this makes an Warning: empty POST. { "error": "Invalid JSON.", "detail": "An empty JSON payload isn't allowed. It must be either a literal (null, true, or false), a number, a string (in double quotes ""), an array (with brackets []), or an object (with braces {}).", "location": { "offset": 0, "line": 1, "column": 1 } }
> 
> What's your command to do it?

Now the json file works, I wrote it and it works... I entered the configuration for the access log but it gives me an error to apply new configuration

`"access_log": {
                "path": "/var/log/unit/basic_access.log",
                "format": "${host}: $uri"
    },
`

This is the command: 

curl -X PUT -d @lab-tools-config.json --unix-socket /var/run/control.unit.sock http://localhost/config/

**Comment by MrSipping** [comment]
> ```json
> "format": "${host}: $uri"
> ```

Okay now work, how can i put as many variables as possible in the access.log file??

**Comment by hongzhidao** [comment]
1. Note the method difference between `PUT` and `POST` for updating configuration.
```
POST | Updates the array at the request URI, appending the JSON value from the HTTP request body.
PUT | Replaces the entity at the request URI and returns a status message in the HTTP response body.
```

2. > how can i put as many variables as possible in the access.log file?

You'll find a list of all the variables that can be included here:
https://unit.nginx.org/configuration/#variables-scripting

BTW, let us know if there are variables you want to use that we don't support yet.

**Comment by MrSipping** [comment]
> 1. Note the method difference between `PUT` and `POST` for updating configuration.
> 
> ```
> POST | Updates the array at the request URI, appending the JSON value from the HTTP request body.
> PUT | Replaces the entity at the request URI and returns a status message in the HTTP response body.
> ```
> 
> 2. > how can i put as many variables as possible in the access.log file?
> 
> You'll find a list of all the variables that can be included here: https://unit.nginx.org/configuration/#variables-scripting
> 
> BTW, let us know if there are variables you want to use that we don't support yet.

hi i can't figure out how to use these variables in logs

_

args.* | Query string arguments; Color=Blue is args.Color, and so on.
cookies.* | Request cookies; an authID cookie is cookies.authID, and so on.
headers.* | Request header fields; Accept is headers.Accept, Content-Encoding is headers['Content-Encoding'] (hyphen requires an array property accessor), and so on.

_

**Comment by lcrilly** [comment]
> args.* | Query string arguments; Color=Blue is args.Color, and so on.
> cookies.* | Request cookies; an authID cookie is cookies.authID, and so on.
> headers.* | Request header fields;

The variable that you've quoted are actually JavaScript objects. They are not listed in the [documentation provided for variables](https://unit.nginx.org/configuration/#variables-scripting) in Unit.

If you wish to log **specific** args, cookies or headers they can be accessed as follows
```json
  "format": "$arg_utm $cookie_session $header_authorization"
```

Notice that the name of the field must be specified. Values with hyphens (`-`) should be folded to an underscore (`_`), e.g. `$header_user_agent`.

If you wish to log **all** of the fields within one of these variables (e.g. log all request headers) that is not currently possible. The JavaScsrpt objects mentioned above will enable this use case in the next release.

What is your intention? It would be easier to help you if you could share your goal, or the final log output you are trying to create.

**Comment by MrSipping** [comment]
> > args.* | Query string arguments; Color=Blue is args.Color, and so on.
> > cookies.* | Request cookies; an authID cookie is cookies.authID, and so on.
> > headers.* | Request header fields;
> 
> The variable that you've quoted are actually JavaScript objects. They are not listed in the [documentation provided for variables](https://unit.nginx.org/configuration/#variables-scripting) in Unit.
> 
> If you wish to log **specific** args, cookies or headers they can be accessed as follows
> 
> ```json
>   "format": "$arg_utm $cookie_session $header_authorization"
> ```
> 
> Notice that the name of the field must be specified. Values with hyphens (`-`) should be folded to an underscore (`_`), e.g. `$header_user_agent`.
> 
> If you wish to log **all** of the fields within one of these variables (e.g. log all request headers) that is not currently possible. The JavaScript objects mentioned above will enable this use case in the next release.
> 
> What is your intention? It would be easier to help you if you could share your goal, or the final log output you are trying to create.

I was trying to have the original host calling the page because the calls go through an api gateway and it gives me the ip of the api gateway

**Comment by lcrilly** [comment]
For this use case, the API gateway should provide the client's source IP address in the `Forwarded` or `X-Forwarded-For` request header (see [RFC 7239](https://www.rfc-editor.org/rfc/rfc7239.html)). The latter is more common, which is then available to Unit as `$header_x_forwarded_for`. This `"access_log"` format will replace the IP address of the API gateway with the value from the `X-Forwarded-For` header.

```json
"format": "$header_x_forwarded_for - - [$time_local] \"$request_line\" $status $body_bytes_sent \"$header_referer\" \"$header_user_agent\""
```

**Comment by MrSipping** [comment]
> 

I try this sequence but give me this: `- - -`

Why?

**Comment by lcrilly** [comment]
Presumably because your API gateway isn't behaving as I described. You may need to configure it to forward the client IP address.

**Comment by MrSipping** [comment]
> Presumably because your API gateway isn't behaving as I described. You may need to configure it to forward the client IP address.

These are the logs I have on nginx and would also like on Unit:

`'$time_iso8601 $msec $remote_addr "$http_x_forwarded_for" "$remote_user" '
                            '"$server_name" "$host" $request_method "$request" $status $request_length $body_bytes_sent $request_time '
                            '$http_referer $upstream_addr $upstream_status $upstream_response_length $upstream_response_time $upstream_cache_status '
                            '"$ssl_protocol/$ssl_cipher" "$http_cf_ray" '
                       '"$http_user_agent" '`

**Comment by tippexs** [comment]
Thanks for sharing @MrSipping with every release we are adding more variables to Unit to fill this gap. The "new variables" will always be announced in the release notes. So keep an eye on them.

**Comment by MrSipping** [comment]
> Thanks for sharing @MrSipping with every release we are adding more variables to Unit to fill this gap. The "new variables" will always be announced in the release notes. So keep an eye on them.

Which variables are already present among those I have indicated? Thank you

**Comment by lcrilly** [comment]
@MrSipping , I have shared the documentation for variables more than once. Please scroll up.

**Comment by MrSipping** [comment]
Hi, one question, how can I insert the cloudflare cf-ray in the access logs via the header? I tried a thousand ways but failed

**Comment by lcrilly** [comment]
`$header_cf_ray` should do it. What does your **/config/access_log/format** value look like?

**Comment by MrSipping** [comment]
This is my config: 
`$header_cf_ray $host - $header_x_forwarded_proto - $header_x_forwarded_for - - [$time_local] | $request_time | $status | $body_bytes_sent \"$header_user_agent\""` 

I would like to include the upstreams but I don't think they are there yet, correct?

> `$header_cf_ray` should do it. What does your **/config/access_log/format** value look like?

**Comment by lcrilly** [comment]
> I would like to include the upstreams but I don't think they are there yet, correct?

That's correct. We don't yet have variables about proxied requests.
