### ISSUE TITLE
Docker Container for PHP 8.2

### ISSUE THREAD

**Issue by nuvolapl** [nginx/unit#829]
Is there any reason why there is no docker image with PHP 8.2 yet?

**Comment by tippexs** [comment]
Hi @nuvolapl Currently non of the supported platforms ship PHP8.2 as a default version. But I can understand the issue. Let me try something for you and come back to you tomorrow if that helps.

**Comment by tippexs** [comment]
Hi @nuvolapl - I have tested the build process for you and if you don't mind you can build the image by yourself.

```shell
git clone https://github.com/nginx/unit
cd unit
git checkout 1.29.0
cd pkg/docker/
make build-php8.2 VERSION_php=8.2
```

This will create a docker image tagged as `unit:1.29.0-php8.2`. Feel free to use this image as a base image to build your containers and add additional php-packages.

**Comment by roman-lyubimov** [comment]
@tippexs thank you :)

**Comment by nuvolapl** [comment]
@tippexs This is a very good temporary solution ;-) Especially that I develop on macOS M1 (arm64 arch, it's not supported on your docker hub registry).

**Comment by tippexs** [comment]
I would say this is a work around it is simply not present enough on our website. Even if it is in our docs.

I am glad we have found a way that is working for you. Quick question how important are fully customizable docker images in terms of language versions and multiple languages in a single container image

**Comment by jameshulse** [comment]
> Quick question how important are fully customizable docker images in terms of language versions and multiple languages in a single container image

Language versioning is really important to us. It is common to have older projects still running on a particular older version of a runtime i.e PHP 7.4, and then newer projects in the same company on the cutting edge like PHP 8.2. We wouldn't require both runtimes in a single image, but having the option to pull both is useful.

Your script to build a custom image has worked for us, but it wasn't very obvious in the documentation. Otherwise we're really happy with Nginx Unit so far!

**Comment by lcrilly** [comment]
Hi @jameshulse , I'm glad this was useful. We'll think about how to provide a wider range of runtime versions in our images.

FWIW, it *is* possible to have multiple language runtime versions in the same Unit instance. It can be helpful for testing and migration purposes.

If you have 5-6 minutes I'd love to get some feedback on how you're using Unit and what we could do better!
A short survey ➡️ https://forms.office.com/r/Ma4WBiaxz8

**Comment by Elnadrion** [comment]
Hi guys. Image with 8.2 on board would be helpful 😅🙏🏻

P.S. We had the same problem last year, when we tried to migrate to 8.1 and there was no Nginx Unit 8.1 image 😭

**Comment by meezaan** [comment]
> Hi guys. Image with 8.2 on board would be helpful 😅🙏🏻
> 
> P.S. We had the same problem last year, when we tried to migrate to 8.1 and there was no Nginx Unit 8.1 image 😭

You can use ghcr.io/islamic-network/php:8.2-unit for now, although it comes with many pho extensions you may not require. 

Or meezaan/unit.129.1-php8.2 for the bare bones image.

Until officially available I will keep this up to date.

**Comment by Elnadrion** [comment]
@meezaan thanks a lot man! 😇

**Comment by meezaan** [comment]
@Elnadrion @nuvolapl @jameshulse There is now an official Docker Hub image for this. See https://hub.docker.com/_/unit and https://github.com/nginx/unit/issues/606.

**Comment by Elnadrion** [comment]
@meezaan awesome! Thanks!

**Comment by thresheek** [comment]
Closing this as we've announced Official Images with 1.30.0.
