### ISSUE TITLE
Is $HOME properly set when setuid() to `unit`? (python)

### ISSUE THREAD

**Issue by sebastian-philipp** [nginx/unit#834]
Hi there, 

I'm facing https://github.com/psycopg/psycopg2/issues/1535 right now, with this app setting: 

```json
  "applications": {
    "myapp": {
      "type": "python 3.10",
      "path": "/usr/src/myapp",
      "module": "myapp.wsgi"
    }
  },
```

Trying to open a secure postgres connection now suddenly fails with: 

```
connection to server at "dbhost" (10.0.0.123), port 20184 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
```

Looks like libpq [now looks into $HOME since version 15.1](https://why-upgrade.depesz.com/show?from=14.6&to=15.1&keywords=libpq):

> On non-Windows platforms, consult the HOME environment variable to find the user's home directory

and `ps aux` looks like so: 

```
root@mycontainer-5d48758b88-8v6db:/usr/src# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2416   512 ?        Ss   09:30   0:00 /bin/sh -c entrypoint.sh
root         7  0.0  0.0   9184  3880 ?        S    09:30   0:00 unit: main v1.26.1 [unitd --no-daemon --control unix:/var/run/control.unit.sock]
root        10  0.0  0.0   4252   564 ?        S    09:30   0:00 tail -f /tmp/django.log
unit        39  0.0  0.0   8540  1240 ?        S    09:30   0:00 unit: controller
unit        40  0.0  0.0 174088  4752 ?        Sl   09:30   0:00 unit: router
unit        41  0.0  0.0  13088  2836 ?        S    09:30   0:00 unit: "myapp" prototype
unit        42  0.0  1.1 200252 81264 ?        Sl   09:30   0:01 unit: "myapp" application
root        53  0.0  0.0   5988  3740 pts/0    S    10:55   0:00 bash
root        61  0.0  0.0   8588  3292 pts/0    R+   10:57   0:00 ps aux
```

Before digging deeper into this: Does unit changes HOME to something suitable or does it still point to `/root/`?

**Comment by lcrilly** [comment]
The error is "permission denied". Notice that the `unit: "myapp"` processes are owned by the `unit` user (not root).

Some options for you to consider. I don't know enough about your environment to make a recommendation.

1. Change the file permissions for postgresql.crt
2. Explicitly set the `"user"` value for the application to a user that can access the file
3. Explicitly set the $HOME environment variable for the application. Example below

```json
  "applications": {
    "myapp": {
      "type": "python 3.10",
      "path": "/usr/src/myapp",
      "module": "myapp.wsgi",
      "user": "appuser",
      "environment": {
        "HOME": "/path/to/app/home"
      }
    }
  },
```

**Comment by sebastian-philipp** [comment]
Thank you! 
> The error is "permission denied". Notice that the `unit: "myapp"` processes are owned by the `unit` user (not root).
>
Right. And the unit user doesn't have read permissions on `/root` that's why I'm getting those permission errors. I wound't be surprised if $HOME for the unit user prints out /root when run by nginx-unit.
 
> Some options for you to consider. I don't know enough about your environment to make a recommendation.
> 
> 1. Change the file permissions for postgresql.crt
> 2. Explicitly set the `"user"` value for the application to a user that can access the file
> 3. Explicitly set the $HOME environment variable for the application. Example below

Thank you!

**Comment by sebastian-philipp** [comment]
Workaround: Setting PGSSLCERT to /tmp/postgresql.crt helps.

**Comment by tippexs** [comment]
Will close this one then. Please let us know if you need anything else @sebastian-philipp
