### ISSUE TITLE
Golang: Is it possible for Unit to use Fiber framework's Fasthttp handler?

### ISSUE THREAD

**Issue by figuerom16** [nginx/unit#835]
unit.ListenAndServe seems to be anticipating an http.Handler and Fiber uses fasthttp.RequestHandler.
I don't think I'm passing Fiber's Handler correctly right now also.
Since Fiber doesn't use the native net/http I'm seeing if it is possible to use Fasthttp with Unit even though it's not standard.
If not then it's no big deal and I'll close this issue as this isn't standard for Go.

Example

    package main
    
    import (
        "github.com/gofiber/fiber/v2"
        unit "unit.nginx.org/go"
    )
    
    func main() {
        app := fiber.New()
    
        app.Get("/", func(c *fiber.Ctx) error {
            return c.SendString("Hello, World!")
        })
        // Fiber's Listener app.Listen(":8080")
        unit.ListenAndServe(":8080", app.Handler())
    }

**Comment by tippexs** [comment]
Hi @figuerom16 thanks for your question. We have never tried this but feel free to elaborate and let us know if you have any issues. Happy to have a look.

Sorry - this is not the kind of an answer you would like to hear I guess :)

**Comment by figuerom16** [comment]
Fiber has an net/http adaptor that will allow it to work with Unit.  I'll have to test the drawbacks to this approach, but it is working.

	package main
	
	import (
		"github.com/gofiber/adaptor/v2"
		"github.com/gofiber/fiber/v2"
		unit "unit.nginx.org/go"
	)
	
	func main() {
		app := fiber.New()
	
		app.Get("/", func(c *fiber.Ctx) error {
			return c.SendString("Hello, World!")
		})
	
		// Fiber's Listener app.Listen(":8080")
		unit.ListenAndServe(":8080", adaptor.FiberApp(app))
	}

**Comment by tippexs** [comment]
This looks good! Thanks for testing. Would like to get your feedback on this.
