### ISSUE TITLE
var/cache folder permissions for root instead unit

### ISSUE THREAD

**Issue by anutator** [nginx/unit#836]
We had docker image generated by werf for Kubernetes. Now I create this image with dind (docker in docker) in Gitlab and I have an error with user permissions when starting appication from this image in Kubernetes. Application runs in docker in /app directory, the owner and group of /app and folders/files inside /app is unit. During start application creates var directory inside /app/ And unit is owner of folders inside that directory (cache, logs). But now root is owner. So application is started but not working. In debug we see errors:

```
Failed to create "/app/var/cache/prod/translations": mkdir(): Permission denied
Unable to write to the "/app/var/cache/prod" directory.
```

Tested on nginx/unit:1.22.0-php8.0, nginx/unit:1.26.0-php8.0. Also created custom image nginx/unit:1.29.0-php8.0? the same result.
Examples.

Old container, correct permissions:
```
pp-lkp-backend-cddb656b6-px5fn:/app# ls -la /app/var
total 0
drwxrwxrwx. 4 root root 30 Feb  6 03:42 .
drwxr-xr-x. 1 unit unit 42 Feb  6 03:43 ..
drwxr-xr-x. 3 unit unit 18 Feb  6 03:42 cache
drwxr-xr-x. 2 unit unit  6 Feb  6 03:42 log
```

New container, incorrect permissions:
```
lkp-back-php-dv-6fcff49c8f-97lxd:/app# ls -la /app/var
total 0
drwxrwxrwx. 4 root root 30 Feb  8 17:05 .
drwxr-xr-x. 1 unit unit 42 Feb  8 17:07 ..
drwxr-xr-x. 3 root root 18 Feb  8 17:06 cache
drwxr-xr-x. 2 root root  6 Feb  8 17:05 log
```

**Comment by tippexs** [comment]
Hi @anutator I will have a look into this today and let you know.

**Comment by anutator** [comment]
I found the reason of problem. In Kubernetes I must start init containers with securityContext:

```
securityContext:
  runAsUser: 101
  runAsUser: 101
```

And the main container must start from root without securityContext. So cache and logs directories are created in init container with right permissions (unit).

**Comment by anutator** [comment]
Please close the 

> Hi @anutator I will have a look into this today and let you know.

Thank you. I've found the reason.
