### ISSUE TITLE
Override control socket permissions

### ISSUE THREAD

**Issue by michaelkosir** [nginx/unit#840]
Hello,

The control API socket is created as `root` with `600` permissions. I am looking to change the permissions to allow a non-privileged process access. I was able to find a past issue that mentions plans to set permissions from the command-line. Is this feature still on the roadmap?

Hoping to find something similar to: `unitd --control unix:/path/to/control.unit.sock --control-mode 660`

I am currently using `ExecStartPost` to do the `chown`/`chmod` as an alternative.

>Because of security reasons the control API socket is created by the main process with strict permissions and privileged user. In order to allow access the socket from non-privileged nginx worker processes you have to change socket permissions with chown/chmod commands. Other option can be opening control socket on an IP address (127.0.0.1 for example), but please take into account the security considerations.
>
>There are also plans to introduce an unitd option to specify control socket permissions from command-line.
>
> _Originally posted by @VBart in https://github.com/nginx/unit/issues/254#issuecomment-495328019_

Thanks!

**Comment by tippexs** [comment]
Hi @michaelkosir thanks for bringing this back up to our attention. This will be a helpful enhancement but currently we are working on `1.30` which is already closed (feature wise) and the next release `1.31` is dedicated to WASM. So it will not find its way into Unit within the next two releases.

**Comment by ac000** [comment]
I will likely add three new options

```
--control-mode
--control-user
--control-group
```

**Comment by ac000** [comment]
Initial [implementation](https://github.com/ac000/unit/tree/uds-ctrl-sock-perms)

Use like

```shell
... --control-mode 644 --control-user unit --control-group unit
```

You can use any combination of the above.

**Comment by lcrilly** [comment]
For clarity, PR is https://github.com/nginx/unit/pull/1000

**Comment by crabique** [comment]
One thing to keep in mind is that this change would break (even further?) the abstract control socket.

On a 1.31.1 trace for  `--control unix:@aaa`, the main process seems to successfully bind the abstract domain socket:
```
socket(AF_UNIX, SOCK_STREAM|SOCK_NONBLOCK, 0) = 6
setsockopt(6, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(6, {sa_family=AF_UNIX, sun_path=@"aaa"}, 6) = 0
```

It even converted the `@` to an `\0`, but then it does something weird:
```
chmod("", 0600)                         = -1 ENOENT (No such file or directory)
...
write(2, "...chmod(\"\") failed (2: No such file or directory) while creating listening socket on unix:@aaa\n",...) = 133
unlink("")                              = -1 ENOENT (No such file or directory)
```

Those are probably multiple unrelated regressions introduced at separate times, but at least both the permission change and `listen_fail` exit path assume the socket is always file-backed.

The code in #1000 seems to be heading in the same direction, so this could be a good time to make the design decision whether the abstract control socket should be supported or not. Given that the control socket can be bound to `AF_INET` 🙂
