### ISSUE TITLE
perl crash after second call to responder from psgi "callback-style response"

### ISSUE THREAD

**Issue by bes-internal** [nginx/unit#841]
## Reproduce

app.psgi
```
#!/usr/bin/perl
use utf8; use open qw(:utf8 :std);
use v5.26;

my $counter=2;

my $app = sub {
 my $env = shift;

 return sub {
  my $responder = shift;
  $responder->( [200, ['Content-Type'=>'text/plain'], [$counter++]] );
  $responder->( [200, ['Content-Type'=>'text/plain'], [$counter++]] );  # <-- this call lead to crash with signal 11
 };

};
```

unit/config
```
 {
		"access_log": "/var/log/unit-access.log",
		"applications": {
			"bug": {
				"processes": 1,
				"script": "app.psgi",
				"type": "perl"
			}

		},

		"listeners": {
			"127.0.0.1:12009": {
				"pass": "applications/bug"
			}
		},

		"settings": {}
}
```
```
$ curl "http://127.0.0.1:12009"
```
Counter does not increase. Unitd restating process after crash with signal 11 (SIGSEGV)

```[1322138.074344] unitd[26295]: segfault at 78 ip 00007f580bd646bd sp 00007fff1eebb030 error 4 in perl.unit.so[7f580bd5f000+e000]```

Debug log - [unit-perl-bug.debug.txt](https://github.com/nginx/unit/files/10842754/unit-perl-bug.debug.txt)

**Comment by ac000** [comment]
Thanks for the bug report with reproducer and config, very helpful!

Can I just check what the expected behaviour and curl output should be?

**Comment by bes-internal** [comment]
> expected behaviour

There doesn't seem to be a definitive answer in the spec at https://github.com/plack/psgi-specs/blob/master/PSGI.pod#delayed-response-and-streaming-body 
But following the formal logic and behavior of other PSGI server implementations, after the server has received a PSGI response, it should ignore all other application responses, but not terminate the application process forced in some form.
As far as I understand the problem, perl is trying to write to a closed fd, but unitd has already disconnected from this process.

> what curl output should be?

This application should print an incrementing counter after each curl request, but now it always shows the same thing because the application crashes and is restarted by unitd itself

**Comment by ac000** [comment]
> > expected behaviour
> 
> There doesn't seem to be a definitive answer in the spec at https://github.com/plack/psgi-specs/blob/master/PSGI.pod#delayed-response-and-streaming-body But following the formal logic and behavior of other PSGI server implementations, after the server has received a PSGI response, it should ignore all other application responses, but not 

Yeah, that makes sense.

> terminate the application process forced in some form. As far as I understand the problem, perl is trying to write to a closed fd, but unitd has already disconnected from this process.

I'll take a look at it.
 
> > what curl output should be?
> 
> This application should print an incrementing counter after each curl request, but now it always shows the same thing because the application crashes and is restarted by unitd itself

Thanks.

**Comment by ac000** [comment]
@bes-internal

With this patch

```diff
diff --git a/src/perl/nxt_perl_psgi.c b/src/perl/nxt_perl_psgi.c
index 5e8d1aee..807d1741 100644
--- a/src/perl/nxt_perl_psgi.c
+++ b/src/perl/nxt_perl_psgi.c
@@ -267,8 +267,11 @@ XS(XS_NGINX__Unit__Sandbox_cb)
         XSRETURN_EMPTY;
     }
 
+    pctx = CvXSUBANY(cv).any_ptr;
+
     if (nxt_slow_path(SvOK(ST(0)) == 0 || SvROK(ST(0)) == 0
-                      || SvTYPE(SvRV(ST(0))) != SVt_PVAV))
+                      || SvTYPE(SvRV(ST(0))) != SVt_PVAV
+                      || pctx->req == NULL))
     {
         nxt_perl_psgi_cb_request_done(CvXSUBANY(cv).any_ptr, NXT_UNIT_ERROR);
 
@@ -278,8 +281,6 @@ XS(XS_NGINX__Unit__Sandbox_cb)
         XSRETURN_EMPTY;
     }
 
-    pctx = CvXSUBANY(cv).any_ptr;
-
     rc = nxt_perl_psgi_result_array(PERL_GET_CONTEXT, ST(0), pctx->req);
     if (nxt_slow_path(rc != NXT_UNIT_OK)) {
         nxt_perl_psgi_cb_request_done(CvXSUBANY(cv).any_ptr, NXT_UNIT_ERROR);
```

the application process no longer crashes.

We get

```
2023/02/28 15:28:27 [error] 51769#51769 [unit] PSGI: Failed to execute result callback: 
PSGI: An unexpected response was received from Perl Application at /home/andrew/src/perl/841.pl line 12.
```

in the main unit log.

When hitting the app with curl the counter goes up by 2...

Does all that look about right to you?

**Comment by bes-internal** [comment]
I just tested. It's all great. Thank you!
