### ISSUE TITLE
Separating application logs

### ISSUE THREAD

**Issue by dgreco3917** [nginx/unit#846]
Question regarding logging in Unit. I have setup multiple PHP applications, routed via the hostname. Currently, an "error_log()" calls from PHP end up in the main unit log file in /var/log/unit.log. I would like to be able to at least separate these logs out form the unit log file, but preferably configure an error log for each application.

Currently the unit.log looks like this:

2023/03/01 20:30:52 [notice] 978431#978431 [unit] #200: php message: PHP Warning:  mysqli_connect(): (HY000/1049): Unknown database 'fraudplatform2' in /var/git/dev/main/fraudanalyzer/webapp/libs/Session.php on line 83
2023/03/01 20:30:52 [notice] 978431#978431 [unit] #200: php message: PHP Fatal error:  Uncaught TypeError: mysqli_error(): Argument #1 ($mysql) must be of type mysqli, bool given i........

Is this possible? I will also be eventually moving a Perl application over to Unit as well, would like the same behavior for STDERR output if possible.

**Comment by ac000** [comment]
This is currently being worked on.

**Comment by ac000** [comment]
This is the same as https://github.com/nginx/unit/issues/197 closing as a duplicate.
