### ISSUE TITLE
error: no Python found.

### ISSUE THREAD

**Issue by djdejawu** [nginx/unit#851]
Hi!

Want to configure unit with python 3.9, but I get an error.

```
~ # ./configure python --config=python3.9-config
configuring Python module
checking for Python ... not found

./configure: error: no Python found.

~ # which python3.9-config
/usr/local/bin/python3.9-config
```

Any ideas?

**Comment by ac000** [comment]
Does it work if you specify the full path in the `--config=` ?

**Comment by ac000** [comment]
What does `/usr/local/bin/python3.9-config --prefix` show?

**Comment by ac000** [comment]
Lets check your Python install. Stick the following in a file, say py.c

```c
#include <Python.h>

int main(void)
{
        Py_Initialize();
        return 0;
}
```

Then try building it with

```shell
$ cc $(/usr/local/bin/python3.9-config --cflags --ldflags) -Wl,-rpath,/usr/local/lib -o py py.c
```

That should leave you with an executable 'py' you can run, it should run without any errors and just return to the shell prompt.

**Comment by djdejawu** [comment]
I recompiled and reinstalled Python 3.9 prefixed with /usr. Now this code gets to the Py_Initialize() function call.
```
# cc $(/usr/bin/python3.9-config --cflags --ldflags) -Wl,-rpath,/usr/lib -o py py.c
/usr/bin/ld: /tmp/ccOGoVQq.o: in function `main':
/home/vagrant/Python-3.9.16/py.c:5: undefined reference to `Py_Initialize'
collect2: error: ld returned 1 exit status
```

**Comment by ac000** [comment]
Did you build Python with the `--enable-shared` configure option?

**Comment by djdejawu** [comment]
> Did you build Python with the `--enable-shared` configure option?

Got it! When rebuild Python with this option it's works. Thank you!
```
# ./unitd --version
unit version: 1.29.1
configured as ./configure --prefix=/usr --log=/var/log/unit.log --pid=/run/unit.pid --user=unit --group=unit --openssl
```
