### ISSUE TITLE
Server listen port range - regression in Docker image 1.23.3

### ISSUE THREAD

**Issue by mariuszjedrzejewski** [nginx/unit#853]
Can anyone confirm that "listen" on port range directive in 1.23.3 tag doesn't work anymore?
I'm using server listening on 100 consecutive ports, config is something like this;

server {
  listen 20001-20100 ssl http2;
  server_name xxxxx.xx;
  proxy_pass http://docker-container:$server_port;
}

It breaks when nginx is running on 1.23.3 tagged official Docker image. Nginx is listening only on first port - 20001 (confirmed with netstat -ant). I had to downgrade container to nginx:1.22-alpine and now it works well again.

Whats wrong with 1.23.3 version then?

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for NGINX Unit but your question seems related to `listen` in NGINX. Please direct this issue to the channels listed at https://nginx.org/en/support.html or to the [nginxcommunity Slack](https://community.nginx.org/joinslack).

FWIW, the [NGINX changelog](http://nginx.org/en/CHANGES) does mention a change, and there is a [fix](https://hg.nginx.org/nginx/rev/2af1287d2da7) that will be in the next release (tomorrow).
