### ISSUE TITLE
Python ASGI - RuntimeError: The server does not support "state" in the lifespan scope. 

### ISSUE THREAD

**Issue by cgearing** [nginx/unit#864]
Hi there,

I've been using nginx-unit for a FastAPI application, and everything has been working fine up until I attempted to use the [Lifespan State](https://asgi.readthedocs.io/en/latest/specs/lifespan.html#lifespan-state) part of the ASGI spec to store a reference to an object that I would like to maintain a reference to through the application lifecycle (it talks to the Google API to get authentication tokens which can seemingly take a long time sometimes).

It looks like currently nginx-unit doesn't support the state part of the lifespan functionality.

Was this purposefully left out or would you be open to PRs implementing this functionality?

**Comment by ac000** [comment]
Hi Chris,

> Was this purposefully left out 

Not as far as I know, but lets check with some others.

Cc: @alejandro-colomar 
Cc: @hongzhidao

**Comment by hawiliali** [comment]
I tested the pull request on a starltte app with a state holding multiple objects between db and http async clients
it's working

**Comment by ac000** [comment]
The fix for this has been merged.
