### ISSUE TITLE
nodejs: Allow wrapped ServerResponse to write Uint8Array chunk

### ISSUE THREAD

**Issue by DamianVu** [nginx/unit#870]
Unit Version: 1.29.1
Nodejs Version: 18.16.0

Node `ServerResponse.write(chunk[, encoding][, callback])` should accept accept `Uint8Array` as the chunk argument according to the docs 
* https://nodejs.org/docs/latest-v18.x/api/http.html#responsewritechunk-encoding-callback 
* https://nodejs.org/api/buffer.html#buffer:~:text=Node.js%20APIs%20accept%20plain%20Uint8Arrays%20wherever%20Buffers%20are%20supported%20as%20well.

`http_server.js` line 246 https://github.com/nginx/unit/blob/7417987923114a30713f7df3905365f297df0daa/src/nodejs/unit-http/http_server.js#LL246C26-L246C26 checks for `chunk instanceof Buffer` which fails if passed a `Uint8Array`

I found this attempting to get a SvelteKit application using `npm create svelte@latest` and using the `adapter-node` to build a nodejs server https://kit.svelte.dev/docs/adapter-node

**Comment by tippexs** [comment]
@DamianVu thanks for reporting this to us. From what the docs are saying it would be fine accepting `Uint8Array` as well as is parent `Buffer` object OR a `string`? From the NGINX Community Slack you mentioned you already patched this for yourself. Are you able to confirm that adding `Uint8Array` as an accepted type of `ServerReponse` `chunk` fixed this issue for you?

**Comment by DamianVu** [comment]
@tippexs Yes, I was able to manually patch to `chunk instanceof Uint8Array` and this fixes the issue.

**Comment by tippexs** [comment]
Thats what I was thinking as well. I will do some testing but looks like this issue can be fixed quite easy.

**Comment by andrey-zelenkov** [comment]
Hi @DamianVu!

Thank you for your report. Could you please check that fix work for you?

```# HG changeset patch
# User Andrei Zeliankou <zelenkov@nginx.com>
# Date 1695205037 -3600
#      Wed Sep 20 11:17:17 2023 +0100
# Node ID 77ad1e350ae3c54882a7f626c0f9f102c6d9aadd
# Parent  6380c3e7e6a5a4258902dee0dd0bb6f147d33d5d
Node.js: response body chunk can now be a Uint8Array.


diff --git a/src/nodejs/unit-http/http_server.js b/src/nodejs/unit-http/http_server.js
--- a/src/nodejs/unit-http/http_server.js
+++ b/src/nodejs/unit-http/http_server.js
@@ -243,8 +243,11 @@ ServerResponse.prototype._writeBody = fu
     }
 
     if (chunk) {
-        if (typeof chunk !== 'string' && !(chunk instanceof Buffer)) {
-            throw new TypeError('First argument must be a string or Buffer');
+        if (typeof chunk !== 'string' && !(chunk instanceof Buffer ||
+                chunk instanceof Uint8Array)) {
+            throw new TypeError(
+                'First argument must be a string, Buffer, ' +
+                'or Uint8Array');
         }
 
         if (typeof chunk === 'string') {
diff --git a/test/node/write_array/app.js b/test/node/write_array/app.js
new file mode 100644
--- /dev/null
+++ b/test/node/write_array/app.js
@@ -0,0 +1,4 @@
+require('http').createServer(function (req, res) {
+    res.writeHead(200, {'Content-Length': 5, 'Content-Type': 'text/plain'})
+        .end(new Uint8Array(Buffer.from('array', 'utf8')));
+}).listen(7080);
diff --git a/test/node/write_buffer/app.js b/test/node/write_buffer/app.js
--- a/test/node/write_buffer/app.js
+++ b/test/node/write_buffer/app.js
@@ -1,5 +1,5 @@
 
 require('http').createServer(function (req, res) {
     res.writeHead(200, {'Content-Type': 'text/plain'})
-       .end(new Buffer([0x62, 0x75, 0x66, 0x66, 0x65, 0x72]));
+       .end(Buffer.from('buffer', 'utf8'));
 }).listen(7080);
diff --git a/test/test_node_application.py b/test/test_node_application.py
--- a/test/test_node_application.py
+++ b/test/test_node_application.py
@@ -149,6 +149,10 @@ def test_node_application_write_buffer()
 
     assert client.get()['body'] == 'buffer', 'write buffer'
 
+def test_node_application_write_array():
+    client.load('write_array')
+
+    assert client.get()['body'] == 'array', 'write array'
 
 def test_node_application_write_callback(temp_dir):
     client.load('write_callback')
```

> Edit: Probably worth clarifying that Buffer inherits directly from Uint8Array so this change would support Buffer objects as well

I decided to leave both `Buffer` and `Uint8Array` checks just in case if the order of inheritance changes in the future.

**Comment by DamianVu** [comment]
Hey @andrey-zelenkov ! Sorry for getting to this so late. That change looks great. I saw it made the 1.31.1 release a couple of weeks ago and works for me. Thanks!
