### ISSUE TITLE
nodejs: Implement ServerResponse.destroy()

### ISSUE THREAD

**Issue by DamianVu** [nginx/unit#871]
The Node `ServerResponse` object inherits from [outgoingMessage](https://nodejs.org/docs/latest-v18.x/api/http.html#class-httpoutgoingmessage). This class implements a `.destroy()` function meant to abort the response and close the socket. 

I found that this was unimplemented in the unit-http `ServerResponse` when attempting to get SvelteKit working. The node adapter for SvelteKit will call `destroy` when attempting to cancel the response if the backend encounters an error: [see here](https://github.com/sveltejs/kit/blob/e445f2e3a43fe4be5cb2fb6c417ba719a82c90bf/packages/kit/src/exports/node/index.js#L90)

Unit will report the error as `destroy` is not a function, which will hide the original error that happened. Manual debugging to find the original error is what led to #870. 

To re-create this, create the starter sveltekit app `npm create svelte@latest` (default demo app) and [switch to the node adapter](https://kit.svelte.dev/docs/adapter-node). Build and run the server through unit with the `unit-http` loader. Attempt to navigate to the "Sverdle" page (hovering also causes an SSR preload, which bombs) and the unit logs will show the `destroy` issue.

**Comment by tippexs** [comment]
Thanks @DamianVu for this one. The nodejs `ServerResponse` is defined here https://nodejs.org/api/http.html#class-httpserverresponse . I was able to see that `ServerResponse` extends `http.OutgoingMessage`. 

I will need to do some debugging on this but in our case the SvelteKit `req` will be an instance of Units `ServerResponse`?  Do you have a demo applications or a stack trace? That would be helpful.

**Comment by DamianVu** [comment]
I can put together a full demo in the next day or two.

This is the stack trace in logs I have handy
```
unit-http: Unimplemented ServerResponse property accessed: destroy
file:///usr/share/unit/applications/radar.20230505.00/src/build/handler.js:1089
		if (error) res.destroy(error);
		               ^

TypeError: res.destroy is not a function
    at cancel (file:///usr/share/unit/applications/radar.20230505.00/src/build/handler.js:1089:18)
    at next (file:///usr/share/unit/applications/radar.20230505.00/src/build/handler.js:1110:4)
```

Where the first line is a debug message I setup in `unit-http` in `http_server.js` by shimming in a proxy to see what calls are missing. Below is the shim I have been using, I put it right before the module exports.
```js
const createProxyHandler = objectName => ({
    get: (target, prop, receiver) => {
        if (!(prop in target)) {
            console.warn(`unit-http: Unimplemented ${objectName} property accessed: ${prop}`);
        }
        return target[prop];
    }
});

ServerResponse.prototype = new Proxy(ServerResponse.prototype, createProxyHandler("ServerResponse"));
ServerRequest.prototype = new Proxy(ServerRequest.prototype, createProxyHandler("ServerRequest"));
Server.prototype = new Proxy(Server.prototype, createProxyHandler("Server"));
```
So since the message immediately preceding the error was related to `ServerResponse`, this was how I found this issue

**Comment by tippexs** [comment]
This is helpful thank you. I will give this a try and let you know but looks legit to me.

**Comment by andrey-zelenkov** [comment]
Hi @DamianVu!

Thank you for report. Could you please try following patch:

```# HG changeset patch
# User Andrei Zeliankou <zelenkov@nginx.com>
# Date 1695204939 -3600
#      Wed Sep 20 11:15:39 2023 +0100
# Node ID 80546e3661917a56695e9c8b1cf4c0ac3d3abebf
# Parent  7dbb6c9be0b46d41d8eb708d2649fd8f3e04d2a0
Node.js: ServerRequest.destroy() implemented.


diff --git a/src/nodejs/unit-http/http_server.js b/src/nodejs/unit-http/http_server.js
--- a/src/nodejs/unit-http/http_server.js
+++ b/src/nodejs/unit-http/http_server.js
@@ -33,8 +33,17 @@ ServerResponse.prototype.statusMessage =
 ServerResponse.prototype.headers_len = 0;
 ServerResponse.prototype.headers_count = 0;
 ServerResponse.prototype.headersSent = false;
+ServerResponse.prototype.destroyed = false;
 ServerResponse.prototype.finished = false;
 
+ServerResponse.prototype.destroy = function destroy(error) {
+    if (!this.destroyed) {
+        this.destroyed = true;
+    }
+
+    return this;
+};
+
 ServerResponse.prototype._finish = function _finish() {
     this.headers = {};
     this.headers_len = 0;
```

**Comment by DamianVu** [comment]
Hey @andrey-zelenkov , thanks for doing this! Sorry for getting to this so late, but I saw it already made the 1.31.1 release a couple of weeks ago, but I'll test it and report back for good measure.
