### ISSUE TITLE
unitc error since upgrade to 1.30.0

### ISSUE THREAD

**Issue by mattxtaz** [nginx/unit#875]
Since upgrading to 1.30.0 unitc now gives an error. It doesn't appear to be unitc at fault as I've tested earlier commits of that and the error persists so I assume something changed with unit itself?

This is on FreeBSD 13.2 with bash 5.2.15 and curl 8.0.1.

% unitc /status
/usr/local/bin/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status

**Comment by ac000** [comment]
Hmm, it looks like it's trying to access a host called status...

Could you stick ```set -x``` in the unitc script, just before the while statement near the top of the file will do and run it again and post the output?

**Comment by mattxtaz** [comment]
ERROR_LOG=/dev/null                                                       
+ REMOTE=0
+ SHOW_LOG=1
+ NOLOG=0
+ QUIET=0
+ URI=
+ SSH_CMD=
+ METHOD=PUT
+ CONF_FILES=()
+ '[' 1 -gt 0 ']'
++ echo /status
++ tr '[a-z]' '[A-Z]'
+ OPTION=/STATUS
+ case $OPTION in
+ '[' -f /status ']'
+ '[' / = / ']'
+ '[' '' = '' ']'
+ URI=/status
+ shift
+ '[' 0 -gt 0 ']'
+ '[' /status = '' ']'
+ '[' '' = '' ']'
+ '[' /sta = http ']'
+ '[' 0 -eq 0 ']'
+ PID=($(ps ax | grep unit:\ main | grep -v \ grep | awk '{print $1}'))
++ ps ax
++ grep 'unit: main'
++ grep -v ' grep'
++ awk '{print $1}'
+ '[' 1 -eq 0 ']'
+ '[' 1 -gt 1 ']'
+ '[' -r /tmp/unitc.66647.env ']'
++ hash curl tr cut sed tail sleep
++ cut -f4 -d:
++ tr -d '\n'
+ MISSING=
+ '[' '' '!=' '' ']'
++ ps 66647
++ grep unitd
++ cut -f2- -dv
++ sed -e 's/ --/\n--/g'
++ tr '[]' ' '
++ cut -f3- -d ' '
+ PARAMS='/usr/local/sbin/unitd  (unitd)'
++ echo '/usr/local/sbin/unitd  (unitd)'
++ grep '\--control'
++ cut -f2 '-d '
+ CTRL_ADDR=
+ '[' '' = '' ']'
++ grep -A1 '\--control'
++ tail -1
+++ echo '/usr/local/sbin/unitd  (unitd)'
++ cut -f2 '-d"'
+++ grep unitd
++ /usr/local/sbin/unitd '(unitd)' --help
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
+ CTRL_ADDR=
++ grep -c '^unix:'
++ echo
+ '[' 0 -eq 1 ']'
+ UNIT_CTRL=http://
++ echo '/usr/local/sbin/unitd  (unitd)'
++ grep '\--log'
++ cut -f2 '-d '
+ ERROR_LOG=
+ '[' '' = '' ']'
++ grep -A1 '\--log'
++ tail -1
+++ echo '/usr/local/sbin/unitd  (unitd)'
++ cut -f2 '-d"'
+++ grep unitd
++ /usr/local/sbin/unitd '(unitd)' --help
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
+ ERROR_LOG=
+ rm -f /tmp/unitc.58793.env
+ echo 'UNIT_CTRL="http://"'
+ echo ERROR_LOG=
+ '[' 0 -eq 1 ']'
+ hash jq
+ OUTPUT=jq
+ '[' -f ']'
+ '[' -r ']'
++ wc -l
/usr/local/bin/unitc: line 185: $ERROR_LOG: ambiguous redirect
+ LOG_LEN=
+ '[' -t 0 ']'
+ '[' 0 -eq 0 ']'
+ '[' PUT = DELETE ']'
++ echo /status
++ grep -c '^/control/'
+ SHOW_LOG=0
+ curl http:///status
+ jq
+ CURL_STATUS=6
+ '[' 6 -ne 0 ']'
+ echo 'unitc: ERROR: curl(1) exited with an error (6)'
unitc: ERROR: curl(1) exited with an error (6)
+ '[' 6 -eq 7 ']'
+ echo 'unitc: Trying to access http:///status'
unitc: Trying to access http:///status 
+ cat /tmp/unitc.68966
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status
+ rm -f /tmp/unitc.68966
+ exit 4

**Comment by ac000** [comment]
Heh. Thanks!

Yeah, something has gone very wrong there!

Just tried it with FreeBSD 13.1 (bash 5.2.15(0)-release, curl 8.0.1). Using unit tagged as 1.30.0 from git.

```shell
$ /usr/local/bin/bash tools/unitc /status
+ ERROR_LOG=/dev/null
+ REMOTE=0
+ SHOW_LOG=1
+ NOLOG=0
+ QUIET=0
+ URI=
+ SSH_CMD=
+ METHOD=PUT
+ CONF_FILES=()
+ '[' 1 -gt 0 ']'
++ echo /status
++ tr '[a-z]' '[A-Z]'
+ OPTION=/STATUS
+ case $OPTION in
+ '[' -f /status ']'
+ '[' / = / ']'
+ '[' '' = '' ']'
+ URI=/status
+ shift
+ '[' 0 -gt 0 ']'
+ '[' /status = '' ']'
+ '[' '' = '' ']'
+ '[' /sta = http ']'
+ '[' 0 -eq 0 ']'
+ PID=($(ps ax | grep unit:\ main | grep -v \ grep | awk '{print $1}'))
++ ps ax
++ grep 'unit: main'
++ awk '{print $1}'
++ grep -v ' grep'
+ '[' 1 -eq 0 ']'
+ '[' 1 -gt 1 ']'
+ '[' -r /tmp/unitc.2949.env ']'
+ source /tmp/unitc.2949.env
++ UNIT_CTRL='--unix-socket /tmp/unit/control.unit.sock _'
++ ERROR_LOG=/tmp/unit/unit.log
+ '[' 0 -eq 1 ']'
+ hash jq
+ OUTPUT=cat
+ '[' -f /tmp/unit/unit.log ']'
+ '[' -r /tmp/unit/unit.log ']'
++ wc -l
+ LOG_LEN='     460'
+ '[' -t 0 ']'
+ '[' 0 -eq 0 ']'
+ '[' PUT = DELETE ']'
++ echo /status
++ grep -c '^/control/'
+ SHOW_LOG=0
+ curl --unix-socket /tmp/unit/control.unit.sock _/status
+ cat
{
        "connections": {
                "accepted": 0,
                "active": 0,
                "idle": 0,
                "closed": 0
        },

        "requests": {
                "total": 0
        },

        "applications": {}
}
+ CURL_STATUS=0
+ '[' 0 -ne 0 ']'
+ rm -f /tmp/unitc.3015
+ '[' 0 -gt 0 ']'
```

Things seem to start going wrong for you around my lines

```shell
+ source /tmp/unitc.2949.env
++ UNIT_CTRL='--unix-socket /tmp/unit/control.unit.sock _'
```

which you don't have, then you start having stuff like

```shell
MISSING=
'[' '' '!=' '' ']'
++ ps 66647
++ grep unitd
++ cut -f2- -dv
++ sed -e 's/ --/\n--/g'
++ tr '[]' ' '
++ cut -f3- -d ' '
PARAMS='/usr/local/sbin/unitd (unitd)'
++ echo '/usr/local/sbin/unitd (unitd)'
++ grep '--control'
++ cut -f2 '-d '
```

that I don't.

Where is your unit from? I tried installing the FreeBSD package, but I only seem to get 1.29.1 that way...

Cc: @alejandro-colomar

**Comment by mattxtaz** [comment]
It's built from the FreeBSD port (/usr/ports/www/unit) on my own build server. The FreeBSD build servers are usually a few days behind so the package won't be updated straight away. The package maintainer did change a few things, not just a simple version upgrade so I don't know if any of those have affected it? [https://cgit.freebsd.org/ports/commit/?id=6684134299d5750fc4c390646a4410e13497e51d](url)

**Comment by ac000** [comment]
Hmm, what does ```unitd --version``` show?

It looks like it's going wrong here

```bash
                # Get control address                                           
                #                                                               
                PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
                CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ') 
                if [ "$CTRL_ADDR" = "" ]; then                                  
                        CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
                fi                                                              
                                                                                
                # Prepare for network or Unix socket addressing                 
                #                                                               
                if [ $(echo $CTRL_ADDR | grep -c ^unix:) -eq 1 ]; then          
                        SOCK_FILE=$(echo $CTRL_ADDR | cut -f2- -d:)             
                        if [ -r $SOCK_FILE ]; then                              
                                UNIT_CTRL="--unix-socket $SOCK_FILE _"          
                        else                                                    
                                echo "${0##*/}: ERROR: cannot read unitd control socket: $SOCK_FILE"
                                ls -l $SOCK_FILE                                
                                exit 2                                          
                        fi                                                      
                else                                                            
                        UNIT_CTRL="http://$CTRL_ADDR"                           
                fi
```

and ```UNIT_CTRL``` is ending up as ```http:///status```.

Then there's something wrong with your ERROR_LOG. Also this looks quite wrong

```shell
++ /usr/local/sbin/unitd '(unitd)' --help
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
```

**Comment by lcrilly** [comment]
That area of the script was modified recently. Perhaps try the unitc script from 1.29?

**Comment by mattxtaz** [comment]
I already tried going back to the older versions of unitc and that made no difference which is what makes me think that unit itself has changed in some way.

unit version: 1.30.0
configured as ./configure --prefix=/usr/local --ld-opt=-L/usr/local/lib --log=/var/log/unit/unit.log --logdir=/var/log/unit --modulesdir=/usr/local/libexec/unit/modules --pid=/var/run/unit/unit.pid --runstatedir=/var/run/unit --statedir=/var/db/unit --tmpdir=/var/tmp/unit --user=www --group=www --openssl --control=unix:/var/run/unit/control.unit.sock

unitd --help works as well showing the list of options etc.

OK. Though now I am really confused. I just downgraded both unit and unitc to 1.29.1 and I still get the same error?! So maybe it wasn't this upgrade that broke it after all. This was working a few weeks ago though. Now I wonder if it's actually the upgrade to FreeBSD 13.2 that has broken this in some way, because andrew tested it under FreeBSD 13.1.

**Comment by ac000** [comment]
Just upgraded my FreeBSD install to 13.2 and it still works...

```shell
$ uname -a
FreeBSD freebsd 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64
$ /usr/local/bin/bash tools/unitc /status
{
        "connections": {
                "accepted": 0,
                "active": 0,
                "idle": 0,
                "closed": 0
        },

        "requests": {
                "total": 0
        },

        "applications": {}
}
```

Perhaps you should verify if a fresh build from git works or not. It may be something particular to your system.

Ah, ha!.

I was testing it with running unitd as myself with --no-daemon. However, running unitd as root as a daemon produces the same thing you're seeing...

Trying it on Fedora 38 running as root

```shell
$ src/unit/tools/unitc /status
unitc: ERROR: cannot read unitd control socket: /opt/unit/control.unit.sock
srw------- 1 root root 0 May 14 04:45 /opt/unit/control.unit.sock
```

In theory this should also be the case on FreeBSD

```shell
$ ls -l /tmp/unit/control.unit.sock 
srw-------  1 root  wheel  0 May 14 03:34 /tmp/unit/control.unit.sock
```

While running the unitc script as root on Fedora makes it work, doing so on FreeBSD still fails...

**Comment by ac000** [comment]
At least part of the problem is this

```shell
# ps 1057 | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g'
/tmp/unit/sbin/unitd  (unitd)
```

We don't want that trailing '(unitd)' but it seems we do want any command line arguments, so it's not as simple as just ignoring everything after the exe.

**Comment by ac000** [comment]
Heh, found a pretty wacky thing

On Linux, in a 80 column terminal

```shell
$ ps 505506 | grep unitd
505506 ?        Ss     0:00 unit: main v1.30.0 [/opt/unit/sbin/unitd --tmpdir /tmp]
$ ps 505506 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
/opt/unit/sbin/unitd
--tmpdir /tmp
```

On FreeBSD, in a 80 column terminal

```shell
$ ps 6861 | grep unitd
6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --tmpdir
$ ps 6861 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd
--tmpdir
```

On FreeBSD, in a 112 column terminal

```shell
$ ps 6861 | grep unitd
6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --tmpdir /tmp] (unitd)
$ ps 6861 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
/tmp/unit/sbin/unitd
--tmpdir /tm
```

This patch seems to fix things

```diff
diff --git a/tools/unitc b/tools/unitc
index 9973e62d..d6871eb9 100755
--- a/tools/unitc
+++ b/tools/unitc
@@ -13,10 +13,13 @@ QUIET=0
 URI=""
 SSH_CMD=""
 METHOD=PUT
 CONF_FILES=()
 
+# FreeBSD will truncate the ps output to the default $COLUMN value of 80.
+export COLUMNS=160
+
 while [ $# -gt 0 ]; do
        OPTION=$(echo $1 | tr '[a-z]' '[A-Z]')
        case $OPTION in
                "-H" | "--HELP")
                        shift
@@ -129,11 +132,11 @@ if [ $REMOTE -eq 0 ]; then
                        exit 1
                fi
 
                # Get control address
                #
-               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
+               PARAMS=$(ps $PID | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g')
                CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
                if [ "$CTRL_ADDR" = "" ]; then
                        CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
                fi
 

```
(You may have to apply that patch manually...)

```shell
# /usr/local/bin/bash /home/andrew/src/unit/tools/unitc /status
{
        "connections": {
                "accepted": 0,
                "active": 0,
                "idle": 0,
                "closed": 0
        },

        "requests": {
                "total": 0
        },

        "applications": {}
}
```

Tested on both Linux/FreeBSD, with unitd running as root and non-root.

**Comment by alejandro-colomar** [comment]
Hi Andrew!


On Tue, May 16, 2023, 15:13 Andrew Clayton ***@***.***> wrote:

> Heh, found a pretty wacky thing
>
> On Linux, in a 80 column terminal
>
> $ ps 505506 | grep unitd
> 505506 ?        Ss     0:00 unit: main v1.30.0 [/opt/unit/sbin/unitd --tmpdir /tmp]
> $ ps 505506 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
> /opt/unit/sbin/unitd
> --tmpdir /tmp
>
> On FreeBSD, in a 80 column terminal
>
> $ ps 6861 | grep unitd
> 6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --tmpdir
> $ ps 6861 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
> 6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd
> --tmpdir
>
> On FreeBSD, in a 112 column terminal
>
> $ ps 6861 | grep unitd
> 6861  -  Is   0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --tmpdir /tmp] (unitd)
> $ ps 6861 | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g'
> /tmp/unit/sbin/unitd
> --tmpdir /tm
>
>
Hmm, ps(1) has -ww for unlimited width output.  This seems to be portable
at least to procps-ng (Linux), FreeBSD ps(1), and macos.  It's not in
POSIX, but I guess it's enough for us.

<https://www.man7.org/linux/man-pages/man1/ps.1.html>

<
https://man.freebsd.org/cgi/man.cgi?query=ps&apropos=0&sektion=0&manpath=FreeBSD+13.2-RELEASE+and+Ports&arch=default&format=html
>

<https://ss64.com/osx/ps.html>

<https://www.man7.org/linux/man-pages/man1/ps.1p.html>


> This patch seems to fix things
>
> diff --git a/tools/unitc b/tools/unitc
> index 9973e62d..d6871eb9 100755--- a/tools/unitc+++ b/tools/unitc@@ -13,10 +13,13 @@ QUIET=0
>  URI=""
>  SSH_CMD=""
>  METHOD=PUT
>  CONF_FILES=()
>  +# FreeBSD will truncate the ps output to the default $COLUMN value of 80.+export COLUMNS=160
>
>
I guess we can just use -ww.

+
>  while [ $# -gt 0 ]; do
>         OPTION=$(echo $1 | tr '[a-z]' '[A-Z]')
>         case $OPTION in
>                 "-H" | "--HELP")
>                         shift@@ -129,11 +132,11 @@ if [ $REMOTE -eq 0 ]; then
>                         exit 1
>                 fi
>
>                 # Get control address
>                 #-               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')+               PARAMS=$(ps $PID | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g')
>                 CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
>
>
Why is this change necessary?  I understand the new version, but the old
one was a bit less clear to me.  Anyway, I prefer your version for
readability reasons, I think.

Cheers,
Alex

**Comment by ac000** [comment]
> Consider ps -w for unlimited width (and seems to be widely implemented)

> Hmm, ps(1) has -ww for unlimited width output. 

Of course that needs to be just ```w``` or ```ww``` without the dash as ```-w``` and ```w``` do different things on procps-ng ps

**Comment by mattxtaz** [comment]
I’ve just tested the above patch on my FreeBSD and that solves the problem. So yes it was ps truncating the output. As for how it’s actually solved to be portable I’ll let you argue it out but thank you for investigating and tracking this down!

**Comment by ac000** [comment]
> Really?  Weird.  The man page seems to say they are the same:

OK, they do the same thing **if** you pass a PID to it.

**Comment by ac000** [comment]
Updated patch

```diff
diff --git a/tools/unitc b/tools/unitc
index 9973e62d..3119a3e3 100755
--- a/tools/unitc
+++ b/tools/unitc
@@ -131,7 +131,7 @@ if [ $REMOTE -eq 0 ]; then
 
                # Get control address
                #
-               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
+               PARAMS=$(ps -ww $PID | grep unitd | sed -e 's/.*\[\(.*\)\].*/\1/' | sed -e 's/ --/\n--/g')
                CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
                if [ "$CTRL_ADDR" = "" ]; then
                        CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
```

> We should fix that shebang.  The portable shebang for bash(1) involves
> env(1), exactly for that reason.

> We should do as here:

> <https://github.com/nginx/unit/blob/master/tools/setup-unit#L1>

Hmm,  I remember when using ```/usr/bin/env``` fell out of favour with at least Fedora

- <https://pagure.io/packaging-committee/issue/700>
- <https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/WYBBLP2PVCVVJVKBDVXDQMJRQ4AT4P35/>
- <https://fedoraproject.org/wiki/Script_Interpreters_(draft)>

Though there seems to be two main issues

1) Packaging dependencies
2) Security concerns (env may end up running _not_ the interpreter you expect).

**Comment by alejandro-colomar** [comment]
On Wed, May 17, 2023, 00:48 Andrew Clayton ***@***.***> wrote:

We should fix that shebang. The portable shebang for bash(1) involves
> env(1), exactly for that reason.
>
> We should do as here:
>
> https://github.com/nginx/unit/blob/master/tools/setup-unit#L1
>
> Hmm, I remember when using /usr/bin/env fell out of favour with at least
> Fedora
>
>    - https://pagure.io/packaging-committee/issue/700
>    -
>    ***@***.***/thread/WYBBLP2PVCVVJVKBDVXDQMJRQ4AT4P35/
>    - https://fedoraproject.org/wiki/Script_Interpreters_(draft)
>
> Though there seems to be two main issues
>
>    1. Packaging dependencies
>    2. Security concerns (env may end up running *not* the interpreter you
>    expect).
>
>
Re: pkg deps:

That seems to be an RPM-specific issue.  They could fix it by adding some
more logic to the parsing of the shebang to detect what env will run (with
a pristine $PATH).

And I'd say it's even a wrong way of calculating deps, since a script can
run many commands that are as important as the interpreter, so only caring
about the shebang line seems incorrect.

Re: sec:

A bash script topically runs dozens, or even hundreds of commands, and it
is very rare to specify them in terms of /use/bin.  Any of those could run
your favourite replacement for a given program that is found in $PATH.
Similarly to the previous point: why should we only care about the
interpreter but not those?

I believe Fedora people to be wrong in this.  I should check what Debian
does, but I don't think there's such a policy.

**Comment by mattxtaz** [comment]
The FreeBSD port uses something called shebangfix to change it to /usr/local/bin/bash anyway. [Unitc port Makefile](https://cgit.freebsd.org/ports/tree/www/unitc/Makefile?id=6684134299d5750fc4c390646a4410e13497e51d#n20)

**Comment by alejandro-colomar** [comment]
Regarding the security concern about the shebang, here's some experiment:

```sh
alx@dell7760:~/tmp$ find
.
./malicious
./malicious/ps
./malicious/bash
./script_noenv
./script_env
```
```sh
alx@dell7760:~/tmp$ cat malicious/ps 
#!/bin/sh
echo "I'm malicious"
```
```sh
alx@dell7760:~/tmp$ cat malicious/bash 
#!/bin/sh
echo "I'm super-malicious"
```
```sh
alx@dell7760:~/tmp$ cat script_noenv 
#!/bin/bash
ps | tail
```
```sh
alx@dell7760:~/tmp$ cat script_env 
#!/usr/bin/env bash
ps | tail
```
```sh
alx@dell7760:~/tmp$ export PATH="/home/alx/tmp/malicious:$PATH";
alx@dell7760:~/tmp$ ./script_noenv 
I'm malicious
alx@dell7760:~/tmp$ ./script_env 
I'm super-malicious
alx@dell7760:~/tmp$ sudo ./script_noenv 
  PID TTY          TIME CMD
14209 pts/11   00:00:00 sudo
14210 pts/11   00:00:00 script_noenv
14211 pts/11   00:00:00 ps
14212 pts/11   00:00:00 tail
alx@dell7760:~/tmp$ sudo ./script_env 
  PID TTY          TIME CMD
14214 pts/11   00:00:00 sudo
14215 pts/11   00:00:00 bash
14216 pts/11   00:00:00 ps
14217 pts/11   00:00:00 tail
```

If a malicious actor has access to `$PATH`, scripts would need to specify the path to all commands within them, and not only the interpreter.  Being able to supplant the interpreter is as bad as being able to supplant any of the commands run by the interpreter, AFAICS, isn't it?  Did I miss anything?

**Comment by alejandro-colomar** [comment]
BTW, I can reproduce this bug in Devuan, even after fixing the ps(1) issue.  It may be that there are several issues behind this.

```diff
$ git diff master
diff --git a/tools/unitc b/tools/unitc
index 9973e62d..c53c4429 100755
--- a/tools/unitc
+++ b/tools/unitc
@@ -131,7 +131,7 @@ if [ $REMOTE -eq 0 ]; then
 
                # Get control address
                #
-               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
+               PARAMS=$(ps -ww -o args=COMMAND $PID | grep unitd | sed 's/.*\[//' | sed 's/\].*//' | sed -e 's/ --/\n--/g')
                CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
                if [ "$CTRL_ADDR" = "" ]; then
                        CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
```
```sh
$ ./tools/unitc GET /config
./tools/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///config
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: config
```
