### ISSUE TITLE
Packaging Custom Modules instructions no longer work since introduction of NJS

### ISSUE THREAD

**Issue by emolitor** [nginx/unit#879]
Following the instructions at https://unit.nginx.org/howto/modules/#packaging-custom-modules fails since the release of 1.30.0 which includes NJS support in the packed versions. When you run the configure step you will get the following error. 

checking for NJS ... not found

./configure: error: no NJS library found.

Reproduce using Ubuntu 22.04 LTS, install unit from https://packages.nginx.org/unit/ubuntu/ jammy unit and follow the instructions.

To fix suggest adding instructions to checkout njs source repo parallel to unit source, compiling and appending --cc-opt="-I../njs//src/ -I../njs/build/"  --ld-opt="-L../njs/build/" options to unit's configure step. This is still quite clunky though and I wonder if there is an easier way to add new modules to an existing install using unit-dev somehow?

**Comment by tippexs** [comment]
Hi @emolitor thanks for reaching out and you are right! This is indeed a blind spot in the documentation! Thanks for letting us know and we will take care of it.

**Comment by websitevirtuoso** [comment]
yes I also hav this problem when tried to configure module
