### ISSUE TITLE
400 Bad Request Potential Security Risk

### ISSUE THREAD

**Issue by Zyptix** [nginx/unit#880]
If a website url is example.com/& or example.com/%/ it will return a 400

**Comment by lcrilly** [comment]
Hello. Thanks for the issue.

Unit implements HTTP/1.1 against RFC 7230, which defines `&` as a reserved character [(appendix A)](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A) and `%` for percent-encoding. As such your examples are both invalid URIs so a 400 is the correct response.

Note that earlier HTTP RFCs permitted `&` as a valid character in path segments [(RFC 2396 3.3)](https://www.rfc-editor.org/rfc/rfc2396.html#section-3.3). As such, some older web servers permit a path of `/&`, including nginx.

If you believe there is an underlying security concern with Unit's implementation then please follow the guidance for reporting security issues at https://github.com/nginx/unit#community
