### ISSUE TITLE
Tools: unitc: empty $ERROR_LOG

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit#886]
```sh
$ sudo ./tools/unitc GET /config >/dev/null
./tools/unitc: line 183: $ERROR_LOG: ambiguous redirect
```

The following diff disables the error message, but it redirects from a file with an empty file name, so it is probably wrong to do that.  I just did it for checking that the error is caused exactly at that line.  Please revise the logic.

```diff
$ git diff HEAD^
diff --git a/tools/unitc b/tools/unitc
index c53c4429..fc16ebcd 100755
--- a/tools/unitc
+++ b/tools/unitc
@@ -180,7 +180,7 @@ fi
 # Get current length of error log before we make any changes
 #
 if [ -f $ERROR_LOG ] && [ -r $ERROR_LOG ]; then
-       LOG_LEN=$(wc -l < $ERROR_LOG)
+       LOG_LEN=$(wc -l < "$ERROR_LOG")
 else
        NOLOG=1
 fi
```

This is one of the issues that appear in the <https://github.com/nginx/unit/issues/875> issue.

**Comment by alejandro-colomar** [comment]
Here's a session without cache, and thus without issues:

```sh
alx@dell7760:~/src/nginx/unit$ sudo rm /tmp/unitc.*.env
alx@dell7760:~/src/nginx/unit$ sudo ./tools/unitc GET /config
{
	"listeners": {},
	"applications": {}
}
```

**Comment by alejandro-colomar** [comment]
@mattxtaz I suspect this might be the root cause of your problem.  Could you try removing any /tmp/unitc.* files and running again as root?  @ac000 what do you think?

**Comment by alejandro-colomar** [comment]
Another improvement that might workaround this issue would be to abort unitc as soon as an error is detected in a command, using `set -Eeuo pipefail`.  However, that might be problematic with some assumptions within the script, and it would need testing.

**Comment by mattxtaz** [comment]
> @mattxtaz I suspect this might be one of the problems you're experiencing. Could you try removing any /tmp/unitc.* files and running again as root? And then reproducing it again by removing again the tmp files and running as non-root? @ac000 what do you think?

You mean like this? This doesn't look like it makes any difference as I'm running it directly as root here. I've edited the prompts because otherwise github treats it as markup text and screws up the formatting.

root% ls -al /tmp/unitc*
-rw-r--r--  1 root  wheel  31 17 May 19:24 /tmp/unitc.10878.env
root% rm /tmp/unitc.10878.env
root% unitc /status
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
/usr/local/bin/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status

And then if I remove the files and run it as non-root, same thing again:

root% ls -al /tmp/unitc*
-rw-r--r--  1 root  wheel  31 17 May 19:25 /tmp/unitc.10878.env
root% rm /tmp/unitc.10878.env
user% unitc /status
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
unknown option "(unitd)", try "/usr/local/sbin/unitd -h" for available options
/usr/local/bin/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status
user% ls -al /tmp/unitc*
-rw-r--r--  1 user  wheel  31 17 May 19:31 /tmp/unitc.10878.env

**Comment by ac000** [comment]
On Wed, 17 May 2023 10:15:05 -0700
Alejandro Colomar ***@***.***> wrote:

> @mattxtaz I suspect this might be the root cause of your problem.  Could you try removing any /tmp/unitc.* files and running again as root?  @ac000 what do you think?

As me (no /tmp/unitc.PID.env...) kept forgetting about that thing!

$ ps 1115
 PID TT  STAT    TIME COMMAND
1115  0  S    0:00.00 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --no-daem

But then I guess it fails back to doing (not that I specified --control
anyway...)

if [ "$CTRL_ADDR" = "" ]; then                                  
                        CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
                fi

so it does work

$ /usr/local/bin/bash tools/unitc /status
{
        "connections": {
                "accepted": 0,
                "active": 0,
                "idle": 0,
                "closed": 0
        },

        "requests": {
                "total": 0
        },

        "applications": {}
}

As root (no /tmp/unitc.PID.env files...)

# ps 1197
 PID TT  STAT    TIME COMMAND
1197  -  Is   0:00.05 unitd: unit: main v1.30.0 [/tmp/unit/sbin/unitd --tmpdir

# /usr/local/bin/bash /home/andrew/src/unit/tools/unitc /status
{
        "connections": {
                "accepted": 0,
                "active": 0,
                "idle": 0,
                "closed": 0
        },

        "requests": {
                "total": 0
        },

        "applications": {}
}

So, bugger!

Now I'm going to forget this sorry mess ever happened! Now where's that
memory erasure thingamajig...

**Comment by ac000** [comment]
On Wed, 17 May 2023 11:03:38 -0700
Liam Crilly ***@***.***> wrote:

> -               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
> +               PARAMS=$(ps -wwo args=COMMAND $PID | grep ^unit | tr '[]()' ^ | cut -f2 -d^ | sed -e 's/ --/\n--/g')

This will fail on at least OpenIndiana. You can't use -ww, but can use
ww, and if you use -o ... you need to also do -p $PID but then the
process command is in a different format.

But this is probably all moot now anyway.

**Comment by alejandro-colomar** [comment]
> Here's my current solution. Tested with:
> 
>     * FreeBSD 12.3 (with both styles of process info (with and without […])
> 
>     * CentOS Stream 9
> 
>     * Debian 11
> 
>     * MacOS 13.2
> 
> 
> ```diff
> diff -r 28282eb943b9 tools/unitc
> --- a/tools/unitc       Wed May 10 21:15:17 2023 +0100
> +++ b/tools/unitc       Wed May 17 18:30:09 2023 +0100
> @@ -131,7 +131,7 @@
> 
>                 # Get control address
>                 #
> -               PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f3- -d ' ' | sed -e 's/ --/\n--/g')
> +               PARAMS=$(ps -wwo args=COMMAND $PID | grep ^unit | tr '[]()' ^ | cut -f2 -d^ | sed -e 's/ --/\n--/g')
>                 CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
>                 if [ "$CTRL_ADDR" = "" ]; then
>                         CTRL_ADDR=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
> @@ -158,6 +158,10 @@
>                 if [ "$ERROR_LOG" = "" ]; then
>                         ERROR_LOG=$($(echo "$PARAMS" | grep unitd) --help | grep -A1 '\--log' | tail -1 | cut -f2 -d\")
>                 fi
> +               if [ "$ERROR_LOG" = "" ]; then
> +                       echo "${0##*/}: WARNING: cannot determine the location of Unit's log file, which probably indicates a more serious problem, continuing anyway..."
> +                       ERROR_LOG=/dev/null
> +               fi
> 
>                 # Cache the discovery for this unit PID (and cleanup any old files)
>                 #
> ```

@lcrilly 
-  The two parts of the patch solve completely different issues (incorrect parsing vs incorrect caching), so please split that into two patches.
-  I'm not convinced by the parsing.  Could you reason about the rare cases where you got the command line without brackets?  I need to understand when that triggers to be able to tell if the code is correct.
-  I'm not convinced by `tr '[]()' ^ | cut -f2 -d^`.  Why do we need to translate the `()`?  I guess `tr '[]' ^ | cut -f2 -d^` would do the same, unless I'm missing some case.
-  `sed 's/.*\[//' | sed 's/\].*//'` is simpler (it doesn't need to translate characters, which tends to be brittle), and is more explicit in that it rejects anything outside the pair of brackets.
-  Please use -p before the PID, which is more explicit, and doesn't rely on what certain implementations of ps(1) decide to do.

Well, I'll implement this in my suggestion, unless you defend some of your proposals.

@ac000 
-  Regarding your concern about support for OpenIndiana, since the sed(1) call already doesn't work in OpenIndiana, and -o args=COMMAND considerably simplifies the parsing, I think we can say we don't support that system.  They should provide `-ww` if they support `ww`.

**Comment by ac000** [comment]
On Wed, 17 May 2023 11:03:38 -0700
Liam Crilly ***@***.***> wrote:


> +               PARAMS=$(ps -wwo args=COMMAND $PID | grep ^unit | tr '[]()' ^ | cut -f2 -d^ | sed -e 's/ --/\n--/g')

FWIW, this will also break on Alpine Linux

$ ps -ww -o args=COMMAND 
ps: unrecognized option: w
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

        -o COL1,COL2=HEADER     Select columns for display
        -T

Without the -ww you get

$ ps -o args=COMMAND | grep unitd
{unitd}
{unitd}
{unitd}

But that's perhaps a moot point anyway as it seems you don't get bash
(or curl) by default...

After installing them... (again, with current version of unitc)

$ tools/unitc /status
unknown option "andrew", try "/home/andrew/src/unit/build/sbin/unitd -h" for available options
unknown option "andrew", try "/home/andrew/src/unit/build/sbin/unitd -h" for available options
tools/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status

However its ps does behave like that from procps-ng in that when it's
being piped you get the full command

$ ps 4413 | grep unitd
 4413 andrew    0:00 {unitd} unit: main v1.30.0 [/home/andrew/src/unit/build/sbin/unitd --no-daemon --tmpdir /tmp]
 4415 andrew    0:00 {unitd} unit: controller
 4416 andrew    0:00 {unitd} unit: router
 4526 andrew    0:00 grep unitd

Except as you may have noticed it ignores the PID and just shows all
the processes.

I can also break it on FreeBSD if I run unitd like

946  0  I     0:00.01 unitd: unit: main v1.30.0 [./unitd --no-daemon --tmpdir /tmp] (unitd)

Only a relative path for the executable...

$ /usr/local/bin/bash tools/unitc /status
tools/unitc: line 137: ./unitd: No such file or directory
tools/unitc: line 159: ./unitd: No such file or directory
tools/unitc: line 183: $ERROR_LOG: ambiguous redirect
unitc: ERROR: curl(1) exited with an error (6)
unitc: Trying to access http:///status
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: status

I guess this would be true in the general case, I.e on any system. It
wants the --control option and if you don't specify it or the script
doesn't find it from ps it will try running the executable to get it
from --help but that requires it being able to find the binary.

Andrew

**Comment by ac000** [comment]
On Wed, 17 May 2023 15:55:11 -0700
Alejandro Colomar ***@***.***> wrote:

> @ac000 
> -  Regarding your concern about support for OpenIndiana, since the sed(1) call already doesn't work in OpenIndiana, and -o args=COMMAND considerably simplifies the parsing, I 

I don't think it does really. Look at your command vs the one I
proposed...

> think we can say we don't support that system.  They should provide
> `-ww` if they support `ww`.

So that would make at least OpenIndiana and Alpine Linux unsupported,
who's next?

**Comment by alejandro-colomar** [comment]
I've just tested that the following works on Devuan, but not on Alpine; just so that no-one else tries it:

```sh
$ ps ww o args=COMMAND 3202
COMMAND
unit: main v1.30.0 [unitd]
```

**Comment by alejandro-colomar** [comment]
> On Wed, 17 May 2023 15:55:11 -0700 Alejandro Colomar ***@***.***> wrote: @ac000 - Regarding your concern about support for OpenIndiana, since the sed(1) call already doesn't work in OpenIndiana, and -o args=COMMAND considerably simplifies the parsing, I
> I don't think it does really. Look at your command vs the one I proposed...

The problem was parsing non-[] lines.  If the line doesn't have [], your proposal doesn't work.  If a line doesn't have [], my proposal works iff the line contains only the command+args; if there's more stuff, it also breaks, which is why the -o args=COMMAND.

> think we can say we don't support that system. They should provide `-ww` if they support `ww`.
> So that would make at least OpenIndiana and Alpine Linux unsupported, who's next?

D'oh.  I guess we need to look at the few cases where the line doesn't have [], and make it have [], which would make -o args=COMMAND unnecessary.

**Comment by lcrilly** [comment]
My priority for unitc platform compatibility is to cover the distros for which we provide [pre-built packages](https://unit.nginx.org/installation/#official-packages).

I also care about FreeBSD because we have community packages for that platform.

I care less about Alpine (especially as there are multiple dependency gaps e.g. curl).
I care even less about OpenIndiana (no offence to the enthusiasts, but I've never seen a reported issue on that platform).

As we can see, ps(1) is a nightmare for command line option compatibility. This is why I was quite pleased with just `ps $PID` in the original version. It actually works in most cases.

I'm now considering taking a two-pass approach to solving this:
1. Start with `ps $PID | pipeline`
2. If unable to obtain the desired information then try a fallback to something like the `ps -wwo …`

Long term, unitc should be written in a proper language to avoid this mess :)

**Comment by alejandro-colomar** [comment]
I got something reliable using minimal ps(1) stuff.  I used tee(1) to inspect the pipeline at each step, so you can see how it works.
I had to resort to perl(1), which is nicely portable, I guess.

```sh
alx@dell7760:~$ cat pipeline 
tee /dev/tty   | grep 'unitd' \
| tee /dev/tty | perl -p -e 's/.*?([^ ]*unit.*)/\1/' \
| tee /dev/tty | sed 's/(.*//' \
| tee /dev/tty | sed 's/.*\[//' \
| tee /dev/tty | sed 's/].*//'
```
```sh
alx@dell7760:~$ unit ps
15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp]
15557 ?        S      0:00 unit: controller
15558 ?        S      0:00 unit: router
```
```sh
alx@dell7760:~$ ps ww 15555 | ./pipeline 
  PID TTY      STAT   TIME COMMAND
15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp]
15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp]
unit: main v1.30.0 [unitd --tmpdir /tmp]
unit: main v1.30.0 [unitd --tmpdir /tmp]
unitd --tmpdir /tmp]
unitd --tmpdir /tmp
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp] (foo)' | ./pipeline 
15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp] (foo)
15555 ?        Ss     0:00 unit: main v1.30.0 [unitd --tmpdir /tmp] (foo)
unit: main v1.30.0 [unitd --tmpdir /tmp] (foo)
unit: main v1.30.0 [unitd --tmpdir /tmp] 
unitd --tmpdir /tmp] 
unitd --tmpdir /tmp
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 unitd --tmpdir /tmp (foo)' | ./pipeline 
15555 ?        Ss     0:00 unitd --tmpdir /tmp (foo)
15555 ?        Ss     0:00 unitd --tmpdir /tmp (foo)
unitd --tmpdir /tmp (foo)
unitd --tmpdir /tmp 
unitd --tmpdir /tmp 
unitd --tmpdir /tmp 
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 unitd --tmpdir /tmp' | ./pipeline 
15555 ?        Ss     0:00 unitd --tmpdir /tmp
15555 ?        Ss     0:00 unitd --tmpdir /tmp
unitd --tmpdir /tmp
unitd --tmpdir /tmp
unitd --tmpdir /tmp
unitd --tmpdir /tmp
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 /foo/barunitd --tmpdir /tmp' | ./pipeline 
15555 ?        Ss     0:00 /foo/barunitd --tmpdir /tmp
15555 ?        Ss     0:00 /foo/barunitd --tmpdir /tmp
/foo/barunitd --tmpdir /tmp
/foo/barunitd --tmpdir /tmp
/foo/barunitd --tmpdir /tmp
/foo/barunitd --tmpdir /tmp
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 /foo/bar/unitd --tmpdir /tmp' | ./pipeline 
15555 ?        Ss     0:00 /foo/bar/unitd --tmpdir /tmp
15555 ?        Ss     0:00 /foo/bar/unitd --tmpdir /tmp
/foo/bar/unitd --tmpdir /tmp
/foo/bar/unitd --tmpdir /tmp
/foo/bar/unitd --tmpdir /tmp
/foo/bar/unitd --tmpdir /tmp
```
```sh
alx@dell7760:~$ echo '15555 ?        Ss     0:00 unit: main v1.30.0 [/foo/bar/unitd --tmpdir /tmp] (foo)' | ./pipeline 
15555 ?        Ss     0:00 unit: main v1.30.0 [/foo/bar/unitd --tmpdir /tmp] (foo)
15555 ?        Ss     0:00 unit: main v1.30.0 [/foo/bar/unitd --tmpdir /tmp] (foo)
unit: main v1.30.0 [/foo/bar/unitd --tmpdir /tmp] (foo)
unit: main v1.30.0 [/foo/bar/unitd --tmpdir /tmp] 
/foo/bar/unitd --tmpdir /tmp] 
/foo/bar/unitd --tmpdir /tmp
```

**Comment by lcrilly** [comment]
[Additional error checking for empty $ERROR_LOG](https://github.com/nginx/unit/commit/9ff59e6c4bc09b0252810b709bd5f6aa35f76691#diff-593b7d477ad67e7c17c9594a29cb0a34e654c92b5d7b5627e50d3e475ce6389eR172) is included in the latest `unitc` revision.

https://github.com/nginx/unit/blob/master/tools/unitc
