### ISSUE TITLE
Permission denied on files created before 1.30.0 in docker, the 'unit' user id changed from 101 to 999

### ISSUE THREAD

**Issue by gabimem** [nginx/unit#893]
Since version 1.30.0 I have had permission errors on files that are in the persistent volume, because the files were created when the 'unit' user had ID 101, now with the new image, the ID is 999, therefore the persisted files left with a permissions error.

![image](https://github.com/nginx/unit/assets/5366368/2f310d37-0f48-448f-8c2a-53c981d679cb)

I fixed it by running a chown on the affected files, but I'll leave it documented here for those who encounter this error.
It would be nice not to alter that ID later.

**Comment by lcrilly** [comment]
Thanks for the issue. What platform (or Linux distro) is this on?

**Comment by gabimem** [comment]
This is inside the container created from the 1.30.0-php8.2 image, running on an ubuntu 22.04 host, the storage folder is on a persistent volume, so the files were already created with the previous user.

**Comment by thresheek** [comment]
Yep, there was a change in our docker images recently - the uids are now consistent between all docker images we ship - previously that might not be the case since we didnt hardcode it.

**Comment by tippexs** [comment]
@gabimem Thanks for reporting this and sorry for not mentioning this in the changelog.
