### ISSUE TITLE
Possible bug in asgi error check

### ISSUE THREAD

**Issue by synodriver** [nginx/unit#895]
>> https://github.com/nginx/unit/blob/b034bf67034c4f0e966ebd207ba2f407f6f15fa8/src/python/nxt_python_asgi.c#L471-L488

Why do we have to check ```nxt_slow_path(receive == NULL)``` three times? Is this a bug?

**Comment by synodriver** [comment]
BTW, this is introduced at the same time when asgi support was add.

**Comment by ac000** [comment]
Heh, yes indeed. Good catch!

**Comment by ac000** [comment]
The fix for this has been merged.
