### ISSUE TITLE
Incorrect handling of large request body

### ISSUE THREAD

**Issue by alejandro-colomar** [nginx/unit#901]
https://github.com/nginx/unit/blob/9ff59e6c4bc09b0252810b709bd5f6aa35f76691/src/nxt_unit.c#L3097

If `req->content_length` is bigger than 16 kB, this function will return 0.  I can share a C app that reproduces it.  Maybe it can also be reproduced by using the existing Python ASGI language module, for example, writing an echo app using that module.  I created the following file to reproduce this: `seq 1 4000`, and sent it as the request body.

When that happens, libunit goes through this line of code.

**Comment by alejandro-colomar** [comment]
Cc: @andrey-zelenkov @ac000 @hongzhidao

**Comment by ac000** [comment]
Hi Alex,

I'm sending files through of around 60MiB OK...

Are you saying you're unable to send through anything larger than 16K?

**Comment by alejandro-colomar** [comment]
@ac000

Yep, anything over 16 KiB (to be more precise) results in reads of 0,
while `req->content_length` reports the correct length.  After reading
libunit's code, I suspect this bug is only triggered when you register a
data_handler callback, which is why I suspect in Python ASGI we'll be
able to reproduce it.

Anyone here knows enough python to try to reproduce it?

**Comment by andreivasiliu** [comment]
Is this happening in the `request_handler()` callback? If a `data_handler()` is defined, then `request_handler()` will be called as soon as the header was available, but for larger requests, the rest of the request body will only be available once data_handler() is called, so this would be normal behavior.

**Comment by alejandro-colomar** [comment]
Hmmm, you're right!  I was just calling the data_handler() from the request_handler(), since I was getting data in the first call, but then, as you say, it may happen that I get no data at all.  What I did to fix it after your comment was to just return if the read returns 0, and wait to be called again.

Still weird is that unitd is buffering the entire request, and then serving it at once in the data_handler(), since it makes it not really that much async...

But it works.  Thanks a lot @andreivasiliu !

Here's the code for a C app that gzips the request body and sends it back as the response body:
<http://www.alejandro-colomar.es/src/alx/alx/nginx/unit-c-app.git/log/?h=gz>

**Comment by alejandro-colomar** [comment]
@ac000 

As for what we talked a few weeks ago, I tried with `--limit-rate` to make curl(1) slower, and I still get a single call to `data_handler()` from libunit (I can check that by printing a line in the log from the app).

We're talking about around 500k of data.

```sh
$ seq 1 100000 > s100000
$ curl --limit-rate 100000 --data-binary @- -v --compressed localhost:81 <s100000 | pee "head" "tail"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:81...
* Connected to localhost (127.0.0.1) port 81 (#0)
> POST / HTTP/1.1
> Host: localhost:81
> User-Agent: curl/7.88.1
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
> Content-Length: 588895
> Content-Type: application/x-www-form-urlencoded
> 
} [65536 bytes data]
 89  575k    0     0   89  512k      0  99968  0:00:05  0:00:05 --:--:-- 99978* We are completely uploaded and fine
100  575k    0     0  100  575k      0  99984  0:00:05  0:00:05 --:--:-- 99983< HTTP/1.1 200 OK
< Content-Type: text/html
< Content-Encoding: gzip
< Server: Unit/1.31.0
< Date: Tue, 20 Jun 2023 23:13:34 GMT
< Transfer-Encoding: chunked
< 
{ [81406 bytes data]
1
2
3
4
5
6
7
8
9
10
100  782k    0  207k  100  575k  36115  99920  0:00:05  0:00:05 --:--:--  150k
* Connection #0 to host localhost left intact
99991
99992
99993
99994
99995
99996
99997
99998
99999
100000
```
