### ISSUE TITLE
Website RSS feed empty

### ISSUE THREAD

**Issue by mattxtaz** [nginx/unit#903]
This isn't actually a unit problem but I can't find any more appropriate ways of contact. The RSS feed found at https://unit.nginx.org/rss.xml was working fine until several days ago and then broke. I haven't worked out exactly what breaks it but loading it directly in Firefox, Edge, or miniflux I get no content returned, it's just empty. But loading it in curl works fine. Setting the user-agent header makes no difference so I assume it's one of the other headers that these things set that's causing it to break.

**Comment by lcrilly** [comment]
Thanks @mattxtaz . We do have a repo for the docs: https://github.com/nginx/unit-docs
This looks like a problem with the auto-compression of site contents. The rss.xml file is there and intact but the compressed version is empty.

You're right. It's the `Accept-Encoding` request header that informs the web server which type to use.

Investigating now.

**Comment by lcrilly** [comment]
Fixed. Thanks again for the report!

**Comment by mattxtaz** [comment]
@lcrilly fyi this problem has reoccured, so whatever you did before needs doing again, or the root cause fixed

**Comment by lcrilly** [comment]
On it!
