### ISSUE TITLE
GKE nginx Ingress Controller Not able to Pass only IP client in X-FORWARDER-FOR Header

### ISSUE THREAD

**Issue by adrianonmobile** [nginx/unit#905]
I am running Nginx as ingress controller in GKE. I have installed ingress controller using terraform release to last chart version 4.7.0.

I am trying to comunicate with another aplication but application said that 2 ips are being received in [X-Forwarded-For] value from Request headers: One Is the Public ip of the client and the other is ip from kuberntes pod, but only client is needed. I just try to update config in values.yaml as follows but no able to get only Public Client Ip. Comments are possible solutions but nothing works.

Please help

controller:
  config:
    #enable-real-ip: "true" 
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    force-ssl-redirect: "true"
    #real-ip-header: "X-Forwarded-For"
    #set_real_ip_from: "X.X.X.X/X"
    #real_ip_recursive: "off"
    #use-proxy-protocol: "true" 
    #proxy-add-original-uri-header: "true"
  ingressClassResource:
    # Specify Ingress to use for the services
    name: external-nginx
    enbaled: true
    default: false
  replicaCount: 2
  autoscaling:
    enabled: true
    maxReplicas: 10
    minReplicas: 2
  admissionWebhooks:
    enabled: false
  service:
    externalTrafficPolicy: "Local"
    annotations:
      # Public Load Balancer
      cloud.google.com/load-balancer-type: External

**Comment by adrianonmobile** [comment]
not able to set use proxy protocol either

**Comment by ac000** [comment]
This is not the issue tracker you're looking for...

This is for the NGINX **Unit** project. Please select the appropriate project from [here](https://github.com/orgs/nginx/repositories).
