### ISSUE TITLE
Problems with Docker-NodeJS

### ISSUE THREAD

**Issue by MrSipping** [nginx/unit#906]
Hi, I'm having problems with the docker unit-nodejs, the docker starts but I don't sell anything on screen and moreover it seems that the app.js inside the docker doesn't start... I copied the Dockerfile I found on the site but even with that I can't get it to start. Can anyone give me a hand?

**Comment by lcrilly** [comment]
Please check that you're using the `unit:node` Docker Official Image. Share your configuration. Share what happens with `docker run` or `docker logs`.

**Comment by MrSipping** [comment]
> Please check that you're using the `unit:node` Docker Official Image. Share your configuration. Share what happens with `docker run` or `docker logs`.

i use this dockerfile i downloaded from the site and i built it
`# keep our base image as small as possible
FROM unit:1.30.0-node18
# Alternatively, you can download the base image from AWS ECR:
# FROM public.ecr.aws/nginx/unit:1.30.0-node18

# port used by the listener in config.json
EXPOSE 8080

#application setup
RUN mkdir /www/ && echo '#!/usr/bin/env node                             \n\
    require("unit-http").createServer(function (req, res) {                \
        res.writeHead(200, {"Content-Type": "text/plain"});                \
        res.end("Hello, Node.js on Unit!")                                 \
    }).listen()                                                            \
    ' > /www/app.js                                                        \
# make app.js executable; link unit-http locally
    && cd /www && chmod +x app.js                                          \
    && npm link unit-http                                                  \
# prepare the app config for Unit
    && echo '{                                                             \
    "listeners": {                                                         \
        "*:8080": {                                                        \
            "pass": "applications/node_app"                                \
        }                                                                  \
    },                                                                     \
    "applications": {                                                      \
        "node_app": {                                                      \
            "type": "external",                                            \
            "working_directory": "/www/",                                  \
            "executable": "app.js"                                         \
        }                                                                  \
    }                                                                      \
    }' > /docker-entrypoint.d/config.json`

I launch docker

`0eab1f14b919   image          "/usr/local/bin/dock…"   5 seconds ago       Up 5 seconds       80/tcp, 8080/tcp   thirsty_tu
`

and this is log

`2023/07/12 10:19:46 [info] 9#9 unit 1.30.0 started
/usr/local/bin/docker-entrypoint.sh: Launching Unit daemon to perform initial configuration...
2023/07/12 10:19:46 [info] 12#12 discovery started
2023/07/12 10:19:46 [notice] 12#12 no modules matching: "/usr/lib/unit/modules/*.unit.so" found
2023/07/12 10:19:46 [info] 10#10 controller started
2023/07/12 10:19:46 [notice] 10#10 process 12 exited with code 0
2023/07/12 10:19:46 [info] 15#15 router started
2023/07/12 10:19:46 [info] 15#15 OpenSSL 1.1.1n  15 Mar 2022, 101010ef
{
	"certificates": {},
	"js_modules": {},
	"config": {
		"listeners": {},
		"applications": {}
	},

	"status": {
		"connections": {
			"accepted": 0,
			"active": 0,
			"idle": 0,
			"closed": 0
		},

		"requests": {
			"total": 0
		},

		"applications": {}
	}
}
/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, applying initial configuration...
/usr/local/bin/docker-entrypoint.sh: Looking for certificate bundles in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Looking for JavaScript modules in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Looking for configuration snippets in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Applying configuration /docker-entrypoint.d/config.json
2023/07/12 10:19:46 [info] 22#22 "node_app" prototype started
2023/07/12 10:19:46 [info] 23#23 "node_app" application started
/usr/local/bin/docker-entrypoint.sh: OK: HTTP response status code is '200'
 }success": "Reconfiguration done."
/usr/local/bin/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/...
/usr/local/bin/docker-entrypoint.sh: Stopping Unit daemon after initial configuration...
2023/07/12 10:19:46 [notice] 10#10 process 14 exited with code 0
2023/07/12 10:19:46 [notice] 10#10 process 15 exited with code 0
/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...
2023/07/12 10:19:46 [notice] 22#22 app process 23 exited with code 0
2023/07/12 10:19:46 [alert] 22#22 sendmsg(13, -1, -1, 2) failed (32: Broken pipe)
2023/07/12 10:19:46 [notice] 10#10 process 22 exited with code 0

/usr/local/bin/docker-entrypoint.sh: Unit initial configuration complete; ready for start up...

2023/07/12 10:19:47 [info] 1#1 unit 1.30.0 started
2023/07/12 10:19:47 [info] 43#43 discovery started
2023/07/12 10:19:47 [notice] 43#43 no modules matching: "/usr/lib/unit/modules/*.unit.so" found
2023/07/12 10:19:47 [info] 1#1 controller started
2023/07/12 10:19:47 [notice] 1#1 process 43 exited with code 0
2023/07/12 10:19:47 [info] 45#45 router started
2023/07/12 10:19:47 [info] 45#45 OpenSSL 1.1.1n  15 Mar 2022, 101010ef
2023/07/12 10:19:47 [info] 46#46 "node_app" prototype started
2023/07/12 10:19:47 [info] 47#47 "node_app" application started
`

**Comment by lcrilly** [comment]
Looks good. What happens when you request **http://localhost:8080/** ?

If that fails, try `docker exec -ti 0eab1f14b919 curl -i localhost:8080`

**Comment by MrSipping** [comment]
> Looks good. What happens when you request **http://localhost:8080/** ?
> 
> If that fails, try `docker exec -ti 0eab1f14b919 curl -i localhost:8080`

with docker exec -ti 0eab1f14b919 curl -i localhost:8080 works!

but now how can i create a docker which is displayed on the host and can be modified via the host (like unit configuration, web-app configuration, log reading)

**Comment by lcrilly** [comment]
You exposed port 8080 in the Dockerfile but did not map it to a local port when you started the container. Use `docker run` with `-p` or `-P` to do that.

https://docs.docker.com/engine/reference/run/#expose-incoming-ports

**Comment by MrSipping** [comment]
> You exposed port 8080 in the Dockerfile but did not map it to a local port when you started the container. Use `docker run` with `-p` or `-P` to do that.
> 
> https://docs.docker.com/engine/reference/run/#expose-incoming-ports

But not working

This is the command:
`sudo docker build -t image  nodejs/ && sudo docker run -d image -P 8080:8080`

and this is the error:
`/usr/local/bin/docker-entrypoint.sh: 101: exec: -p: not found`

**Comment by lcrilly** [comment]
`docker run` syntax is `[OPTIONS] IMAGE` so you need to put the port mapping before the image name.

`-P` is for auto mapping. Use `-p` for manual mapping.

Try this
```
docker run -d -p 8080:8080 image
```

For more assistance with Docker tooling you might want to try the Docker Community Slack.

**Comment by MrSipping** [comment]
> ntrypoint.

okay but the error is not docker syntax, it says dento docker can't execute -p command because it doesn't exist. I downloaded the dockerfile from the Nginx Unit site

**Comment by MrSipping** [comment]
> docker run -d -p 8080:8080 image

okay now work, thank you! 

but now how can I bind the configuration on the host in the docker configurations?

**Comment by MrSipping** [comment]
Now works!
