### ISSUE TITLE
Trying to compile node20 via makefile

### ISSUE THREAD

**Issue by MrSipping** [nginx/unit#908]
Hi, I'm trying to create docker with node 20, it gets to a certain point and it crashes and gives me the following error.

`./configure: error: no node-gyp found.`

The error gives me after trying to do this configure.
`+ ./configure nodejs --node-gyp=/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp`

I can't understand why it should give me an error if I change only the version, however has anyone ever tried to compile it and gives this error?

**Comment by thresheek** [comment]
Hi @MrSipping,

It looks like node 20 images don't have the node-gyp binary under the specified path.

**Comment by thresheek** [comment]
It seems they don't ship node-gyp as a part of 20 images at all anymore - we'll need to expore our options on how to fix that.  Likely another step in Dockerfiles to install it manually.

**Comment by MrSipping** [comment]
> Hi @MrSipping,
> 
> It looks like node 20 images don't have the node-gyp binary under the specified path.

okay i get it, so the important thing is that it's installed not where it's installed. I have another question, I'm used to mapping the folders on the filesystem one by one using the --mount bind command, but I noticed that with this command the changes to the Unit configuration are not saved in the docker instead if I use the -v command it works, can you tell me why?

**Comment by tippexs** [comment]
Hi @MrSipping depending on the exact `docker run` command and if a file already exists or not it is very likely you are hitting this `issue`

https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

>Because the -v and --volume flags have been a part of Docker for a long time, their behavior cannot be changed. This means that there is one behavior that is different between -v and --mount.

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.

> If you use --mount to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.
