### ISSUE TITLE
unit 1.30 images not available on Docker Hub?

### ISSUE THREAD

**Issue by taisph** [nginx/unit#911]
Latest tags are 1.29.1 based. Is this an error or are images no longer available on Docker Hub?

**Comment by tippexs** [comment]
Hi @taisph 

Thanks for reaching out. What's the specific image you are looking for?

We published the 1.30.0 images to docker hub. See the Node18 image as a reference. https://hub.docker.com/layers/library/unit/1.30.0-node18/images/sha256-90754932bc49a61e9ca25c7bcdf6d44ccc56c06d2caabcdb74cda0c271d3f678?context=explore

Let me know if you need anything else.

**Comment by taisph** [comment]
> Hi @taisph 
> 
> Thanks for reaching out. What's the specific image you are looking for?
> 
> We published the 1.30.0 images to docker hub. See the Node18 image as a reference. https://hub.docker.com/layers/library/unit/1.30.0-node18/images/sha256-90754932bc49a61e9ca25c7bcdf6d44ccc56c06d2caabcdb74cda0c271d3f678?context=explore
> 
> Let me know if you need anything else. 

Ah, I was pulling from nginx/unit, not library/unit or just unit. Sorry for the noise.
