### ISSUE TITLE
PROXY: How can we set custom headers in the proxy?

### ISSUE THREAD

**Issue by khalid3n** [nginx/unit#913]
In nginx I would set headers like this in the location
```
    location /v1/database-svc {
      proxy_pass http://database-svc:8000/v1/database-svc;
      proxy_http_version 1.1;
      proxy_set_header X-API-Key "SOME_X_API_KEY";
    }
```

How can we do that in nginx unit when proxying?

```
[
    {
      "match": {
        "uri": "/private/*"
      },

      "action": {
        "rewrite": "`${uri.replace('/private', '')}`",
        "proxy": "http://127.1.1.0:80"
      }
    },
    {
      "action": {
        "share": "/www/$uri"
      }
    }
  ]
```

**Comment by tippexs** [comment]
Hi @khalid3n 
The proxy feature is not under active development at the moment and this is currently not possible nor planed. We are about to release the possibility to control the response headers BUT this does not include headers that should be shared with the upstream.

In your case (something simliar to what I did) you can use a NodeJS based middleware. 
https://gist.github.com/tippexs/ab23fbce26e9e101b38ffb765b7d1082

This will give  you an idea. Let me know if thats sounds copletly crazy, if not I am more than happy to assist you with the setup if needed.
