### ISSUE TITLE
application logging to files not working for php wordpress

### ISSUE THREAD

**Issue by yosefy** [nginx/unit#915]
even though we setup as in doc: https://unit.nginx.org/news/2023/unit-1.30.0-released/#application-logging

still php error log goes to main unit.log file

```
"testsite": {
		"stderr": "/tmp/unit_app.log",
		"stdout": "/tmp/unit_app_error.log",
		"user": "unit",
		"type": "php 7.4",
		"targets": {
			"direct": {
				"root": "/sites/site/"
			},

			"index": {
				"root": "/sites/site/",
				"script": "index.php"
			}
		}
	}
```
thanks

```
# unitd --version
unit version: 1.30.0
configured as ./configure --prefix=/usr --statedir=/var/lib/unit --control=unix:/var/run/unit/control.sock --pid=/var/run/unit/unit.pid --log=/var/log/unit/unit.log --tmpdir=/var/tmp --user=unit --group=unit --tests --openssl --njs --modulesdir=/usr/lib64/unit/modules --libdir=/usr/lib64 --cc-opt='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC' --ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
```

**Comment by ac000** [comment]
Couple of quick questions

1) Is Unit running as a **daemon**? I.e **without** the *--no-daemon* command line argument.
2) Does the *unit* user have write access to those log files?

**Comment by yosefy** [comment]
[Service]
Type=simple
Environment="UNITD_OPTIONS=--log /var/log/unit/unit.log --pid
/var/run/unit/unit.pid "
ExecStart=/usr/sbin/unitd $UNITD_OPTIONS --no-daemon
ExecReload=
RuntimeDirectory=unit
RuntimeDirectoryMode=0755

i have set it to /tmp/files.log so yep it has rights

**Comment by ac000** [comment]
Please remove the **--no-daemon** option. 

The stdout/stderr options only take effect when running as a daemon. (Yes, our documentation is wrong!).

**Comment by yosefy** [comment]
it wouldn't work with systemd without --no-daemon option
do you have some advice on it may be?

**Comment by ac000** [comment]
Also change the **Type** from simple to **forking**

That works for me on Fedora...

(**NOTE:** You should probably copy /usr/lib/systemd/system/unit.service into **/etc/systemd/system/** and edit that one instead which will override the one from the package.)

@thresheek 

Any reason not to use a systemd service 'Type' of forking and run unit as a daemon by default?

Otherwise users can't make use of per application logging...

**Comment by thresheek** [comment]
See https://github.com/nginx/unit/pull/212 and https://github.com/nginx/unit/issues/213 for some comments on why we're not using forking. The commit that changed that is https://github.com/nginx/unit/commit/b78ed44f396cbfde7d8353cbc3faaf35c0f4dddf

**Comment by yosefy** [comment]
clear.
but how to split the logs now?

**Comment by ac000** [comment]
@yosefy 

I currently see no reason why we shouldn't switch back to _forking_.

However in the meantime, create the file ```/etc/systemd/system/unit.service``` with the following contents

```
[Unit]
Description=NGINX Unit
Wants=network-online.target
After=network-online.target

[Service]
Type=forking
Environment="UNITD_OPTIONS=--log /var/log/unit/unit.log --pid /var/run/unit/unit.pid"
ExecStart=/usr/sbin/unitd $UNITD_OPTIONS
ExecReload=
RuntimeDirectory=unit
RuntimeDirectoryMode=0755
PIDFile=/var/run/unit/unit.pid

[Install]
WantedBy=multi-user.target
```

(This will take precedence over the service file from the unit package)

Then do a ```systemctl restart unit```

**Comment by ac000** [comment]
Re-opening to raise visibility...

**Comment by sidz** [comment]
Hi guys.

It seems like per application logging obviously doesn't work for dockerized application due to the fact that `--no-daemon` mode is used.

Does anybody aware of any hack or workaround?

**Comment by ac000** [comment]
Are you able to run Unit as a [daemon(7)](https://man7.org/linux/man-pages/man7/daemon.7.html)? I.e _without_ the `--no-daemon` option. If not, is there some fundamental reason why?

**Comment by lcrilly** [comment]
That's how Docker works, Andrew :)

https://github.com/nginx/unit/blob/master/pkg/docker/template.Dockerfile#L89

We expect people to use container logging conventions, but sounds like in this case real log files are required.

@sidz This topic should really be moved to a separate discussion.

**Comment by tippexs** [comment]
@sidz yes please do. I am happy to link it to this issue but we should open another one to work on the per application logging OR better to say application logging in Docker using Unit.
