### ISSUE TITLE
Very minor typos in log entries

### ISSUE THREAD

**Issue by jeffdafoe** [nginx/unit#920]
There's a couple of places where log messages have "received" as "recevied".

**Comment by meezaan** [comment]
Loving the attention to detail! 😊

**Comment by tippexs** [comment]
Thanks for reporting this to us! @alejandro-colomar please have a look on this.

We are in preparation for the release 1.31 next Thursday and heading towards a code freeze but we will take are of it.

**Comment by ac000** [comment]
Committed as https://github.com/nginx/unit/commit/7dd5ad93a4c147b086a8d82ecb403f96981bb4ee
