### ISSUE TITLE
RISC V Support?

### ISSUE THREAD

**Issue by Syndesi** [nginx/unit#926]
Hi,

does NGINX Unit already support RISC V, or is such support planned?

If so, can the [documentation](https://unit.nginx.org/installation/#prerequisites) be updated?

Kind regards,
Syndesi

**Comment by lcrilly** [comment]
Hi Syndesi, I'm not aware of anyone using Unit on RISC-V and there are no current plans to support it.

What is your use case for RISC-V?

Did you already try to build from source? It might be enough to modify the `--cc-opt` configure arguments.

**Comment by Syndesi** [comment]
Hi Icrilly,

currently I am not using RISC V myself either, though the development of RISC V hardware and software seems to get more useful every month. For example, [Debian just announced to officially support this architecture](https://www.phoronix.com/news/Debian-Official-RISC-V) and more useful developer hardware like the [HiFive Pro P550](https://www.sifive.com/boards/hifive-pro-p550) should be released soon. This is quite fascinating for me, and I want to experiment with this ecosystem soon.

And as I just added ARM support to [my own software project](https://github.com/ember-nexus/api), which uses NGINX Unit internally, I am wondering how easy (or hard) it would be to compile it for RISC V.

I will try to compile it in the next weeks, and post results here :D

Should we close this issue in the mean time?

**Comment by thresheek** [comment]
It seems to be compiling just fine for RISCV for at least some Linux distros: https://packages.altlinux.org/en/sisyphus_riscv64/srpms/unit/

**Comment by thresheek** [comment]
With that, I don't think adding explicit support for RISCV packages or Docker image makes sense at this moment.  It just isnt useful enough to warrant spending time on it.

**Comment by lcrilly** [comment]
@Syndesi thanks for sharing your use case and the Ember Nexus project!
