### ISSUE TITLE
Support static distribuition of `unitd`

### ISSUE THREAD

**Issue by lolgab** [nginx/unit#927]
Having a static distribution of `unitd` is handy for applications that use a subset of NGINX Unit features and don't need TLS (since it's maybe handled by another layer) or other dependencies.
I tried adding `-static` when building `build/sbin/unitd` and the compilation succeeds.
It would be nice if static linking was supported out of the box.

**Comment by lcrilly** [comment]
What problem would this solve for you?

Would it be enough to include a `unitd-minimal` binary in the official packages that is statically linked?

**Comment by lolgab** [comment]
> What problem would this solve for you?

The creation of a minimal docker image that has only `unitd` and my application.

> Would it be enough to include a `unitd-minimal` binary in the official packages that is statically linked?

It would!

**Comment by lolgab** [comment]
> Providing pre-built statically linked binary with SSL libraries is a bad idea, though.

I agree with that.

> And providing `unitd` binary that lacks features compared to the proper one is a nightmare in the user experience, let alone documentation.

I think it's not a nightmare if it's stated clearly that it's a minimal distribution. NGINX Unit is full of features but not everybody needs all of them. In my case, I'm happy if I can run a simple HTTP app with a small linux binary and serve some files as well. Go developers like to have a single static binary with an application and with this approach you can have a container with two files instead (your go app and `unitd`) without having to carry a linux distribution to run a Go app. You can still serve static files, have processes scaling and other nice features NGINX Unit provides.

**Comment by thresheek** [comment]
Yeah, that's understood.  The "minimal" image we will provide with 1.31.0 (we did some cleanup after 1.30.0) is around 100 megabytes with all the bells and whistles;  and chances are for a typical stack that the layers we base it upon (debian:bullseye-slim) would be shared between other images.  That's not the case for a typical Go app, for sure, but still something worth considering - since maintaining yet another Docker image based on scratch comes with support and documentation tasks.

**Comment by lolgab** [comment]
A good first step would be to allow config in `./configure` to emit a `-static` `unitd`.
What I have at the moment is a patch which I would remove if you could pass a flag to emit a static `unitd` binary.

**Comment by thresheek** [comment]
You can just use --cc-opt="-static" to produce one.  You don't need any patches for that.

**Comment by lolgab** [comment]
Oh, that's awesome! Thank you!

**Comment by tippexs** [comment]
@lolgab @thresheek can we consider this issue for beeing resolved? 

Is this worth mentioning in our docs?
