### ISSUE TITLE
Serving static content fails

### ISSUE THREAD

**Issue by arthall-online** [nginx/unit#931]
I have a route in Unit config for serving simple Angular application 
![Screenshot 2023-08-26 at 21 30 43](https://github.com/nginx/unit/assets/69581668/561d4859-a50e-44d2-b027-3d7b75a58de7)

It works fine on a domain call, but fails if something is added (url)
<img width="1114" alt="Screenshot 2023-08-26 at 21 31 03" src="https://github.com/nginx/unit/assets/69581668/86de384a-4bff-49e1-9908-95b16cb2f639">
<img width="843" alt="Screenshot 2023-08-26 at 21 31 12" src="https://github.com/nginx/unit/assets/69581668/8110c0af-88a9-4143-bc18-2e97df04c906">

I can't find any documentation describing this behaviour in Docs(

**Comment by lcrilly** [comment]
Please try enabling `log_route` in the **/config/settings/http** object so that you can be sure that the URI request is reaching the expected route.

https://unit.nginx.org/configuration/#settings

More info [here](https://unit.nginx.org/news/2023/unit-1.30.0-released/#router-diagnostic-logging).
