### ISSUE TITLE
nxt_runtime_thread_pool_exit() does not call the rt->continuation() correctly

### ISSUE THREAD

**Issue by tsinghai1982** [nginx/unit#934]
as following codes from nxt_runtime_thread_pool_exit()

    for (i = 0; i < n; i++) {

        if (tp == thread_pools[i]) {
            nxt_array_remove(rt->thread_pools, &thread_pools[i]);

            nxt_free(tp);

           /*if there are more thread pools than one， it's can't be called*/
            if (n == 1) {
                /* The last thread pool. */
                rt->continuation(task, 0);
            }

            return;
        }
    }

**Comment by hongzhidao** [comment]
What's the issue?

**Comment by tsinghai1982** [comment]
/*if there are more thread pools than one， it's can't be called*/
   rt->continuation(task, 0);

**Comment by hongzhidao** [comment]
The source code of how thread pool works is in `src/nxt_thread_pool.c`, you could deep into it.
