### ISSUE TITLE
GeoIp module

### ISSUE THREAD

**Issue by ruudk** [nginx/unit#937]
I'm using `ngx_http_geoip2_module` with regular Nginx. Can I something similar for Unit?

I'd like to get geo info for IP's that hit my server.

**Comment by tippexs** [comment]
Thanks for bringing this up. At the moment we don't have a GeoIp implementation. I can think of some njs hacks to make it work but haven't tried it. The tricky part would be the performance impact of looking it up if not implemented I a efficient manner. I will keep you posted.

**Comment by ruudk** [comment]
We want to pass these headers to our php-fpm server so that they appear as request headers on the PHP side.
