### ISSUE TITLE
JavaScript/Node.js support request

### ISSUE THREAD

**Issue by SergeC** [nginx/unit#95]
The issue to track community interest to JavaScript/Node.js support. Please upvote if you interested. Hope we will get it sooner.

**Comment by tkalfigo** [comment]
Just read the 1.0 production ready release of nginx unit. Comes with  Go support and only mention for future plans was for Java support. No mention of Node.

**Comment by VBart** [comment]
@tkalfigo Could please you clarify what did you read? Because the [announcement blog post ](https://www.nginx.com/blog/nginx-unit-1-0-released/) mentions Node.

**Comment by tkalfigo** [comment]
I see now that further down node is mentioned. But in the beginning were all the languages as well as future is concerned, there is no mention of Node.

```
As of Release 1.0, NGINX Unit supports Go, Perl, PHP, Python, and Ruby on the same server. Multiple language versions are also supported, so you can, for instance, run applications written for PHP 5 and PHP 7 on the same server. Support for additional languages, including Java, is planned for future NGINX Unit releases.
```

Stopped reading after Igor's bio where next paragraph was 'What Is NGINX Unit?'. Apologies for jumping to a conclusion too early. Glad to hear so.

**Comment by SergeC** [comment]
@VBart Is any roadmap on Node support roll out?

**Comment by VBart** [comment]
It's planned till the end of the year. That's what I can only say right now.

**Comment by steven-cuthill-otm** [comment]
Hello, Any updated on Java / Node support yet ?

**Comment by nshadrin** [comment]
Steven,

this is currently in research / engineering.
Active work on this feature is in progress.

**Comment by Zmeu213** [comment]
Well, it seems that we finally have node.js support https://github.com/nginx/unit/commit/ea62327b008b39dc48a51aa80343b20a0a122cd6 but there is no documentation yet and no possibility to get unit-node module for experiments

**Comment by VBart** [comment]
@Zmeu213 The documentation is on the web-site since the release day:
http://unit.nginx.org/configuration/#go-node-js-applications
http://unit.nginx.org/installation/#configuring-node-js
