### ISSUE TITLE
Nginx reverse proxy works on localhost but not on IP

### ISSUE THREAD

**Issue by Patsjemoe** [nginx/unit#955]
Hi,
Have NGINX on my raspberry pi, with a localhost 127.x.x.x.
Approach it with https://dyndsn.../rasp or https://dyndsn.../esp32
I use " location / " to go to Rasp server, one to ESP32cam server, which is on IP.
When using location /rasp.....proxy_pass http://127.x.x.x, it works
when using location/esp32 ..proxy_pass http://192.x.x.x, it does not work.
When doing Ifconfig on my raspberry pi , it shows the ESP32cam IP address.
Anyone any idea what to do/how to check ?
Thanks in advance
best regards
Ludo

**Comment by lcrilly** [comment]
Hello. This is the issue tracker for NGINX Unit but your question seems related to proxying in NGINX. Please direct this issue to the channels listed at https://nginx.org/en/support.html or to the [nginxcommunity Slack](https://community.nginx.org/joinslack).

**Comment by Patsjemoe** [comment]
Hi Lily
Not sure I understand why this is not an nginx issue...
Logged in in slack community, but could not find where to ask the question.
Regards
Ludo



Op wo 20 sep. 2023 20:17 schreef Liam Crilly ***@***.***>:

**Comment by ac000** [comment]
On Wed, 20 Sep 2023 11:45:44 -0700
Patsjemoe ***@***.***> wrote:

> Hi Lily
> Not sure I understand why this is not an nginx issue...

That's not what _Liam_ said.

This bug tracker is for NGINX **Unit**, your problem is related to NGINX
the web server which is a different project.
