### ISSUE TITLE
Python 3.11 Package for Ubuntu 22.04 (Jammy) 

### ISSUE THREAD

**Issue by acnebs** [nginx/unit#966]
Hi, I noticed there is a `unit-python3.11` package for Ubuntu 23.04 (Lunar) but not for Ubuntu 22.04 (Jammy). Because Jammy is the LTS version I would prefer to use that, but I would also like to use Python 3.11. 

Would it be possible to add a 3.11 package to the jammy repo?

**Comment by acnebs** [comment]
Gotcha, makes sense. I had not seen that, I will give that a go! Thanks for pointing me in the right direction.

**Comment by vishgyana** [comment]
Hey there,
    The same I'm using Ubuntu 22.04 (Jammy) and I require using Python3.11.
