### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by ruudk** [nginx/unit#971]
It would be great if you could enable GitHub Discussions here, so that we can ask questions and help each other.

**Comment by lcrilly** [comment]
Hi @ruudk , we are considering that, but for now the best place is our [Community Slack](https://community.nginx.org/joinslack)

There is a link from the [unit.nginx.org Community page](https://unit.nginx.org/community/).

**Comment by lcrilly** [comment]
Discussions are now open!
