### ISSUE TITLE
Access all Unit variables from JavaScript

### ISSUE THREAD

**Issue by lcrilly** [nginx/unit#977]
When creating complex configurations with JavaScript expressions or modules, it is often necessary to access specific attributes of the request/response such as cookie values.

Currently, [JavaScript has access to a subset of the attributes](https://unit.nginx.org/scripting/) that Unit provides as [variables](https://unit.nginx.org/configuration/#variables).

This enhancement is to provide a native method for JavaScript to access all current and future variables that Unit provides.

**Comment by lcrilly** [comment]
Implemented by https://github.com/nginx/unit/pull/1024

**Comment by ac000** [comment]
This has been merged.
