### ISSUE TITLE
SIGQUIT and SIGTERM handlers in worker processes accidentally swapped?

### ISSUE THREAD

**Issue by julianbrost** [nginx/unit#99]
I just stumbled across the following two lines in the worker signal handling code, which look like the two signal handlers were swapped accidentally there:

https://github.com/nginx/unit/blob/c610b356497136f11c7c8d7dc3d28c29a9a76cd4/src/nxt_worker_process.c#L61-L62

Unfortunately I didn't find any documentation on how Unit should handle signals, so I don't know what's the intended behavior, but the code looks like it's a bug.

**Comment by VBart** [comment]
Thanks for noticing this.
